; Generated by scriptc (LLVM backend) from /Users/sam/Dev/llama.scriptc/tests/tensor/test_shape.ts. Do not edit.

%ScrStr = type { i64, i64, i64 }
%ScrLogArg = type { i32, i64 }
%ScrVt = type { i64, i64, ptr }
%ScrUnion = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrClosure = type { i64, ptr, i64, ptr }
%ScrRegex = type { i64, ptr, ptr, ptr }
%ScrArr = type { i64, i64, i64, i32, ptr, ptr, ptr, ptr }
%ScrError = type { i64, ptr, ptr, ptr, ptr }
%ScrClassObj = type { i64, i64, i64, ptr, ptr }
%ScrEmitter = type { i64, ptr, ptr, ptr }
%ScrStream = type { i64, ptr, ptr, ptr, ptr }
%ScrCaught = type { i64, i32, double, i8, ptr, ptr, ptr, ptr }
%ScrBytes = type { i64, i64, i32, ptr, ptr }
%ScrBox = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrJsonBuf = type { ptr, i64, i64, ptr, i64, i64 }
%ScrDynPath = type { ptr, ptr, i64 }
%ScrIslandModule = type { ptr, ptr, i64, i64, i32, ptr, i64, i64 }
%ScrIslandEdge = type { ptr, ptr, ptr, i32 }
%sc_rs_r0 = type { i64, ptr, ptr } ; record r0 { fn; name }

@scr_error_vts = external global [5 x %ScrVt]
declare void @scr_init()
declare void @scr_lib_init(i32, ptr)
declare ptr @scr_arr_retain_v(ptr)
declare void @scr_arr_release_v(ptr)
declare double @scr_arr_len(ptr)
declare void @scr_arr_release(ptr)
declare double @scr_arr_get_f64(ptr, double)
declare ptr @scr_str_retain_v(ptr)
declare void @scr_str_release_v(ptr)
declare ptr @scr_f64_to_scrstr(double)
declare ptr @scr_str_concat(ptr, ptr)
declare ptr @scr_error_new(i32, ptr)
declare ptr @scr_error_retain_v(ptr)
declare void @scr_error_release_v(ptr)
declare void @scr_throw_obj(ptr, ptr, ptr, ptr)
declare void @scr_str_release(ptr)
declare ptr @scr_arr_new(i32, i64)
declare double @scr_arr_push_f64(ptr, double)
declare void @scr_arr_set_f64(ptr, double, double)
declare double @llvm.floor.f64(double)
declare double @scr_math_max(double, double)
declare ptr @scr_arr_join(ptr, ptr)
declare ptr @scr_union_retain_v(ptr)
declare void @scr_union_release_v(ptr)
declare void @scr_union_release(ptr)
declare zeroext i1 @scr_union_get_bool(ptr)
declare double @scr_union_get_f64(ptr)
declare zeroext i1 @scr_str_eq(ptr, ptr)
declare double @scr_str_utf16_len(ptr)
declare ptr @scr_bool_to_scrstr(i1 zeroext)
declare ptr @scr_closure_retain_v(ptr)
declare void @scr_closure_release_v(ptr)
declare zeroext i1 @scr_exc_pending()
declare void @scr_closure_release(ptr)
declare ptr @scr_exc_take()
declare ptr @scr_caught_retain(ptr)
declare void @scr_caught_release(ptr)
declare zeroext i1 @scr_caught_instanceof(ptr, i64, i64)
declare zeroext i1 @scr_str_includes(ptr, ptr)
declare void @scr_console_log(i64, ptr)
declare ptr @scr_arr_get_ref(ptr, double)
declare void @scr_throw_error_msg_code(i32, ptr, i64, ptr)
declare ptr @scr_arr_new_ref(ptr, ptr, ptr, i64)
declare ptr @scr_closure_new(ptr, i64)
declare double @scr_arr_push_ref(ptr, ptr)
declare ptr @scr_union_new_f64(i32, double)
declare ptr @scr_union_new_ref(i32, ptr, ptr, ptr, ptr)
declare void @scr_obj_alloc_note()
declare void @scr_obj_free_note()
declare void @scr_cyc_on_dead(ptr)
declare void @scr_cyc_free(ptr)
declare void @scr_cyc_on_release(ptr)
declare ptr @scr_cyc_alloc(i64, ptr, ptr)
declare void @scr_closure_trace_v(ptr, ptr, ptr)
declare void @scr_trap(ptr)

@sc_lit_0 = internal global { i64, i64, i64, [28 x i8] } { i64 -1, i64 27, i64 27, [28 x i8] c"Invalid negative dimension \00" }
@sc_lit_1 = internal global { i64, i64, i64, [10 x i8] } { i64 -1, i64 9, i64 9, [10 x i8] c" at axis \00" }
@sc_lit_2 = internal global { i64, i64, i64, [19 x i8] } { i64 -1, i64 18, i64 18, [19 x i8] c"Dimension at axis \00" }
@sc_lit_3 = internal global { i64, i64, i64, [38 x i8] } { i64 -1, i64 37, i64 37, [38 x i8] c" must be a non-negative integer, got \00" }
@sc_lit_4 = internal global { i64, i64, i64, [40 x i8] } { i64 -1, i64 39, i64 39, [40 x i8] c"Incompatible shapes for broadcasting: [\00" }
@sc_lit_5 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c", \00" }
@sc_lit_6 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"] and [\00" }
@sc_lit_7 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"]\00" }
@sc_lit_8 = internal global { i64, i64, i64, [17 x i8] } { i64 -1, i64 16, i64 16, [17 x i8] c"Assertion failed\00" }
@sc_lit_9 = internal global { i64, i64, i64, [20 x i8] } { i64 -1, i64 19, i64 19, [20 x i8] c"[ASSERTION FAILED] \00" }
@sc_lit_10 = internal global { i64, i64, i64, [1 x i8] } { i64 -1, i64 0, i64 0, [1 x i8] c"\00" }
@sc_lit_11 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c" (\00" }
@sc_lit_12 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c")\00" }
@sc_lit_13 = internal global { i64, i64, i64, [29 x i8] } { i64 -1, i64 28, i64 28, [29 x i8] c"[ASSERTION FAILED] Expected \00" }
@sc_lit_14 = internal global { i64, i64, i64, [7 x i8] } { i64 -1, i64 6, i64 6, [7 x i8] c", got \00" }
@sc_lit_15 = internal global { i64, i64, i64, [47 x i8] } { i64 -1, i64 46, i64 46, [47 x i8] c"[ASSERTION FAILED] Array length mismatch: got \00" }
@sc_lit_16 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c", expected \00" }
@sc_lit_17 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c". \00" }
@sc_lit_18 = internal global { i64, i64, i64, [43 x i8] } { i64 -1, i64 42, i64 42, [43 x i8] c"[ASSERTION FAILED] Array element at index \00" }
@sc_lit_19 = internal global { i64, i64, i64, [7 x i8] } { i64 -1, i64 6, i64 6, [7 x i8] c": got \00" }
@sc_lit_20 = internal global { i64, i64, i64, [27 x i8] } { i64 -1, i64 26, i64 26, [27 x i8] c"[ASSERTION FAILED] Threw '\00" }
@sc_lit_21 = internal global { i64, i64, i64, [24 x i8] } { i64 -1, i64 23, i64 23, [24 x i8] c"', expected substring '\00" }
@sc_lit_22 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"'\00" }
@sc_lit_23 = internal global { i64, i64, i64, [72 x i8] } { i64 -1, i64 71, i64 71, [72 x i8] c"[ASSERTION FAILED] Expected function to throw an error, but it did not.\00" }
@sc_lit_24 = internal global { i64, i64, i64, [26 x i8] } { i64 -1, i64 25, i64 25, [26 x i8] c"\0A=== Running Test Suite: \00" }
@sc_lit_25 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c" ===\00" }
@sc_lit_26 = internal global { i64, i64, i64, [7 x i8] } { i64 -1, i64 6, i64 6, [7 x i8] c"  \E2\9C\93 \00" }
@sc_lit_27 = internal global { i64, i64, i64, [7 x i8] } { i64 -1, i64 6, i64 6, [7 x i8] c"  \E2\9C\97 \00" }
@sc_lit_28 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c"    Error: \00" }
@sc_lit_29 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"\0AResults: \00" }
@sc_lit_30 = internal global { i64, i64, i64, [10 x i8] } { i64 -1, i64 9, i64 9, [10 x i8] c" passed, \00" }
@sc_lit_31 = internal global { i64, i64, i64, [10 x i8] } { i64 -1, i64 9, i64 9, [10 x i8] c" failed (\00" }
@sc_lit_32 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c" total)\00" }
@sc_lit_33 = internal global { i64, i64, i64, [26 x i8] } { i64 -1, i64 25, i64 25, [26 x i8] c"\E2\9D\8C Some tests failed in \00" }
@sc_lit_34 = internal global { i64, i64, i64, [25 x i8] } { i64 -1, i64 24, i64 24, [25 x i8] c"\E2\9C\85 All tests passed in \00" }
@sc_lit_35 = internal global { i64, i64, i64, [23 x i8] } { i64 -1, i64 22, i64 22, [23 x i8] c"Tensor Shape & Strides\00" }
@sc_lit_36 = internal global { i64, i64, i64, [24 x i8] } { i64 -1, i64 23, i64 23, [24 x i8] c"shapeToSize calculation\00" }
@sc_lit_37 = internal global { i64, i64, i64, [25 x i8] } { i64 -1, i64 24, i64 24, [25 x i8] c"computeStrides row-major\00" }
@sc_lit_38 = internal global { i64, i64, i64, [35 x i8] } { i64 -1, i64 34, i64 34, [35 x i8] c"validateShape rejects invalid dims\00" }
@sc_lit_39 = internal global { i64, i64, i64, [23 x i8] } { i64 -1, i64 22, i64 22, [23 x i8] c"shapesEqual comparison\00" }
@sc_lit_40 = internal global { i64, i64, i64, [26 x i8] } { i64 -1, i64 25, i64 25, [26 x i8] c"areBroadcastable checking\00" }
@sc_lit_41 = internal global { i64, i64, i64, [28 x i8] } { i64 -1, i64 27, i64 27, [28 x i8] c"broadcastShapes calculation\00" }
@sc_lit_42 = internal global { i64, i64, i64, [21 x i8] } { i64 -1, i64 20, i64 20, [21 x i8] c"non-negative integer\00" }
@sc_lit_43 = internal global { i64, i64, i64, [20 x i8] } { i64 -1, i64 19, i64 19, [20 x i8] c"Incompatible shapes\00" }

@sc_unit_0 = internal global %ScrUnion { i64 -1, i32 1, ptr null, ptr null, ptr null, i64 0 } ; u1 unit arm

@sc_cs_0 = internal constant [124 x i8] c"unreachable: a non-void function completed without returning (the checker proved every path returns) \E2\80\94 please report this\00"
@sc_cs_1 = internal constant [7 x i8] c"SC9002\00"

@sc_g_e_tests = internal global ptr null ; tests
@sc_g_m0__x25_loaded = internal global i1 false ; %loaded
@sc_g_m1__x25_loaded = internal global i1 false ; %loaded
@sc_g_e__x25_loaded = internal global i1 false ; %loaded

@sc_bad_tag_msg = internal constant [44 x i8] c"scriptc: internal error: invalid union tag\0A\00"
define internal void @sc_bad_tag() #0 {
entry:
  call void @scr_trap(ptr @sc_bad_tag_msg)
  unreachable
}

define internal ptr @sc_rretain_r0(ptr %o) #0 {
entry:
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %done, label %check
check:
  %rc = load i64, ptr %o
  %imm = icmp eq i64 %rc, -1
  br i1 %imm, label %done, label %inc
inc:
  %n = add i64 %rc, 1
  store i64 %n, ptr %o
  %colorp = getelementptr i8, ptr %o, i64 -16
  store i32 0, ptr %colorp ; mark live
  br label %done
done:
  ret ptr %o
}

define internal void @sc_rrelease_r0(ptr %o) #0 {
entry:
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %done, label %check
check:
  %rc = load i64, ptr %o
  %imm = icmp eq i64 %rc, -1
  br i1 %imm, label %done, label %dec
dec:
  %n = sub i64 %rc, 1
  store i64 %n, ptr %o
  %dead = icmp eq i64 %n, 0
  br i1 %dead, label %free, label %root
free:
  call void @scr_cyc_on_dead(ptr %o)
  %f0 = getelementptr inbounds %sc_rs_r0, ptr %o, i64 0, i32 1
  %v0 = load ptr, ptr %f0
  call void @scr_closure_release(ptr %v0) ; fn
  %f1 = getelementptr inbounds %sc_rs_r0, ptr %o, i64 0, i32 2
  %v1 = load ptr, ptr %f1
  call void @scr_str_release(ptr %v1) ; name
  call void @scr_obj_free_note()
  call void @scr_cyc_free(ptr %o)
  br label %done
root:
  call void @scr_cyc_on_release(ptr %o) ; possible cycle root; may collect
  br label %done
done:
  ret void
}

define internal ptr @sc_rnew_r0() #0 {
entry:
  %o = call ptr @scr_cyc_alloc(i64 ptrtoint (ptr getelementptr (%sc_rs_r0, ptr null, i32 1) to i64), ptr @sc_rtrace_r0, ptr @sc_rgcfree_r0)
  store i64 1, ptr %o
  call void @scr_obj_alloc_note()
  ret ptr %o
}

define internal void @sc_rtrace_r0(ptr %o, ptr %visit, ptr %ctx) #0 {
entry:
  %f0 = getelementptr inbounds %sc_rs_r0, ptr %o, i64 0, i32 1
  %v0 = load ptr, ptr %f0
  call void %visit(ptr %v0, ptr %ctx) ; fn
  ret void
}

define internal void @sc_rgcfree_r0(ptr %o) #0 {
entry:
  %f0 = getelementptr inbounds %sc_rs_r0, ptr %o, i64 0, i32 2
  %v0 = load ptr, ptr %f0
  call void @scr_str_release(ptr %v0) ; name (acyclic)
  call void @scr_obj_free_note()
  call void @scr_cyc_free(ptr %o)
  ret void
}

define internal double @sc_f__x25_m0_shapeToSize(ptr %p_sc_l_shape_0) #0 { ; %m0.shapeToSize
entry:
  %sc_l_shape_0 = alloca ptr ; shape
  %sc_l_size_0 = alloca double ; size
  %sc_l_i_0 = alloca double ; i
  %sc_l_dim_0 = alloca double ; dim
  store ptr %p_sc_l_shape_0, ptr %sc_l_shape_0
  %t0 = load ptr, ptr %sc_l_shape_0
  %t1 = call ptr @scr_arr_retain_v(ptr %t0)
  %t2 = call double @scr_arr_len(ptr %t1)
  %t3 = fcmp oeq double %t2, 0x0000000000000000
  call void @scr_arr_release(ptr %t1)
  br i1 %t3, label %if.t0, label %if.j1
if.t0:
  %t4 = load ptr, ptr %sc_l_shape_0
  call void @scr_arr_release(ptr %t4)
  ret double 0x0000000000000000
if.j1:
  store double 0x3FF0000000000000, ptr %sc_l_size_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c2
loop.c2:
  %t5 = load double, ptr %sc_l_i_0
  %t6 = load ptr, ptr %sc_l_shape_0
  %t7 = call ptr @scr_arr_retain_v(ptr %t6)
  %t8 = call double @scr_arr_len(ptr %t7)
  %t9 = fcmp olt double %t5, %t8
  call void @scr_arr_release(ptr %t7)
  br i1 %t9, label %loop.b3, label %loop.e4
loop.b3:
  %t10 = load ptr, ptr %sc_l_shape_0
  %t11 = call ptr @scr_arr_retain_v(ptr %t10)
  %t12 = load double, ptr %sc_l_i_0
  %t13 = call double @scr_arr_get_f64(ptr %t11, double %t12)
  store double %t13, ptr %sc_l_dim_0
  call void @scr_arr_release(ptr %t11)
  %t14 = load double, ptr %sc_l_dim_0
  %t15 = fcmp olt double %t14, 0x0000000000000000
  br i1 %t15, label %if.t6, label %if.j7
if.t6:
  %t16 = call ptr @scr_str_retain_v(ptr @sc_lit_0)
  %t17 = load double, ptr %sc_l_dim_0
  %t18 = call ptr @scr_f64_to_scrstr(double %t17)
  %t19 = call ptr @scr_str_concat(ptr %t16, ptr %t18)
  %t20 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t21 = call ptr @scr_str_concat(ptr %t19, ptr %t20)
  %t22 = load double, ptr %sc_l_i_0
  %t23 = call ptr @scr_f64_to_scrstr(double %t22)
  %t24 = call ptr @scr_str_concat(ptr %t21, ptr %t23)
  %t25 = call ptr @scr_error_new(i32 0, ptr %t24)
  call void @scr_throw_obj(ptr %t25, ptr @scr_error_retain_v, ptr @scr_error_release_v, ptr null)
  call void @scr_str_release(ptr %t16)
  call void @scr_str_release(ptr %t18)
  call void @scr_str_release(ptr %t19)
  call void @scr_str_release(ptr %t20)
  call void @scr_str_release(ptr %t21)
  call void @scr_str_release(ptr %t23)
  call void @scr_str_release(ptr %t24)
  %t26 = load ptr, ptr %sc_l_shape_0
  call void @scr_arr_release(ptr %t26)
  ret double 0x0000000000000000
if.j7:
  %t27 = load double, ptr %sc_l_size_0
  %t28 = load double, ptr %sc_l_dim_0
  %t29 = fmul double %t27, %t28
  store double %t29, ptr %sc_l_size_0
  br label %loop.u5
loop.u5:
  %t30 = load double, ptr %sc_l_i_0
  %t31 = fadd double %t30, 0x3FF0000000000000
  store double %t31, ptr %sc_l_i_0
  br label %loop.c2
loop.e4:
  %t32 = load double, ptr %sc_l_size_0
  %t33 = load ptr, ptr %sc_l_shape_0
  call void @scr_arr_release(ptr %t33)
  ret double %t32
}

define internal ptr @sc_f__x25_m0_computeStrides(ptr %p_sc_l_shape_0) #0 { ; %m0.computeStrides
entry:
  %sc_l_shape_0 = alloca ptr ; shape
  %sc_l_ndim_0 = alloca double ; ndim
  %sc_l_strides_0 = alloca ptr ; strides
  %sc_l_i_0 = alloca double ; i
  %sc_l_currentStride_0 = alloca double ; currentStride
  %sc_l_i_1 = alloca double ; i
  store ptr null, ptr %sc_l_strides_0
  store ptr %p_sc_l_shape_0, ptr %sc_l_shape_0
  %t0 = load ptr, ptr %sc_l_shape_0
  %t1 = call ptr @scr_arr_retain_v(ptr %t0)
  %t2 = call double @scr_arr_len(ptr %t1)
  store double %t2, ptr %sc_l_ndim_0
  call void @scr_arr_release(ptr %t1)
  %t3 = load double, ptr %sc_l_ndim_0
  %t4 = fcmp oeq double %t3, 0x0000000000000000
  br i1 %t4, label %if.t0, label %if.j1
if.t0:
  %t5 = call ptr @scr_arr_new(i32 0, i64 0)
  %t6 = load ptr, ptr %sc_l_shape_0
  call void @scr_arr_release(ptr %t6)
  ret ptr %t5
if.j1:
  %t7 = call ptr @scr_arr_new(i32 0, i64 0)
  store ptr %t7, ptr %sc_l_strides_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c2
loop.c2:
  %t8 = load double, ptr %sc_l_i_0
  %t9 = load double, ptr %sc_l_ndim_0
  %t10 = fcmp olt double %t8, %t9
  br i1 %t10, label %loop.b3, label %loop.e4
loop.b3:
  %t11 = load ptr, ptr %sc_l_strides_0
  %t12 = call ptr @scr_arr_retain_v(ptr %t11)
  %t13 = call double @scr_arr_push_f64(ptr %t12, double 0x0000000000000000)
  call void @scr_arr_release(ptr %t12)
  br label %loop.u5
loop.u5:
  %t14 = load double, ptr %sc_l_i_0
  %t15 = fadd double %t14, 0x3FF0000000000000
  store double %t15, ptr %sc_l_i_0
  br label %loop.c2
loop.e4:
  store double 0x3FF0000000000000, ptr %sc_l_currentStride_0
  %t16 = load double, ptr %sc_l_ndim_0
  %t17 = fsub double %t16, 0x3FF0000000000000
  store double %t17, ptr %sc_l_i_1
  br label %loop.c6
loop.c6:
  %t18 = load double, ptr %sc_l_i_1
  %t19 = fcmp oge double %t18, 0x0000000000000000
  br i1 %t19, label %loop.b7, label %loop.e8
loop.b7:
  %t20 = load ptr, ptr %sc_l_strides_0
  %t21 = call ptr @scr_arr_retain_v(ptr %t20)
  %t22 = load double, ptr %sc_l_i_1
  %t23 = load double, ptr %sc_l_currentStride_0
  call void @scr_arr_set_f64(ptr %t21, double %t22, double %t23)
  call void @scr_arr_release(ptr %t21)
  %t24 = load double, ptr %sc_l_currentStride_0
  %t25 = load ptr, ptr %sc_l_shape_0
  %t26 = call ptr @scr_arr_retain_v(ptr %t25)
  %t27 = load double, ptr %sc_l_i_1
  %t28 = call double @scr_arr_get_f64(ptr %t26, double %t27)
  %t29 = fmul double %t24, %t28
  store double %t29, ptr %sc_l_currentStride_0
  call void @scr_arr_release(ptr %t26)
  br label %loop.u9
loop.u9:
  %t30 = load double, ptr %sc_l_i_1
  %t31 = fsub double %t30, 0x3FF0000000000000
  store double %t31, ptr %sc_l_i_1
  br label %loop.c6
loop.e8:
  %t32 = load ptr, ptr %sc_l_strides_0
  %t33 = call ptr @scr_arr_retain_v(ptr %t32)
  %t34 = load ptr, ptr %sc_l_shape_0
  call void @scr_arr_release(ptr %t34)
  %t35 = load ptr, ptr %sc_l_strides_0
  call void @scr_arr_release(ptr %t35)
  ret ptr %t33
}

define internal void @sc_f__x25_m0_validateShape(ptr %p_sc_l_shape_0) #0 { ; %m0.validateShape
entry:
  %sc_l_shape_0 = alloca ptr ; shape
  %sc_l_i_0 = alloca double ; i
  %s10 = alloca i1
  store ptr %p_sc_l_shape_0, ptr %sc_l_shape_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c0
loop.c0:
  %t0 = load double, ptr %sc_l_i_0
  %t1 = load ptr, ptr %sc_l_shape_0
  %t2 = call ptr @scr_arr_retain_v(ptr %t1)
  %t3 = call double @scr_arr_len(ptr %t2)
  %t4 = fcmp olt double %t0, %t3
  call void @scr_arr_release(ptr %t2)
  br i1 %t4, label %loop.b1, label %loop.e2
loop.b1:
  %t5 = load ptr, ptr %sc_l_shape_0
  %t6 = call ptr @scr_arr_retain_v(ptr %t5)
  %t7 = load double, ptr %sc_l_i_0
  %t8 = call double @scr_arr_get_f64(ptr %t6, double %t7)
  %t9 = fcmp olt double %t8, 0x0000000000000000
  store i1 %t9, ptr %s10
  br i1 %t9, label %log.j5, label %log.r4
log.r4:
  %t11 = load ptr, ptr %sc_l_shape_0
  %t12 = call ptr @scr_arr_retain_v(ptr %t11)
  %t13 = load double, ptr %sc_l_i_0
  %t14 = call double @scr_arr_get_f64(ptr %t12, double %t13)
  %t15 = call double @llvm.floor.f64(double %t14)
  %t16 = load ptr, ptr %sc_l_shape_0
  %t17 = call ptr @scr_arr_retain_v(ptr %t16)
  %t18 = load double, ptr %sc_l_i_0
  %t19 = call double @scr_arr_get_f64(ptr %t17, double %t18)
  %t20 = fcmp une double %t15, %t19
  store i1 %t20, ptr %s10
  call void @scr_arr_release(ptr %t12)
  call void @scr_arr_release(ptr %t17)
  br label %log.j5
log.j5:
  %t21 = load i1, ptr %s10
  call void @scr_arr_release(ptr %t6)
  br i1 %t21, label %if.t6, label %if.j7
if.t6:
  %t22 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  %t23 = load double, ptr %sc_l_i_0
  %t24 = call ptr @scr_f64_to_scrstr(double %t23)
  %t25 = call ptr @scr_str_concat(ptr %t22, ptr %t24)
  %t26 = call ptr @scr_str_retain_v(ptr @sc_lit_3)
  %t27 = call ptr @scr_str_concat(ptr %t25, ptr %t26)
  %t28 = load ptr, ptr %sc_l_shape_0
  %t29 = call ptr @scr_arr_retain_v(ptr %t28)
  %t30 = load double, ptr %sc_l_i_0
  %t31 = call double @scr_arr_get_f64(ptr %t29, double %t30)
  %t32 = call ptr @scr_f64_to_scrstr(double %t31)
  %t33 = call ptr @scr_str_concat(ptr %t27, ptr %t32)
  %t34 = call ptr @scr_error_new(i32 0, ptr %t33)
  call void @scr_throw_obj(ptr %t34, ptr @scr_error_retain_v, ptr @scr_error_release_v, ptr null)
  call void @scr_str_release(ptr %t22)
  call void @scr_str_release(ptr %t24)
  call void @scr_str_release(ptr %t25)
  call void @scr_str_release(ptr %t26)
  call void @scr_str_release(ptr %t27)
  call void @scr_arr_release(ptr %t29)
  call void @scr_str_release(ptr %t32)
  call void @scr_str_release(ptr %t33)
  %t35 = load ptr, ptr %sc_l_shape_0
  call void @scr_arr_release(ptr %t35)
  ret void
if.j7:
  br label %loop.u3
loop.u3:
  %t36 = load double, ptr %sc_l_i_0
  %t37 = fadd double %t36, 0x3FF0000000000000
  store double %t37, ptr %sc_l_i_0
  br label %loop.c0
loop.e2:
  %t38 = load ptr, ptr %sc_l_shape_0
  call void @scr_arr_release(ptr %t38)
  ret void
}

define internal i1 @sc_f__x25_m0_shapesEqual(ptr %p_sc_l_a_0, ptr %p_sc_l_b_0) #0 { ; %m0.shapesEqual
entry:
  %sc_l_a_0 = alloca ptr ; a
  %sc_l_b_0 = alloca ptr ; b
  %sc_l_i_0 = alloca double ; i
  store ptr %p_sc_l_a_0, ptr %sc_l_a_0
  store ptr %p_sc_l_b_0, ptr %sc_l_b_0
  %t0 = load ptr, ptr %sc_l_a_0
  %t1 = call ptr @scr_arr_retain_v(ptr %t0)
  %t2 = call double @scr_arr_len(ptr %t1)
  %t3 = load ptr, ptr %sc_l_b_0
  %t4 = call ptr @scr_arr_retain_v(ptr %t3)
  %t5 = call double @scr_arr_len(ptr %t4)
  %t6 = fcmp une double %t2, %t5
  call void @scr_arr_release(ptr %t1)
  call void @scr_arr_release(ptr %t4)
  br i1 %t6, label %if.t0, label %if.j1
if.t0:
  %t7 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t7)
  %t8 = load ptr, ptr %sc_l_b_0
  call void @scr_arr_release(ptr %t8)
  ret i1 false
if.j1:
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c2
loop.c2:
  %t9 = load double, ptr %sc_l_i_0
  %t10 = load ptr, ptr %sc_l_a_0
  %t11 = call ptr @scr_arr_retain_v(ptr %t10)
  %t12 = call double @scr_arr_len(ptr %t11)
  %t13 = fcmp olt double %t9, %t12
  call void @scr_arr_release(ptr %t11)
  br i1 %t13, label %loop.b3, label %loop.e4
loop.b3:
  %t14 = load ptr, ptr %sc_l_a_0
  %t15 = call ptr @scr_arr_retain_v(ptr %t14)
  %t16 = load double, ptr %sc_l_i_0
  %t17 = call double @scr_arr_get_f64(ptr %t15, double %t16)
  %t18 = load ptr, ptr %sc_l_b_0
  %t19 = call ptr @scr_arr_retain_v(ptr %t18)
  %t20 = load double, ptr %sc_l_i_0
  %t21 = call double @scr_arr_get_f64(ptr %t19, double %t20)
  %t22 = fcmp une double %t17, %t21
  call void @scr_arr_release(ptr %t15)
  call void @scr_arr_release(ptr %t19)
  br i1 %t22, label %if.t6, label %if.j7
if.t6:
  %t23 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t23)
  %t24 = load ptr, ptr %sc_l_b_0
  call void @scr_arr_release(ptr %t24)
  ret i1 false
if.j7:
  br label %loop.u5
loop.u5:
  %t25 = load double, ptr %sc_l_i_0
  %t26 = fadd double %t25, 0x3FF0000000000000
  store double %t26, ptr %sc_l_i_0
  br label %loop.c2
loop.e4:
  %t27 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t27)
  %t28 = load ptr, ptr %sc_l_b_0
  call void @scr_arr_release(ptr %t28)
  ret i1 true
}

define internal i1 @sc_f__x25_m0_areBroadcastable(ptr %p_sc_l_a_0, ptr %p_sc_l_b_0) #0 { ; %m0.areBroadcastable
entry:
  %sc_l_a_0 = alloca ptr ; a
  %sc_l_b_0 = alloca ptr ; b
  %sc_l_maxLen_0 = alloca double ; maxLen
  %sc_l_padA_0 = alloca ptr ; padA
  %sc_l_padB_0 = alloca ptr ; padB
  %sc_l_i_0 = alloca double ; i
  %sc_l_da_0 = alloca double ; da
  %sc_l_db_0 = alloca double ; db
  %s29 = alloca i1
  %s33 = alloca i1
  store ptr null, ptr %sc_l_padA_0
  store ptr null, ptr %sc_l_padB_0
  store ptr %p_sc_l_a_0, ptr %sc_l_a_0
  store ptr %p_sc_l_b_0, ptr %sc_l_b_0
  %t0 = load ptr, ptr %sc_l_a_0
  %t1 = call ptr @scr_arr_retain_v(ptr %t0)
  %t2 = call double @scr_arr_len(ptr %t1)
  %t3 = load ptr, ptr %sc_l_b_0
  %t4 = call ptr @scr_arr_retain_v(ptr %t3)
  %t5 = call double @scr_arr_len(ptr %t4)
  %t6 = call double @scr_math_max(double %t2, double %t5)
  store double %t6, ptr %sc_l_maxLen_0
  call void @scr_arr_release(ptr %t1)
  call void @scr_arr_release(ptr %t4)
  %t7 = load ptr, ptr %sc_l_a_0
  %t8 = call ptr @scr_arr_retain_v(ptr %t7)
  %t9 = load double, ptr %sc_l_maxLen_0
  %t10 = call ptr @sc_f__x25_m0_padShape(ptr %t8, double %t9)
  store ptr %t10, ptr %sc_l_padA_0
  %t11 = load ptr, ptr %sc_l_b_0
  %t12 = call ptr @scr_arr_retain_v(ptr %t11)
  %t13 = load double, ptr %sc_l_maxLen_0
  %t14 = call ptr @sc_f__x25_m0_padShape(ptr %t12, double %t13)
  store ptr %t14, ptr %sc_l_padB_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c0
loop.c0:
  %t15 = load double, ptr %sc_l_i_0
  %t16 = load double, ptr %sc_l_maxLen_0
  %t17 = fcmp olt double %t15, %t16
  br i1 %t17, label %loop.b1, label %loop.e2
loop.b1:
  %t18 = load ptr, ptr %sc_l_padA_0
  %t19 = call ptr @scr_arr_retain_v(ptr %t18)
  %t20 = load double, ptr %sc_l_i_0
  %t21 = call double @scr_arr_get_f64(ptr %t19, double %t20)
  store double %t21, ptr %sc_l_da_0
  call void @scr_arr_release(ptr %t19)
  %t22 = load ptr, ptr %sc_l_padB_0
  %t23 = call ptr @scr_arr_retain_v(ptr %t22)
  %t24 = load double, ptr %sc_l_i_0
  %t25 = call double @scr_arr_get_f64(ptr %t23, double %t24)
  store double %t25, ptr %sc_l_db_0
  call void @scr_arr_release(ptr %t23)
  %t26 = load double, ptr %sc_l_da_0
  %t27 = load double, ptr %sc_l_db_0
  %t28 = fcmp une double %t26, %t27
  store i1 %t28, ptr %s29
  br i1 %t28, label %log.r4, label %log.j5
log.r4:
  %t30 = load double, ptr %sc_l_da_0
  %t31 = fcmp une double %t30, 0x3FF0000000000000
  store i1 %t31, ptr %s29
  br label %log.j5
log.j5:
  %t32 = load i1, ptr %s29
  store i1 %t32, ptr %s33
  br i1 %t32, label %log.r6, label %log.j7
log.r6:
  %t34 = load double, ptr %sc_l_db_0
  %t35 = fcmp une double %t34, 0x3FF0000000000000
  store i1 %t35, ptr %s33
  br label %log.j7
log.j7:
  %t36 = load i1, ptr %s33
  br i1 %t36, label %if.t8, label %if.j9
if.t8:
  %t37 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t37)
  %t38 = load ptr, ptr %sc_l_b_0
  call void @scr_arr_release(ptr %t38)
  %t39 = load ptr, ptr %sc_l_padA_0
  call void @scr_arr_release(ptr %t39)
  %t40 = load ptr, ptr %sc_l_padB_0
  call void @scr_arr_release(ptr %t40)
  ret i1 false
if.j9:
  br label %loop.u3
loop.u3:
  %t41 = load double, ptr %sc_l_i_0
  %t42 = fadd double %t41, 0x3FF0000000000000
  store double %t42, ptr %sc_l_i_0
  br label %loop.c0
loop.e2:
  %t43 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t43)
  %t44 = load ptr, ptr %sc_l_b_0
  call void @scr_arr_release(ptr %t44)
  %t45 = load ptr, ptr %sc_l_padA_0
  call void @scr_arr_release(ptr %t45)
  %t46 = load ptr, ptr %sc_l_padB_0
  call void @scr_arr_release(ptr %t46)
  ret i1 true
}

define internal ptr @sc_f__x25_m0_broadcastShapes(ptr %p_sc_l_a_0, ptr %p_sc_l_b_0) #0 { ; %m0.broadcastShapes
entry:
  %sc_l_a_0 = alloca ptr ; a
  %sc_l_b_0 = alloca ptr ; b
  %sc_l_maxLen_0 = alloca double ; maxLen
  %sc_l_padA_0 = alloca ptr ; padA
  %sc_l_padB_0 = alloca ptr ; padB
  %sc_l_outShape_0 = alloca ptr ; outShape
  %sc_l_i_0 = alloca double ; i
  %sc_l_da_0 = alloca double ; da
  %sc_l_db_0 = alloca double ; db
  store ptr null, ptr %sc_l_padA_0
  store ptr null, ptr %sc_l_padB_0
  store ptr null, ptr %sc_l_outShape_0
  store ptr %p_sc_l_a_0, ptr %sc_l_a_0
  store ptr %p_sc_l_b_0, ptr %sc_l_b_0
  %t0 = load ptr, ptr %sc_l_a_0
  %t1 = call ptr @scr_arr_retain_v(ptr %t0)
  %t2 = call double @scr_arr_len(ptr %t1)
  %t3 = load ptr, ptr %sc_l_b_0
  %t4 = call ptr @scr_arr_retain_v(ptr %t3)
  %t5 = call double @scr_arr_len(ptr %t4)
  %t6 = call double @scr_math_max(double %t2, double %t5)
  store double %t6, ptr %sc_l_maxLen_0
  call void @scr_arr_release(ptr %t1)
  call void @scr_arr_release(ptr %t4)
  %t7 = load ptr, ptr %sc_l_a_0
  %t8 = call ptr @scr_arr_retain_v(ptr %t7)
  %t9 = load double, ptr %sc_l_maxLen_0
  %t10 = call ptr @sc_f__x25_m0_padShape(ptr %t8, double %t9)
  store ptr %t10, ptr %sc_l_padA_0
  %t11 = load ptr, ptr %sc_l_b_0
  %t12 = call ptr @scr_arr_retain_v(ptr %t11)
  %t13 = load double, ptr %sc_l_maxLen_0
  %t14 = call ptr @sc_f__x25_m0_padShape(ptr %t12, double %t13)
  store ptr %t14, ptr %sc_l_padB_0
  %t15 = call ptr @scr_arr_new(i32 0, i64 0)
  store ptr %t15, ptr %sc_l_outShape_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c0
loop.c0:
  %t16 = load double, ptr %sc_l_i_0
  %t17 = load double, ptr %sc_l_maxLen_0
  %t18 = fcmp olt double %t16, %t17
  br i1 %t18, label %loop.b1, label %loop.e2
loop.b1:
  %t19 = load ptr, ptr %sc_l_padA_0
  %t20 = call ptr @scr_arr_retain_v(ptr %t19)
  %t21 = load double, ptr %sc_l_i_0
  %t22 = call double @scr_arr_get_f64(ptr %t20, double %t21)
  store double %t22, ptr %sc_l_da_0
  call void @scr_arr_release(ptr %t20)
  %t23 = load ptr, ptr %sc_l_padB_0
  %t24 = call ptr @scr_arr_retain_v(ptr %t23)
  %t25 = load double, ptr %sc_l_i_0
  %t26 = call double @scr_arr_get_f64(ptr %t24, double %t25)
  store double %t26, ptr %sc_l_db_0
  call void @scr_arr_release(ptr %t24)
  %t27 = load double, ptr %sc_l_da_0
  %t28 = load double, ptr %sc_l_db_0
  %t29 = fcmp oeq double %t27, %t28
  br i1 %t29, label %if.t4, label %if.f6
if.t4:
  %t30 = load ptr, ptr %sc_l_outShape_0
  %t31 = call ptr @scr_arr_retain_v(ptr %t30)
  %t32 = load double, ptr %sc_l_da_0
  %t33 = call double @scr_arr_push_f64(ptr %t31, double %t32)
  call void @scr_arr_release(ptr %t31)
  br label %if.j5
if.f6:
  %t34 = load double, ptr %sc_l_da_0
  %t35 = fcmp oeq double %t34, 0x3FF0000000000000
  br i1 %t35, label %if.t7, label %if.f9
if.t7:
  %t36 = load ptr, ptr %sc_l_outShape_0
  %t37 = call ptr @scr_arr_retain_v(ptr %t36)
  %t38 = load double, ptr %sc_l_db_0
  %t39 = call double @scr_arr_push_f64(ptr %t37, double %t38)
  call void @scr_arr_release(ptr %t37)
  br label %if.j8
if.f9:
  %t40 = load double, ptr %sc_l_db_0
  %t41 = fcmp oeq double %t40, 0x3FF0000000000000
  br i1 %t41, label %if.t10, label %if.f12
if.t10:
  %t42 = load ptr, ptr %sc_l_outShape_0
  %t43 = call ptr @scr_arr_retain_v(ptr %t42)
  %t44 = load double, ptr %sc_l_da_0
  %t45 = call double @scr_arr_push_f64(ptr %t43, double %t44)
  call void @scr_arr_release(ptr %t43)
  br label %if.j11
if.f12:
  %t46 = call ptr @scr_str_retain_v(ptr @sc_lit_4)
  %t47 = load ptr, ptr %sc_l_a_0
  %t48 = call ptr @scr_arr_retain_v(ptr %t47)
  %t49 = call ptr @scr_str_retain_v(ptr @sc_lit_5)
  %t50 = call ptr @scr_arr_join(ptr %t48, ptr %t49)
  %t51 = call ptr @scr_str_concat(ptr %t46, ptr %t50)
  %t52 = call ptr @scr_str_retain_v(ptr @sc_lit_6)
  %t53 = call ptr @scr_str_concat(ptr %t51, ptr %t52)
  %t54 = load ptr, ptr %sc_l_b_0
  %t55 = call ptr @scr_arr_retain_v(ptr %t54)
  %t56 = call ptr @scr_str_retain_v(ptr @sc_lit_5)
  %t57 = call ptr @scr_arr_join(ptr %t55, ptr %t56)
  %t58 = call ptr @scr_str_concat(ptr %t53, ptr %t57)
  %t59 = call ptr @scr_str_retain_v(ptr @sc_lit_7)
  %t60 = call ptr @scr_str_concat(ptr %t58, ptr %t59)
  %t61 = call ptr @scr_error_new(i32 0, ptr %t60)
  call void @scr_throw_obj(ptr %t61, ptr @scr_error_retain_v, ptr @scr_error_release_v, ptr null)
  call void @scr_str_release(ptr %t46)
  call void @scr_arr_release(ptr %t48)
  call void @scr_str_release(ptr %t49)
  call void @scr_str_release(ptr %t50)
  call void @scr_str_release(ptr %t51)
  call void @scr_str_release(ptr %t52)
  call void @scr_str_release(ptr %t53)
  call void @scr_arr_release(ptr %t55)
  call void @scr_str_release(ptr %t56)
  call void @scr_str_release(ptr %t57)
  call void @scr_str_release(ptr %t58)
  call void @scr_str_release(ptr %t59)
  call void @scr_str_release(ptr %t60)
  %t62 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t62)
  %t63 = load ptr, ptr %sc_l_b_0
  call void @scr_arr_release(ptr %t63)
  %t64 = load ptr, ptr %sc_l_padA_0
  call void @scr_arr_release(ptr %t64)
  %t65 = load ptr, ptr %sc_l_padB_0
  call void @scr_arr_release(ptr %t65)
  %t66 = load ptr, ptr %sc_l_outShape_0
  call void @scr_arr_release(ptr %t66)
  ret ptr null
if.j11:
  br label %if.j8
if.j8:
  br label %if.j5
if.j5:
  br label %loop.u3
loop.u3:
  %t67 = load double, ptr %sc_l_i_0
  %t68 = fadd double %t67, 0x3FF0000000000000
  store double %t68, ptr %sc_l_i_0
  br label %loop.c0
loop.e2:
  %t69 = load ptr, ptr %sc_l_outShape_0
  %t70 = call ptr @scr_arr_retain_v(ptr %t69)
  %t71 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t71)
  %t72 = load ptr, ptr %sc_l_b_0
  call void @scr_arr_release(ptr %t72)
  %t73 = load ptr, ptr %sc_l_padA_0
  call void @scr_arr_release(ptr %t73)
  %t74 = load ptr, ptr %sc_l_padB_0
  call void @scr_arr_release(ptr %t74)
  %t75 = load ptr, ptr %sc_l_outShape_0
  call void @scr_arr_release(ptr %t75)
  ret ptr %t70
}

define internal ptr @sc_f__x25_m0_padShape(ptr %p_sc_l_shape_0, double %p_sc_l_targetLength_0) #0 { ; %m0.padShape
entry:
  %sc_l_shape_0 = alloca ptr ; shape
  %sc_l_targetLength_0 = alloca double ; targetLength
  %sc_l_padCount_0 = alloca double ; padCount
  %sc_l_result_0 = alloca ptr ; result
  %sc_l_i_0 = alloca double ; i
  %sc_l_i_1 = alloca double ; i
  store ptr null, ptr %sc_l_result_0
  store ptr %p_sc_l_shape_0, ptr %sc_l_shape_0
  store double %p_sc_l_targetLength_0, ptr %sc_l_targetLength_0
  %t0 = load double, ptr %sc_l_targetLength_0
  %t1 = load ptr, ptr %sc_l_shape_0
  %t2 = call ptr @scr_arr_retain_v(ptr %t1)
  %t3 = call double @scr_arr_len(ptr %t2)
  %t4 = fsub double %t0, %t3
  store double %t4, ptr %sc_l_padCount_0
  call void @scr_arr_release(ptr %t2)
  %t5 = call ptr @scr_arr_new(i32 0, i64 0)
  store ptr %t5, ptr %sc_l_result_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c0
loop.c0:
  %t6 = load double, ptr %sc_l_i_0
  %t7 = load double, ptr %sc_l_padCount_0
  %t8 = fcmp olt double %t6, %t7
  br i1 %t8, label %loop.b1, label %loop.e2
loop.b1:
  %t9 = load ptr, ptr %sc_l_result_0
  %t10 = call ptr @scr_arr_retain_v(ptr %t9)
  %t11 = call double @scr_arr_push_f64(ptr %t10, double 0x3FF0000000000000)
  call void @scr_arr_release(ptr %t10)
  br label %loop.u3
loop.u3:
  %t12 = load double, ptr %sc_l_i_0
  %t13 = fadd double %t12, 0x3FF0000000000000
  store double %t13, ptr %sc_l_i_0
  br label %loop.c0
loop.e2:
  store double 0x0000000000000000, ptr %sc_l_i_1
  br label %loop.c4
loop.c4:
  %t14 = load double, ptr %sc_l_i_1
  %t15 = load ptr, ptr %sc_l_shape_0
  %t16 = call ptr @scr_arr_retain_v(ptr %t15)
  %t17 = call double @scr_arr_len(ptr %t16)
  %t18 = fcmp olt double %t14, %t17
  call void @scr_arr_release(ptr %t16)
  br i1 %t18, label %loop.b5, label %loop.e6
loop.b5:
  %t19 = load ptr, ptr %sc_l_result_0
  %t20 = call ptr @scr_arr_retain_v(ptr %t19)
  %t21 = load ptr, ptr %sc_l_shape_0
  %t22 = call ptr @scr_arr_retain_v(ptr %t21)
  %t23 = load double, ptr %sc_l_i_1
  %t24 = call double @scr_arr_get_f64(ptr %t22, double %t23)
  %t25 = call double @scr_arr_push_f64(ptr %t20, double %t24)
  call void @scr_arr_release(ptr %t20)
  call void @scr_arr_release(ptr %t22)
  br label %loop.u7
loop.u7:
  %t26 = load double, ptr %sc_l_i_1
  %t27 = fadd double %t26, 0x3FF0000000000000
  store double %t27, ptr %sc_l_i_1
  br label %loop.c4
loop.e6:
  %t28 = load ptr, ptr %sc_l_result_0
  %t29 = call ptr @scr_arr_retain_v(ptr %t28)
  %t30 = load ptr, ptr %sc_l_shape_0
  call void @scr_arr_release(ptr %t30)
  %t31 = load ptr, ptr %sc_l_result_0
  call void @scr_arr_release(ptr %t31)
  ret ptr %t29
}

define internal void @sc_f__x25_m1_assert(i1 %p_sc_l_condition_0, ptr %p_sc_l_message_0) #0 { ; %m1.assert
entry:
  %sc_l_condition_0 = alloca i1 ; condition
  %sc_l_message_0 = alloca ptr ; message
  %sc_l_message_1 = alloca ptr ; message
  %s5 = alloca ptr
  store ptr null, ptr %sc_l_message_1
  store i1 %p_sc_l_condition_0, ptr %sc_l_condition_0
  store ptr %p_sc_l_message_0, ptr %sc_l_message_0
  %t0 = load ptr, ptr %sc_l_message_0
  %t1 = call ptr @scr_union_retain_v(ptr %t0)
  %t2 = getelementptr inbounds %ScrUnion, ptr %t1, i64 0, i32 1
  %t3 = load i32, ptr %t2
  %t4 = icmp eq i32 %t3, 1
  br i1 %t4, label %tern.t0, label %tern.f1
tern.t0:
  %t6 = call ptr @scr_str_retain_v(ptr @sc_lit_8)
  store ptr %t6, ptr %s5
  br label %tern.j2
tern.f1:
  %t7 = load ptr, ptr %sc_l_message_0
  %t8 = call ptr @scr_union_retain_v(ptr %t7)
  %t9 = getelementptr inbounds %ScrUnion, ptr %t8, i64 0, i32 5
  %t10 = load ptr, ptr %t9
  %t11 = call ptr @scr_str_retain_v(ptr %t10)
  store ptr %t11, ptr %s5
  call void @scr_union_release(ptr %t8)
  br label %tern.j2
tern.j2:
  %t12 = load ptr, ptr %s5
  store ptr %t12, ptr %sc_l_message_1
  call void @scr_union_release(ptr %t1)
  %t13 = load i1, ptr %sc_l_condition_0
  %t14 = xor i1 %t13, true
  br i1 %t14, label %if.t3, label %if.j4
if.t3:
  %t15 = call ptr @scr_str_retain_v(ptr @sc_lit_9)
  %t16 = load ptr, ptr %sc_l_message_1
  %t17 = call ptr @scr_str_retain_v(ptr %t16)
  %t18 = call ptr @scr_str_concat(ptr %t15, ptr %t17)
  %t19 = call ptr @scr_error_new(i32 0, ptr %t18)
  call void @scr_throw_obj(ptr %t19, ptr @scr_error_retain_v, ptr @scr_error_release_v, ptr null)
  call void @scr_str_release(ptr %t15)
  call void @scr_str_release(ptr %t17)
  call void @scr_str_release(ptr %t18)
  %t20 = load ptr, ptr %sc_l_message_0
  call void @scr_union_release(ptr %t20)
  %t21 = load ptr, ptr %sc_l_message_1
  call void @scr_str_release(ptr %t21)
  ret void
if.j4:
  %t22 = load ptr, ptr %sc_l_message_0
  call void @scr_union_release(ptr %t22)
  %t23 = load ptr, ptr %sc_l_message_1
  call void @scr_str_release(ptr %t23)
  ret void
}

define internal void @sc_f__x25_m1_assertEqual(ptr %p_sc_l_actual_0, ptr %p_sc_l_expected_0, ptr %p_sc_l_message_0) #0 { ; %m1.assertEqual
entry:
  %sc_l_actual_0 = alloca ptr ; actual
  %sc_l_expected_0 = alloca ptr ; expected
  %sc_l_message_0 = alloca ptr ; message
  %sc_l_message_1 = alloca ptr ; message
  %sc_l_detail_0 = alloca ptr ; detail
  %s5 = alloca ptr
  %s17 = alloca i1
  %s42 = alloca ptr
  %s54 = alloca ptr
  %s70 = alloca ptr
  store ptr null, ptr %sc_l_message_1
  store ptr null, ptr %sc_l_detail_0
  store ptr %p_sc_l_actual_0, ptr %sc_l_actual_0
  store ptr %p_sc_l_expected_0, ptr %sc_l_expected_0
  store ptr %p_sc_l_message_0, ptr %sc_l_message_0
  %t0 = load ptr, ptr %sc_l_message_0
  %t1 = call ptr @scr_union_retain_v(ptr %t0)
  %t2 = getelementptr inbounds %ScrUnion, ptr %t1, i64 0, i32 1
  %t3 = load i32, ptr %t2
  %t4 = icmp eq i32 %t3, 1
  br i1 %t4, label %tern.t0, label %tern.f1
tern.t0:
  %t6 = call ptr @scr_str_retain_v(ptr @sc_lit_10)
  store ptr %t6, ptr %s5
  br label %tern.j2
tern.f1:
  %t7 = load ptr, ptr %sc_l_message_0
  %t8 = call ptr @scr_union_retain_v(ptr %t7)
  %t9 = getelementptr inbounds %ScrUnion, ptr %t8, i64 0, i32 5
  %t10 = load ptr, ptr %t9
  %t11 = call ptr @scr_str_retain_v(ptr %t10)
  store ptr %t11, ptr %s5
  call void @scr_union_release(ptr %t8)
  br label %tern.j2
tern.j2:
  %t12 = load ptr, ptr %s5
  store ptr %t12, ptr %sc_l_message_1
  call void @scr_union_release(ptr %t1)
  %t13 = load ptr, ptr %sc_l_actual_0
  %t14 = call ptr @scr_union_retain_v(ptr %t13)
  %t15 = load ptr, ptr %sc_l_expected_0
  %t16 = call ptr @scr_union_retain_v(ptr %t15)
  %t18 = getelementptr inbounds %ScrUnion, ptr %t14, i64 0, i32 1
  %t19 = load i32, ptr %t18
  %t20 = getelementptr inbounds %ScrUnion, ptr %t16, i64 0, i32 1
  %t21 = load i32, ptr %t20
  %t22 = icmp eq i32 %t19, %t21
  store i1 false, ptr %s17
  br i1 %t22, label %ue.s4, label %ue.j3
ue.s4:
  %t23 = getelementptr inbounds %ScrUnion, ptr %t14, i64 0, i32 1
  %t24 = load i32, ptr %t23
  switch i32 %t24, label %u.bad5 [ i32 0, label %u.a6 i32 1, label %u.a7 i32 2, label %u.a8 ]
u.a6:
  %t25 = call zeroext i1 @scr_union_get_bool(ptr %t14)
  %t26 = call zeroext i1 @scr_union_get_bool(ptr %t16)
  %t27 = icmp eq i1 %t25, %t26
  store i1 %t27, ptr %s17
  br label %ue.j3
u.a7:
  %t28 = call double @scr_union_get_f64(ptr %t14)
  %t29 = call double @scr_union_get_f64(ptr %t16)
  %t30 = fcmp oeq double %t28, %t29
  store i1 %t30, ptr %s17
  br label %ue.j3
u.a8:
  %t31 = getelementptr inbounds %ScrUnion, ptr %t14, i64 0, i32 5
  %t32 = load ptr, ptr %t31
  %t33 = getelementptr inbounds %ScrUnion, ptr %t16, i64 0, i32 5
  %t34 = load ptr, ptr %t33
  %t35 = call zeroext i1 @scr_str_eq(ptr %t32, ptr %t34)
  store i1 %t35, ptr %s17
  br label %ue.j3
u.bad5:
  call void @sc_bad_tag()
  unreachable
ue.j3:
  %t36 = load i1, ptr %s17
  %t37 = xor i1 %t36, true
  call void @scr_union_release(ptr %t14)
  call void @scr_union_release(ptr %t16)
  br i1 %t37, label %if.t9, label %if.j10
if.t9:
  %t38 = load ptr, ptr %sc_l_message_1
  %t39 = call ptr @scr_str_retain_v(ptr %t38)
  %t40 = call double @scr_str_utf16_len(ptr %t39)
  %t41 = fcmp ogt double %t40, 0x0000000000000000
  br i1 %t41, label %tern.t11, label %tern.f12
tern.t11:
  %t43 = call ptr @scr_str_retain_v(ptr @sc_lit_11)
  %t44 = load ptr, ptr %sc_l_message_1
  %t45 = call ptr @scr_str_retain_v(ptr %t44)
  %t46 = call ptr @scr_str_concat(ptr %t43, ptr %t45)
  %t47 = call ptr @scr_str_retain_v(ptr @sc_lit_12)
  %t48 = call ptr @scr_str_concat(ptr %t46, ptr %t47)
  store ptr %t48, ptr %s42
  call void @scr_str_release(ptr %t43)
  call void @scr_str_release(ptr %t45)
  call void @scr_str_release(ptr %t46)
  call void @scr_str_release(ptr %t47)
  br label %tern.j13
tern.f12:
  %t49 = call ptr @scr_str_retain_v(ptr @sc_lit_10)
  store ptr %t49, ptr %s42
  br label %tern.j13
tern.j13:
  %t50 = load ptr, ptr %s42
  store ptr %t50, ptr %sc_l_detail_0
  call void @scr_str_release(ptr %t39)
  %t51 = call ptr @scr_str_retain_v(ptr @sc_lit_13)
  %t52 = load ptr, ptr %sc_l_expected_0
  %t53 = call ptr @scr_union_retain_v(ptr %t52)
  %t55 = getelementptr inbounds %ScrUnion, ptr %t53, i64 0, i32 1
  %t56 = load i32, ptr %t55
  switch i32 %t56, label %u.bad15 [ i32 0, label %u.a16 i32 1, label %u.a17 i32 2, label %u.a18 ]
u.a16:
  %t57 = call zeroext i1 @scr_union_get_bool(ptr %t53)
  %t58 = call ptr @scr_bool_to_scrstr(i1 zeroext %t57)
  store ptr %t58, ptr %s54
  br label %us.j14
u.a17:
  %t59 = call double @scr_union_get_f64(ptr %t53)
  %t60 = call ptr @scr_f64_to_scrstr(double %t59)
  store ptr %t60, ptr %s54
  br label %us.j14
u.a18:
  %t61 = getelementptr inbounds %ScrUnion, ptr %t53, i64 0, i32 5
  %t62 = load ptr, ptr %t61
  %t63 = call ptr @scr_str_retain_v(ptr %t62)
  store ptr %t63, ptr %s54
  br label %us.j14
u.bad15:
  call void @sc_bad_tag()
  unreachable
us.j14:
  %t64 = load ptr, ptr %s54
  %t65 = call ptr @scr_str_concat(ptr %t51, ptr %t64)
  %t66 = call ptr @scr_str_retain_v(ptr @sc_lit_14)
  %t67 = call ptr @scr_str_concat(ptr %t65, ptr %t66)
  %t68 = load ptr, ptr %sc_l_actual_0
  %t69 = call ptr @scr_union_retain_v(ptr %t68)
  %t71 = getelementptr inbounds %ScrUnion, ptr %t69, i64 0, i32 1
  %t72 = load i32, ptr %t71
  switch i32 %t72, label %u.bad20 [ i32 0, label %u.a21 i32 1, label %u.a22 i32 2, label %u.a23 ]
u.a21:
  %t73 = call zeroext i1 @scr_union_get_bool(ptr %t69)
  %t74 = call ptr @scr_bool_to_scrstr(i1 zeroext %t73)
  store ptr %t74, ptr %s70
  br label %us.j19
u.a22:
  %t75 = call double @scr_union_get_f64(ptr %t69)
  %t76 = call ptr @scr_f64_to_scrstr(double %t75)
  store ptr %t76, ptr %s70
  br label %us.j19
u.a23:
  %t77 = getelementptr inbounds %ScrUnion, ptr %t69, i64 0, i32 5
  %t78 = load ptr, ptr %t77
  %t79 = call ptr @scr_str_retain_v(ptr %t78)
  store ptr %t79, ptr %s70
  br label %us.j19
u.bad20:
  call void @sc_bad_tag()
  unreachable
us.j19:
  %t80 = load ptr, ptr %s70
  %t81 = call ptr @scr_str_concat(ptr %t67, ptr %t80)
  %t82 = load ptr, ptr %sc_l_detail_0
  %t83 = call ptr @scr_str_retain_v(ptr %t82)
  %t84 = call ptr @scr_str_concat(ptr %t81, ptr %t83)
  %t85 = call ptr @scr_error_new(i32 0, ptr %t84)
  call void @scr_throw_obj(ptr %t85, ptr @scr_error_retain_v, ptr @scr_error_release_v, ptr null)
  call void @scr_str_release(ptr %t51)
  call void @scr_union_release(ptr %t53)
  call void @scr_str_release(ptr %t64)
  call void @scr_str_release(ptr %t65)
  call void @scr_str_release(ptr %t66)
  call void @scr_str_release(ptr %t67)
  call void @scr_union_release(ptr %t69)
  call void @scr_str_release(ptr %t80)
  call void @scr_str_release(ptr %t81)
  call void @scr_str_release(ptr %t83)
  call void @scr_str_release(ptr %t84)
  %t86 = load ptr, ptr %sc_l_detail_0
  call void @scr_str_release(ptr %t86)
  %t87 = load ptr, ptr %sc_l_actual_0
  call void @scr_union_release(ptr %t87)
  %t88 = load ptr, ptr %sc_l_expected_0
  call void @scr_union_release(ptr %t88)
  %t89 = load ptr, ptr %sc_l_message_0
  call void @scr_union_release(ptr %t89)
  %t90 = load ptr, ptr %sc_l_message_1
  call void @scr_str_release(ptr %t90)
  ret void
if.j10:
  %t91 = load ptr, ptr %sc_l_actual_0
  call void @scr_union_release(ptr %t91)
  %t92 = load ptr, ptr %sc_l_expected_0
  call void @scr_union_release(ptr %t92)
  %t93 = load ptr, ptr %sc_l_message_0
  call void @scr_union_release(ptr %t93)
  %t94 = load ptr, ptr %sc_l_message_1
  call void @scr_str_release(ptr %t94)
  ret void
}

define internal void @sc_f__x25_m1_assertArrayEqual(ptr %p_sc_l_actual_0, ptr %p_sc_l_expected_0, ptr %p_sc_l_message_0) #0 { ; %m1.assertArrayEqual
entry:
  %sc_l_actual_0 = alloca ptr ; actual
  %sc_l_expected_0 = alloca ptr ; expected
  %sc_l_message_0 = alloca ptr ; message
  %sc_l_message_1 = alloca ptr ; message
  %sc_l_i_0 = alloca double ; i
  %s5 = alloca ptr
  store ptr null, ptr %sc_l_message_1
  store ptr %p_sc_l_actual_0, ptr %sc_l_actual_0
  store ptr %p_sc_l_expected_0, ptr %sc_l_expected_0
  store ptr %p_sc_l_message_0, ptr %sc_l_message_0
  %t0 = load ptr, ptr %sc_l_message_0
  %t1 = call ptr @scr_union_retain_v(ptr %t0)
  %t2 = getelementptr inbounds %ScrUnion, ptr %t1, i64 0, i32 1
  %t3 = load i32, ptr %t2
  %t4 = icmp eq i32 %t3, 1
  br i1 %t4, label %tern.t0, label %tern.f1
tern.t0:
  %t6 = call ptr @scr_str_retain_v(ptr @sc_lit_10)
  store ptr %t6, ptr %s5
  br label %tern.j2
tern.f1:
  %t7 = load ptr, ptr %sc_l_message_0
  %t8 = call ptr @scr_union_retain_v(ptr %t7)
  %t9 = getelementptr inbounds %ScrUnion, ptr %t8, i64 0, i32 5
  %t10 = load ptr, ptr %t9
  %t11 = call ptr @scr_str_retain_v(ptr %t10)
  store ptr %t11, ptr %s5
  call void @scr_union_release(ptr %t8)
  br label %tern.j2
tern.j2:
  %t12 = load ptr, ptr %s5
  store ptr %t12, ptr %sc_l_message_1
  call void @scr_union_release(ptr %t1)
  %t13 = load ptr, ptr %sc_l_actual_0
  %t14 = call ptr @scr_arr_retain_v(ptr %t13)
  %t15 = call double @scr_arr_len(ptr %t14)
  %t16 = load ptr, ptr %sc_l_expected_0
  %t17 = call ptr @scr_arr_retain_v(ptr %t16)
  %t18 = call double @scr_arr_len(ptr %t17)
  %t19 = fcmp une double %t15, %t18
  call void @scr_arr_release(ptr %t14)
  call void @scr_arr_release(ptr %t17)
  br i1 %t19, label %if.t3, label %if.j4
if.t3:
  %t20 = call ptr @scr_str_retain_v(ptr @sc_lit_15)
  %t21 = load ptr, ptr %sc_l_actual_0
  %t22 = call ptr @scr_arr_retain_v(ptr %t21)
  %t23 = call double @scr_arr_len(ptr %t22)
  %t24 = call ptr @scr_f64_to_scrstr(double %t23)
  %t25 = call ptr @scr_str_concat(ptr %t20, ptr %t24)
  %t26 = call ptr @scr_str_retain_v(ptr @sc_lit_16)
  %t27 = call ptr @scr_str_concat(ptr %t25, ptr %t26)
  %t28 = load ptr, ptr %sc_l_expected_0
  %t29 = call ptr @scr_arr_retain_v(ptr %t28)
  %t30 = call double @scr_arr_len(ptr %t29)
  %t31 = call ptr @scr_f64_to_scrstr(double %t30)
  %t32 = call ptr @scr_str_concat(ptr %t27, ptr %t31)
  %t33 = call ptr @scr_str_retain_v(ptr @sc_lit_17)
  %t34 = call ptr @scr_str_concat(ptr %t32, ptr %t33)
  %t35 = load ptr, ptr %sc_l_message_1
  %t36 = call ptr @scr_str_retain_v(ptr %t35)
  %t37 = call ptr @scr_str_concat(ptr %t34, ptr %t36)
  %t38 = call ptr @scr_error_new(i32 0, ptr %t37)
  call void @scr_throw_obj(ptr %t38, ptr @scr_error_retain_v, ptr @scr_error_release_v, ptr null)
  call void @scr_str_release(ptr %t20)
  call void @scr_arr_release(ptr %t22)
  call void @scr_str_release(ptr %t24)
  call void @scr_str_release(ptr %t25)
  call void @scr_str_release(ptr %t26)
  call void @scr_str_release(ptr %t27)
  call void @scr_arr_release(ptr %t29)
  call void @scr_str_release(ptr %t31)
  call void @scr_str_release(ptr %t32)
  call void @scr_str_release(ptr %t33)
  call void @scr_str_release(ptr %t34)
  call void @scr_str_release(ptr %t36)
  call void @scr_str_release(ptr %t37)
  %t39 = load ptr, ptr %sc_l_actual_0
  call void @scr_arr_release(ptr %t39)
  %t40 = load ptr, ptr %sc_l_expected_0
  call void @scr_arr_release(ptr %t40)
  %t41 = load ptr, ptr %sc_l_message_0
  call void @scr_union_release(ptr %t41)
  %t42 = load ptr, ptr %sc_l_message_1
  call void @scr_str_release(ptr %t42)
  ret void
if.j4:
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c5
loop.c5:
  %t43 = load double, ptr %sc_l_i_0
  %t44 = load ptr, ptr %sc_l_actual_0
  %t45 = call ptr @scr_arr_retain_v(ptr %t44)
  %t46 = call double @scr_arr_len(ptr %t45)
  %t47 = fcmp olt double %t43, %t46
  call void @scr_arr_release(ptr %t45)
  br i1 %t47, label %loop.b6, label %loop.e7
loop.b6:
  %t48 = load ptr, ptr %sc_l_actual_0
  %t49 = call ptr @scr_arr_retain_v(ptr %t48)
  %t50 = load double, ptr %sc_l_i_0
  %t51 = call double @scr_arr_get_f64(ptr %t49, double %t50)
  %t52 = load ptr, ptr %sc_l_expected_0
  %t53 = call ptr @scr_arr_retain_v(ptr %t52)
  %t54 = load double, ptr %sc_l_i_0
  %t55 = call double @scr_arr_get_f64(ptr %t53, double %t54)
  %t56 = fcmp une double %t51, %t55
  call void @scr_arr_release(ptr %t49)
  call void @scr_arr_release(ptr %t53)
  br i1 %t56, label %if.t9, label %if.j10
if.t9:
  %t57 = call ptr @scr_str_retain_v(ptr @sc_lit_18)
  %t58 = load double, ptr %sc_l_i_0
  %t59 = call ptr @scr_f64_to_scrstr(double %t58)
  %t60 = call ptr @scr_str_concat(ptr %t57, ptr %t59)
  %t61 = call ptr @scr_str_retain_v(ptr @sc_lit_19)
  %t62 = call ptr @scr_str_concat(ptr %t60, ptr %t61)
  %t63 = load ptr, ptr %sc_l_actual_0
  %t64 = call ptr @scr_arr_retain_v(ptr %t63)
  %t65 = load double, ptr %sc_l_i_0
  %t66 = call double @scr_arr_get_f64(ptr %t64, double %t65)
  %t67 = call ptr @scr_f64_to_scrstr(double %t66)
  %t68 = call ptr @scr_str_concat(ptr %t62, ptr %t67)
  %t69 = call ptr @scr_str_retain_v(ptr @sc_lit_16)
  %t70 = call ptr @scr_str_concat(ptr %t68, ptr %t69)
  %t71 = load ptr, ptr %sc_l_expected_0
  %t72 = call ptr @scr_arr_retain_v(ptr %t71)
  %t73 = load double, ptr %sc_l_i_0
  %t74 = call double @scr_arr_get_f64(ptr %t72, double %t73)
  %t75 = call ptr @scr_f64_to_scrstr(double %t74)
  %t76 = call ptr @scr_str_concat(ptr %t70, ptr %t75)
  %t77 = call ptr @scr_str_retain_v(ptr @sc_lit_17)
  %t78 = call ptr @scr_str_concat(ptr %t76, ptr %t77)
  %t79 = load ptr, ptr %sc_l_message_1
  %t80 = call ptr @scr_str_retain_v(ptr %t79)
  %t81 = call ptr @scr_str_concat(ptr %t78, ptr %t80)
  %t82 = call ptr @scr_error_new(i32 0, ptr %t81)
  call void @scr_throw_obj(ptr %t82, ptr @scr_error_retain_v, ptr @scr_error_release_v, ptr null)
  call void @scr_str_release(ptr %t57)
  call void @scr_str_release(ptr %t59)
  call void @scr_str_release(ptr %t60)
  call void @scr_str_release(ptr %t61)
  call void @scr_str_release(ptr %t62)
  call void @scr_arr_release(ptr %t64)
  call void @scr_str_release(ptr %t67)
  call void @scr_str_release(ptr %t68)
  call void @scr_str_release(ptr %t69)
  call void @scr_str_release(ptr %t70)
  call void @scr_arr_release(ptr %t72)
  call void @scr_str_release(ptr %t75)
  call void @scr_str_release(ptr %t76)
  call void @scr_str_release(ptr %t77)
  call void @scr_str_release(ptr %t78)
  call void @scr_str_release(ptr %t80)
  call void @scr_str_release(ptr %t81)
  %t83 = load ptr, ptr %sc_l_actual_0
  call void @scr_arr_release(ptr %t83)
  %t84 = load ptr, ptr %sc_l_expected_0
  call void @scr_arr_release(ptr %t84)
  %t85 = load ptr, ptr %sc_l_message_0
  call void @scr_union_release(ptr %t85)
  %t86 = load ptr, ptr %sc_l_message_1
  call void @scr_str_release(ptr %t86)
  ret void
if.j10:
  br label %loop.u8
loop.u8:
  %t87 = load double, ptr %sc_l_i_0
  %t88 = fadd double %t87, 0x3FF0000000000000
  store double %t88, ptr %sc_l_i_0
  br label %loop.c5
loop.e7:
  %t89 = load ptr, ptr %sc_l_actual_0
  call void @scr_arr_release(ptr %t89)
  %t90 = load ptr, ptr %sc_l_expected_0
  call void @scr_arr_release(ptr %t90)
  %t91 = load ptr, ptr %sc_l_message_0
  call void @scr_union_release(ptr %t91)
  %t92 = load ptr, ptr %sc_l_message_1
  call void @scr_str_release(ptr %t92)
  ret void
}

define internal void @sc_f__x25_m1_assertThrows(ptr %p_sc_l_fn_0, ptr %p_sc_l_expectedMessageSubstr_0) #0 { ; %m1.assertThrows
entry:
  %sc_l_fn_0 = alloca ptr ; fn
  %sc_l_expectedMessageSubstr_0 = alloca ptr ; expectedMessageSubstr
  %sc_l_expectedMessageSubstr_1 = alloca ptr ; expectedMessageSubstr
  %sc_l_threw_0 = alloca i1 ; threw
  %sc_l_e_0 = alloca ptr ; e
  %s5 = alloca ptr
  %s23 = alloca i1
  store ptr null, ptr %sc_l_expectedMessageSubstr_1
  store ptr null, ptr %sc_l_e_0
  store ptr %p_sc_l_fn_0, ptr %sc_l_fn_0
  store ptr %p_sc_l_expectedMessageSubstr_0, ptr %sc_l_expectedMessageSubstr_0
  %t0 = load ptr, ptr %sc_l_expectedMessageSubstr_0
  %t1 = call ptr @scr_union_retain_v(ptr %t0)
  %t2 = getelementptr inbounds %ScrUnion, ptr %t1, i64 0, i32 1
  %t3 = load i32, ptr %t2
  %t4 = icmp eq i32 %t3, 1
  br i1 %t4, label %tern.t0, label %tern.f1
tern.t0:
  %t6 = call ptr @scr_str_retain_v(ptr @sc_lit_10)
  store ptr %t6, ptr %s5
  br label %tern.j2
tern.f1:
  %t7 = load ptr, ptr %sc_l_expectedMessageSubstr_0
  %t8 = call ptr @scr_union_retain_v(ptr %t7)
  %t9 = getelementptr inbounds %ScrUnion, ptr %t8, i64 0, i32 5
  %t10 = load ptr, ptr %t9
  %t11 = call ptr @scr_str_retain_v(ptr %t10)
  store ptr %t11, ptr %s5
  call void @scr_union_release(ptr %t8)
  br label %tern.j2
tern.j2:
  %t12 = load ptr, ptr %s5
  store ptr %t12, ptr %sc_l_expectedMessageSubstr_1
  call void @scr_union_release(ptr %t1)
  store i1 false, ptr %sc_l_threw_0
  %t13 = load ptr, ptr %sc_l_fn_0
  %t14 = call ptr @scr_closure_retain_v(ptr %t13)
  %t15 = getelementptr inbounds %ScrClosure, ptr %t14, i64 0, i32 1
  %t16 = load ptr, ptr %t15
  call void %t16(ptr %t14)
  %t17 = call zeroext i1 @scr_exc_pending()
  br i1 %t17, label %exc.u6, label %exc.k7
exc.u6:
  call void @scr_closure_release(ptr %t14)
  br label %try.c3
exc.k7:
  call void @scr_closure_release(ptr %t14)
  br label %try.e5
try.c3:
  %t18 = call ptr @scr_exc_take() ; catch binding
  store ptr %t18, ptr %sc_l_e_0
  store i1 true, ptr %sc_l_threw_0
  %t19 = load ptr, ptr %sc_l_expectedMessageSubstr_1
  %t20 = call ptr @scr_str_retain_v(ptr %t19)
  %t21 = call double @scr_str_utf16_len(ptr %t20)
  %t22 = fcmp ogt double %t21, 0x0000000000000000
  store i1 %t22, ptr %s23
  br i1 %t22, label %log.r8, label %log.j9
log.r8:
  %t24 = load ptr, ptr %sc_l_e_0
  %t25 = call ptr @scr_caught_retain(ptr %t24)
  %t26 = call zeroext i1 @scr_caught_instanceof(ptr %t25, i64 0, i64 4)
  store i1 %t26, ptr %s23
  call void @scr_caught_release(ptr %t25)
  br label %log.j9
log.j9:
  %t27 = load i1, ptr %s23
  call void @scr_str_release(ptr %t20)
  br i1 %t27, label %if.t10, label %if.j11
if.t10:
  %t28 = load ptr, ptr %sc_l_e_0
  %t29 = call ptr @scr_caught_retain(ptr %t28)
  %t30 = getelementptr inbounds %ScrCaught, ptr %t29, i64 0, i32 4
  %t31 = load ptr, ptr %t30
  %t32 = getelementptr inbounds %ScrCaught, ptr %t29, i64 0, i32 5
  %t33 = load ptr, ptr %t32
  %t34 = call ptr %t33(ptr %t31)
  %t35 = getelementptr inbounds %ScrError, ptr %t34, i64 0, i32 3
  %t36 = load ptr, ptr %t35
  %t37 = call ptr @scr_str_retain_v(ptr %t36)
  %t38 = load ptr, ptr %sc_l_expectedMessageSubstr_1
  %t39 = call ptr @scr_str_retain_v(ptr %t38)
  %t40 = call i1 @scr_str_includes(ptr %t37, ptr %t39)
  %t41 = xor i1 %t40, true
  call void @scr_caught_release(ptr %t29)
  call void @scr_error_release_v(ptr %t34)
  call void @scr_str_release(ptr %t37)
  call void @scr_str_release(ptr %t39)
  br i1 %t41, label %if.t12, label %if.j13
if.t12:
  %t42 = call ptr @scr_str_retain_v(ptr @sc_lit_20)
  %t43 = load ptr, ptr %sc_l_e_0
  %t44 = call ptr @scr_caught_retain(ptr %t43)
  %t45 = getelementptr inbounds %ScrCaught, ptr %t44, i64 0, i32 4
  %t46 = load ptr, ptr %t45
  %t47 = getelementptr inbounds %ScrCaught, ptr %t44, i64 0, i32 5
  %t48 = load ptr, ptr %t47
  %t49 = call ptr %t48(ptr %t46)
  %t50 = getelementptr inbounds %ScrError, ptr %t49, i64 0, i32 3
  %t51 = load ptr, ptr %t50
  %t52 = call ptr @scr_str_retain_v(ptr %t51)
  %t53 = call ptr @scr_str_concat(ptr %t42, ptr %t52)
  %t54 = call ptr @scr_str_retain_v(ptr @sc_lit_21)
  %t55 = call ptr @scr_str_concat(ptr %t53, ptr %t54)
  %t56 = load ptr, ptr %sc_l_expectedMessageSubstr_1
  %t57 = call ptr @scr_str_retain_v(ptr %t56)
  %t58 = call ptr @scr_str_concat(ptr %t55, ptr %t57)
  %t59 = call ptr @scr_str_retain_v(ptr @sc_lit_22)
  %t60 = call ptr @scr_str_concat(ptr %t58, ptr %t59)
  %t61 = call ptr @scr_error_new(i32 0, ptr %t60)
  call void @scr_throw_obj(ptr %t61, ptr @scr_error_retain_v, ptr @scr_error_release_v, ptr null)
  call void @scr_str_release(ptr %t42)
  call void @scr_caught_release(ptr %t44)
  call void @scr_error_release_v(ptr %t49)
  call void @scr_str_release(ptr %t52)
  call void @scr_str_release(ptr %t53)
  call void @scr_str_release(ptr %t54)
  call void @scr_str_release(ptr %t55)
  call void @scr_str_release(ptr %t57)
  call void @scr_str_release(ptr %t58)
  call void @scr_str_release(ptr %t59)
  call void @scr_str_release(ptr %t60)
  %t62 = load ptr, ptr %sc_l_e_0
  call void @scr_caught_release(ptr %t62)
  %t63 = load ptr, ptr %sc_l_fn_0
  call void @scr_closure_release(ptr %t63)
  %t64 = load ptr, ptr %sc_l_expectedMessageSubstr_0
  call void @scr_union_release(ptr %t64)
  %t65 = load ptr, ptr %sc_l_expectedMessageSubstr_1
  call void @scr_str_release(ptr %t65)
  ret void
if.j13:
  br label %if.j11
if.j11:
  %t66 = load ptr, ptr %sc_l_e_0
  call void @scr_caught_release(ptr %t66)
  br label %try.e5
try.e5:
  %t67 = load i1, ptr %sc_l_threw_0
  %t68 = xor i1 %t67, true
  br i1 %t68, label %if.t14, label %if.j15
if.t14:
  %t69 = call ptr @scr_str_retain_v(ptr @sc_lit_23)
  %t70 = call ptr @scr_error_new(i32 0, ptr %t69)
  call void @scr_throw_obj(ptr %t70, ptr @scr_error_retain_v, ptr @scr_error_release_v, ptr null)
  call void @scr_str_release(ptr %t69)
  %t71 = load ptr, ptr %sc_l_fn_0
  call void @scr_closure_release(ptr %t71)
  %t72 = load ptr, ptr %sc_l_expectedMessageSubstr_0
  call void @scr_union_release(ptr %t72)
  %t73 = load ptr, ptr %sc_l_expectedMessageSubstr_1
  call void @scr_str_release(ptr %t73)
  ret void
if.j15:
  %t74 = load ptr, ptr %sc_l_fn_0
  call void @scr_closure_release(ptr %t74)
  %t75 = load ptr, ptr %sc_l_expectedMessageSubstr_0
  call void @scr_union_release(ptr %t75)
  %t76 = load ptr, ptr %sc_l_expectedMessageSubstr_1
  call void @scr_str_release(ptr %t76)
  ret void
}

define internal i1 @sc_f__x25_m1_runTests(ptr %p_sc_l_suiteName_0, ptr %p_sc_l_tests_0) #0 { ; %m1.runTests
entry:
  %sc_l_suiteName_0 = alloca ptr ; suiteName
  %sc_l_tests_0 = alloca ptr ; tests
  %sc_l_passed_0 = alloca double ; passed
  %sc_l_failed_0 = alloca double ; failed
  %sc_l_i_0 = alloca double ; i
  %sc_l_t_0 = alloca ptr ; t
  %sc_l_e_0 = alloca ptr ; e
  %logargs = alloca [1 x %ScrLogArg]
  store ptr null, ptr %sc_l_t_0
  store ptr null, ptr %sc_l_e_0
  store ptr %p_sc_l_suiteName_0, ptr %sc_l_suiteName_0
  store ptr %p_sc_l_tests_0, ptr %sc_l_tests_0
  %t0 = call ptr @scr_str_retain_v(ptr @sc_lit_24)
  %t1 = load ptr, ptr %sc_l_suiteName_0
  %t2 = call ptr @scr_str_retain_v(ptr %t1)
  %t3 = call ptr @scr_str_concat(ptr %t0, ptr %t2)
  %t4 = call ptr @scr_str_retain_v(ptr @sc_lit_25)
  %t5 = call ptr @scr_str_concat(ptr %t3, ptr %t4)
  %t6 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t6
  %t7 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t5, ptr %t7
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t0)
  call void @scr_str_release(ptr %t2)
  call void @scr_str_release(ptr %t3)
  call void @scr_str_release(ptr %t4)
  call void @scr_str_release(ptr %t5)
  store double 0x0000000000000000, ptr %sc_l_passed_0
  store double 0x0000000000000000, ptr %sc_l_failed_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c0
loop.c0:
  %t8 = load double, ptr %sc_l_i_0
  %t9 = load ptr, ptr %sc_l_tests_0
  %t10 = call ptr @scr_arr_retain_v(ptr %t9)
  %t11 = call double @scr_arr_len(ptr %t10)
  %t12 = fcmp olt double %t8, %t11
  call void @scr_arr_release(ptr %t10)
  br i1 %t12, label %loop.b1, label %loop.e2
loop.b1:
  %t13 = load ptr, ptr %sc_l_tests_0
  %t14 = call ptr @scr_arr_retain_v(ptr %t13)
  %t15 = load double, ptr %sc_l_i_0
  %t16 = call ptr @scr_arr_get_ref(ptr %t14, double %t15)
  store ptr %t16, ptr %sc_l_t_0
  call void @scr_arr_release(ptr %t14)
  %t17 = load ptr, ptr %sc_l_t_0
  %t18 = call ptr @sc_rretain_r0(ptr %t17)
  %t19 = getelementptr inbounds %sc_rs_r0, ptr %t18, i64 0, i32 1
  %t20 = load ptr, ptr %t19
  %t21 = call ptr @scr_closure_retain_v(ptr %t20)
  %t22 = getelementptr inbounds %ScrClosure, ptr %t21, i64 0, i32 1
  %t23 = load ptr, ptr %t22
  call void %t23(ptr %t21)
  %t24 = call zeroext i1 @scr_exc_pending()
  br i1 %t24, label %exc.u7, label %exc.k8
exc.u7:
  call void @sc_rrelease_r0(ptr %t18)
  call void @scr_closure_release(ptr %t21)
  br label %try.c4
exc.k8:
  call void @sc_rrelease_r0(ptr %t18)
  call void @scr_closure_release(ptr %t21)
  %t25 = call ptr @scr_str_retain_v(ptr @sc_lit_26)
  %t26 = load ptr, ptr %sc_l_t_0
  %t27 = call ptr @sc_rretain_r0(ptr %t26)
  %t28 = getelementptr inbounds %sc_rs_r0, ptr %t27, i64 0, i32 2
  %t29 = load ptr, ptr %t28
  %t30 = call ptr @scr_str_retain_v(ptr %t29)
  %t31 = call ptr @scr_str_concat(ptr %t25, ptr %t30)
  %t32 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t32
  %t33 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t31, ptr %t33
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t25)
  call void @sc_rrelease_r0(ptr %t27)
  call void @scr_str_release(ptr %t30)
  call void @scr_str_release(ptr %t31)
  %t34 = load double, ptr %sc_l_passed_0
  %t35 = fadd double %t34, 0x3FF0000000000000
  store double %t35, ptr %sc_l_passed_0
  br label %try.e6
try.c4:
  %t36 = call ptr @scr_exc_take() ; catch binding
  store ptr %t36, ptr %sc_l_e_0
  %t37 = call ptr @scr_str_retain_v(ptr @sc_lit_27)
  %t38 = load ptr, ptr %sc_l_t_0
  %t39 = call ptr @sc_rretain_r0(ptr %t38)
  %t40 = getelementptr inbounds %sc_rs_r0, ptr %t39, i64 0, i32 2
  %t41 = load ptr, ptr %t40
  %t42 = call ptr @scr_str_retain_v(ptr %t41)
  %t43 = call ptr @scr_str_concat(ptr %t37, ptr %t42)
  %t44 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t44
  %t45 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t43, ptr %t45
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t37)
  call void @sc_rrelease_r0(ptr %t39)
  call void @scr_str_release(ptr %t42)
  call void @scr_str_release(ptr %t43)
  %t46 = load ptr, ptr %sc_l_e_0
  %t47 = call ptr @scr_caught_retain(ptr %t46)
  %t48 = call zeroext i1 @scr_caught_instanceof(ptr %t47, i64 0, i64 4)
  call void @scr_caught_release(ptr %t47)
  br i1 %t48, label %if.t9, label %if.j10
if.t9:
  %t49 = call ptr @scr_str_retain_v(ptr @sc_lit_28)
  %t50 = load ptr, ptr %sc_l_e_0
  %t51 = call ptr @scr_caught_retain(ptr %t50)
  %t52 = getelementptr inbounds %ScrCaught, ptr %t51, i64 0, i32 4
  %t53 = load ptr, ptr %t52
  %t54 = getelementptr inbounds %ScrCaught, ptr %t51, i64 0, i32 5
  %t55 = load ptr, ptr %t54
  %t56 = call ptr %t55(ptr %t53)
  %t57 = getelementptr inbounds %ScrError, ptr %t56, i64 0, i32 3
  %t58 = load ptr, ptr %t57
  %t59 = call ptr @scr_str_retain_v(ptr %t58)
  %t60 = call ptr @scr_str_concat(ptr %t49, ptr %t59)
  %t61 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t61
  %t62 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t60, ptr %t62
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t49)
  call void @scr_caught_release(ptr %t51)
  call void @scr_error_release_v(ptr %t56)
  call void @scr_str_release(ptr %t59)
  call void @scr_str_release(ptr %t60)
  br label %if.j10
if.j10:
  %t63 = load double, ptr %sc_l_failed_0
  %t64 = fadd double %t63, 0x3FF0000000000000
  store double %t64, ptr %sc_l_failed_0
  %t65 = load ptr, ptr %sc_l_e_0
  call void @scr_caught_release(ptr %t65)
  br label %try.e6
try.e6:
  %t66 = load ptr, ptr %sc_l_t_0
  call void @sc_rrelease_r0(ptr %t66)
  br label %loop.u3
loop.u3:
  %t67 = load double, ptr %sc_l_i_0
  %t68 = fadd double %t67, 0x3FF0000000000000
  store double %t68, ptr %sc_l_i_0
  br label %loop.c0
loop.e2:
  %t69 = call ptr @scr_str_retain_v(ptr @sc_lit_29)
  %t70 = load double, ptr %sc_l_passed_0
  %t71 = call ptr @scr_f64_to_scrstr(double %t70)
  %t72 = call ptr @scr_str_concat(ptr %t69, ptr %t71)
  %t73 = call ptr @scr_str_retain_v(ptr @sc_lit_30)
  %t74 = call ptr @scr_str_concat(ptr %t72, ptr %t73)
  %t75 = load double, ptr %sc_l_failed_0
  %t76 = call ptr @scr_f64_to_scrstr(double %t75)
  %t77 = call ptr @scr_str_concat(ptr %t74, ptr %t76)
  %t78 = call ptr @scr_str_retain_v(ptr @sc_lit_31)
  %t79 = call ptr @scr_str_concat(ptr %t77, ptr %t78)
  %t80 = load ptr, ptr %sc_l_tests_0
  %t81 = call ptr @scr_arr_retain_v(ptr %t80)
  %t82 = call double @scr_arr_len(ptr %t81)
  %t83 = call ptr @scr_f64_to_scrstr(double %t82)
  %t84 = call ptr @scr_str_concat(ptr %t79, ptr %t83)
  %t85 = call ptr @scr_str_retain_v(ptr @sc_lit_32)
  %t86 = call ptr @scr_str_concat(ptr %t84, ptr %t85)
  %t87 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t87
  %t88 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t86, ptr %t88
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t69)
  call void @scr_str_release(ptr %t71)
  call void @scr_str_release(ptr %t72)
  call void @scr_str_release(ptr %t73)
  call void @scr_str_release(ptr %t74)
  call void @scr_str_release(ptr %t76)
  call void @scr_str_release(ptr %t77)
  call void @scr_str_release(ptr %t78)
  call void @scr_str_release(ptr %t79)
  call void @scr_arr_release(ptr %t81)
  call void @scr_str_release(ptr %t83)
  call void @scr_str_release(ptr %t84)
  call void @scr_str_release(ptr %t85)
  call void @scr_str_release(ptr %t86)
  %t89 = load double, ptr %sc_l_failed_0
  %t90 = fcmp ogt double %t89, 0x0000000000000000
  br i1 %t90, label %if.t11, label %if.f13
if.t11:
  %t91 = call ptr @scr_str_retain_v(ptr @sc_lit_33)
  %t92 = load ptr, ptr %sc_l_suiteName_0
  %t93 = call ptr @scr_str_retain_v(ptr %t92)
  %t94 = call ptr @scr_str_concat(ptr %t91, ptr %t93)
  %t95 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t95
  %t96 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t94, ptr %t96
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t91)
  call void @scr_str_release(ptr %t93)
  call void @scr_str_release(ptr %t94)
  %t97 = load ptr, ptr %sc_l_suiteName_0
  call void @scr_str_release(ptr %t97)
  %t98 = load ptr, ptr %sc_l_tests_0
  call void @scr_arr_release(ptr %t98)
  ret i1 false
if.f13:
  %t99 = call ptr @scr_str_retain_v(ptr @sc_lit_34)
  %t100 = load ptr, ptr %sc_l_suiteName_0
  %t101 = call ptr @scr_str_retain_v(ptr %t100)
  %t102 = call ptr @scr_str_concat(ptr %t99, ptr %t101)
  %t103 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t103
  %t104 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t102, ptr %t104
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t99)
  call void @scr_str_release(ptr %t101)
  call void @scr_str_release(ptr %t102)
  %t105 = load ptr, ptr %sc_l_suiteName_0
  call void @scr_str_release(ptr %t105)
  %t106 = load ptr, ptr %sc_l_tests_0
  call void @scr_arr_release(ptr %t106)
  ret i1 true
if.j12:
  call void @scr_throw_error_msg_code(i32 0, ptr @sc_cs_0, i64 123, ptr @sc_cs_1)
  %t107 = load ptr, ptr %sc_l_suiteName_0
  call void @scr_str_release(ptr %t107)
  %t108 = load ptr, ptr %sc_l_tests_0
  call void @scr_arr_release(ptr %t108)
  ret i1 false
}

define internal i1 @sc_f_runShapeTests() #0 { ; runShapeTests
entry:
  %t0 = call ptr @scr_str_retain_v(ptr @sc_lit_35)
  %t1 = load ptr, ptr @sc_g_e_tests
  %t2 = call ptr @scr_arr_retain_v(ptr %t1)
  %t3 = call i1 @sc_f__x25_m1_runTests(ptr %t0, ptr %t2)
  %t4 = call zeroext i1 @scr_exc_pending()
  br i1 %t4, label %exc.u0, label %exc.k1
exc.u0:
  ret i1 false
exc.k1:
  ret i1 %t3
}

define internal void @sc_f__x25_init_0() #0 { ; %init.0
entry:
  %t0 = load i1, ptr @sc_g_m0__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_m0__x25_loaded
  ret void
}

define internal void @sc_f__x25_init_1() #0 { ; %init.1
entry:
  %t0 = load i1, ptr @sc_g_m1__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_m1__x25_loaded
  ret void
}

define internal void @sc_f__x25_init_2() #0 { ; %init.2
entry:
  %t0 = load i1, ptr @sc_g_e__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_e__x25_loaded
  call void @sc_f__x25_init_0()
  call void @sc_f__x25_init_1()
  %t1 = call ptr @scr_arr_new_ref(ptr @sc_rretain_r0, ptr @sc_rrelease_r0, ptr @sc_rtrace_r0, i64 6)
  %t2 = call ptr @sc_rnew_r0()
  %t3 = call ptr @scr_str_retain_v(ptr @sc_lit_36)
  %t4 = getelementptr inbounds %sc_rs_r0, ptr %t2, i64 0, i32 2
  store ptr %t3, ptr %t4
  %t5 = call ptr @scr_closure_new(ptr @sc_f__x25_fn0, i64 0)
  %t6 = getelementptr inbounds %sc_rs_r0, ptr %t2, i64 0, i32 1
  store ptr %t5, ptr %t6
  %t7 = call double @scr_arr_push_ref(ptr %t1, ptr %t2)
  %t8 = call ptr @sc_rnew_r0()
  %t9 = call ptr @scr_str_retain_v(ptr @sc_lit_37)
  %t10 = getelementptr inbounds %sc_rs_r0, ptr %t8, i64 0, i32 2
  store ptr %t9, ptr %t10
  %t11 = call ptr @scr_closure_new(ptr @sc_f__x25_fn1, i64 0)
  %t12 = getelementptr inbounds %sc_rs_r0, ptr %t8, i64 0, i32 1
  store ptr %t11, ptr %t12
  %t13 = call double @scr_arr_push_ref(ptr %t1, ptr %t8)
  %t14 = call ptr @sc_rnew_r0()
  %t15 = call ptr @scr_str_retain_v(ptr @sc_lit_38)
  %t16 = getelementptr inbounds %sc_rs_r0, ptr %t14, i64 0, i32 2
  store ptr %t15, ptr %t16
  %t17 = call ptr @scr_closure_new(ptr @sc_f__x25_fn2, i64 0)
  %t18 = getelementptr inbounds %sc_rs_r0, ptr %t14, i64 0, i32 1
  store ptr %t17, ptr %t18
  %t19 = call double @scr_arr_push_ref(ptr %t1, ptr %t14)
  %t20 = call ptr @sc_rnew_r0()
  %t21 = call ptr @scr_str_retain_v(ptr @sc_lit_39)
  %t22 = getelementptr inbounds %sc_rs_r0, ptr %t20, i64 0, i32 2
  store ptr %t21, ptr %t22
  %t23 = call ptr @scr_closure_new(ptr @sc_f__x25_fn5, i64 0)
  %t24 = getelementptr inbounds %sc_rs_r0, ptr %t20, i64 0, i32 1
  store ptr %t23, ptr %t24
  %t25 = call double @scr_arr_push_ref(ptr %t1, ptr %t20)
  %t26 = call ptr @sc_rnew_r0()
  %t27 = call ptr @scr_str_retain_v(ptr @sc_lit_40)
  %t28 = getelementptr inbounds %sc_rs_r0, ptr %t26, i64 0, i32 2
  store ptr %t27, ptr %t28
  %t29 = call ptr @scr_closure_new(ptr @sc_f__x25_fn6, i64 0)
  %t30 = getelementptr inbounds %sc_rs_r0, ptr %t26, i64 0, i32 1
  store ptr %t29, ptr %t30
  %t31 = call double @scr_arr_push_ref(ptr %t1, ptr %t26)
  %t32 = call ptr @sc_rnew_r0()
  %t33 = call ptr @scr_str_retain_v(ptr @sc_lit_41)
  %t34 = getelementptr inbounds %sc_rs_r0, ptr %t32, i64 0, i32 2
  store ptr %t33, ptr %t34
  %t35 = call ptr @scr_closure_new(ptr @sc_f__x25_fn7, i64 0)
  %t36 = getelementptr inbounds %sc_rs_r0, ptr %t32, i64 0, i32 1
  store ptr %t35, ptr %t36
  %t37 = call double @scr_arr_push_ref(ptr %t1, ptr %t32)
  %t38 = load ptr, ptr @sc_g_e_tests
  call void @scr_arr_release(ptr %t38)
  store ptr %t1, ptr @sc_g_e_tests
  %t39 = call i1 @sc_f_runShapeTests()
  %t40 = call zeroext i1 @scr_exc_pending()
  br i1 %t40, label %exc.u2, label %exc.k3
exc.u2:
  ret void
exc.k3:
  ret void
}

define internal void @sc_f__x25_main() #0 { ; %main
entry:
  call void @sc_f__x25_init_2()
  %t0 = call zeroext i1 @scr_exc_pending()
  br i1 %t0, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  ret void
}

define internal void @sc_f__x25_fn0(ptr %sc_env) #0 { ; %fn0
entry:
  %t0 = call ptr @scr_arr_new(i32 0, i64 0)
  %t1 = call double @sc_f__x25_m0_shapeToSize(ptr %t0)
  %t2 = call zeroext i1 @scr_exc_pending()
  br i1 %t2, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  %t3 = call ptr @scr_union_new_f64(i32 1, double %t1)
  %t4 = call ptr @scr_union_new_f64(i32 1, double 0x0000000000000000)
  call void @sc_f__x25_m1_assertEqual(ptr %t3, ptr %t4, ptr @sc_unit_0)
  %t5 = call zeroext i1 @scr_exc_pending()
  br i1 %t5, label %exc.u2, label %exc.k3
exc.u2:
  ret void
exc.k3:
  %t6 = call ptr @scr_arr_new(i32 0, i64 1)
  %t7 = call double @scr_arr_push_f64(ptr %t6, double 0x4014000000000000)
  %t8 = call double @sc_f__x25_m0_shapeToSize(ptr %t6)
  %t9 = call zeroext i1 @scr_exc_pending()
  br i1 %t9, label %exc.u4, label %exc.k5
exc.u4:
  ret void
exc.k5:
  %t10 = call ptr @scr_union_new_f64(i32 1, double %t8)
  %t11 = call ptr @scr_union_new_f64(i32 1, double 0x4014000000000000)
  call void @sc_f__x25_m1_assertEqual(ptr %t10, ptr %t11, ptr @sc_unit_0)
  %t12 = call zeroext i1 @scr_exc_pending()
  br i1 %t12, label %exc.u6, label %exc.k7
exc.u6:
  ret void
exc.k7:
  %t13 = call ptr @scr_arr_new(i32 0, i64 2)
  %t14 = call double @scr_arr_push_f64(ptr %t13, double 0x4000000000000000)
  %t15 = call double @scr_arr_push_f64(ptr %t13, double 0x4008000000000000)
  %t16 = call double @sc_f__x25_m0_shapeToSize(ptr %t13)
  %t17 = call zeroext i1 @scr_exc_pending()
  br i1 %t17, label %exc.u8, label %exc.k9
exc.u8:
  ret void
exc.k9:
  %t18 = call ptr @scr_union_new_f64(i32 1, double %t16)
  %t19 = call ptr @scr_union_new_f64(i32 1, double 0x4018000000000000)
  call void @sc_f__x25_m1_assertEqual(ptr %t18, ptr %t19, ptr @sc_unit_0)
  %t20 = call zeroext i1 @scr_exc_pending()
  br i1 %t20, label %exc.u10, label %exc.k11
exc.u10:
  ret void
exc.k11:
  %t21 = call ptr @scr_arr_new(i32 0, i64 3)
  %t22 = call double @scr_arr_push_f64(ptr %t21, double 0x4000000000000000)
  %t23 = call double @scr_arr_push_f64(ptr %t21, double 0x4008000000000000)
  %t24 = call double @scr_arr_push_f64(ptr %t21, double 0x4010000000000000)
  %t25 = call double @sc_f__x25_m0_shapeToSize(ptr %t21)
  %t26 = call zeroext i1 @scr_exc_pending()
  br i1 %t26, label %exc.u12, label %exc.k13
exc.u12:
  ret void
exc.k13:
  %t27 = call ptr @scr_union_new_f64(i32 1, double %t25)
  %t28 = call ptr @scr_union_new_f64(i32 1, double 0x4038000000000000)
  call void @sc_f__x25_m1_assertEqual(ptr %t27, ptr %t28, ptr @sc_unit_0)
  %t29 = call zeroext i1 @scr_exc_pending()
  br i1 %t29, label %exc.u14, label %exc.k15
exc.u14:
  ret void
exc.k15:
  %t30 = call ptr @scr_arr_new(i32 0, i64 3)
  %t31 = call double @scr_arr_push_f64(ptr %t30, double 0x3FF0000000000000)
  %t32 = call double @scr_arr_push_f64(ptr %t30, double 0x3FF0000000000000)
  %t33 = call double @scr_arr_push_f64(ptr %t30, double 0x3FF0000000000000)
  %t34 = call double @sc_f__x25_m0_shapeToSize(ptr %t30)
  %t35 = call zeroext i1 @scr_exc_pending()
  br i1 %t35, label %exc.u16, label %exc.k17
exc.u16:
  ret void
exc.k17:
  %t36 = call ptr @scr_union_new_f64(i32 1, double %t34)
  %t37 = call ptr @scr_union_new_f64(i32 1, double 0x3FF0000000000000)
  call void @sc_f__x25_m1_assertEqual(ptr %t36, ptr %t37, ptr @sc_unit_0)
  %t38 = call zeroext i1 @scr_exc_pending()
  br i1 %t38, label %exc.u18, label %exc.k19
exc.u18:
  ret void
exc.k19:
  ret void
}

define internal void @sc_f__x25_fn1(ptr %sc_env) #0 { ; %fn1
entry:
  %t0 = call ptr @scr_arr_new(i32 0, i64 0)
  %t1 = call ptr @sc_f__x25_m0_computeStrides(ptr %t0)
  %t2 = call ptr @scr_arr_new(i32 0, i64 0)
  call void @sc_f__x25_m1_assertArrayEqual(ptr %t1, ptr %t2, ptr @sc_unit_0)
  %t3 = call zeroext i1 @scr_exc_pending()
  br i1 %t3, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  %t4 = call ptr @scr_arr_new(i32 0, i64 1)
  %t5 = call double @scr_arr_push_f64(ptr %t4, double 0x4014000000000000)
  %t6 = call ptr @sc_f__x25_m0_computeStrides(ptr %t4)
  %t7 = call ptr @scr_arr_new(i32 0, i64 1)
  %t8 = call double @scr_arr_push_f64(ptr %t7, double 0x3FF0000000000000)
  call void @sc_f__x25_m1_assertArrayEqual(ptr %t6, ptr %t7, ptr @sc_unit_0)
  %t9 = call zeroext i1 @scr_exc_pending()
  br i1 %t9, label %exc.u2, label %exc.k3
exc.u2:
  ret void
exc.k3:
  %t10 = call ptr @scr_arr_new(i32 0, i64 2)
  %t11 = call double @scr_arr_push_f64(ptr %t10, double 0x4000000000000000)
  %t12 = call double @scr_arr_push_f64(ptr %t10, double 0x4008000000000000)
  %t13 = call ptr @sc_f__x25_m0_computeStrides(ptr %t10)
  %t14 = call ptr @scr_arr_new(i32 0, i64 2)
  %t15 = call double @scr_arr_push_f64(ptr %t14, double 0x4008000000000000)
  %t16 = call double @scr_arr_push_f64(ptr %t14, double 0x3FF0000000000000)
  call void @sc_f__x25_m1_assertArrayEqual(ptr %t13, ptr %t14, ptr @sc_unit_0)
  %t17 = call zeroext i1 @scr_exc_pending()
  br i1 %t17, label %exc.u4, label %exc.k5
exc.u4:
  ret void
exc.k5:
  %t18 = call ptr @scr_arr_new(i32 0, i64 3)
  %t19 = call double @scr_arr_push_f64(ptr %t18, double 0x4000000000000000)
  %t20 = call double @scr_arr_push_f64(ptr %t18, double 0x4008000000000000)
  %t21 = call double @scr_arr_push_f64(ptr %t18, double 0x4010000000000000)
  %t22 = call ptr @sc_f__x25_m0_computeStrides(ptr %t18)
  %t23 = call ptr @scr_arr_new(i32 0, i64 3)
  %t24 = call double @scr_arr_push_f64(ptr %t23, double 0x4028000000000000)
  %t25 = call double @scr_arr_push_f64(ptr %t23, double 0x4010000000000000)
  %t26 = call double @scr_arr_push_f64(ptr %t23, double 0x3FF0000000000000)
  call void @sc_f__x25_m1_assertArrayEqual(ptr %t22, ptr %t23, ptr @sc_unit_0)
  %t27 = call zeroext i1 @scr_exc_pending()
  br i1 %t27, label %exc.u6, label %exc.k7
exc.u6:
  ret void
exc.k7:
  %t28 = call ptr @scr_arr_new(i32 0, i64 4)
  %t29 = call double @scr_arr_push_f64(ptr %t28, double 0x3FF0000000000000)
  %t30 = call double @scr_arr_push_f64(ptr %t28, double 0x4024000000000000)
  %t31 = call double @scr_arr_push_f64(ptr %t28, double 0x4014000000000000)
  %t32 = call double @scr_arr_push_f64(ptr %t28, double 0x4000000000000000)
  %t33 = call ptr @sc_f__x25_m0_computeStrides(ptr %t28)
  %t34 = call ptr @scr_arr_new(i32 0, i64 4)
  %t35 = call double @scr_arr_push_f64(ptr %t34, double 0x4059000000000000)
  %t36 = call double @scr_arr_push_f64(ptr %t34, double 0x4024000000000000)
  %t37 = call double @scr_arr_push_f64(ptr %t34, double 0x4000000000000000)
  %t38 = call double @scr_arr_push_f64(ptr %t34, double 0x3FF0000000000000)
  call void @sc_f__x25_m1_assertArrayEqual(ptr %t33, ptr %t34, ptr @sc_unit_0)
  %t39 = call zeroext i1 @scr_exc_pending()
  br i1 %t39, label %exc.u8, label %exc.k9
exc.u8:
  ret void
exc.k9:
  ret void
}

define internal void @sc_f__x25_fn3(ptr %sc_env) #0 { ; %fn3
entry:
  %t0 = call ptr @scr_arr_new(i32 0, i64 2)
  %t1 = call double @scr_arr_push_f64(ptr %t0, double 0xBFF0000000000000)
  %t2 = call double @scr_arr_push_f64(ptr %t0, double 0x4000000000000000)
  call void @sc_f__x25_m0_validateShape(ptr %t0)
  %t3 = call zeroext i1 @scr_exc_pending()
  br i1 %t3, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  ret void
}

define internal void @sc_f__x25_fn4(ptr %sc_env) #0 { ; %fn4
entry:
  %t0 = call ptr @scr_arr_new(i32 0, i64 2)
  %t1 = call double @scr_arr_push_f64(ptr %t0, double 0x4004000000000000)
  %t2 = call double @scr_arr_push_f64(ptr %t0, double 0x4008000000000000)
  call void @sc_f__x25_m0_validateShape(ptr %t0)
  %t3 = call zeroext i1 @scr_exc_pending()
  br i1 %t3, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  ret void
}

define internal void @sc_f__x25_fn2(ptr %sc_env) #0 { ; %fn2
entry:
  %t0 = call ptr @scr_arr_new(i32 0, i64 3)
  %t1 = call double @scr_arr_push_f64(ptr %t0, double 0x3FF0000000000000)
  %t2 = call double @scr_arr_push_f64(ptr %t0, double 0x4000000000000000)
  %t3 = call double @scr_arr_push_f64(ptr %t0, double 0x4008000000000000)
  call void @sc_f__x25_m0_validateShape(ptr %t0)
  %t4 = call zeroext i1 @scr_exc_pending()
  br i1 %t4, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  %t5 = call ptr @scr_closure_new(ptr @sc_f__x25_fn3, i64 0)
  %t6 = call ptr @scr_str_retain_v(ptr @sc_lit_42)
  %t7 = call ptr @scr_union_new_ref(i32 0, ptr %t6, ptr @scr_str_retain_v, ptr @scr_str_release_v, ptr null)
  call void @sc_f__x25_m1_assertThrows(ptr %t5, ptr %t7)
  %t8 = call zeroext i1 @scr_exc_pending()
  br i1 %t8, label %exc.u2, label %exc.k3
exc.u2:
  ret void
exc.k3:
  %t9 = call ptr @scr_closure_new(ptr @sc_f__x25_fn4, i64 0)
  %t10 = call ptr @scr_str_retain_v(ptr @sc_lit_42)
  %t11 = call ptr @scr_union_new_ref(i32 0, ptr %t10, ptr @scr_str_retain_v, ptr @scr_str_release_v, ptr null)
  call void @sc_f__x25_m1_assertThrows(ptr %t9, ptr %t11)
  %t12 = call zeroext i1 @scr_exc_pending()
  br i1 %t12, label %exc.u4, label %exc.k5
exc.u4:
  ret void
exc.k5:
  ret void
}

define internal void @sc_f__x25_fn5(ptr %sc_env) #0 { ; %fn5
entry:
  %t0 = call ptr @scr_arr_new(i32 0, i64 2)
  %t1 = call double @scr_arr_push_f64(ptr %t0, double 0x4000000000000000)
  %t2 = call double @scr_arr_push_f64(ptr %t0, double 0x4008000000000000)
  %t3 = call ptr @scr_arr_new(i32 0, i64 2)
  %t4 = call double @scr_arr_push_f64(ptr %t3, double 0x4000000000000000)
  %t5 = call double @scr_arr_push_f64(ptr %t3, double 0x4008000000000000)
  %t6 = call i1 @sc_f__x25_m0_shapesEqual(ptr %t0, ptr %t3)
  call void @sc_f__x25_m1_assert(i1 %t6, ptr @sc_unit_0)
  %t7 = call zeroext i1 @scr_exc_pending()
  br i1 %t7, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  %t8 = call ptr @scr_arr_new(i32 0, i64 2)
  %t9 = call double @scr_arr_push_f64(ptr %t8, double 0x4000000000000000)
  %t10 = call double @scr_arr_push_f64(ptr %t8, double 0x4008000000000000)
  %t11 = call ptr @scr_arr_new(i32 0, i64 2)
  %t12 = call double @scr_arr_push_f64(ptr %t11, double 0x4008000000000000)
  %t13 = call double @scr_arr_push_f64(ptr %t11, double 0x4000000000000000)
  %t14 = call i1 @sc_f__x25_m0_shapesEqual(ptr %t8, ptr %t11)
  %t15 = xor i1 %t14, true
  call void @sc_f__x25_m1_assert(i1 %t15, ptr @sc_unit_0)
  %t16 = call zeroext i1 @scr_exc_pending()
  br i1 %t16, label %exc.u2, label %exc.k3
exc.u2:
  ret void
exc.k3:
  %t17 = call ptr @scr_arr_new(i32 0, i64 2)
  %t18 = call double @scr_arr_push_f64(ptr %t17, double 0x4000000000000000)
  %t19 = call double @scr_arr_push_f64(ptr %t17, double 0x4008000000000000)
  %t20 = call ptr @scr_arr_new(i32 0, i64 3)
  %t21 = call double @scr_arr_push_f64(ptr %t20, double 0x4000000000000000)
  %t22 = call double @scr_arr_push_f64(ptr %t20, double 0x4008000000000000)
  %t23 = call double @scr_arr_push_f64(ptr %t20, double 0x3FF0000000000000)
  %t24 = call i1 @sc_f__x25_m0_shapesEqual(ptr %t17, ptr %t20)
  %t25 = xor i1 %t24, true
  call void @sc_f__x25_m1_assert(i1 %t25, ptr @sc_unit_0)
  %t26 = call zeroext i1 @scr_exc_pending()
  br i1 %t26, label %exc.u4, label %exc.k5
exc.u4:
  ret void
exc.k5:
  ret void
}

define internal void @sc_f__x25_fn6(ptr %sc_env) #0 { ; %fn6
entry:
  %t0 = call ptr @scr_arr_new(i32 0, i64 2)
  %t1 = call double @scr_arr_push_f64(ptr %t0, double 0x4000000000000000)
  %t2 = call double @scr_arr_push_f64(ptr %t0, double 0x4008000000000000)
  %t3 = call ptr @scr_arr_new(i32 0, i64 2)
  %t4 = call double @scr_arr_push_f64(ptr %t3, double 0x4000000000000000)
  %t5 = call double @scr_arr_push_f64(ptr %t3, double 0x4008000000000000)
  %t6 = call i1 @sc_f__x25_m0_areBroadcastable(ptr %t0, ptr %t3)
  call void @sc_f__x25_m1_assert(i1 %t6, ptr @sc_unit_0)
  %t7 = call zeroext i1 @scr_exc_pending()
  br i1 %t7, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  %t8 = call ptr @scr_arr_new(i32 0, i64 2)
  %t9 = call double @scr_arr_push_f64(ptr %t8, double 0x4000000000000000)
  %t10 = call double @scr_arr_push_f64(ptr %t8, double 0x4008000000000000)
  %t11 = call ptr @scr_arr_new(i32 0, i64 2)
  %t12 = call double @scr_arr_push_f64(ptr %t11, double 0x3FF0000000000000)
  %t13 = call double @scr_arr_push_f64(ptr %t11, double 0x4008000000000000)
  %t14 = call i1 @sc_f__x25_m0_areBroadcastable(ptr %t8, ptr %t11)
  call void @sc_f__x25_m1_assert(i1 %t14, ptr @sc_unit_0)
  %t15 = call zeroext i1 @scr_exc_pending()
  br i1 %t15, label %exc.u2, label %exc.k3
exc.u2:
  ret void
exc.k3:
  %t16 = call ptr @scr_arr_new(i32 0, i64 2)
  %t17 = call double @scr_arr_push_f64(ptr %t16, double 0x4000000000000000)
  %t18 = call double @scr_arr_push_f64(ptr %t16, double 0x4008000000000000)
  %t19 = call ptr @scr_arr_new(i32 0, i64 1)
  %t20 = call double @scr_arr_push_f64(ptr %t19, double 0x4008000000000000)
  %t21 = call i1 @sc_f__x25_m0_areBroadcastable(ptr %t16, ptr %t19)
  call void @sc_f__x25_m1_assert(i1 %t21, ptr @sc_unit_0)
  %t22 = call zeroext i1 @scr_exc_pending()
  br i1 %t22, label %exc.u4, label %exc.k5
exc.u4:
  ret void
exc.k5:
  %t23 = call ptr @scr_arr_new(i32 0, i64 3)
  %t24 = call double @scr_arr_push_f64(ptr %t23, double 0x4000000000000000)
  %t25 = call double @scr_arr_push_f64(ptr %t23, double 0x3FF0000000000000)
  %t26 = call double @scr_arr_push_f64(ptr %t23, double 0x4010000000000000)
  %t27 = call ptr @scr_arr_new(i32 0, i64 2)
  %t28 = call double @scr_arr_push_f64(ptr %t27, double 0x4008000000000000)
  %t29 = call double @scr_arr_push_f64(ptr %t27, double 0x4010000000000000)
  %t30 = call i1 @sc_f__x25_m0_areBroadcastable(ptr %t23, ptr %t27)
  call void @sc_f__x25_m1_assert(i1 %t30, ptr @sc_unit_0)
  %t31 = call zeroext i1 @scr_exc_pending()
  br i1 %t31, label %exc.u6, label %exc.k7
exc.u6:
  ret void
exc.k7:
  %t32 = call ptr @scr_arr_new(i32 0, i64 2)
  %t33 = call double @scr_arr_push_f64(ptr %t32, double 0x4000000000000000)
  %t34 = call double @scr_arr_push_f64(ptr %t32, double 0x4008000000000000)
  %t35 = call ptr @scr_arr_new(i32 0, i64 2)
  %t36 = call double @scr_arr_push_f64(ptr %t35, double 0x4000000000000000)
  %t37 = call double @scr_arr_push_f64(ptr %t35, double 0x4010000000000000)
  %t38 = call i1 @sc_f__x25_m0_areBroadcastable(ptr %t32, ptr %t35)
  %t39 = xor i1 %t38, true
  call void @sc_f__x25_m1_assert(i1 %t39, ptr @sc_unit_0)
  %t40 = call zeroext i1 @scr_exc_pending()
  br i1 %t40, label %exc.u8, label %exc.k9
exc.u8:
  ret void
exc.k9:
  %t41 = call ptr @scr_arr_new(i32 0, i64 2)
  %t42 = call double @scr_arr_push_f64(ptr %t41, double 0x4000000000000000)
  %t43 = call double @scr_arr_push_f64(ptr %t41, double 0x4008000000000000)
  %t44 = call ptr @scr_arr_new(i32 0, i64 1)
  %t45 = call double @scr_arr_push_f64(ptr %t44, double 0x4010000000000000)
  %t46 = call i1 @sc_f__x25_m0_areBroadcastable(ptr %t41, ptr %t44)
  %t47 = xor i1 %t46, true
  call void @sc_f__x25_m1_assert(i1 %t47, ptr @sc_unit_0)
  %t48 = call zeroext i1 @scr_exc_pending()
  br i1 %t48, label %exc.u10, label %exc.k11
exc.u10:
  ret void
exc.k11:
  ret void
}

define internal void @sc_f__x25_fn8(ptr %sc_env) #0 { ; %fn8
entry:
  %t0 = call ptr @scr_arr_new(i32 0, i64 2)
  %t1 = call double @scr_arr_push_f64(ptr %t0, double 0x4000000000000000)
  %t2 = call double @scr_arr_push_f64(ptr %t0, double 0x4008000000000000)
  %t3 = call ptr @scr_arr_new(i32 0, i64 2)
  %t4 = call double @scr_arr_push_f64(ptr %t3, double 0x4000000000000000)
  %t5 = call double @scr_arr_push_f64(ptr %t3, double 0x4010000000000000)
  %t6 = call ptr @sc_f__x25_m0_broadcastShapes(ptr %t0, ptr %t3)
  %t7 = call zeroext i1 @scr_exc_pending()
  br i1 %t7, label %exc.u0, label %exc.k1
exc.u0:
  call void @scr_arr_release(ptr %t6)
  ret void
exc.k1:
  call void @scr_arr_release(ptr %t6)
  ret void
}

define internal void @sc_f__x25_fn7(ptr %sc_env) #0 { ; %fn7
entry:
  %t0 = call ptr @scr_arr_new(i32 0, i64 2)
  %t1 = call double @scr_arr_push_f64(ptr %t0, double 0x4000000000000000)
  %t2 = call double @scr_arr_push_f64(ptr %t0, double 0x4008000000000000)
  %t3 = call ptr @scr_arr_new(i32 0, i64 2)
  %t4 = call double @scr_arr_push_f64(ptr %t3, double 0x4000000000000000)
  %t5 = call double @scr_arr_push_f64(ptr %t3, double 0x4008000000000000)
  %t6 = call ptr @sc_f__x25_m0_broadcastShapes(ptr %t0, ptr %t3)
  %t7 = call zeroext i1 @scr_exc_pending()
  br i1 %t7, label %exc.u0, label %exc.k1
exc.u0:
  call void @scr_arr_release(ptr %t6)
  ret void
exc.k1:
  %t8 = call ptr @scr_arr_new(i32 0, i64 2)
  %t9 = call double @scr_arr_push_f64(ptr %t8, double 0x4000000000000000)
  %t10 = call double @scr_arr_push_f64(ptr %t8, double 0x4008000000000000)
  call void @sc_f__x25_m1_assertArrayEqual(ptr %t6, ptr %t8, ptr @sc_unit_0)
  %t11 = call zeroext i1 @scr_exc_pending()
  br i1 %t11, label %exc.u2, label %exc.k3
exc.u2:
  ret void
exc.k3:
  %t12 = call ptr @scr_arr_new(i32 0, i64 2)
  %t13 = call double @scr_arr_push_f64(ptr %t12, double 0x4000000000000000)
  %t14 = call double @scr_arr_push_f64(ptr %t12, double 0x4008000000000000)
  %t15 = call ptr @scr_arr_new(i32 0, i64 2)
  %t16 = call double @scr_arr_push_f64(ptr %t15, double 0x3FF0000000000000)
  %t17 = call double @scr_arr_push_f64(ptr %t15, double 0x4008000000000000)
  %t18 = call ptr @sc_f__x25_m0_broadcastShapes(ptr %t12, ptr %t15)
  %t19 = call zeroext i1 @scr_exc_pending()
  br i1 %t19, label %exc.u4, label %exc.k5
exc.u4:
  call void @scr_arr_release(ptr %t18)
  ret void
exc.k5:
  %t20 = call ptr @scr_arr_new(i32 0, i64 2)
  %t21 = call double @scr_arr_push_f64(ptr %t20, double 0x4000000000000000)
  %t22 = call double @scr_arr_push_f64(ptr %t20, double 0x4008000000000000)
  call void @sc_f__x25_m1_assertArrayEqual(ptr %t18, ptr %t20, ptr @sc_unit_0)
  %t23 = call zeroext i1 @scr_exc_pending()
  br i1 %t23, label %exc.u6, label %exc.k7
exc.u6:
  ret void
exc.k7:
  %t24 = call ptr @scr_arr_new(i32 0, i64 2)
  %t25 = call double @scr_arr_push_f64(ptr %t24, double 0x4000000000000000)
  %t26 = call double @scr_arr_push_f64(ptr %t24, double 0x3FF0000000000000)
  %t27 = call ptr @scr_arr_new(i32 0, i64 2)
  %t28 = call double @scr_arr_push_f64(ptr %t27, double 0x4000000000000000)
  %t29 = call double @scr_arr_push_f64(ptr %t27, double 0x4010000000000000)
  %t30 = call ptr @sc_f__x25_m0_broadcastShapes(ptr %t24, ptr %t27)
  %t31 = call zeroext i1 @scr_exc_pending()
  br i1 %t31, label %exc.u8, label %exc.k9
exc.u8:
  call void @scr_arr_release(ptr %t30)
  ret void
exc.k9:
  %t32 = call ptr @scr_arr_new(i32 0, i64 2)
  %t33 = call double @scr_arr_push_f64(ptr %t32, double 0x4000000000000000)
  %t34 = call double @scr_arr_push_f64(ptr %t32, double 0x4010000000000000)
  call void @sc_f__x25_m1_assertArrayEqual(ptr %t30, ptr %t32, ptr @sc_unit_0)
  %t35 = call zeroext i1 @scr_exc_pending()
  br i1 %t35, label %exc.u10, label %exc.k11
exc.u10:
  ret void
exc.k11:
  %t36 = call ptr @scr_arr_new(i32 0, i64 2)
  %t37 = call double @scr_arr_push_f64(ptr %t36, double 0x4000000000000000)
  %t38 = call double @scr_arr_push_f64(ptr %t36, double 0x4008000000000000)
  %t39 = call ptr @scr_arr_new(i32 0, i64 1)
  %t40 = call double @scr_arr_push_f64(ptr %t39, double 0x4008000000000000)
  %t41 = call ptr @sc_f__x25_m0_broadcastShapes(ptr %t36, ptr %t39)
  %t42 = call zeroext i1 @scr_exc_pending()
  br i1 %t42, label %exc.u12, label %exc.k13
exc.u12:
  call void @scr_arr_release(ptr %t41)
  ret void
exc.k13:
  %t43 = call ptr @scr_arr_new(i32 0, i64 2)
  %t44 = call double @scr_arr_push_f64(ptr %t43, double 0x4000000000000000)
  %t45 = call double @scr_arr_push_f64(ptr %t43, double 0x4008000000000000)
  call void @sc_f__x25_m1_assertArrayEqual(ptr %t41, ptr %t43, ptr @sc_unit_0)
  %t46 = call zeroext i1 @scr_exc_pending()
  br i1 %t46, label %exc.u14, label %exc.k15
exc.u14:
  ret void
exc.k15:
  %t47 = call ptr @scr_arr_new(i32 0, i64 2)
  %t48 = call double @scr_arr_push_f64(ptr %t47, double 0x3FF0000000000000)
  %t49 = call double @scr_arr_push_f64(ptr %t47, double 0x4010000000000000)
  %t50 = call ptr @scr_arr_new(i32 0, i64 2)
  %t51 = call double @scr_arr_push_f64(ptr %t50, double 0x4008000000000000)
  %t52 = call double @scr_arr_push_f64(ptr %t50, double 0x3FF0000000000000)
  %t53 = call ptr @sc_f__x25_m0_broadcastShapes(ptr %t47, ptr %t50)
  %t54 = call zeroext i1 @scr_exc_pending()
  br i1 %t54, label %exc.u16, label %exc.k17
exc.u16:
  call void @scr_arr_release(ptr %t53)
  ret void
exc.k17:
  %t55 = call ptr @scr_arr_new(i32 0, i64 2)
  %t56 = call double @scr_arr_push_f64(ptr %t55, double 0x4008000000000000)
  %t57 = call double @scr_arr_push_f64(ptr %t55, double 0x4010000000000000)
  call void @sc_f__x25_m1_assertArrayEqual(ptr %t53, ptr %t55, ptr @sc_unit_0)
  %t58 = call zeroext i1 @scr_exc_pending()
  br i1 %t58, label %exc.u18, label %exc.k19
exc.u18:
  ret void
exc.k19:
  %t59 = call ptr @scr_closure_new(ptr @sc_f__x25_fn8, i64 0)
  %t60 = call ptr @scr_str_retain_v(ptr @sc_lit_43)
  %t61 = call ptr @scr_union_new_ref(i32 0, ptr %t60, ptr @scr_str_retain_v, ptr @scr_str_release_v, ptr null)
  call void @sc_f__x25_m1_assertThrows(ptr %t59, ptr %t61)
  %t62 = call zeroext i1 @scr_exc_pending()
  br i1 %t62, label %exc.u20, label %exc.k21
exc.u20:
  ret void
exc.k21:
  ret void
}

declare void @scr_exc_print_uncaught()

define i32 @main(i32 %argc, ptr %argv) #0 {
entry:
  call void @scr_init()
  store i64 0, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 1) ; Error
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 0)
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 1) ; TypeError
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 0)
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 1) ; RangeError
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 0)
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 1) ; SyntaxError
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 1) ; DOMException
  call void @scr_lib_init(i32 %argc, ptr %argv)
  call void @sc_f__x25_main()
  %exc = call zeroext i1 @scr_exc_pending()
  br i1 %exc, label %uncaught, label %ok
uncaught:
  call void @scr_exc_print_uncaught()
  %gu0 = load ptr, ptr @sc_g_e_tests
  call void @scr_arr_release(ptr %gu0) ; tests
  ret i32 1
ok:
  %g0 = load ptr, ptr @sc_g_e_tests
  call void @scr_arr_release(ptr %g0) ; tests
  ret i32 0
}

attributes #0 = { sanitize_address }
