; Generated by scriptc (LLVM backend) from /Users/sam/Dev/llama.scriptc/examples/phase0/arrays.ts. Do not edit.

%ScrStr = type { i64, i64, i64 }
%ScrLogArg = type { i32, i64 }
%ScrVt = type { i64, i64, ptr }
%ScrUnion = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrClosure = type { i64, ptr, i64, ptr }
%ScrRegex = type { i64, ptr, ptr, ptr }
%ScrArr = type { i64, i64, i64, i32, ptr, ptr, ptr, ptr }
%ScrError = type { i64, ptr, ptr, ptr, ptr }
%ScrClassObj = type { i64, i64, i64, ptr, ptr }
%ScrEmitter = type { i64, ptr, ptr, ptr }
%ScrStream = type { i64, ptr, ptr, ptr, ptr }
%ScrCaught = type { i64, i32, double, i8, ptr, ptr, ptr, ptr }
%ScrBytes = type { i64, i64, i32, ptr, ptr }
%ScrBox = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrJsonBuf = type { ptr, i64, i64, ptr, i64, i64 }
%ScrDynPath = type { ptr, ptr, i64 }
%ScrIslandModule = type { ptr, ptr, i64, i64, i32, ptr, i64, i64 }
%ScrIslandEdge = type { ptr, ptr, ptr, i32 }

@scr_error_vts = external global [5 x %ScrVt]
declare void @scr_init()
declare void @scr_lib_init(i32, ptr)
declare ptr @scr_str_retain_v(ptr)
declare void @scr_str_release_v(ptr)
declare void @scr_console_log(i64, ptr)
declare void @scr_str_release(ptr)
declare ptr @scr_arr_new(i32, i64)
declare double @scr_arr_push_f64(ptr, double)
declare void @scr_arr_release(ptr)
declare ptr @scr_arr_retain_v(ptr)
declare void @scr_arr_release_v(ptr)
declare double @scr_arr_len(ptr)
declare double @scr_arr_get_f64(ptr, double)
declare double @scr_arr_pop_f64(ptr)
declare ptr @scr_arr_slice(ptr, double, double)
declare ptr @scr_closure_new(ptr, i64)
declare double @scr_arr_index_of_f64(ptr, double)
declare zeroext i1 @scr_arr_includes_f64(ptr, double)
declare double @scr_arr_push_ref(ptr, ptr)
declare ptr @scr_arr_get_ref(ptr, double)
declare void @scr_insp_begin(double)
declare ptr @scr_insp_f64(double)
declare void @scr_insp_entry(ptr, i1 zeroext)
declare ptr @scr_insp_more_items(double)
declare ptr @scr_insp_end(ptr, ptr, ptr, double, i1 zeroext, i1 zeroext)
declare ptr @scr_closure_retain_v(ptr)
declare void @scr_closure_release_v(ptr)
declare void @scr_closure_release(ptr)
declare double @fmod(double, double)
declare void @scr_arr_set_f64(ptr, double, double)

@sc_lit_0 = internal global { i64, i64, i64, [31 x i8] } { i64 -1, i64 30, i64 30, [31 x i8] c"--- Basic array operations ---\00" }
@sc_lit_1 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"arr:\00" }
@sc_lit_2 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c"arr.length:\00" }
@sc_lit_3 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"arr[0]:\00" }
@sc_lit_4 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"arr[4]:\00" }
@sc_lit_5 = internal global { i64, i64, i64, [20 x i8] } { i64 -1, i64 19, i64 19, [20 x i8] c"\0A--- Push / Pop ---\00" }
@sc_lit_6 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c"after push:\00" }
@sc_lit_7 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"popped:\00" }
@sc_lit_8 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"remaining:\00" }
@sc_lit_9 = internal global { i64, i64, i64, [15 x i8] } { i64 -1, i64 14, i64 14, [15 x i8] c"\0A--- Slice ---\00" }
@sc_lit_10 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"slice(2, 5):\00" }
@sc_lit_11 = internal global { i64, i64, i64, [10 x i8] } { i64 -1, i64 9, i64 9, [10 x i8] c"slice(5):\00" }
@sc_lit_12 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"slice(-3):\00" }
@sc_lit_13 = internal global { i64, i64, i64, [31 x i8] } { i64 -1, i64 30, i64 30, [31 x i8] c"\0A--- Map / Filter / Reduce ---\00" }
@sc_lit_14 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"map x*2:\00" }
@sc_lit_15 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"filter even:\00" }
@sc_lit_16 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c"reduce sum:\00" }
@sc_lit_17 = internal global { i64, i64, i64, [28 x i8] } { i64 -1, i64 27, i64 27, [28 x i8] c"\0A--- indexOf / includes ---\00" }
@sc_lit_18 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c"indexOf(3):\00" }
@sc_lit_19 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"indexOf(99):\00" }
@sc_lit_20 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"includes(3):\00" }
@sc_lit_21 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c"includes(99):\00" }
@sc_lit_22 = internal global { i64, i64, i64, [19 x i8] } { i64 -1, i64 18, i64 18, [19 x i8] c"\0A--- 2D arrays ---\00" }
@sc_lit_23 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c"matrix[1][2]:\00" }
@sc_lit_24 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"rows:\00" }
@sc_lit_25 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"cols:\00" }
@sc_lit_26 = internal global { i64, i64, i64, [22 x i8] } { i64 -1, i64 21, i64 21, [22 x i8] c"\0A--- Fill pattern ---\00" }
@sc_lit_27 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"squares:\00" }
@sc_lit_28 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c"\0A--- Sort ---\00" }
@sc_lit_29 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"sorted:\00" }
@sc_lit_30 = internal global { i64, i64, i64, [21 x i8] } { i64 -1, i64 20, i64 20, [21 x i8] c"\0A--- Large array ---\00" }
@sc_lit_31 = internal global { i64, i64, i64, [18 x i8] } { i64 -1, i64 17, i64 17, [18 x i8] c"big array length:\00" }
@sc_lit_32 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c"big[99999]:\00" }
@sc_lit_33 = internal global { i64, i64, i64, [23 x i8] } { i64 -1, i64 22, i64 22, [23 x i8] c"\0A--- Bounds safety ---\00" }
@sc_lit_34 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"safe[2]:\00" }
@sc_lit_35 = internal global { i64, i64, i64, [27 x i8] } { i64 -1, i64 26, i64 26, [27 x i8] c"Safe bounds checking works\00" }
@sc_lit_36 = internal global { i64, i64, i64, [22 x i8] } { i64 -1, i64 21, i64 21, [22 x i8] c"\0A\E2\9C\85 arrays.ts passed\00" }
@sc_lit_37 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"[]\00" }
@sc_lit_38 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"[Array]\00" }
@sc_lit_39 = internal global { i64, i64, i64, [1 x i8] } { i64 -1, i64 0, i64 0, [1 x i8] c"\00" }
@sc_lit_40 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"[\00" }
@sc_lit_41 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"]\00" }

@sc_g_e_arr = internal global ptr null ; arr
@sc_g_e_dynamic = internal global ptr null ; dynamic
@sc_g_e_popped = internal global double 0x0000000000000000 ; popped
@sc_g_e_original = internal global ptr null ; original
@sc_g_e_doubled = internal global ptr null ; doubled
@sc_g_e_evens = internal global ptr null ; evens
@sc_g_e_total = internal global double 0x0000000000000000 ; total
@sc_g_e_matrix = internal global ptr null ; matrix
@sc_g_e_filled = internal global ptr null ; filled
@sc_g_e_unsorted = internal global ptr null ; unsorted
@sc_g_e_sorted = internal global ptr null ; sorted
@sc_g_e_big = internal global ptr null ; big
@sc_g_e_safe = internal global ptr null ; safe
@sc_g_e__x25_loaded = internal global i1 false ; %loaded

define internal void @sc_f__x25_init_0() #0 { ; %init.0
entry:
  %sc_l_i_0 = alloca double ; i
  %sc_l_i_1 = alloca double ; i
  %logargs = alloca [4 x %ScrLogArg]
  %t0 = load i1, ptr @sc_g_e__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_e__x25_loaded
  %t1 = call ptr @scr_str_retain_v(ptr @sc_lit_0)
  %t2 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t2
  %t3 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t1, ptr %t3
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t1)
  %t4 = call ptr @scr_arr_new(i32 0, i64 5)
  %t5 = call double @scr_arr_push_f64(ptr %t4, double 0x3FF0000000000000)
  %t6 = call double @scr_arr_push_f64(ptr %t4, double 0x4000000000000000)
  %t7 = call double @scr_arr_push_f64(ptr %t4, double 0x4008000000000000)
  %t8 = call double @scr_arr_push_f64(ptr %t4, double 0x4010000000000000)
  %t9 = call double @scr_arr_push_f64(ptr %t4, double 0x4014000000000000)
  %t10 = load ptr, ptr @sc_g_e_arr
  call void @scr_arr_release(ptr %t10)
  store ptr %t4, ptr @sc_g_e_arr
  %t11 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t12 = load ptr, ptr @sc_g_e_arr
  %t13 = call ptr @scr_arr_retain_v(ptr %t12)
  %t14 = call ptr @sc_f__x25_util_insp_0(ptr %t13, double 0x0000000000000000, double 0x4000000000000000)
  %t15 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t15
  %t16 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t11, ptr %t16
  %t17 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t17
  %t18 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t14, ptr %t18
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t11)
  call void @scr_str_release(ptr %t14)
  %t19 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  %t20 = load ptr, ptr @sc_g_e_arr
  %t21 = call ptr @scr_arr_retain_v(ptr %t20)
  %t22 = call double @scr_arr_len(ptr %t21)
  %t23 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t23
  %t24 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t19, ptr %t24
  %t25 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t25
  %t26 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t22, ptr %t26
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t19)
  call void @scr_arr_release(ptr %t21)
  %t27 = call ptr @scr_str_retain_v(ptr @sc_lit_3)
  %t28 = load ptr, ptr @sc_g_e_arr
  %t29 = call ptr @scr_arr_retain_v(ptr %t28)
  %t30 = call double @scr_arr_get_f64(ptr %t29, double 0x0000000000000000)
  %t31 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t31
  %t32 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t27, ptr %t32
  %t33 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t33
  %t34 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t30, ptr %t34
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t27)
  call void @scr_arr_release(ptr %t29)
  %t35 = call ptr @scr_str_retain_v(ptr @sc_lit_4)
  %t36 = load ptr, ptr @sc_g_e_arr
  %t37 = call ptr @scr_arr_retain_v(ptr %t36)
  %t38 = call double @scr_arr_get_f64(ptr %t37, double 0x4010000000000000)
  %t39 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t39
  %t40 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t35, ptr %t40
  %t41 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t41
  %t42 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t38, ptr %t42
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t35)
  call void @scr_arr_release(ptr %t37)
  %t43 = call ptr @scr_str_retain_v(ptr @sc_lit_5)
  %t44 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t44
  %t45 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t43, ptr %t45
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t43)
  %t46 = call ptr @scr_arr_new(i32 0, i64 0)
  %t47 = load ptr, ptr @sc_g_e_dynamic
  call void @scr_arr_release(ptr %t47)
  store ptr %t46, ptr @sc_g_e_dynamic
  %t48 = load ptr, ptr @sc_g_e_dynamic
  %t49 = call ptr @scr_arr_retain_v(ptr %t48)
  %t50 = call double @scr_arr_push_f64(ptr %t49, double 0x4024000000000000)
  call void @scr_arr_release(ptr %t49)
  %t51 = load ptr, ptr @sc_g_e_dynamic
  %t52 = call ptr @scr_arr_retain_v(ptr %t51)
  %t53 = call double @scr_arr_push_f64(ptr %t52, double 0x4034000000000000)
  call void @scr_arr_release(ptr %t52)
  %t54 = load ptr, ptr @sc_g_e_dynamic
  %t55 = call ptr @scr_arr_retain_v(ptr %t54)
  %t56 = call double @scr_arr_push_f64(ptr %t55, double 0x403E000000000000)
  call void @scr_arr_release(ptr %t55)
  %t57 = call ptr @scr_str_retain_v(ptr @sc_lit_6)
  %t58 = load ptr, ptr @sc_g_e_dynamic
  %t59 = call ptr @scr_arr_retain_v(ptr %t58)
  %t60 = call ptr @sc_f__x25_util_insp_0(ptr %t59, double 0x0000000000000000, double 0x4000000000000000)
  %t61 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t61
  %t62 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t57, ptr %t62
  %t63 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t63
  %t64 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t60, ptr %t64
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t57)
  call void @scr_str_release(ptr %t60)
  %t65 = load ptr, ptr @sc_g_e_dynamic
  %t66 = call ptr @scr_arr_retain_v(ptr %t65)
  %t67 = call double @scr_arr_pop_f64(ptr %t66)
  store double %t67, ptr @sc_g_e_popped
  call void @scr_arr_release(ptr %t66)
  %t68 = call ptr @scr_str_retain_v(ptr @sc_lit_7)
  %t69 = load double, ptr @sc_g_e_popped
  %t70 = call ptr @scr_str_retain_v(ptr @sc_lit_8)
  %t71 = load ptr, ptr @sc_g_e_dynamic
  %t72 = call ptr @scr_arr_retain_v(ptr %t71)
  %t73 = call ptr @sc_f__x25_util_insp_0(ptr %t72, double 0x0000000000000000, double 0x4000000000000000)
  %t74 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t74
  %t75 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t68, ptr %t75
  %t76 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t76
  %t77 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t69, ptr %t77
  %t78 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 0
  store i32 1, ptr %t78
  %t79 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 1
  store ptr %t70, ptr %t79
  %t80 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 3, i32 0
  store i32 1, ptr %t80
  %t81 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 3, i32 1
  store ptr %t73, ptr %t81
  call void @scr_console_log(i64 4, ptr %logargs)
  call void @scr_str_release(ptr %t68)
  call void @scr_str_release(ptr %t70)
  call void @scr_str_release(ptr %t73)
  %t82 = call ptr @scr_str_retain_v(ptr @sc_lit_9)
  %t83 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t83
  %t84 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t82, ptr %t84
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t82)
  %t85 = call ptr @scr_arr_new(i32 0, i64 10)
  %t86 = call double @scr_arr_push_f64(ptr %t85, double 0x0000000000000000)
  %t87 = call double @scr_arr_push_f64(ptr %t85, double 0x3FF0000000000000)
  %t88 = call double @scr_arr_push_f64(ptr %t85, double 0x4000000000000000)
  %t89 = call double @scr_arr_push_f64(ptr %t85, double 0x4008000000000000)
  %t90 = call double @scr_arr_push_f64(ptr %t85, double 0x4010000000000000)
  %t91 = call double @scr_arr_push_f64(ptr %t85, double 0x4014000000000000)
  %t92 = call double @scr_arr_push_f64(ptr %t85, double 0x4018000000000000)
  %t93 = call double @scr_arr_push_f64(ptr %t85, double 0x401C000000000000)
  %t94 = call double @scr_arr_push_f64(ptr %t85, double 0x4020000000000000)
  %t95 = call double @scr_arr_push_f64(ptr %t85, double 0x4022000000000000)
  %t96 = load ptr, ptr @sc_g_e_original
  call void @scr_arr_release(ptr %t96)
  store ptr %t85, ptr @sc_g_e_original
  %t97 = call ptr @scr_str_retain_v(ptr @sc_lit_10)
  %t98 = load ptr, ptr @sc_g_e_original
  %t99 = call ptr @scr_arr_retain_v(ptr %t98)
  %t100 = call ptr @scr_arr_slice(ptr %t99, double 0x4000000000000000, double 0x4014000000000000)
  %t101 = call ptr @sc_f__x25_util_insp_0(ptr %t100, double 0x0000000000000000, double 0x4000000000000000)
  %t102 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t102
  %t103 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t97, ptr %t103
  %t104 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t104
  %t105 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t101, ptr %t105
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t97)
  call void @scr_arr_release(ptr %t99)
  call void @scr_str_release(ptr %t101)
  %t106 = call ptr @scr_str_retain_v(ptr @sc_lit_11)
  %t107 = load ptr, ptr @sc_g_e_original
  %t108 = call ptr @scr_arr_retain_v(ptr %t107)
  %t109 = call ptr @scr_arr_slice(ptr %t108, double 0x4014000000000000, double 0x7FF0000000000000)
  %t110 = call ptr @sc_f__x25_util_insp_0(ptr %t109, double 0x0000000000000000, double 0x4000000000000000)
  %t111 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t111
  %t112 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t106, ptr %t112
  %t113 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t113
  %t114 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t110, ptr %t114
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t106)
  call void @scr_arr_release(ptr %t108)
  call void @scr_str_release(ptr %t110)
  %t115 = call ptr @scr_str_retain_v(ptr @sc_lit_12)
  %t116 = load ptr, ptr @sc_g_e_original
  %t117 = call ptr @scr_arr_retain_v(ptr %t116)
  %t118 = call ptr @scr_arr_slice(ptr %t117, double 0xC008000000000000, double 0x7FF0000000000000)
  %t119 = call ptr @sc_f__x25_util_insp_0(ptr %t118, double 0x0000000000000000, double 0x4000000000000000)
  %t120 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t120
  %t121 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t115, ptr %t121
  %t122 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t122
  %t123 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t119, ptr %t123
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t115)
  call void @scr_arr_release(ptr %t117)
  call void @scr_str_release(ptr %t119)
  %t124 = call ptr @scr_str_retain_v(ptr @sc_lit_13)
  %t125 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t125
  %t126 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t124, ptr %t126
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t124)
  %t127 = load ptr, ptr @sc_g_e_arr
  %t128 = call ptr @scr_arr_retain_v(ptr %t127)
  %t129 = call ptr @scr_closure_new(ptr @sc_f__x25_fn0, i64 0)
  %t130 = call ptr @sc_f__x25_arr_map_0(ptr %t128, ptr %t129)
  %t131 = load ptr, ptr @sc_g_e_doubled
  call void @scr_arr_release(ptr %t131)
  store ptr %t130, ptr @sc_g_e_doubled
  %t132 = call ptr @scr_str_retain_v(ptr @sc_lit_14)
  %t133 = load ptr, ptr @sc_g_e_doubled
  %t134 = call ptr @scr_arr_retain_v(ptr %t133)
  %t135 = call ptr @sc_f__x25_util_insp_0(ptr %t134, double 0x0000000000000000, double 0x4000000000000000)
  %t136 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t136
  %t137 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t132, ptr %t137
  %t138 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t138
  %t139 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t135, ptr %t139
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t132)
  call void @scr_str_release(ptr %t135)
  %t140 = load ptr, ptr @sc_g_e_arr
  %t141 = call ptr @scr_arr_retain_v(ptr %t140)
  %t142 = call ptr @scr_closure_new(ptr @sc_f__x25_fn1, i64 0)
  %t143 = call ptr @sc_f__x25_arr_filter_1(ptr %t141, ptr %t142)
  %t144 = load ptr, ptr @sc_g_e_evens
  call void @scr_arr_release(ptr %t144)
  store ptr %t143, ptr @sc_g_e_evens
  %t145 = call ptr @scr_str_retain_v(ptr @sc_lit_15)
  %t146 = load ptr, ptr @sc_g_e_evens
  %t147 = call ptr @scr_arr_retain_v(ptr %t146)
  %t148 = call ptr @sc_f__x25_util_insp_0(ptr %t147, double 0x0000000000000000, double 0x4000000000000000)
  %t149 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t149
  %t150 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t145, ptr %t150
  %t151 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t151
  %t152 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t148, ptr %t152
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t145)
  call void @scr_str_release(ptr %t148)
  %t153 = load ptr, ptr @sc_g_e_arr
  %t154 = call ptr @scr_arr_retain_v(ptr %t153)
  %t155 = call ptr @scr_closure_new(ptr @sc_f__x25_fn2, i64 0)
  %t156 = call double @sc_f__x25_arr_reduce_2(ptr %t154, ptr %t155, double 0x0000000000000000)
  store double %t156, ptr @sc_g_e_total
  %t157 = call ptr @scr_str_retain_v(ptr @sc_lit_16)
  %t158 = load double, ptr @sc_g_e_total
  %t159 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t159
  %t160 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t157, ptr %t160
  %t161 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t161
  %t162 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t158, ptr %t162
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t157)
  %t163 = call ptr @scr_str_retain_v(ptr @sc_lit_17)
  %t164 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t164
  %t165 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t163, ptr %t165
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t163)
  %t166 = call ptr @scr_str_retain_v(ptr @sc_lit_18)
  %t167 = load ptr, ptr @sc_g_e_arr
  %t168 = call ptr @scr_arr_retain_v(ptr %t167)
  %t169 = call double @scr_arr_index_of_f64(ptr %t168, double 0x4008000000000000)
  %t170 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t170
  %t171 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t166, ptr %t171
  %t172 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t172
  %t173 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t169, ptr %t173
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t166)
  call void @scr_arr_release(ptr %t168)
  %t174 = call ptr @scr_str_retain_v(ptr @sc_lit_19)
  %t175 = load ptr, ptr @sc_g_e_arr
  %t176 = call ptr @scr_arr_retain_v(ptr %t175)
  %t177 = call double @scr_arr_index_of_f64(ptr %t176, double 0x4058C00000000000)
  %t178 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t178
  %t179 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t174, ptr %t179
  %t180 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t180
  %t181 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t177, ptr %t181
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t174)
  call void @scr_arr_release(ptr %t176)
  %t182 = call ptr @scr_str_retain_v(ptr @sc_lit_20)
  %t183 = load ptr, ptr @sc_g_e_arr
  %t184 = call ptr @scr_arr_retain_v(ptr %t183)
  %t185 = call zeroext i1 @scr_arr_includes_f64(ptr %t184, double 0x4008000000000000)
  %t186 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t186
  %t187 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t182, ptr %t187
  %t188 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 2, ptr %t188
  %t189 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  %t190 = zext i1 %t185 to i8
  store i8 %t190, ptr %t189
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t182)
  call void @scr_arr_release(ptr %t184)
  %t191 = call ptr @scr_str_retain_v(ptr @sc_lit_21)
  %t192 = load ptr, ptr @sc_g_e_arr
  %t193 = call ptr @scr_arr_retain_v(ptr %t192)
  %t194 = call zeroext i1 @scr_arr_includes_f64(ptr %t193, double 0x4058C00000000000)
  %t195 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t195
  %t196 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t191, ptr %t196
  %t197 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 2, ptr %t197
  %t198 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  %t199 = zext i1 %t194 to i8
  store i8 %t199, ptr %t198
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t191)
  call void @scr_arr_release(ptr %t193)
  %t200 = call ptr @scr_str_retain_v(ptr @sc_lit_22)
  %t201 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t201
  %t202 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t200, ptr %t202
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t200)
  %t203 = call ptr @scr_arr_new(i32 3, i64 3)
  %t204 = call ptr @scr_arr_new(i32 0, i64 3)
  %t205 = call double @scr_arr_push_f64(ptr %t204, double 0x3FF0000000000000)
  %t206 = call double @scr_arr_push_f64(ptr %t204, double 0x4000000000000000)
  %t207 = call double @scr_arr_push_f64(ptr %t204, double 0x4008000000000000)
  %t208 = call double @scr_arr_push_ref(ptr %t203, ptr %t204)
  %t209 = call ptr @scr_arr_new(i32 0, i64 3)
  %t210 = call double @scr_arr_push_f64(ptr %t209, double 0x4010000000000000)
  %t211 = call double @scr_arr_push_f64(ptr %t209, double 0x4014000000000000)
  %t212 = call double @scr_arr_push_f64(ptr %t209, double 0x4018000000000000)
  %t213 = call double @scr_arr_push_ref(ptr %t203, ptr %t209)
  %t214 = call ptr @scr_arr_new(i32 0, i64 3)
  %t215 = call double @scr_arr_push_f64(ptr %t214, double 0x401C000000000000)
  %t216 = call double @scr_arr_push_f64(ptr %t214, double 0x4020000000000000)
  %t217 = call double @scr_arr_push_f64(ptr %t214, double 0x4022000000000000)
  %t218 = call double @scr_arr_push_ref(ptr %t203, ptr %t214)
  %t219 = load ptr, ptr @sc_g_e_matrix
  call void @scr_arr_release(ptr %t219)
  store ptr %t203, ptr @sc_g_e_matrix
  %t220 = call ptr @scr_str_retain_v(ptr @sc_lit_23)
  %t221 = load ptr, ptr @sc_g_e_matrix
  %t222 = call ptr @scr_arr_retain_v(ptr %t221)
  %t223 = call ptr @scr_arr_get_ref(ptr %t222, double 0x3FF0000000000000)
  %t224 = call double @scr_arr_get_f64(ptr %t223, double 0x4000000000000000)
  %t225 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t225
  %t226 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t220, ptr %t226
  %t227 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t227
  %t228 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t224, ptr %t228
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t220)
  call void @scr_arr_release(ptr %t222)
  call void @scr_arr_release(ptr %t223)
  %t229 = call ptr @scr_str_retain_v(ptr @sc_lit_24)
  %t230 = load ptr, ptr @sc_g_e_matrix
  %t231 = call ptr @scr_arr_retain_v(ptr %t230)
  %t232 = call double @scr_arr_len(ptr %t231)
  %t233 = call ptr @scr_str_retain_v(ptr @sc_lit_25)
  %t234 = load ptr, ptr @sc_g_e_matrix
  %t235 = call ptr @scr_arr_retain_v(ptr %t234)
  %t236 = call ptr @scr_arr_get_ref(ptr %t235, double 0x0000000000000000)
  %t237 = call double @scr_arr_len(ptr %t236)
  %t238 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t238
  %t239 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t229, ptr %t239
  %t240 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t240
  %t241 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t232, ptr %t241
  %t242 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 0
  store i32 1, ptr %t242
  %t243 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 1
  store ptr %t233, ptr %t243
  %t244 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 3, i32 0
  store i32 0, ptr %t244
  %t245 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 3, i32 1
  store double %t237, ptr %t245
  call void @scr_console_log(i64 4, ptr %logargs)
  call void @scr_str_release(ptr %t229)
  call void @scr_arr_release(ptr %t231)
  call void @scr_str_release(ptr %t233)
  call void @scr_arr_release(ptr %t235)
  call void @scr_arr_release(ptr %t236)
  %t246 = call ptr @scr_str_retain_v(ptr @sc_lit_26)
  %t247 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t247
  %t248 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t246, ptr %t248
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t246)
  %t249 = call ptr @scr_arr_new(i32 0, i64 0)
  %t250 = load ptr, ptr @sc_g_e_filled
  call void @scr_arr_release(ptr %t250)
  store ptr %t249, ptr @sc_g_e_filled
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c2
loop.c2:
  %t251 = load double, ptr %sc_l_i_0
  %t252 = fcmp olt double %t251, 0x4024000000000000
  br i1 %t252, label %loop.b3, label %loop.e4
loop.b3:
  %t253 = load ptr, ptr @sc_g_e_filled
  %t254 = call ptr @scr_arr_retain_v(ptr %t253)
  %t255 = load double, ptr %sc_l_i_0
  %t256 = load double, ptr %sc_l_i_0
  %t257 = fmul double %t255, %t256
  %t258 = call double @scr_arr_push_f64(ptr %t254, double %t257)
  call void @scr_arr_release(ptr %t254)
  br label %loop.u5
loop.u5:
  %t259 = load double, ptr %sc_l_i_0
  %t260 = fadd double %t259, 0x3FF0000000000000
  store double %t260, ptr %sc_l_i_0
  br label %loop.c2
loop.e4:
  %t261 = call ptr @scr_str_retain_v(ptr @sc_lit_27)
  %t262 = load ptr, ptr @sc_g_e_filled
  %t263 = call ptr @scr_arr_retain_v(ptr %t262)
  %t264 = call ptr @sc_f__x25_util_insp_0(ptr %t263, double 0x0000000000000000, double 0x4000000000000000)
  %t265 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t265
  %t266 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t261, ptr %t266
  %t267 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t267
  %t268 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t264, ptr %t268
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t261)
  call void @scr_str_release(ptr %t264)
  %t269 = call ptr @scr_str_retain_v(ptr @sc_lit_28)
  %t270 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t270
  %t271 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t269, ptr %t271
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t269)
  %t272 = call ptr @scr_arr_new(i32 0, i64 8)
  %t273 = call double @scr_arr_push_f64(ptr %t272, double 0x4008000000000000)
  %t274 = call double @scr_arr_push_f64(ptr %t272, double 0x3FF0000000000000)
  %t275 = call double @scr_arr_push_f64(ptr %t272, double 0x4010000000000000)
  %t276 = call double @scr_arr_push_f64(ptr %t272, double 0x3FF0000000000000)
  %t277 = call double @scr_arr_push_f64(ptr %t272, double 0x4014000000000000)
  %t278 = call double @scr_arr_push_f64(ptr %t272, double 0x4022000000000000)
  %t279 = call double @scr_arr_push_f64(ptr %t272, double 0x4000000000000000)
  %t280 = call double @scr_arr_push_f64(ptr %t272, double 0x4018000000000000)
  %t281 = load ptr, ptr @sc_g_e_unsorted
  call void @scr_arr_release(ptr %t281)
  store ptr %t272, ptr @sc_g_e_unsorted
  %t282 = load ptr, ptr @sc_g_e_unsorted
  %t283 = call ptr @scr_arr_retain_v(ptr %t282)
  %t284 = call ptr @scr_arr_slice(ptr %t283, double 0x0000000000000000, double 0x7FF0000000000000)
  %t285 = call ptr @scr_closure_new(ptr @sc_f__x25_fn3, i64 0)
  %t286 = call ptr @sc_f__x25_arr_sort_3(ptr %t284, ptr %t285)
  %t287 = load ptr, ptr @sc_g_e_sorted
  call void @scr_arr_release(ptr %t287)
  store ptr %t286, ptr @sc_g_e_sorted
  call void @scr_arr_release(ptr %t283)
  %t288 = call ptr @scr_str_retain_v(ptr @sc_lit_29)
  %t289 = load ptr, ptr @sc_g_e_sorted
  %t290 = call ptr @scr_arr_retain_v(ptr %t289)
  %t291 = call ptr @sc_f__x25_util_insp_0(ptr %t290, double 0x0000000000000000, double 0x4000000000000000)
  %t292 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t292
  %t293 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t288, ptr %t293
  %t294 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t294
  %t295 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t291, ptr %t295
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t288)
  call void @scr_str_release(ptr %t291)
  %t296 = call ptr @scr_str_retain_v(ptr @sc_lit_30)
  %t297 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t297
  %t298 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t296, ptr %t298
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t296)
  %t299 = call ptr @scr_arr_new(i32 0, i64 0)
  %t300 = load ptr, ptr @sc_g_e_big
  call void @scr_arr_release(ptr %t300)
  store ptr %t299, ptr @sc_g_e_big
  store double 0x0000000000000000, ptr %sc_l_i_1
  br label %loop.c6
loop.c6:
  %t301 = load double, ptr %sc_l_i_1
  %t302 = fcmp olt double %t301, 0x40F86A0000000000
  br i1 %t302, label %loop.b7, label %loop.e8
loop.b7:
  %t303 = load ptr, ptr @sc_g_e_big
  %t304 = call ptr @scr_arr_retain_v(ptr %t303)
  %t305 = load double, ptr %sc_l_i_1
  %t306 = call double @scr_arr_push_f64(ptr %t304, double %t305)
  call void @scr_arr_release(ptr %t304)
  br label %loop.u9
loop.u9:
  %t307 = load double, ptr %sc_l_i_1
  %t308 = fadd double %t307, 0x3FF0000000000000
  store double %t308, ptr %sc_l_i_1
  br label %loop.c6
loop.e8:
  %t309 = call ptr @scr_str_retain_v(ptr @sc_lit_31)
  %t310 = load ptr, ptr @sc_g_e_big
  %t311 = call ptr @scr_arr_retain_v(ptr %t310)
  %t312 = call double @scr_arr_len(ptr %t311)
  %t313 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t313
  %t314 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t309, ptr %t314
  %t315 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t315
  %t316 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t312, ptr %t316
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t309)
  call void @scr_arr_release(ptr %t311)
  %t317 = call ptr @scr_str_retain_v(ptr @sc_lit_32)
  %t318 = load ptr, ptr @sc_g_e_big
  %t319 = call ptr @scr_arr_retain_v(ptr %t318)
  %t320 = call double @scr_arr_get_f64(ptr %t319, double 0x40F869F000000000)
  %t321 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t321
  %t322 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t317, ptr %t322
  %t323 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t323
  %t324 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t320, ptr %t324
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t317)
  call void @scr_arr_release(ptr %t319)
  %t325 = call ptr @scr_str_retain_v(ptr @sc_lit_33)
  %t326 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t326
  %t327 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t325, ptr %t327
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t325)
  %t328 = call ptr @scr_arr_new(i32 0, i64 3)
  %t329 = call double @scr_arr_push_f64(ptr %t328, double 0x4024000000000000)
  %t330 = call double @scr_arr_push_f64(ptr %t328, double 0x4034000000000000)
  %t331 = call double @scr_arr_push_f64(ptr %t328, double 0x403E000000000000)
  %t332 = load ptr, ptr @sc_g_e_safe
  call void @scr_arr_release(ptr %t332)
  store ptr %t328, ptr @sc_g_e_safe
  %t333 = load ptr, ptr @sc_g_e_safe
  %t334 = call ptr @scr_arr_retain_v(ptr %t333)
  %t335 = call double @scr_arr_len(ptr %t334)
  %t336 = fcmp ogt double %t335, 0x4000000000000000
  call void @scr_arr_release(ptr %t334)
  br i1 %t336, label %if.t10, label %if.j11
if.t10:
  %t337 = call ptr @scr_str_retain_v(ptr @sc_lit_34)
  %t338 = load ptr, ptr @sc_g_e_safe
  %t339 = call ptr @scr_arr_retain_v(ptr %t338)
  %t340 = call double @scr_arr_get_f64(ptr %t339, double 0x4000000000000000)
  %t341 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t341
  %t342 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t337, ptr %t342
  %t343 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t343
  %t344 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t340, ptr %t344
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t337)
  call void @scr_arr_release(ptr %t339)
  br label %if.j11
if.j11:
  %t345 = call ptr @scr_str_retain_v(ptr @sc_lit_35)
  %t346 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t346
  %t347 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t345, ptr %t347
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t345)
  %t348 = call ptr @scr_str_retain_v(ptr @sc_lit_36)
  %t349 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t349
  %t350 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t348, ptr %t350
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t348)
  ret void
}

define internal void @sc_f__x25_main() #0 { ; %main
entry:
  call void @sc_f__x25_init_0()
  ret void
}

define internal ptr @sc_f__x25_util_insp_0(ptr %p_sc_l_v_0, double %p_sc_l_r_0, double %p_sc_l_d_0) #0 { ; %util.insp.0
entry:
  %sc_l_v_0 = alloca ptr ; v
  %sc_l_r_0 = alloca double ; r
  %sc_l_d_0 = alloca double ; d
  %sc_l_n_0 = alloca double ; n
  %sc_l_s_0 = alloca double ; s
  %sc_l_i_0 = alloca double ; i
  %s14 = alloca double
  store ptr %p_sc_l_v_0, ptr %sc_l_v_0
  store double %p_sc_l_r_0, ptr %sc_l_r_0
  store double %p_sc_l_d_0, ptr %sc_l_d_0
  %t0 = load ptr, ptr %sc_l_v_0
  %t1 = call ptr @scr_arr_retain_v(ptr %t0)
  %t2 = call double @scr_arr_len(ptr %t1)
  store double %t2, ptr %sc_l_n_0
  call void @scr_arr_release(ptr %t1)
  %t3 = load double, ptr %sc_l_n_0
  %t4 = fcmp oeq double %t3, 0x0000000000000000
  br i1 %t4, label %if.t0, label %if.j1
if.t0:
  %t5 = call ptr @scr_str_retain_v(ptr @sc_lit_37)
  %t6 = load ptr, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t6)
  ret ptr %t5
if.j1:
  %t7 = load double, ptr %sc_l_r_0
  %t8 = load double, ptr %sc_l_d_0
  %t9 = fcmp ogt double %t7, %t8
  br i1 %t9, label %if.t2, label %if.j3
if.t2:
  %t10 = call ptr @scr_str_retain_v(ptr @sc_lit_38)
  %t11 = load ptr, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t11)
  ret ptr %t10
if.j3:
  %t12 = load double, ptr %sc_l_n_0
  %t13 = fcmp ogt double %t12, 0x4059000000000000
  br i1 %t13, label %tern.t4, label %tern.f5
tern.t4:
  store double 0x4059000000000000, ptr %s14
  br label %tern.j6
tern.f5:
  %t15 = load double, ptr %sc_l_n_0
  store double %t15, ptr %s14
  br label %tern.j6
tern.j6:
  %t16 = load double, ptr %s14
  store double %t16, ptr %sc_l_s_0
  %t17 = load double, ptr %sc_l_r_0
  %t18 = fadd double %t17, 0x3FF0000000000000
  call void @scr_insp_begin(double %t18)
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c7
loop.c7:
  %t19 = load double, ptr %sc_l_i_0
  %t20 = load double, ptr %sc_l_s_0
  %t21 = fcmp olt double %t19, %t20
  br i1 %t21, label %loop.b8, label %loop.e9
loop.b8:
  %t22 = load ptr, ptr %sc_l_v_0
  %t23 = call ptr @scr_arr_retain_v(ptr %t22)
  %t24 = load double, ptr %sc_l_i_0
  %t25 = call double @scr_arr_get_f64(ptr %t23, double %t24)
  %t26 = call ptr @scr_insp_f64(double %t25)
  call void @scr_insp_entry(ptr %t26, i1 true)
  call void @scr_arr_release(ptr %t23)
  call void @scr_str_release(ptr %t26)
  br label %loop.u10
loop.u10:
  %t27 = load double, ptr %sc_l_i_0
  %t28 = fadd double %t27, 0x3FF0000000000000
  store double %t28, ptr %sc_l_i_0
  br label %loop.c7
loop.e9:
  %t29 = load double, ptr %sc_l_n_0
  %t30 = fcmp ogt double %t29, 0x4059000000000000
  br i1 %t30, label %if.t11, label %if.j12
if.t11:
  %t31 = load double, ptr %sc_l_n_0
  %t32 = fsub double %t31, 0x4059000000000000
  %t33 = call ptr @scr_insp_more_items(double %t32)
  call void @scr_insp_entry(ptr %t33, i1 true)
  call void @scr_str_release(ptr %t33)
  br label %if.j12
if.j12:
  %t34 = call ptr @scr_str_retain_v(ptr @sc_lit_39)
  %t35 = call ptr @scr_str_retain_v(ptr @sc_lit_40)
  %t36 = call ptr @scr_str_retain_v(ptr @sc_lit_41)
  %t37 = load double, ptr %sc_l_r_0
  %t38 = fadd double %t37, 0x3FF0000000000000
  %t39 = load double, ptr %sc_l_n_0
  %t40 = fcmp ogt double %t39, 0x4059000000000000
  %t41 = call ptr @scr_insp_end(ptr %t34, ptr %t35, ptr %t36, double %t38, i1 true, i1 %t40)
  call void @scr_str_release(ptr %t34)
  call void @scr_str_release(ptr %t35)
  call void @scr_str_release(ptr %t36)
  %t42 = load ptr, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t42)
  ret ptr %t41
}

define internal double @sc_f__x25_fn0(ptr %sc_env, double %p_sc_l_x_0) #0 { ; %fn0
entry:
  %sc_l_x_0 = alloca double ; x
  store double %p_sc_l_x_0, ptr %sc_l_x_0
  %t0 = load double, ptr %sc_l_x_0
  %t1 = fmul double %t0, 0x4000000000000000
  ret double %t1
}

define internal ptr @sc_f__x25_arr_map_0(ptr %p_sc_l_a_0, ptr %p_sc_l_f_0) #0 { ; %arr.map.0
entry:
  %sc_l_a_0 = alloca ptr ; a
  %sc_l_f_0 = alloca ptr ; f
  %sc_l_n_0 = alloca double ; n
  %sc_l_i_0 = alloca double ; i
  %sc_l_out_0 = alloca ptr ; out
  store ptr null, ptr %sc_l_out_0
  store ptr %p_sc_l_a_0, ptr %sc_l_a_0
  store ptr %p_sc_l_f_0, ptr %sc_l_f_0
  %t0 = call ptr @scr_arr_new(i32 0, i64 0)
  store ptr %t0, ptr %sc_l_out_0
  %t1 = load ptr, ptr %sc_l_a_0
  %t2 = call ptr @scr_arr_retain_v(ptr %t1)
  %t3 = call double @scr_arr_len(ptr %t2)
  store double %t3, ptr %sc_l_n_0
  call void @scr_arr_release(ptr %t2)
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c0
loop.c0:
  %t4 = load double, ptr %sc_l_i_0
  %t5 = load double, ptr %sc_l_n_0
  %t6 = fcmp olt double %t4, %t5
  br i1 %t6, label %loop.b1, label %loop.e2
loop.b1:
  %t7 = load ptr, ptr %sc_l_out_0
  %t8 = call ptr @scr_arr_retain_v(ptr %t7)
  %t9 = load ptr, ptr %sc_l_f_0
  %t10 = call ptr @scr_closure_retain_v(ptr %t9)
  %t11 = load ptr, ptr %sc_l_a_0
  %t12 = call ptr @scr_arr_retain_v(ptr %t11)
  %t13 = load double, ptr %sc_l_i_0
  %t14 = call double @scr_arr_get_f64(ptr %t12, double %t13)
  %t15 = getelementptr inbounds %ScrClosure, ptr %t10, i64 0, i32 1
  %t16 = load ptr, ptr %t15
  %t17 = call double %t16(ptr %t10, double %t14)
  %t18 = call double @scr_arr_push_f64(ptr %t8, double %t17)
  call void @scr_arr_release(ptr %t8)
  call void @scr_closure_release(ptr %t10)
  call void @scr_arr_release(ptr %t12)
  br label %loop.u3
loop.u3:
  %t19 = load double, ptr %sc_l_i_0
  %t20 = fadd double %t19, 0x3FF0000000000000
  store double %t20, ptr %sc_l_i_0
  br label %loop.c0
loop.e2:
  %t21 = load ptr, ptr %sc_l_out_0
  %t22 = call ptr @scr_arr_retain_v(ptr %t21)
  %t23 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t23)
  %t24 = load ptr, ptr %sc_l_f_0
  call void @scr_closure_release(ptr %t24)
  %t25 = load ptr, ptr %sc_l_out_0
  call void @scr_arr_release(ptr %t25)
  ret ptr %t22
}

define internal i1 @sc_f__x25_fn1(ptr %sc_env, double %p_sc_l_x_0) #0 { ; %fn1
entry:
  %sc_l_x_0 = alloca double ; x
  store double %p_sc_l_x_0, ptr %sc_l_x_0
  %t0 = load double, ptr %sc_l_x_0
  %t1 = call double @fmod(double %t0, double 0x4000000000000000)
  %t2 = fcmp oeq double %t1, 0x0000000000000000
  ret i1 %t2
}

define internal ptr @sc_f__x25_arr_filter_1(ptr %p_sc_l_a_0, ptr %p_sc_l_f_0) #0 { ; %arr.filter.1
entry:
  %sc_l_a_0 = alloca ptr ; a
  %sc_l_f_0 = alloca ptr ; f
  %sc_l_n_0 = alloca double ; n
  %sc_l_i_0 = alloca double ; i
  %sc_l_out_0 = alloca ptr ; out
  %sc_l_v_0 = alloca double ; v
  store ptr null, ptr %sc_l_out_0
  store ptr %p_sc_l_a_0, ptr %sc_l_a_0
  store ptr %p_sc_l_f_0, ptr %sc_l_f_0
  %t0 = call ptr @scr_arr_new(i32 0, i64 0)
  store ptr %t0, ptr %sc_l_out_0
  %t1 = load ptr, ptr %sc_l_a_0
  %t2 = call ptr @scr_arr_retain_v(ptr %t1)
  %t3 = call double @scr_arr_len(ptr %t2)
  store double %t3, ptr %sc_l_n_0
  call void @scr_arr_release(ptr %t2)
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c0
loop.c0:
  %t4 = load double, ptr %sc_l_i_0
  %t5 = load double, ptr %sc_l_n_0
  %t6 = fcmp olt double %t4, %t5
  br i1 %t6, label %loop.b1, label %loop.e2
loop.b1:
  %t7 = load ptr, ptr %sc_l_a_0
  %t8 = call ptr @scr_arr_retain_v(ptr %t7)
  %t9 = load double, ptr %sc_l_i_0
  %t10 = call double @scr_arr_get_f64(ptr %t8, double %t9)
  store double %t10, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t8)
  %t11 = load ptr, ptr %sc_l_f_0
  %t12 = call ptr @scr_closure_retain_v(ptr %t11)
  %t13 = load double, ptr %sc_l_v_0
  %t14 = getelementptr inbounds %ScrClosure, ptr %t12, i64 0, i32 1
  %t15 = load ptr, ptr %t14
  %t16 = call i1 %t15(ptr %t12, double %t13)
  call void @scr_closure_release(ptr %t12)
  br i1 %t16, label %if.t4, label %if.j5
if.t4:
  %t17 = load ptr, ptr %sc_l_out_0
  %t18 = call ptr @scr_arr_retain_v(ptr %t17)
  %t19 = load double, ptr %sc_l_v_0
  %t20 = call double @scr_arr_push_f64(ptr %t18, double %t19)
  call void @scr_arr_release(ptr %t18)
  br label %if.j5
if.j5:
  br label %loop.u3
loop.u3:
  %t21 = load double, ptr %sc_l_i_0
  %t22 = fadd double %t21, 0x3FF0000000000000
  store double %t22, ptr %sc_l_i_0
  br label %loop.c0
loop.e2:
  %t23 = load ptr, ptr %sc_l_out_0
  %t24 = call ptr @scr_arr_retain_v(ptr %t23)
  %t25 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t25)
  %t26 = load ptr, ptr %sc_l_f_0
  call void @scr_closure_release(ptr %t26)
  %t27 = load ptr, ptr %sc_l_out_0
  call void @scr_arr_release(ptr %t27)
  ret ptr %t24
}

define internal double @sc_f__x25_fn2(ptr %sc_env, double %p_sc_l_acc_0, double %p_sc_l_x_0) #0 { ; %fn2
entry:
  %sc_l_acc_0 = alloca double ; acc
  %sc_l_x_0 = alloca double ; x
  store double %p_sc_l_acc_0, ptr %sc_l_acc_0
  store double %p_sc_l_x_0, ptr %sc_l_x_0
  %t0 = load double, ptr %sc_l_acc_0
  %t1 = load double, ptr %sc_l_x_0
  %t2 = fadd double %t0, %t1
  ret double %t2
}

define internal double @sc_f__x25_arr_reduce_2(ptr %p_sc_l_a_0, ptr %p_sc_l_f_0, double %p_sc_l_z_0) #0 { ; %arr.reduce.2
entry:
  %sc_l_a_0 = alloca ptr ; a
  %sc_l_f_0 = alloca ptr ; f
  %sc_l_z_0 = alloca double ; z
  %sc_l_acc_0 = alloca double ; acc
  %sc_l_n_0 = alloca double ; n
  %sc_l_i_0 = alloca double ; i
  store ptr %p_sc_l_a_0, ptr %sc_l_a_0
  store ptr %p_sc_l_f_0, ptr %sc_l_f_0
  store double %p_sc_l_z_0, ptr %sc_l_z_0
  %t0 = load ptr, ptr %sc_l_a_0
  %t1 = call ptr @scr_arr_retain_v(ptr %t0)
  %t2 = call double @scr_arr_len(ptr %t1)
  store double %t2, ptr %sc_l_n_0
  call void @scr_arr_release(ptr %t1)
  %t3 = load double, ptr %sc_l_z_0
  store double %t3, ptr %sc_l_acc_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c0
loop.c0:
  %t4 = load double, ptr %sc_l_i_0
  %t5 = load double, ptr %sc_l_n_0
  %t6 = fcmp olt double %t4, %t5
  br i1 %t6, label %loop.b1, label %loop.e2
loop.b1:
  %t7 = load ptr, ptr %sc_l_f_0
  %t8 = call ptr @scr_closure_retain_v(ptr %t7)
  %t9 = load double, ptr %sc_l_acc_0
  %t10 = load ptr, ptr %sc_l_a_0
  %t11 = call ptr @scr_arr_retain_v(ptr %t10)
  %t12 = load double, ptr %sc_l_i_0
  %t13 = call double @scr_arr_get_f64(ptr %t11, double %t12)
  %t14 = getelementptr inbounds %ScrClosure, ptr %t8, i64 0, i32 1
  %t15 = load ptr, ptr %t14
  %t16 = call double %t15(ptr %t8, double %t9, double %t13)
  store double %t16, ptr %sc_l_acc_0
  call void @scr_closure_release(ptr %t8)
  call void @scr_arr_release(ptr %t11)
  br label %loop.u3
loop.u3:
  %t17 = load double, ptr %sc_l_i_0
  %t18 = fadd double %t17, 0x3FF0000000000000
  store double %t18, ptr %sc_l_i_0
  br label %loop.c0
loop.e2:
  %t19 = load double, ptr %sc_l_acc_0
  %t20 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t20)
  %t21 = load ptr, ptr %sc_l_f_0
  call void @scr_closure_release(ptr %t21)
  ret double %t19
}

define internal double @sc_f__x25_fn3(ptr %sc_env, double %p_sc_l_a_0, double %p_sc_l_b_0) #0 { ; %fn3
entry:
  %sc_l_a_0 = alloca double ; a
  %sc_l_b_0 = alloca double ; b
  store double %p_sc_l_a_0, ptr %sc_l_a_0
  store double %p_sc_l_b_0, ptr %sc_l_b_0
  %t0 = load double, ptr %sc_l_a_0
  %t1 = load double, ptr %sc_l_b_0
  %t2 = fsub double %t0, %t1
  ret double %t2
}

define internal ptr @sc_f__x25_arr_sort_3(ptr %p_sc_l_a_0, ptr %p_sc_l_f_0) #0 { ; %arr.sort.3
entry:
  %sc_l_a_0 = alloca ptr ; a
  %sc_l_f_0 = alloca ptr ; f
  %sc_l_n_0 = alloca double ; n
  %sc_l_i_0 = alloca double ; i
  %sc_l_v_0 = alloca double ; v
  %sc_l_j_0 = alloca double ; j
  store ptr %p_sc_l_a_0, ptr %sc_l_a_0
  store ptr %p_sc_l_f_0, ptr %sc_l_f_0
  %t0 = load ptr, ptr %sc_l_a_0
  %t1 = call ptr @scr_arr_retain_v(ptr %t0)
  %t2 = call double @scr_arr_len(ptr %t1)
  store double %t2, ptr %sc_l_n_0
  call void @scr_arr_release(ptr %t1)
  store double 0x3FF0000000000000, ptr %sc_l_i_0
  br label %loop.c0
loop.c0:
  %t3 = load double, ptr %sc_l_i_0
  %t4 = load double, ptr %sc_l_n_0
  %t5 = fcmp olt double %t3, %t4
  br i1 %t5, label %loop.b1, label %loop.e2
loop.b1:
  %t6 = load ptr, ptr %sc_l_a_0
  %t7 = call ptr @scr_arr_retain_v(ptr %t6)
  %t8 = load double, ptr %sc_l_i_0
  %t9 = call double @scr_arr_get_f64(ptr %t7, double %t8)
  store double %t9, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t7)
  %t10 = load double, ptr %sc_l_i_0
  %t11 = fsub double %t10, 0x3FF0000000000000
  store double %t11, ptr %sc_l_j_0
  br label %loop.c4
loop.c4:
  %t12 = load double, ptr %sc_l_j_0
  %t13 = fcmp oge double %t12, 0x0000000000000000
  br i1 %t13, label %loop.b5, label %loop.e6
loop.b5:
  %t14 = load ptr, ptr %sc_l_f_0
  %t15 = call ptr @scr_closure_retain_v(ptr %t14)
  %t16 = load ptr, ptr %sc_l_a_0
  %t17 = call ptr @scr_arr_retain_v(ptr %t16)
  %t18 = load double, ptr %sc_l_j_0
  %t19 = call double @scr_arr_get_f64(ptr %t17, double %t18)
  %t20 = load double, ptr %sc_l_v_0
  %t21 = getelementptr inbounds %ScrClosure, ptr %t15, i64 0, i32 1
  %t22 = load ptr, ptr %t21
  %t23 = call double %t22(ptr %t15, double %t19, double %t20)
  %t24 = fcmp ogt double %t23, 0x0000000000000000
  call void @scr_closure_release(ptr %t15)
  call void @scr_arr_release(ptr %t17)
  br i1 %t24, label %if.t7, label %if.f9
if.t7:
  %t25 = load ptr, ptr %sc_l_a_0
  %t26 = call ptr @scr_arr_retain_v(ptr %t25)
  %t27 = load double, ptr %sc_l_j_0
  %t28 = fadd double %t27, 0x3FF0000000000000
  %t29 = load ptr, ptr %sc_l_a_0
  %t30 = call ptr @scr_arr_retain_v(ptr %t29)
  %t31 = load double, ptr %sc_l_j_0
  %t32 = call double @scr_arr_get_f64(ptr %t30, double %t31)
  call void @scr_arr_set_f64(ptr %t26, double %t28, double %t32)
  call void @scr_arr_release(ptr %t26)
  call void @scr_arr_release(ptr %t30)
  %t33 = load double, ptr %sc_l_j_0
  %t34 = fsub double %t33, 0x3FF0000000000000
  store double %t34, ptr %sc_l_j_0
  br label %if.j8
if.f9:
  br label %loop.e6
if.j8:
  br label %loop.c4
loop.e6:
  %t35 = load ptr, ptr %sc_l_a_0
  %t36 = call ptr @scr_arr_retain_v(ptr %t35)
  %t37 = load double, ptr %sc_l_j_0
  %t38 = fadd double %t37, 0x3FF0000000000000
  %t39 = load double, ptr %sc_l_v_0
  call void @scr_arr_set_f64(ptr %t36, double %t38, double %t39)
  call void @scr_arr_release(ptr %t36)
  br label %loop.u3
loop.u3:
  %t40 = load double, ptr %sc_l_i_0
  %t41 = fadd double %t40, 0x3FF0000000000000
  store double %t41, ptr %sc_l_i_0
  br label %loop.c0
loop.e2:
  %t42 = load ptr, ptr %sc_l_a_0
  %t43 = call ptr @scr_arr_retain_v(ptr %t42)
  %t44 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t44)
  %t45 = load ptr, ptr %sc_l_f_0
  call void @scr_closure_release(ptr %t45)
  ret ptr %t43
}

define i32 @main(i32 %argc, ptr %argv) #0 {
entry:
  call void @scr_init()
  store i64 0, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 1) ; Error
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 0)
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 1) ; TypeError
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 0)
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 1) ; RangeError
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 0)
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 1) ; SyntaxError
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 1) ; DOMException
  call void @scr_lib_init(i32 %argc, ptr %argv)
  call void @sc_f__x25_main()
  %g0 = load ptr, ptr @sc_g_e_arr
  call void @scr_arr_release(ptr %g0) ; arr
  %g1 = load ptr, ptr @sc_g_e_dynamic
  call void @scr_arr_release(ptr %g1) ; dynamic
  %g3 = load ptr, ptr @sc_g_e_original
  call void @scr_arr_release(ptr %g3) ; original
  %g4 = load ptr, ptr @sc_g_e_doubled
  call void @scr_arr_release(ptr %g4) ; doubled
  %g5 = load ptr, ptr @sc_g_e_evens
  call void @scr_arr_release(ptr %g5) ; evens
  %g7 = load ptr, ptr @sc_g_e_matrix
  call void @scr_arr_release(ptr %g7) ; matrix
  %g8 = load ptr, ptr @sc_g_e_filled
  call void @scr_arr_release(ptr %g8) ; filled
  %g9 = load ptr, ptr @sc_g_e_unsorted
  call void @scr_arr_release(ptr %g9) ; unsorted
  %g10 = load ptr, ptr @sc_g_e_sorted
  call void @scr_arr_release(ptr %g10) ; sorted
  %g11 = load ptr, ptr @sc_g_e_big
  call void @scr_arr_release(ptr %g11) ; big
  %g12 = load ptr, ptr @sc_g_e_safe
  call void @scr_arr_release(ptr %g12) ; safe
  ret i32 0
}

attributes #0 = { sanitize_address }
