; Generated by scriptc (LLVM backend) from /Users/sam/Dev/llama.scriptc/examples/phase0/files.ts. Do not edit.

%ScrStr = type { i64, i64, i64 }
%ScrLogArg = type { i32, i64 }
%ScrVt = type { i64, i64, ptr }
%ScrUnion = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrClosure = type { i64, ptr, i64, ptr }
%ScrRegex = type { i64, ptr, ptr, ptr }
%ScrArr = type { i64, i64, i64, i32, ptr, ptr, ptr, ptr }
%ScrError = type { i64, ptr, ptr, ptr, ptr }
%ScrClassObj = type { i64, i64, i64, ptr, ptr }
%ScrEmitter = type { i64, ptr, ptr, ptr }
%ScrStream = type { i64, ptr, ptr, ptr, ptr }
%ScrCaught = type { i64, i32, double, i8, ptr, ptr, ptr, ptr }
%ScrBytes = type { i64, i64, i32, ptr, ptr }
%ScrBox = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrJsonBuf = type { ptr, i64, i64, ptr, i64, i64 }
%ScrDynPath = type { ptr, ptr, i64 }
%ScrIslandModule = type { ptr, ptr, i64, i64, i32, ptr, i64, i64 }
%ScrIslandEdge = type { ptr, ptr, ptr, i32 }
%sc_rs_r0 = type { i64, double, double } ; record r0 { hidden_size; vocab_size }
%sc_rs_r1 = type { i64, ptr, ptr } ; record r1 { config; weights }

@scr_error_vts = external global [5 x %ScrVt]
declare void @scr_init()
declare void @scr_lib_init(i32, ptr)
declare ptr @scr_str_retain_v(ptr)
declare void @scr_str_release_v(ptr)
declare void @scr_console_log(i64, ptr)
declare void @scr_str_release(ptr)
declare ptr @scr_arr_new(i32, i64)
declare ptr @scr_process_argv()
declare ptr @scr_arr_get_ref(ptr, double)
declare ptr @scr_path_dirname(ptr)
declare double @scr_arr_push_ref(ptr, ptr)
declare ptr @scr_path_join(ptr)
declare void @scr_arr_release(ptr)
declare zeroext i1 @scr_fs_exists(ptr)
declare void @scr_fs_mkdir_recursive(ptr)
declare zeroext i1 @scr_exc_pending()
declare void @scr_fs_write_file(ptr, ptr)
declare ptr @scr_fs_read_file(ptr)
declare ptr @scr_str_split_limit(ptr, ptr, double)
declare double @scr_arr_len(ptr)
declare double @scr_arr_push_f64(ptr, double)
declare ptr @scr_arr_retain_v(ptr)
declare void @scr_arr_release_v(ptr)
declare ptr @scr_bytes_from_arr(i32, ptr)
declare void @scr_bytes_release(ptr)
declare ptr @scr_bytes_retain_v(ptr)
declare void @scr_bytes_release_v(ptr)
declare void @scr_fs_write_file_bytes(ptr, ptr)
declare ptr @scr_fs_read_file_bytes(ptr)
declare double @scr_bytes_get(ptr, double)
declare void @scr_jb_putc(ptr, i8)
declare void @scr_jb_puts(ptr, ptr)
declare void @scr_jb_put_f64(ptr, double)
declare double @scr_arr_get_f64(ptr, double)
declare void @scr_jb_init(ptr)
declare ptr @scr_jb_finish(ptr)
declare double @scr_str_utf16_len(ptr)
declare void @scr_fs_unlink(ptr)
declare ptr @scr_fs_stat(ptr)
declare void @scr_stats_release_v(ptr)
declare ptr @scr_stats_retain_v(ptr)
declare double @scr_stats_size(ptr)
declare zeroext i1 @scr_stats_is_file(ptr)
declare void @scr_fs_rmdir(ptr)
declare void @scr_obj_alloc_note()
declare void @scr_obj_free_note()
declare void @free(ptr)
declare ptr @calloc(i64, i64)
declare void @scr_trap(ptr)

@sc_lit_0 = internal global { i64, i64, i64, [24 x i8] } { i64 -1, i64 23, i64 23, [24 x i8] c"--- Write text file ---\00" }
@sc_lit_1 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"tmp_test\00" }
@sc_lit_2 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"test.txt\00" }
@sc_lit_3 = internal global { i64, i64, i64, [35 x i8] } { i64 -1, i64 34, i64 34, [35 x i8] c"Hello from ScriptC!\0ALine 2\0ALine 3\0A\00" }
@sc_lit_4 = internal global { i64, i64, i64, [7 x i8] } { i64 -1, i64 6, i64 6, [7 x i8] c"Wrote:\00" }
@sc_lit_5 = internal global { i64, i64, i64, [24 x i8] } { i64 -1, i64 23, i64 23, [24 x i8] c"\0A--- Read text file ---\00" }
@sc_lit_6 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"utf-8\00" }
@sc_lit_7 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"Content:\00" }
@sc_lit_8 = internal global { i64, i64, i64, [7 x i8] } { i64 -1, i64 6, i64 6, [7 x i8] c"Lines:\00" }
@sc_lit_9 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"\0A\00" }
@sc_lit_10 = internal global { i64, i64, i64, [27 x i8] } { i64 -1, i64 26, i64 26, [27 x i8] c"\0A--- Write binary data ---\00" }
@sc_lit_11 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"test.bin\00" }
@sc_lit_12 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c"Wrote binary:\00" }
@sc_lit_13 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"bytes\00" }
@sc_lit_14 = internal global { i64, i64, i64, [26 x i8] } { i64 -1, i64 25, i64 25, [26 x i8] c"\0A--- Read binary data ---\00" }
@sc_lit_15 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"Read binary:\00" }
@sc_lit_16 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"Byte values:\00" }
@sc_lit_17 = internal global { i64, i64, i64, [33 x i8] } { i64 -1, i64 32, i64 32, [33 x i8] c"\0A--- JSON serialization test ---\00" }
@sc_lit_18 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"model.json\00" }
@sc_lit_19 = internal global { i64, i64, i64, [20 x i8] } { i64 -1, i64 19, i64 19, [20 x i8] c"JSON loaded length:\00" }
@sc_lit_20 = internal global { i64, i64, i64, [20 x i8] } { i64 -1, i64 19, i64 19, [20 x i8] c"\0A--- File stats ---\00" }
@sc_lit_21 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"Size:\00" }
@sc_lit_22 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"Is file:\00" }
@sc_lit_23 = internal global { i64, i64, i64, [23 x i8] } { i64 -1, i64 22, i64 22, [23 x i8] c"\0ACleaned up temp files\00" }
@sc_lit_24 = internal global { i64, i64, i64, [21 x i8] } { i64 -1, i64 20, i64 20, [21 x i8] c"\0A\E2\9C\85 files.ts passed\00" }

@sc_cs_0 = internal constant [10 x i8] c"\22config\22:\00"
@sc_cs_1 = internal constant [14 x i8] c"\22vocab_size\22:\00"
@sc_cs_2 = internal constant [16 x i8] c",\22hidden_size\22:\00"
@sc_cs_3 = internal constant [12 x i8] c",\22weights\22:\00"

@sc_g_e_tmpDir = internal global ptr null ; tmpDir
@sc_g_e_textFile = internal global ptr null ; textFile
@sc_g_e_content = internal global ptr null ; content
@sc_g_e_binFile = internal global ptr null ; binFile
@sc_g_e_rawBytes = internal global ptr null ; rawBytes
@sc_g_e_buffer = internal global ptr null ; buffer
@sc_g_e_readBuf = internal global ptr null ; readBuf
@sc_g_e_jsonFile = internal global ptr null ; jsonFile
@sc_g_e_modelData = internal global ptr null ; modelData
@sc_g_e_loadedJson = internal global ptr null ; loadedJson
@sc_g_e_stats = internal global ptr null ; stats
@sc_g_e__x25_loaded = internal global i1 false ; %loaded

@sc_oom_msg = internal constant [24 x i8] c"scriptc: out of memory\0A\00"
define internal void @sc_oom() #0 {
entry:
  call void @scr_trap(ptr @sc_oom_msg)
  unreachable
}

define internal ptr @sc_rretain_r0(ptr %o) #0 {
entry:
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %done, label %check
check:
  %rc = load i64, ptr %o
  %imm = icmp eq i64 %rc, -1
  br i1 %imm, label %done, label %inc
inc:
  %n = add i64 %rc, 1
  store i64 %n, ptr %o
  br label %done
done:
  ret ptr %o
}

define internal void @sc_rrelease_r0(ptr %o) #0 {
entry:
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %done, label %check
check:
  %rc = load i64, ptr %o
  %imm = icmp eq i64 %rc, -1
  br i1 %imm, label %done, label %dec
dec:
  %n = sub i64 %rc, 1
  store i64 %n, ptr %o
  %dead = icmp eq i64 %n, 0
  br i1 %dead, label %free, label %done
free:
  call void @scr_obj_free_note()
  call void @free(ptr %o)
  br label %done
done:
  ret void
}

define internal ptr @sc_rnew_r0() #0 {
entry:
  %o = call ptr @calloc(i64 1, i64 ptrtoint (ptr getelementptr (%sc_rs_r0, ptr null, i32 1) to i64))
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %oom, label %ok
oom:
  call void @sc_oom()
  unreachable
ok:
  store i64 1, ptr %o
  call void @scr_obj_alloc_note()
  ret ptr %o
}

define internal ptr @sc_rretain_r1(ptr %o) #0 {
entry:
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %done, label %check
check:
  %rc = load i64, ptr %o
  %imm = icmp eq i64 %rc, -1
  br i1 %imm, label %done, label %inc
inc:
  %n = add i64 %rc, 1
  store i64 %n, ptr %o
  br label %done
done:
  ret ptr %o
}

define internal void @sc_rrelease_r1(ptr %o) #0 {
entry:
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %done, label %check
check:
  %rc = load i64, ptr %o
  %imm = icmp eq i64 %rc, -1
  br i1 %imm, label %done, label %dec
dec:
  %n = sub i64 %rc, 1
  store i64 %n, ptr %o
  %dead = icmp eq i64 %n, 0
  br i1 %dead, label %free, label %done
free:
  %f0 = getelementptr inbounds %sc_rs_r1, ptr %o, i64 0, i32 1
  %v0 = load ptr, ptr %f0
  call void @sc_rrelease_r0(ptr %v0) ; config
  %f1 = getelementptr inbounds %sc_rs_r1, ptr %o, i64 0, i32 2
  %v1 = load ptr, ptr %f1
  call void @scr_arr_release(ptr %v1) ; weights
  call void @scr_obj_free_note()
  call void @free(ptr %o)
  br label %done
done:
  ret void
}

define internal ptr @sc_rnew_r1() #0 {
entry:
  %o = call ptr @calloc(i64 1, i64 ptrtoint (ptr getelementptr (%sc_rs_r1, ptr null, i32 1) to i64))
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %oom, label %ok
oom:
  call void @sc_oom()
  unreachable
ok:
  store i64 1, ptr %o
  call void @scr_obj_alloc_note()
  ret ptr %o
}

define internal void @sc_jw_2(ptr %b, double %v) #0 { ; stringify f64
entry:
  call void @scr_jb_put_f64(ptr %b, double %v) ; NaN/Infinity -> null, -0 -> 0, like JS
  ret void
}

define internal void @sc_jw_1(ptr %b, ptr %v) #0 { ; stringify record:r0
entry:
  call void @scr_jb_putc(ptr %b, i8 123)
  call void @scr_jb_puts(ptr %b, ptr @sc_cs_1) ; "\"vocab_size\":"
  %t0 = getelementptr inbounds %sc_rs_r0, ptr %v, i64 0, i32 2
  %t1 = load double, ptr %t0
  call void @sc_jw_2(ptr %b, double %t1) ; vocab_size
  call void @scr_jb_puts(ptr %b, ptr @sc_cs_2) ; ",\"hidden_size\":"
  %t2 = getelementptr inbounds %sc_rs_r0, ptr %v, i64 0, i32 1
  %t3 = load double, ptr %t2
  call void @sc_jw_2(ptr %b, double %t3) ; hidden_size
  call void @scr_jb_putc(ptr %b, i8 125)
  ret void
}

define internal void @sc_jw_3(ptr %b, ptr %v) #0 { ; stringify array<f64>
entry:
  %s1 = alloca double
  call void @scr_jb_putc(ptr %b, i8 91)
  %t0 = call double @scr_arr_len(ptr %v)
  store double 0x0000000000000000, ptr %s1
  br label %jwa.c0
jwa.c0:
  %t2 = load double, ptr %s1
  %t3 = fcmp olt double %t2, %t0
  br i1 %t3, label %jwa.b1, label %jwa.e2
jwa.b1:
  %t4 = fcmp ogt double %t2, 0x0000000000000000
  br i1 %t4, label %jwa.cm3, label %jwa.cj4
jwa.cm3:
  call void @scr_jb_putc(ptr %b, i8 44)
  br label %jwa.cj4
jwa.cj4:
  %t5 = call double @scr_arr_get_f64(ptr %v, double %t2)
  call void @sc_jw_2(ptr %b, double %t5)
  %t6 = fadd double %t2, 0x3FF0000000000000
  store double %t6, ptr %s1
  br label %jwa.c0
jwa.e2:
  call void @scr_jb_putc(ptr %b, i8 93)
  ret void
}

define internal void @sc_jw_0(ptr %b, ptr %v) #0 { ; stringify record:r1
entry:
  call void @scr_jb_putc(ptr %b, i8 123)
  call void @scr_jb_puts(ptr %b, ptr @sc_cs_0) ; "\"config\":"
  %t0 = getelementptr inbounds %sc_rs_r1, ptr %v, i64 0, i32 1
  %t1 = load ptr, ptr %t0
  call void @sc_jw_1(ptr %b, ptr %t1) ; config
  call void @scr_jb_puts(ptr %b, ptr @sc_cs_3) ; ",\"weights\":"
  %t2 = getelementptr inbounds %sc_rs_r1, ptr %v, i64 0, i32 2
  %t3 = load ptr, ptr %t2
  call void @sc_jw_3(ptr %b, ptr %t3) ; weights
  call void @scr_jb_putc(ptr %b, i8 125)
  ret void
}

define internal void @sc_f__x25_init_0() #0 { ; %init.0
entry:
  %s239 = alloca %ScrJsonBuf
  %logargs = alloca [6 x %ScrLogArg]
  %t0 = load i1, ptr @sc_g_e__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_e__x25_loaded
  %t1 = call ptr @scr_str_retain_v(ptr @sc_lit_0)
  %t2 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t2
  %t3 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t1, ptr %t3
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t1)
  %t4 = call ptr @scr_arr_new(i32 2, i64 2)
  %t5 = call ptr @scr_process_argv()
  %t6 = call ptr @scr_arr_get_ref(ptr %t5, double 0x3FF0000000000000)
  %t7 = call ptr @scr_path_dirname(ptr %t6)
  %t8 = call double @scr_arr_push_ref(ptr %t4, ptr %t7)
  %t9 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t10 = call double @scr_arr_push_ref(ptr %t4, ptr %t9)
  %t11 = call ptr @scr_path_join(ptr %t4)
  %t12 = load ptr, ptr @sc_g_e_tmpDir
  call void @scr_str_release(ptr %t12)
  store ptr %t11, ptr @sc_g_e_tmpDir
  call void @scr_arr_release(ptr %t4)
  call void @scr_arr_release(ptr %t5)
  call void @scr_str_release(ptr %t6)
  %t13 = load ptr, ptr @sc_g_e_tmpDir
  %t14 = call ptr @scr_str_retain_v(ptr %t13)
  %t15 = call i1 @scr_fs_exists(ptr %t14)
  %t16 = xor i1 %t15, true
  call void @scr_str_release(ptr %t14)
  br i1 %t16, label %if.t2, label %if.j3
if.t2:
  %t17 = load ptr, ptr @sc_g_e_tmpDir
  %t18 = call ptr @scr_str_retain_v(ptr %t17)
  call void @scr_fs_mkdir_recursive(ptr %t18)
  %t19 = call zeroext i1 @scr_exc_pending()
  br i1 %t19, label %exc.u4, label %exc.k5
exc.u4:
  call void @scr_str_release(ptr %t18)
  ret void
exc.k5:
  call void @scr_str_release(ptr %t18)
  br label %if.j3
if.j3:
  %t20 = call ptr @scr_arr_new(i32 2, i64 2)
  %t21 = load ptr, ptr @sc_g_e_tmpDir
  %t22 = call ptr @scr_str_retain_v(ptr %t21)
  %t23 = call double @scr_arr_push_ref(ptr %t20, ptr %t22)
  %t24 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  %t25 = call double @scr_arr_push_ref(ptr %t20, ptr %t24)
  %t26 = call ptr @scr_path_join(ptr %t20)
  %t27 = load ptr, ptr @sc_g_e_textFile
  call void @scr_str_release(ptr %t27)
  store ptr %t26, ptr @sc_g_e_textFile
  call void @scr_arr_release(ptr %t20)
  %t28 = load ptr, ptr @sc_g_e_textFile
  %t29 = call ptr @scr_str_retain_v(ptr %t28)
  %t30 = call ptr @scr_str_retain_v(ptr @sc_lit_3)
  call void @scr_fs_write_file(ptr %t29, ptr %t30)
  %t31 = call zeroext i1 @scr_exc_pending()
  br i1 %t31, label %exc.u6, label %exc.k7
exc.u6:
  call void @scr_str_release(ptr %t29)
  call void @scr_str_release(ptr %t30)
  ret void
exc.k7:
  call void @scr_str_release(ptr %t29)
  call void @scr_str_release(ptr %t30)
  %t32 = call ptr @scr_str_retain_v(ptr @sc_lit_4)
  %t33 = load ptr, ptr @sc_g_e_textFile
  %t34 = call ptr @scr_str_retain_v(ptr %t33)
  %t35 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t35
  %t36 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t32, ptr %t36
  %t37 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t37
  %t38 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t34, ptr %t38
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t32)
  call void @scr_str_release(ptr %t34)
  %t39 = call ptr @scr_str_retain_v(ptr @sc_lit_5)
  %t40 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t40
  %t41 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t39, ptr %t41
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t39)
  %t42 = load ptr, ptr @sc_g_e_textFile
  %t43 = call ptr @scr_str_retain_v(ptr %t42)
  %t44 = call ptr @scr_str_retain_v(ptr @sc_lit_6)
  %t45 = call ptr @scr_fs_read_file(ptr %t43)
  %t46 = call zeroext i1 @scr_exc_pending()
  br i1 %t46, label %exc.u8, label %exc.k9
exc.u8:
  call void @scr_str_release(ptr %t43)
  call void @scr_str_release(ptr %t44)
  call void @scr_str_release(ptr %t45)
  ret void
exc.k9:
  %t47 = load ptr, ptr @sc_g_e_content
  call void @scr_str_release(ptr %t47)
  store ptr %t45, ptr @sc_g_e_content
  call void @scr_str_release(ptr %t43)
  call void @scr_str_release(ptr %t44)
  %t48 = call ptr @scr_str_retain_v(ptr @sc_lit_7)
  %t49 = load ptr, ptr @sc_g_e_content
  %t50 = call ptr @scr_str_retain_v(ptr %t49)
  %t51 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t51
  %t52 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t48, ptr %t52
  %t53 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t53
  %t54 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t50, ptr %t54
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t48)
  call void @scr_str_release(ptr %t50)
  %t55 = call ptr @scr_str_retain_v(ptr @sc_lit_8)
  %t56 = load ptr, ptr @sc_g_e_content
  %t57 = call ptr @scr_str_retain_v(ptr %t56)
  %t58 = call ptr @scr_str_retain_v(ptr @sc_lit_9)
  %t59 = call ptr @scr_str_split_limit(ptr %t57, ptr %t58, double 0x41EFFFFFFFE00000)
  %t60 = call double @scr_arr_len(ptr %t59)
  %t61 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t61
  %t62 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t55, ptr %t62
  %t63 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t63
  %t64 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t60, ptr %t64
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t55)
  call void @scr_str_release(ptr %t57)
  call void @scr_str_release(ptr %t58)
  call void @scr_arr_release(ptr %t59)
  %t65 = call ptr @scr_str_retain_v(ptr @sc_lit_10)
  %t66 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t66
  %t67 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t65, ptr %t67
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t65)
  %t68 = call ptr @scr_arr_new(i32 2, i64 2)
  %t69 = load ptr, ptr @sc_g_e_tmpDir
  %t70 = call ptr @scr_str_retain_v(ptr %t69)
  %t71 = call double @scr_arr_push_ref(ptr %t68, ptr %t70)
  %t72 = call ptr @scr_str_retain_v(ptr @sc_lit_11)
  %t73 = call double @scr_arr_push_ref(ptr %t68, ptr %t72)
  %t74 = call ptr @scr_path_join(ptr %t68)
  %t75 = load ptr, ptr @sc_g_e_binFile
  call void @scr_str_release(ptr %t75)
  store ptr %t74, ptr @sc_g_e_binFile
  call void @scr_arr_release(ptr %t68)
  %t76 = call ptr @scr_arr_new(i32 0, i64 5)
  %t77 = call double @scr_arr_push_f64(ptr %t76, double 0x4052000000000000)
  %t78 = call double @scr_arr_push_f64(ptr %t76, double 0x4059400000000000)
  %t79 = call double @scr_arr_push_f64(ptr %t76, double 0x405B000000000000)
  %t80 = call double @scr_arr_push_f64(ptr %t76, double 0x405B000000000000)
  %t81 = call double @scr_arr_push_f64(ptr %t76, double 0x405BC00000000000)
  %t82 = load ptr, ptr @sc_g_e_rawBytes
  call void @scr_arr_release(ptr %t82)
  store ptr %t76, ptr @sc_g_e_rawBytes
  %t83 = load ptr, ptr @sc_g_e_rawBytes
  %t84 = call ptr @scr_arr_retain_v(ptr %t83)
  %t85 = call ptr @scr_bytes_from_arr(i32 0, ptr %t84)
  %t86 = load ptr, ptr @sc_g_e_buffer
  call void @scr_bytes_release(ptr %t86)
  store ptr %t85, ptr @sc_g_e_buffer
  call void @scr_arr_release(ptr %t84)
  %t87 = load ptr, ptr @sc_g_e_binFile
  %t88 = call ptr @scr_str_retain_v(ptr %t87)
  %t89 = load ptr, ptr @sc_g_e_buffer
  %t90 = call ptr @scr_bytes_retain_v(ptr %t89)
  call void @scr_fs_write_file_bytes(ptr %t88, ptr %t90)
  %t91 = call zeroext i1 @scr_exc_pending()
  br i1 %t91, label %exc.u10, label %exc.k11
exc.u10:
  call void @scr_str_release(ptr %t88)
  call void @scr_bytes_release(ptr %t90)
  ret void
exc.k11:
  call void @scr_str_release(ptr %t88)
  call void @scr_bytes_release(ptr %t90)
  %t92 = call ptr @scr_str_retain_v(ptr @sc_lit_12)
  %t93 = load ptr, ptr @sc_g_e_buffer
  %t94 = getelementptr inbounds %ScrBytes, ptr %t93, i64 0, i32 1
  %t95 = load i64, ptr %t94
  %t96 = uitofp i64 %t95 to double
  %t97 = call ptr @scr_str_retain_v(ptr @sc_lit_13)
  %t98 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t98
  %t99 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t92, ptr %t99
  %t100 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t100
  %t101 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t96, ptr %t101
  %t102 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 0
  store i32 1, ptr %t102
  %t103 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 1
  store ptr %t97, ptr %t103
  call void @scr_console_log(i64 3, ptr %logargs)
  call void @scr_str_release(ptr %t92)
  call void @scr_str_release(ptr %t97)
  %t104 = call ptr @scr_str_retain_v(ptr @sc_lit_14)
  %t105 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t105
  %t106 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t104, ptr %t106
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t104)
  %t107 = load ptr, ptr @sc_g_e_binFile
  %t108 = call ptr @scr_str_retain_v(ptr %t107)
  %t109 = call ptr @scr_fs_read_file_bytes(ptr %t108)
  %t110 = call zeroext i1 @scr_exc_pending()
  br i1 %t110, label %exc.u12, label %exc.k13
exc.u12:
  call void @scr_str_release(ptr %t108)
  call void @scr_bytes_release(ptr %t109)
  ret void
exc.k13:
  %t111 = load ptr, ptr @sc_g_e_readBuf
  call void @scr_bytes_release(ptr %t111)
  store ptr %t109, ptr @sc_g_e_readBuf
  call void @scr_str_release(ptr %t108)
  %t112 = call ptr @scr_str_retain_v(ptr @sc_lit_15)
  %t113 = load ptr, ptr @sc_g_e_readBuf
  %t114 = getelementptr inbounds %ScrBytes, ptr %t113, i64 0, i32 1
  %t115 = load i64, ptr %t114
  %t116 = uitofp i64 %t115 to double
  %t117 = call ptr @scr_str_retain_v(ptr @sc_lit_13)
  %t118 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t118
  %t119 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t112, ptr %t119
  %t120 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t120
  %t121 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t116, ptr %t121
  %t122 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 0
  store i32 1, ptr %t122
  %t123 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 1
  store ptr %t117, ptr %t123
  call void @scr_console_log(i64 3, ptr %logargs)
  call void @scr_str_release(ptr %t112)
  call void @scr_str_release(ptr %t117)
  %t124 = call ptr @scr_str_retain_v(ptr @sc_lit_16)
  %t125 = load ptr, ptr @sc_g_e_readBuf
  %t126 = getelementptr inbounds %ScrBytes, ptr %t125, i64 0, i32 1
  %t127 = load i64, ptr %t126
  %t128 = uitofp i64 %t127 to double
  %t129 = fcmp oge double 0x0000000000000000, 0x0000000000000000
  %t130 = fcmp olt double 0x0000000000000000, %t128
  %t131 = and i1 %t129, %t130
  br i1 %t131, label %bytes.index.range14, label %bytes.index.invalid15
bytes.index.range14:
  %t132 = fptoui double 0x0000000000000000 to i64
  %t133 = uitofp i64 %t132 to double
  %t134 = fcmp oeq double %t133, 0x0000000000000000
  br i1 %t134, label %bytes.index.valid16, label %bytes.index.invalid15
bytes.index.invalid15:
  call double @scr_bytes_get(ptr %t125, double 0x0000000000000000)
  unreachable
bytes.index.valid16:
  %t135 = getelementptr inbounds %ScrBytes, ptr %t125, i64 0, i32 3
  %t136 = load ptr, ptr %t135
  %t137 = getelementptr inbounds i8, ptr %t136, i64 %t132
  %t138 = load i8, ptr %t137, align 1
  %t139 = zext i8 %t138 to i32
  %t140 = uitofp i32 %t139 to double
  %t141 = load ptr, ptr @sc_g_e_readBuf
  %t142 = getelementptr inbounds %ScrBytes, ptr %t141, i64 0, i32 1
  %t143 = load i64, ptr %t142
  %t144 = uitofp i64 %t143 to double
  %t145 = fcmp oge double 0x3FF0000000000000, 0x0000000000000000
  %t146 = fcmp olt double 0x3FF0000000000000, %t144
  %t147 = and i1 %t145, %t146
  br i1 %t147, label %bytes.index.range17, label %bytes.index.invalid18
bytes.index.range17:
  %t148 = fptoui double 0x3FF0000000000000 to i64
  %t149 = uitofp i64 %t148 to double
  %t150 = fcmp oeq double %t149, 0x3FF0000000000000
  br i1 %t150, label %bytes.index.valid19, label %bytes.index.invalid18
bytes.index.invalid18:
  call double @scr_bytes_get(ptr %t141, double 0x3FF0000000000000)
  unreachable
bytes.index.valid19:
  %t151 = getelementptr inbounds %ScrBytes, ptr %t141, i64 0, i32 3
  %t152 = load ptr, ptr %t151
  %t153 = getelementptr inbounds i8, ptr %t152, i64 %t148
  %t154 = load i8, ptr %t153, align 1
  %t155 = zext i8 %t154 to i32
  %t156 = uitofp i32 %t155 to double
  %t157 = load ptr, ptr @sc_g_e_readBuf
  %t158 = getelementptr inbounds %ScrBytes, ptr %t157, i64 0, i32 1
  %t159 = load i64, ptr %t158
  %t160 = uitofp i64 %t159 to double
  %t161 = fcmp oge double 0x4000000000000000, 0x0000000000000000
  %t162 = fcmp olt double 0x4000000000000000, %t160
  %t163 = and i1 %t161, %t162
  br i1 %t163, label %bytes.index.range20, label %bytes.index.invalid21
bytes.index.range20:
  %t164 = fptoui double 0x4000000000000000 to i64
  %t165 = uitofp i64 %t164 to double
  %t166 = fcmp oeq double %t165, 0x4000000000000000
  br i1 %t166, label %bytes.index.valid22, label %bytes.index.invalid21
bytes.index.invalid21:
  call double @scr_bytes_get(ptr %t157, double 0x4000000000000000)
  unreachable
bytes.index.valid22:
  %t167 = getelementptr inbounds %ScrBytes, ptr %t157, i64 0, i32 3
  %t168 = load ptr, ptr %t167
  %t169 = getelementptr inbounds i8, ptr %t168, i64 %t164
  %t170 = load i8, ptr %t169, align 1
  %t171 = zext i8 %t170 to i32
  %t172 = uitofp i32 %t171 to double
  %t173 = load ptr, ptr @sc_g_e_readBuf
  %t174 = getelementptr inbounds %ScrBytes, ptr %t173, i64 0, i32 1
  %t175 = load i64, ptr %t174
  %t176 = uitofp i64 %t175 to double
  %t177 = fcmp oge double 0x4008000000000000, 0x0000000000000000
  %t178 = fcmp olt double 0x4008000000000000, %t176
  %t179 = and i1 %t177, %t178
  br i1 %t179, label %bytes.index.range23, label %bytes.index.invalid24
bytes.index.range23:
  %t180 = fptoui double 0x4008000000000000 to i64
  %t181 = uitofp i64 %t180 to double
  %t182 = fcmp oeq double %t181, 0x4008000000000000
  br i1 %t182, label %bytes.index.valid25, label %bytes.index.invalid24
bytes.index.invalid24:
  call double @scr_bytes_get(ptr %t173, double 0x4008000000000000)
  unreachable
bytes.index.valid25:
  %t183 = getelementptr inbounds %ScrBytes, ptr %t173, i64 0, i32 3
  %t184 = load ptr, ptr %t183
  %t185 = getelementptr inbounds i8, ptr %t184, i64 %t180
  %t186 = load i8, ptr %t185, align 1
  %t187 = zext i8 %t186 to i32
  %t188 = uitofp i32 %t187 to double
  %t189 = load ptr, ptr @sc_g_e_readBuf
  %t190 = getelementptr inbounds %ScrBytes, ptr %t189, i64 0, i32 1
  %t191 = load i64, ptr %t190
  %t192 = uitofp i64 %t191 to double
  %t193 = fcmp oge double 0x4010000000000000, 0x0000000000000000
  %t194 = fcmp olt double 0x4010000000000000, %t192
  %t195 = and i1 %t193, %t194
  br i1 %t195, label %bytes.index.range26, label %bytes.index.invalid27
bytes.index.range26:
  %t196 = fptoui double 0x4010000000000000 to i64
  %t197 = uitofp i64 %t196 to double
  %t198 = fcmp oeq double %t197, 0x4010000000000000
  br i1 %t198, label %bytes.index.valid28, label %bytes.index.invalid27
bytes.index.invalid27:
  call double @scr_bytes_get(ptr %t189, double 0x4010000000000000)
  unreachable
bytes.index.valid28:
  %t199 = getelementptr inbounds %ScrBytes, ptr %t189, i64 0, i32 3
  %t200 = load ptr, ptr %t199
  %t201 = getelementptr inbounds i8, ptr %t200, i64 %t196
  %t202 = load i8, ptr %t201, align 1
  %t203 = zext i8 %t202 to i32
  %t204 = uitofp i32 %t203 to double
  %t205 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t205
  %t206 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t124, ptr %t206
  %t207 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t207
  %t208 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t140, ptr %t208
  %t209 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 0
  store i32 0, ptr %t209
  %t210 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 1
  store double %t156, ptr %t210
  %t211 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 3, i32 0
  store i32 0, ptr %t211
  %t212 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 3, i32 1
  store double %t172, ptr %t212
  %t213 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 4, i32 0
  store i32 0, ptr %t213
  %t214 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 4, i32 1
  store double %t188, ptr %t214
  %t215 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 5, i32 0
  store i32 0, ptr %t215
  %t216 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 5, i32 1
  store double %t204, ptr %t216
  call void @scr_console_log(i64 6, ptr %logargs)
  call void @scr_str_release(ptr %t124)
  %t217 = call ptr @scr_str_retain_v(ptr @sc_lit_17)
  %t218 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t218
  %t219 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t217, ptr %t219
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t217)
  %t220 = call ptr @scr_arr_new(i32 2, i64 2)
  %t221 = load ptr, ptr @sc_g_e_tmpDir
  %t222 = call ptr @scr_str_retain_v(ptr %t221)
  %t223 = call double @scr_arr_push_ref(ptr %t220, ptr %t222)
  %t224 = call ptr @scr_str_retain_v(ptr @sc_lit_18)
  %t225 = call double @scr_arr_push_ref(ptr %t220, ptr %t224)
  %t226 = call ptr @scr_path_join(ptr %t220)
  %t227 = load ptr, ptr @sc_g_e_jsonFile
  call void @scr_str_release(ptr %t227)
  store ptr %t226, ptr @sc_g_e_jsonFile
  call void @scr_arr_release(ptr %t220)
  %t228 = call ptr @sc_rnew_r1()
  %t229 = call ptr @sc_rnew_r0()
  %t230 = getelementptr inbounds %sc_rs_r0, ptr %t229, i64 0, i32 2
  store double 0x408F400000000000, ptr %t230
  %t231 = getelementptr inbounds %sc_rs_r0, ptr %t229, i64 0, i32 1
  store double 0x4060000000000000, ptr %t231
  %t232 = getelementptr inbounds %sc_rs_r1, ptr %t228, i64 0, i32 1
  store ptr %t229, ptr %t232
  %t233 = call ptr @scr_arr_new(i32 0, i64 4)
  %t234 = call double @scr_arr_push_f64(ptr %t233, double 0x3FB999999999999A)
  %t235 = call double @scr_arr_push_f64(ptr %t233, double 0x3FC999999999999A)
  %t236 = call double @scr_arr_push_f64(ptr %t233, double 0x3FD3333333333333)
  %t237 = call double @scr_arr_push_f64(ptr %t233, double 0xBFD999999999999A)
  %t238 = getelementptr inbounds %sc_rs_r1, ptr %t228, i64 0, i32 2
  store ptr %t233, ptr %t238
  call void @scr_jb_init(ptr %s239)
  call void @sc_jw_0(ptr %s239, ptr %t228)
  %t240 = call ptr @scr_jb_finish(ptr %s239)
  %t241 = load ptr, ptr @sc_g_e_modelData
  call void @scr_str_release(ptr %t241)
  store ptr %t240, ptr @sc_g_e_modelData
  call void @sc_rrelease_r1(ptr %t228)
  %t242 = load ptr, ptr @sc_g_e_jsonFile
  %t243 = call ptr @scr_str_retain_v(ptr %t242)
  %t244 = load ptr, ptr @sc_g_e_modelData
  %t245 = call ptr @scr_str_retain_v(ptr %t244)
  call void @scr_fs_write_file(ptr %t243, ptr %t245)
  %t246 = call zeroext i1 @scr_exc_pending()
  br i1 %t246, label %exc.u29, label %exc.k30
exc.u29:
  call void @scr_str_release(ptr %t243)
  call void @scr_str_release(ptr %t245)
  ret void
exc.k30:
  call void @scr_str_release(ptr %t243)
  call void @scr_str_release(ptr %t245)
  %t247 = load ptr, ptr @sc_g_e_jsonFile
  %t248 = call ptr @scr_str_retain_v(ptr %t247)
  %t249 = call ptr @scr_str_retain_v(ptr @sc_lit_6)
  %t250 = call ptr @scr_fs_read_file(ptr %t248)
  %t251 = call zeroext i1 @scr_exc_pending()
  br i1 %t251, label %exc.u31, label %exc.k32
exc.u31:
  call void @scr_str_release(ptr %t248)
  call void @scr_str_release(ptr %t249)
  call void @scr_str_release(ptr %t250)
  ret void
exc.k32:
  %t252 = load ptr, ptr @sc_g_e_loadedJson
  call void @scr_str_release(ptr %t252)
  store ptr %t250, ptr @sc_g_e_loadedJson
  call void @scr_str_release(ptr %t248)
  call void @scr_str_release(ptr %t249)
  %t253 = call ptr @scr_str_retain_v(ptr @sc_lit_19)
  %t254 = load ptr, ptr @sc_g_e_loadedJson
  %t255 = call ptr @scr_str_retain_v(ptr %t254)
  %t256 = call double @scr_str_utf16_len(ptr %t255)
  %t257 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t257
  %t258 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t253, ptr %t258
  %t259 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t259
  %t260 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t256, ptr %t260
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t253)
  call void @scr_str_release(ptr %t255)
  %t261 = load ptr, ptr @sc_g_e_jsonFile
  %t262 = call ptr @scr_str_retain_v(ptr %t261)
  call void @scr_fs_unlink(ptr %t262)
  %t263 = call zeroext i1 @scr_exc_pending()
  br i1 %t263, label %exc.u33, label %exc.k34
exc.u33:
  call void @scr_str_release(ptr %t262)
  ret void
exc.k34:
  call void @scr_str_release(ptr %t262)
  %t264 = call ptr @scr_str_retain_v(ptr @sc_lit_20)
  %t265 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t265
  %t266 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t264, ptr %t266
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t264)
  %t267 = load ptr, ptr @sc_g_e_binFile
  %t268 = call ptr @scr_str_retain_v(ptr %t267)
  %t269 = call ptr @scr_fs_stat(ptr %t268)
  %t270 = call zeroext i1 @scr_exc_pending()
  br i1 %t270, label %exc.u35, label %exc.k36
exc.u35:
  call void @scr_str_release(ptr %t268)
  call void @scr_stats_release_v(ptr %t269)
  ret void
exc.k36:
  %t271 = load ptr, ptr @sc_g_e_stats
  call void @scr_stats_release_v(ptr %t271)
  store ptr %t269, ptr @sc_g_e_stats
  call void @scr_str_release(ptr %t268)
  %t272 = call ptr @scr_str_retain_v(ptr @sc_lit_21)
  %t273 = load ptr, ptr @sc_g_e_stats
  %t274 = call ptr @scr_stats_retain_v(ptr %t273)
  %t275 = call double @scr_stats_size(ptr %t274)
  %t276 = call ptr @scr_str_retain_v(ptr @sc_lit_13)
  %t277 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t277
  %t278 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t272, ptr %t278
  %t279 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t279
  %t280 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t275, ptr %t280
  %t281 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 0
  store i32 1, ptr %t281
  %t282 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 1
  store ptr %t276, ptr %t282
  call void @scr_console_log(i64 3, ptr %logargs)
  call void @scr_str_release(ptr %t272)
  call void @scr_stats_release_v(ptr %t274)
  call void @scr_str_release(ptr %t276)
  %t283 = call ptr @scr_str_retain_v(ptr @sc_lit_22)
  %t284 = load ptr, ptr @sc_g_e_stats
  %t285 = call ptr @scr_stats_retain_v(ptr %t284)
  %t286 = call i1 @scr_stats_is_file(ptr %t285)
  %t287 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t287
  %t288 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t283, ptr %t288
  %t289 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 2, ptr %t289
  %t290 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  %t291 = zext i1 %t286 to i8
  store i8 %t291, ptr %t290
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t283)
  call void @scr_stats_release_v(ptr %t285)
  %t292 = load ptr, ptr @sc_g_e_textFile
  %t293 = call ptr @scr_str_retain_v(ptr %t292)
  call void @scr_fs_unlink(ptr %t293)
  %t294 = call zeroext i1 @scr_exc_pending()
  br i1 %t294, label %exc.u37, label %exc.k38
exc.u37:
  call void @scr_str_release(ptr %t293)
  ret void
exc.k38:
  call void @scr_str_release(ptr %t293)
  %t295 = load ptr, ptr @sc_g_e_binFile
  %t296 = call ptr @scr_str_retain_v(ptr %t295)
  call void @scr_fs_unlink(ptr %t296)
  %t297 = call zeroext i1 @scr_exc_pending()
  br i1 %t297, label %exc.u39, label %exc.k40
exc.u39:
  call void @scr_str_release(ptr %t296)
  ret void
exc.k40:
  call void @scr_str_release(ptr %t296)
  %t298 = load ptr, ptr @sc_g_e_tmpDir
  %t299 = call ptr @scr_str_retain_v(ptr %t298)
  call void @scr_fs_rmdir(ptr %t299)
  %t300 = call zeroext i1 @scr_exc_pending()
  br i1 %t300, label %exc.u41, label %exc.k42
exc.u41:
  call void @scr_str_release(ptr %t299)
  ret void
exc.k42:
  call void @scr_str_release(ptr %t299)
  %t301 = call ptr @scr_str_retain_v(ptr @sc_lit_23)
  %t302 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t302
  %t303 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t301, ptr %t303
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t301)
  %t304 = call ptr @scr_str_retain_v(ptr @sc_lit_24)
  %t305 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t305
  %t306 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t304, ptr %t306
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t304)
  ret void
}

define internal void @sc_f__x25_main() #0 { ; %main
entry:
  call void @sc_f__x25_init_0()
  %t0 = call zeroext i1 @scr_exc_pending()
  br i1 %t0, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  ret void
}

declare void @scr_exc_print_uncaught()

define i32 @main(i32 %argc, ptr %argv) #0 {
entry:
  call void @scr_init()
  store i64 0, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 1) ; Error
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 0)
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 1) ; TypeError
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 0)
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 1) ; RangeError
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 0)
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 1) ; SyntaxError
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 1) ; DOMException
  call void @scr_lib_init(i32 %argc, ptr %argv)
  call void @sc_f__x25_main()
  %exc = call zeroext i1 @scr_exc_pending()
  br i1 %exc, label %uncaught, label %ok
uncaught:
  call void @scr_exc_print_uncaught()
  %gu0 = load ptr, ptr @sc_g_e_tmpDir
  call void @scr_str_release(ptr %gu0) ; tmpDir
  %gu1 = load ptr, ptr @sc_g_e_textFile
  call void @scr_str_release(ptr %gu1) ; textFile
  %gu2 = load ptr, ptr @sc_g_e_content
  call void @scr_str_release(ptr %gu2) ; content
  %gu3 = load ptr, ptr @sc_g_e_binFile
  call void @scr_str_release(ptr %gu3) ; binFile
  %gu4 = load ptr, ptr @sc_g_e_rawBytes
  call void @scr_arr_release(ptr %gu4) ; rawBytes
  %gu5 = load ptr, ptr @sc_g_e_buffer
  call void @scr_bytes_release(ptr %gu5) ; buffer
  %gu6 = load ptr, ptr @sc_g_e_readBuf
  call void @scr_bytes_release(ptr %gu6) ; readBuf
  %gu7 = load ptr, ptr @sc_g_e_jsonFile
  call void @scr_str_release(ptr %gu7) ; jsonFile
  %gu8 = load ptr, ptr @sc_g_e_modelData
  call void @scr_str_release(ptr %gu8) ; modelData
  %gu9 = load ptr, ptr @sc_g_e_loadedJson
  call void @scr_str_release(ptr %gu9) ; loadedJson
  %gu10 = load ptr, ptr @sc_g_e_stats
  call void @scr_stats_release_v(ptr %gu10) ; stats
  ret i32 1
ok:
  %g0 = load ptr, ptr @sc_g_e_tmpDir
  call void @scr_str_release(ptr %g0) ; tmpDir
  %g1 = load ptr, ptr @sc_g_e_textFile
  call void @scr_str_release(ptr %g1) ; textFile
  %g2 = load ptr, ptr @sc_g_e_content
  call void @scr_str_release(ptr %g2) ; content
  %g3 = load ptr, ptr @sc_g_e_binFile
  call void @scr_str_release(ptr %g3) ; binFile
  %g4 = load ptr, ptr @sc_g_e_rawBytes
  call void @scr_arr_release(ptr %g4) ; rawBytes
  %g5 = load ptr, ptr @sc_g_e_buffer
  call void @scr_bytes_release(ptr %g5) ; buffer
  %g6 = load ptr, ptr @sc_g_e_readBuf
  call void @scr_bytes_release(ptr %g6) ; readBuf
  %g7 = load ptr, ptr @sc_g_e_jsonFile
  call void @scr_str_release(ptr %g7) ; jsonFile
  %g8 = load ptr, ptr @sc_g_e_modelData
  call void @scr_str_release(ptr %g8) ; modelData
  %g9 = load ptr, ptr @sc_g_e_loadedJson
  call void @scr_str_release(ptr %g9) ; loadedJson
  %g10 = load ptr, ptr @sc_g_e_stats
  call void @scr_stats_release_v(ptr %g10) ; stats
  ret i32 0
}

attributes #0 = { sanitize_address }
