; Generated by scriptc (LLVM backend) from /Users/sam/Dev/llama.scriptc/examples/phase0/math.ts. Do not edit.

%ScrStr = type { i64, i64, i64 }
%ScrLogArg = type { i32, i64 }
%ScrVt = type { i64, i64, ptr }
%ScrUnion = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrClosure = type { i64, ptr, i64, ptr }
%ScrRegex = type { i64, ptr, ptr, ptr }
%ScrArr = type { i64, i64, i64, i32, ptr, ptr, ptr, ptr }
%ScrError = type { i64, ptr, ptr, ptr, ptr }
%ScrClassObj = type { i64, i64, i64, ptr, ptr }
%ScrEmitter = type { i64, ptr, ptr, ptr }
%ScrStream = type { i64, ptr, ptr, ptr, ptr }
%ScrCaught = type { i64, i32, double, i8, ptr, ptr, ptr, ptr }
%ScrBytes = type { i64, i64, i32, ptr, ptr }
%ScrBox = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrJsonBuf = type { ptr, i64, i64, ptr, i64, i64 }
%ScrDynPath = type { ptr, ptr, i64 }
%ScrIslandModule = type { ptr, ptr, i64, i64, i32, ptr, i64, i64 }
%ScrIslandEdge = type { ptr, ptr, ptr, i32 }

@scr_error_vts = external global [5 x %ScrVt]
declare void @scr_init()
declare void @scr_lib_init(i32, ptr)
declare ptr @scr_jsval_global_get(ptr)
declare zeroext i1 @scr_exc_pending()
declare void @scr_jsval_release_v(ptr)
declare ptr @scr_jsval_from_f64(double)
declare ptr @scr_jsval_call_method(ptr, ptr, i32, ptr)
declare i32 @scr_jsval_exit_f64(ptr, ptr)
declare ptr @scr_str_retain_v(ptr)
declare void @scr_str_release_v(ptr)
declare void @scr_console_log(i64, ptr)
declare void @scr_str_release(ptr)
declare ptr @scr_jsval_get_prop(ptr, ptr)
declare double @llvm.fabs.f64(double)
declare double @scr_math_max(double, double)
declare double @scr_math_min(double, double)
declare double @pow(double, double)
declare ptr @scr_arr_new(i32, i64)
declare double @scr_arr_push_f64(ptr, double)
declare void @scr_arr_release(ptr)
declare ptr @scr_arr_retain_v(ptr)
declare void @scr_arr_release_v(ptr)
declare double @scr_arr_len(ptr)
declare double @scr_arr_get_f64(ptr, double)
declare void @scr_insp_begin(double)
declare ptr @scr_insp_f64(double)
declare void @scr_insp_entry(ptr, i1 zeroext)
declare ptr @scr_insp_more_items(double)
declare ptr @scr_insp_end(ptr, ptr, ptr, double, i1 zeroext, i1 zeroext)

@sc_lit_0 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"Math\00" }
@sc_lit_1 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"sqrt\00" }
@sc_lit_2 = internal global { i64, i64, i64, [19 x i8] } { i64 -1, i64 18, i64 18, [19 x i8] c"--- Basic Math ---\00" }
@sc_lit_3 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c"Math.sqrt(2):\00" }
@sc_lit_4 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c"Math.sqrt(4):\00" }
@sc_lit_5 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"Math.exp(0):\00" }
@sc_lit_6 = internal global { i64, i64, i64, [4 x i8] } { i64 -1, i64 3, i64 3, [4 x i8] c"exp\00" }
@sc_lit_7 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"Math.exp(1):\00" }
@sc_lit_8 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"Math.log(1):\00" }
@sc_lit_9 = internal global { i64, i64, i64, [4 x i8] } { i64 -1, i64 3, i64 3, [4 x i8] c"log\00" }
@sc_lit_10 = internal global { i64, i64, i64, [18 x i8] } { i64 -1, i64 17, i64 17, [18 x i8] c"Math.log(Math.E):\00" }
@sc_lit_11 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"E\00" }
@sc_lit_12 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c"Math.abs(-5):\00" }
@sc_lit_13 = internal global { i64, i64, i64, [16 x i8] } { i64 -1, i64 15, i64 15, [16 x i8] c"Math.max(3, 7):\00" }
@sc_lit_14 = internal global { i64, i64, i64, [16 x i8] } { i64 -1, i64 15, i64 15, [16 x i8] c"Math.min(3, 7):\00" }
@sc_lit_15 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"Math.PI:\00" }
@sc_lit_16 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"PI\00" }
@sc_lit_17 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"Math.E:\00" }
@sc_lit_18 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c"\0A--- Trig ---\00" }
@sc_lit_19 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"Math.sin(0):\00" }
@sc_lit_20 = internal global { i64, i64, i64, [4 x i8] } { i64 -1, i64 3, i64 3, [4 x i8] c"sin\00" }
@sc_lit_21 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"Math.cos(0):\00" }
@sc_lit_22 = internal global { i64, i64, i64, [4 x i8] } { i64 -1, i64 3, i64 3, [4 x i8] c"cos\00" }
@sc_lit_23 = internal global { i64, i64, i64, [21 x i8] } { i64 -1, i64 20, i64 20, [21 x i8] c"Math.sin(Math.PI/2):\00" }
@sc_lit_24 = internal global { i64, i64, i64, [19 x i8] } { i64 -1, i64 18, i64 18, [19 x i8] c"Math.cos(Math.PI):\00" }
@sc_lit_25 = internal global { i64, i64, i64, [21 x i8] } { i64 -1, i64 20, i64 20, [21 x i8] c"\0A--- Power / Log ---\00" }
@sc_lit_26 = internal global { i64, i64, i64, [17 x i8] } { i64 -1, i64 16, i64 16, [17 x i8] c"Math.pow(2, 10):\00" }
@sc_lit_27 = internal global { i64, i64, i64, [4 x i8] } { i64 -1, i64 3, i64 3, [4 x i8] c"pow\00" }
@sc_lit_28 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"2 ** 10:\00" }
@sc_lit_29 = internal global { i64, i64, i64, [17 x i8] } { i64 -1, i64 16, i64 16, [17 x i8] c"Math.log2(1024):\00" }
@sc_lit_30 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"log2\00" }
@sc_lit_31 = internal global { i64, i64, i64, [18 x i8] } { i64 -1, i64 17, i64 17, [18 x i8] c"Math.log10(1000):\00" }
@sc_lit_32 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"log10\00" }
@sc_lit_33 = internal global { i64, i64, i64, [33 x i8] } { i64 -1, i64 32, i64 32, [33 x i8] c"\0A--- Softmax building blocks ---\00" }
@sc_lit_34 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"max:\00" }
@sc_lit_35 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c"exp(x-max):\00" }
@sc_lit_36 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"sum:\00" }
@sc_lit_37 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"softmax:\00" }
@sc_lit_38 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"softmax sum:\00" }
@sc_lit_39 = internal global { i64, i64, i64, [7 x i8] } { i64 -1, i64 6, i64 6, [7 x i8] c"\E2\89\88 1?\00" }
@sc_lit_40 = internal global { i64, i64, i64, [15 x i8] } { i64 -1, i64 14, i64 14, [15 x i8] c"\0A--- rsqrt ---\00" }
@sc_lit_41 = internal global { i64, i64, i64, [10 x i8] } { i64 -1, i64 9, i64 9, [10 x i8] c"rsqrt(4):\00" }
@sc_lit_42 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"rsqrt(64):\00" }
@sc_lit_43 = internal global { i64, i64, i64, [33 x i8] } { i64 -1, i64 32, i64 32, [33 x i8] c"\0A--- RMSNorm building blocks ---\00" }
@sc_lit_44 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"mean(x^2):\00" }
@sc_lit_45 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"rms:\00" }
@sc_lit_46 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c"normalized:\00" }
@sc_lit_47 = internal global { i64, i64, i64, [20 x i8] } { i64 -1, i64 19, i64 19, [20 x i8] c"\0A\E2\9C\85 math.ts passed\00" }
@sc_lit_48 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"[]\00" }
@sc_lit_49 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"[Array]\00" }
@sc_lit_50 = internal global { i64, i64, i64, [1 x i8] } { i64 -1, i64 0, i64 0, [1 x i8] c"\00" }
@sc_lit_51 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"[\00" }
@sc_lit_52 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"]\00" }

@sc_g_e_logits = internal global ptr null ; logits
@sc_g_e_maxVal = internal global double 0x0000000000000000 ; maxVal
@sc_g_e_exps = internal global ptr null ; exps
@sc_g_e_expSum = internal global double 0x0000000000000000 ; expSum
@sc_g_e_softmax = internal global ptr null ; softmax
@sc_g_e_checkSum = internal global double 0x0000000000000000 ; checkSum
@sc_g_e_x = internal global ptr null ; x
@sc_g_e_eps = internal global double 0x0000000000000000 ; eps
@sc_g_e_sumSq = internal global double 0x0000000000000000 ; sumSq
@sc_g_e_meanSq = internal global double 0x0000000000000000 ; meanSq
@sc_g_e_rms = internal global double 0x0000000000000000 ; rms
@sc_g_e_normalized = internal global ptr null ; normalized
@sc_g_e__x25_loaded = internal global i1 false ; %loaded

define internal double @sc_f_rsqrt(double %p_sc_l_x_0) #0 { ; rsqrt
entry:
  %sc_l_x_0 = alloca double ; x
  %s4 = alloca [1 x ptr]
  %s8 = alloca double
  store double %p_sc_l_x_0, ptr %sc_l_x_0
  %t0 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t1 = call zeroext i1 @scr_exc_pending()
  br i1 %t1, label %exc.u0, label %exc.k1
exc.u0:
  call void @scr_jsval_release_v(ptr %t0)
  ret double 0x0000000000000000
exc.k1:
  %t2 = load double, ptr %sc_l_x_0
  %t3 = call ptr @scr_jsval_from_f64(double %t2)
  %t5 = getelementptr inbounds [1 x ptr], ptr %s4, i64 0, i64 0
  store ptr %t3, ptr %t5
  %t6 = call ptr @scr_jsval_call_method(ptr %t0, ptr @sc_lit_1, i32 1, ptr %s4)
  %t7 = call zeroext i1 @scr_exc_pending()
  br i1 %t7, label %exc.u2, label %exc.k3
exc.u2:
  call void @scr_jsval_release_v(ptr %t0)
  call void @scr_jsval_release_v(ptr %t3)
  call void @scr_jsval_release_v(ptr %t6)
  ret double 0x0000000000000000
exc.k3:
  store double 0x0000000000000000, ptr %s8
  %t9 = call i32 @scr_jsval_exit_f64(ptr %t6, ptr %s8)
  %t10 = call zeroext i1 @scr_exc_pending()
  br i1 %t10, label %exc.u4, label %exc.k5
exc.u4:
  call void @scr_jsval_release_v(ptr %t0)
  call void @scr_jsval_release_v(ptr %t3)
  call void @scr_jsval_release_v(ptr %t6)
  ret double 0x0000000000000000
exc.k5:
  %t11 = load double, ptr %s8
  %t12 = fdiv double 0x3FF0000000000000, %t11
  call void @scr_jsval_release_v(ptr %t0)
  call void @scr_jsval_release_v(ptr %t3)
  call void @scr_jsval_release_v(ptr %t6)
  ret double %t12
}

define internal void @sc_f__x25_init_0() #0 { ; %init.0
entry:
  %sc_l_i_0 = alloca double ; i
  %sc_l_i_1 = alloca double ; i
  %sc_l_i_2 = alloca double ; i
  %sc_l_i_3 = alloca double ; i
  %sc_l_i_4 = alloca double ; i
  %sc_l_i_5 = alloca double ; i
  %sc_l_i_6 = alloca double ; i
  %s8 = alloca [1 x ptr]
  %s12 = alloca double
  %s24 = alloca [1 x ptr]
  %s28 = alloca double
  %s40 = alloca [1 x ptr]
  %s44 = alloca double
  %s56 = alloca [1 x ptr]
  %s60 = alloca double
  %s72 = alloca [1 x ptr]
  %s76 = alloca double
  %s91 = alloca double
  %s96 = alloca [1 x ptr]
  %s100 = alloca double
  %s131 = alloca double
  %s144 = alloca double
  %s159 = alloca [1 x ptr]
  %s163 = alloca double
  %s175 = alloca [1 x ptr]
  %s179 = alloca double
  %s194 = alloca double
  %s200 = alloca [1 x ptr]
  %s204 = alloca double
  %s219 = alloca double
  %s224 = alloca [1 x ptr]
  %s228 = alloca double
  %s244 = alloca [2 x ptr]
  %s249 = alloca double
  %s267 = alloca [1 x ptr]
  %s271 = alloca double
  %s283 = alloca [1 x ptr]
  %s287 = alloca double
  %s344 = alloca [1 x ptr]
  %s348 = alloca double
  %s498 = alloca [1 x ptr]
  %s502 = alloca double
  %logargs = alloca [4 x %ScrLogArg]
  %t0 = load i1, ptr @sc_g_e__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_e__x25_loaded
  %t1 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  %t2 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t2
  %t3 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t1, ptr %t3
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t1)
  %t4 = call ptr @scr_str_retain_v(ptr @sc_lit_3)
  %t5 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t6 = call zeroext i1 @scr_exc_pending()
  br i1 %t6, label %exc.u2, label %exc.k3
exc.u2:
  call void @scr_str_release(ptr %t4)
  call void @scr_jsval_release_v(ptr %t5)
  ret void
exc.k3:
  %t7 = call ptr @scr_jsval_from_f64(double 0x4000000000000000)
  %t9 = getelementptr inbounds [1 x ptr], ptr %s8, i64 0, i64 0
  store ptr %t7, ptr %t9
  %t10 = call ptr @scr_jsval_call_method(ptr %t5, ptr @sc_lit_1, i32 1, ptr %s8)
  %t11 = call zeroext i1 @scr_exc_pending()
  br i1 %t11, label %exc.u4, label %exc.k5
exc.u4:
  call void @scr_str_release(ptr %t4)
  call void @scr_jsval_release_v(ptr %t5)
  call void @scr_jsval_release_v(ptr %t7)
  call void @scr_jsval_release_v(ptr %t10)
  ret void
exc.k5:
  store double 0x0000000000000000, ptr %s12
  %t13 = call i32 @scr_jsval_exit_f64(ptr %t10, ptr %s12)
  %t14 = call zeroext i1 @scr_exc_pending()
  br i1 %t14, label %exc.u6, label %exc.k7
exc.u6:
  call void @scr_str_release(ptr %t4)
  call void @scr_jsval_release_v(ptr %t5)
  call void @scr_jsval_release_v(ptr %t7)
  call void @scr_jsval_release_v(ptr %t10)
  ret void
exc.k7:
  %t15 = load double, ptr %s12
  %t16 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t16
  %t17 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t4, ptr %t17
  %t18 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t18
  %t19 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t15, ptr %t19
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t4)
  call void @scr_jsval_release_v(ptr %t5)
  call void @scr_jsval_release_v(ptr %t7)
  call void @scr_jsval_release_v(ptr %t10)
  %t20 = call ptr @scr_str_retain_v(ptr @sc_lit_4)
  %t21 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t22 = call zeroext i1 @scr_exc_pending()
  br i1 %t22, label %exc.u8, label %exc.k9
exc.u8:
  call void @scr_str_release(ptr %t20)
  call void @scr_jsval_release_v(ptr %t21)
  ret void
exc.k9:
  %t23 = call ptr @scr_jsval_from_f64(double 0x4010000000000000)
  %t25 = getelementptr inbounds [1 x ptr], ptr %s24, i64 0, i64 0
  store ptr %t23, ptr %t25
  %t26 = call ptr @scr_jsval_call_method(ptr %t21, ptr @sc_lit_1, i32 1, ptr %s24)
  %t27 = call zeroext i1 @scr_exc_pending()
  br i1 %t27, label %exc.u10, label %exc.k11
exc.u10:
  call void @scr_str_release(ptr %t20)
  call void @scr_jsval_release_v(ptr %t21)
  call void @scr_jsval_release_v(ptr %t23)
  call void @scr_jsval_release_v(ptr %t26)
  ret void
exc.k11:
  store double 0x0000000000000000, ptr %s28
  %t29 = call i32 @scr_jsval_exit_f64(ptr %t26, ptr %s28)
  %t30 = call zeroext i1 @scr_exc_pending()
  br i1 %t30, label %exc.u12, label %exc.k13
exc.u12:
  call void @scr_str_release(ptr %t20)
  call void @scr_jsval_release_v(ptr %t21)
  call void @scr_jsval_release_v(ptr %t23)
  call void @scr_jsval_release_v(ptr %t26)
  ret void
exc.k13:
  %t31 = load double, ptr %s28
  %t32 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t32
  %t33 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t20, ptr %t33
  %t34 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t34
  %t35 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t31, ptr %t35
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t20)
  call void @scr_jsval_release_v(ptr %t21)
  call void @scr_jsval_release_v(ptr %t23)
  call void @scr_jsval_release_v(ptr %t26)
  %t36 = call ptr @scr_str_retain_v(ptr @sc_lit_5)
  %t37 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t38 = call zeroext i1 @scr_exc_pending()
  br i1 %t38, label %exc.u14, label %exc.k15
exc.u14:
  call void @scr_str_release(ptr %t36)
  call void @scr_jsval_release_v(ptr %t37)
  ret void
exc.k15:
  %t39 = call ptr @scr_jsval_from_f64(double 0x0000000000000000)
  %t41 = getelementptr inbounds [1 x ptr], ptr %s40, i64 0, i64 0
  store ptr %t39, ptr %t41
  %t42 = call ptr @scr_jsval_call_method(ptr %t37, ptr @sc_lit_6, i32 1, ptr %s40)
  %t43 = call zeroext i1 @scr_exc_pending()
  br i1 %t43, label %exc.u16, label %exc.k17
exc.u16:
  call void @scr_str_release(ptr %t36)
  call void @scr_jsval_release_v(ptr %t37)
  call void @scr_jsval_release_v(ptr %t39)
  call void @scr_jsval_release_v(ptr %t42)
  ret void
exc.k17:
  store double 0x0000000000000000, ptr %s44
  %t45 = call i32 @scr_jsval_exit_f64(ptr %t42, ptr %s44)
  %t46 = call zeroext i1 @scr_exc_pending()
  br i1 %t46, label %exc.u18, label %exc.k19
exc.u18:
  call void @scr_str_release(ptr %t36)
  call void @scr_jsval_release_v(ptr %t37)
  call void @scr_jsval_release_v(ptr %t39)
  call void @scr_jsval_release_v(ptr %t42)
  ret void
exc.k19:
  %t47 = load double, ptr %s44
  %t48 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t48
  %t49 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t36, ptr %t49
  %t50 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t50
  %t51 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t47, ptr %t51
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t36)
  call void @scr_jsval_release_v(ptr %t37)
  call void @scr_jsval_release_v(ptr %t39)
  call void @scr_jsval_release_v(ptr %t42)
  %t52 = call ptr @scr_str_retain_v(ptr @sc_lit_7)
  %t53 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t54 = call zeroext i1 @scr_exc_pending()
  br i1 %t54, label %exc.u20, label %exc.k21
exc.u20:
  call void @scr_str_release(ptr %t52)
  call void @scr_jsval_release_v(ptr %t53)
  ret void
exc.k21:
  %t55 = call ptr @scr_jsval_from_f64(double 0x3FF0000000000000)
  %t57 = getelementptr inbounds [1 x ptr], ptr %s56, i64 0, i64 0
  store ptr %t55, ptr %t57
  %t58 = call ptr @scr_jsval_call_method(ptr %t53, ptr @sc_lit_6, i32 1, ptr %s56)
  %t59 = call zeroext i1 @scr_exc_pending()
  br i1 %t59, label %exc.u22, label %exc.k23
exc.u22:
  call void @scr_str_release(ptr %t52)
  call void @scr_jsval_release_v(ptr %t53)
  call void @scr_jsval_release_v(ptr %t55)
  call void @scr_jsval_release_v(ptr %t58)
  ret void
exc.k23:
  store double 0x0000000000000000, ptr %s60
  %t61 = call i32 @scr_jsval_exit_f64(ptr %t58, ptr %s60)
  %t62 = call zeroext i1 @scr_exc_pending()
  br i1 %t62, label %exc.u24, label %exc.k25
exc.u24:
  call void @scr_str_release(ptr %t52)
  call void @scr_jsval_release_v(ptr %t53)
  call void @scr_jsval_release_v(ptr %t55)
  call void @scr_jsval_release_v(ptr %t58)
  ret void
exc.k25:
  %t63 = load double, ptr %s60
  %t64 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t64
  %t65 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t52, ptr %t65
  %t66 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t66
  %t67 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t63, ptr %t67
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t52)
  call void @scr_jsval_release_v(ptr %t53)
  call void @scr_jsval_release_v(ptr %t55)
  call void @scr_jsval_release_v(ptr %t58)
  %t68 = call ptr @scr_str_retain_v(ptr @sc_lit_8)
  %t69 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t70 = call zeroext i1 @scr_exc_pending()
  br i1 %t70, label %exc.u26, label %exc.k27
exc.u26:
  call void @scr_str_release(ptr %t68)
  call void @scr_jsval_release_v(ptr %t69)
  ret void
exc.k27:
  %t71 = call ptr @scr_jsval_from_f64(double 0x3FF0000000000000)
  %t73 = getelementptr inbounds [1 x ptr], ptr %s72, i64 0, i64 0
  store ptr %t71, ptr %t73
  %t74 = call ptr @scr_jsval_call_method(ptr %t69, ptr @sc_lit_9, i32 1, ptr %s72)
  %t75 = call zeroext i1 @scr_exc_pending()
  br i1 %t75, label %exc.u28, label %exc.k29
exc.u28:
  call void @scr_str_release(ptr %t68)
  call void @scr_jsval_release_v(ptr %t69)
  call void @scr_jsval_release_v(ptr %t71)
  call void @scr_jsval_release_v(ptr %t74)
  ret void
exc.k29:
  store double 0x0000000000000000, ptr %s76
  %t77 = call i32 @scr_jsval_exit_f64(ptr %t74, ptr %s76)
  %t78 = call zeroext i1 @scr_exc_pending()
  br i1 %t78, label %exc.u30, label %exc.k31
exc.u30:
  call void @scr_str_release(ptr %t68)
  call void @scr_jsval_release_v(ptr %t69)
  call void @scr_jsval_release_v(ptr %t71)
  call void @scr_jsval_release_v(ptr %t74)
  ret void
exc.k31:
  %t79 = load double, ptr %s76
  %t80 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t80
  %t81 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t68, ptr %t81
  %t82 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t82
  %t83 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t79, ptr %t83
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t68)
  call void @scr_jsval_release_v(ptr %t69)
  call void @scr_jsval_release_v(ptr %t71)
  call void @scr_jsval_release_v(ptr %t74)
  %t84 = call ptr @scr_str_retain_v(ptr @sc_lit_10)
  %t85 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t86 = call zeroext i1 @scr_exc_pending()
  br i1 %t86, label %exc.u32, label %exc.k33
exc.u32:
  call void @scr_str_release(ptr %t84)
  call void @scr_jsval_release_v(ptr %t85)
  ret void
exc.k33:
  %t87 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t88 = call zeroext i1 @scr_exc_pending()
  br i1 %t88, label %exc.u34, label %exc.k35
exc.u34:
  call void @scr_str_release(ptr %t84)
  call void @scr_jsval_release_v(ptr %t85)
  call void @scr_jsval_release_v(ptr %t87)
  ret void
exc.k35:
  %t89 = call ptr @scr_jsval_get_prop(ptr %t87, ptr @sc_lit_11)
  %t90 = call zeroext i1 @scr_exc_pending()
  br i1 %t90, label %exc.u36, label %exc.k37
exc.u36:
  call void @scr_str_release(ptr %t84)
  call void @scr_jsval_release_v(ptr %t85)
  call void @scr_jsval_release_v(ptr %t87)
  call void @scr_jsval_release_v(ptr %t89)
  ret void
exc.k37:
  store double 0x0000000000000000, ptr %s91
  %t92 = call i32 @scr_jsval_exit_f64(ptr %t89, ptr %s91)
  %t93 = call zeroext i1 @scr_exc_pending()
  br i1 %t93, label %exc.u38, label %exc.k39
exc.u38:
  call void @scr_str_release(ptr %t84)
  call void @scr_jsval_release_v(ptr %t85)
  call void @scr_jsval_release_v(ptr %t87)
  call void @scr_jsval_release_v(ptr %t89)
  ret void
exc.k39:
  %t94 = load double, ptr %s91
  %t95 = call ptr @scr_jsval_from_f64(double %t94)
  %t97 = getelementptr inbounds [1 x ptr], ptr %s96, i64 0, i64 0
  store ptr %t95, ptr %t97
  %t98 = call ptr @scr_jsval_call_method(ptr %t85, ptr @sc_lit_9, i32 1, ptr %s96)
  %t99 = call zeroext i1 @scr_exc_pending()
  br i1 %t99, label %exc.u40, label %exc.k41
exc.u40:
  call void @scr_str_release(ptr %t84)
  call void @scr_jsval_release_v(ptr %t85)
  call void @scr_jsval_release_v(ptr %t87)
  call void @scr_jsval_release_v(ptr %t89)
  call void @scr_jsval_release_v(ptr %t95)
  call void @scr_jsval_release_v(ptr %t98)
  ret void
exc.k41:
  store double 0x0000000000000000, ptr %s100
  %t101 = call i32 @scr_jsval_exit_f64(ptr %t98, ptr %s100)
  %t102 = call zeroext i1 @scr_exc_pending()
  br i1 %t102, label %exc.u42, label %exc.k43
exc.u42:
  call void @scr_str_release(ptr %t84)
  call void @scr_jsval_release_v(ptr %t85)
  call void @scr_jsval_release_v(ptr %t87)
  call void @scr_jsval_release_v(ptr %t89)
  call void @scr_jsval_release_v(ptr %t95)
  call void @scr_jsval_release_v(ptr %t98)
  ret void
exc.k43:
  %t103 = load double, ptr %s100
  %t104 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t104
  %t105 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t84, ptr %t105
  %t106 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t106
  %t107 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t103, ptr %t107
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t84)
  call void @scr_jsval_release_v(ptr %t85)
  call void @scr_jsval_release_v(ptr %t87)
  call void @scr_jsval_release_v(ptr %t89)
  call void @scr_jsval_release_v(ptr %t95)
  call void @scr_jsval_release_v(ptr %t98)
  %t108 = call ptr @scr_str_retain_v(ptr @sc_lit_12)
  %t109 = call double @llvm.fabs.f64(double 0xC014000000000000)
  %t110 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t110
  %t111 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t108, ptr %t111
  %t112 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t112
  %t113 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t109, ptr %t113
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t108)
  %t114 = call ptr @scr_str_retain_v(ptr @sc_lit_13)
  %t115 = call double @scr_math_max(double 0x4008000000000000, double 0x401C000000000000)
  %t116 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t116
  %t117 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t114, ptr %t117
  %t118 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t118
  %t119 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t115, ptr %t119
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t114)
  %t120 = call ptr @scr_str_retain_v(ptr @sc_lit_14)
  %t121 = call double @scr_math_min(double 0x4008000000000000, double 0x401C000000000000)
  %t122 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t122
  %t123 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t120, ptr %t123
  %t124 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t124
  %t125 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t121, ptr %t125
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t120)
  %t126 = call ptr @scr_str_retain_v(ptr @sc_lit_15)
  %t127 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t128 = call zeroext i1 @scr_exc_pending()
  br i1 %t128, label %exc.u44, label %exc.k45
exc.u44:
  call void @scr_str_release(ptr %t126)
  call void @scr_jsval_release_v(ptr %t127)
  ret void
exc.k45:
  %t129 = call ptr @scr_jsval_get_prop(ptr %t127, ptr @sc_lit_16)
  %t130 = call zeroext i1 @scr_exc_pending()
  br i1 %t130, label %exc.u46, label %exc.k47
exc.u46:
  call void @scr_str_release(ptr %t126)
  call void @scr_jsval_release_v(ptr %t127)
  call void @scr_jsval_release_v(ptr %t129)
  ret void
exc.k47:
  store double 0x0000000000000000, ptr %s131
  %t132 = call i32 @scr_jsval_exit_f64(ptr %t129, ptr %s131)
  %t133 = call zeroext i1 @scr_exc_pending()
  br i1 %t133, label %exc.u48, label %exc.k49
exc.u48:
  call void @scr_str_release(ptr %t126)
  call void @scr_jsval_release_v(ptr %t127)
  call void @scr_jsval_release_v(ptr %t129)
  ret void
exc.k49:
  %t134 = load double, ptr %s131
  %t135 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t135
  %t136 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t126, ptr %t136
  %t137 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t137
  %t138 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t134, ptr %t138
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t126)
  call void @scr_jsval_release_v(ptr %t127)
  call void @scr_jsval_release_v(ptr %t129)
  %t139 = call ptr @scr_str_retain_v(ptr @sc_lit_17)
  %t140 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t141 = call zeroext i1 @scr_exc_pending()
  br i1 %t141, label %exc.u50, label %exc.k51
exc.u50:
  call void @scr_str_release(ptr %t139)
  call void @scr_jsval_release_v(ptr %t140)
  ret void
exc.k51:
  %t142 = call ptr @scr_jsval_get_prop(ptr %t140, ptr @sc_lit_11)
  %t143 = call zeroext i1 @scr_exc_pending()
  br i1 %t143, label %exc.u52, label %exc.k53
exc.u52:
  call void @scr_str_release(ptr %t139)
  call void @scr_jsval_release_v(ptr %t140)
  call void @scr_jsval_release_v(ptr %t142)
  ret void
exc.k53:
  store double 0x0000000000000000, ptr %s144
  %t145 = call i32 @scr_jsval_exit_f64(ptr %t142, ptr %s144)
  %t146 = call zeroext i1 @scr_exc_pending()
  br i1 %t146, label %exc.u54, label %exc.k55
exc.u54:
  call void @scr_str_release(ptr %t139)
  call void @scr_jsval_release_v(ptr %t140)
  call void @scr_jsval_release_v(ptr %t142)
  ret void
exc.k55:
  %t147 = load double, ptr %s144
  %t148 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t148
  %t149 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t139, ptr %t149
  %t150 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t150
  %t151 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t147, ptr %t151
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t139)
  call void @scr_jsval_release_v(ptr %t140)
  call void @scr_jsval_release_v(ptr %t142)
  %t152 = call ptr @scr_str_retain_v(ptr @sc_lit_18)
  %t153 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t153
  %t154 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t152, ptr %t154
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t152)
  %t155 = call ptr @scr_str_retain_v(ptr @sc_lit_19)
  %t156 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t157 = call zeroext i1 @scr_exc_pending()
  br i1 %t157, label %exc.u56, label %exc.k57
exc.u56:
  call void @scr_str_release(ptr %t155)
  call void @scr_jsval_release_v(ptr %t156)
  ret void
exc.k57:
  %t158 = call ptr @scr_jsval_from_f64(double 0x0000000000000000)
  %t160 = getelementptr inbounds [1 x ptr], ptr %s159, i64 0, i64 0
  store ptr %t158, ptr %t160
  %t161 = call ptr @scr_jsval_call_method(ptr %t156, ptr @sc_lit_20, i32 1, ptr %s159)
  %t162 = call zeroext i1 @scr_exc_pending()
  br i1 %t162, label %exc.u58, label %exc.k59
exc.u58:
  call void @scr_str_release(ptr %t155)
  call void @scr_jsval_release_v(ptr %t156)
  call void @scr_jsval_release_v(ptr %t158)
  call void @scr_jsval_release_v(ptr %t161)
  ret void
exc.k59:
  store double 0x0000000000000000, ptr %s163
  %t164 = call i32 @scr_jsval_exit_f64(ptr %t161, ptr %s163)
  %t165 = call zeroext i1 @scr_exc_pending()
  br i1 %t165, label %exc.u60, label %exc.k61
exc.u60:
  call void @scr_str_release(ptr %t155)
  call void @scr_jsval_release_v(ptr %t156)
  call void @scr_jsval_release_v(ptr %t158)
  call void @scr_jsval_release_v(ptr %t161)
  ret void
exc.k61:
  %t166 = load double, ptr %s163
  %t167 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t167
  %t168 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t155, ptr %t168
  %t169 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t169
  %t170 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t166, ptr %t170
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t155)
  call void @scr_jsval_release_v(ptr %t156)
  call void @scr_jsval_release_v(ptr %t158)
  call void @scr_jsval_release_v(ptr %t161)
  %t171 = call ptr @scr_str_retain_v(ptr @sc_lit_21)
  %t172 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t173 = call zeroext i1 @scr_exc_pending()
  br i1 %t173, label %exc.u62, label %exc.k63
exc.u62:
  call void @scr_str_release(ptr %t171)
  call void @scr_jsval_release_v(ptr %t172)
  ret void
exc.k63:
  %t174 = call ptr @scr_jsval_from_f64(double 0x0000000000000000)
  %t176 = getelementptr inbounds [1 x ptr], ptr %s175, i64 0, i64 0
  store ptr %t174, ptr %t176
  %t177 = call ptr @scr_jsval_call_method(ptr %t172, ptr @sc_lit_22, i32 1, ptr %s175)
  %t178 = call zeroext i1 @scr_exc_pending()
  br i1 %t178, label %exc.u64, label %exc.k65
exc.u64:
  call void @scr_str_release(ptr %t171)
  call void @scr_jsval_release_v(ptr %t172)
  call void @scr_jsval_release_v(ptr %t174)
  call void @scr_jsval_release_v(ptr %t177)
  ret void
exc.k65:
  store double 0x0000000000000000, ptr %s179
  %t180 = call i32 @scr_jsval_exit_f64(ptr %t177, ptr %s179)
  %t181 = call zeroext i1 @scr_exc_pending()
  br i1 %t181, label %exc.u66, label %exc.k67
exc.u66:
  call void @scr_str_release(ptr %t171)
  call void @scr_jsval_release_v(ptr %t172)
  call void @scr_jsval_release_v(ptr %t174)
  call void @scr_jsval_release_v(ptr %t177)
  ret void
exc.k67:
  %t182 = load double, ptr %s179
  %t183 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t183
  %t184 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t171, ptr %t184
  %t185 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t185
  %t186 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t182, ptr %t186
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t171)
  call void @scr_jsval_release_v(ptr %t172)
  call void @scr_jsval_release_v(ptr %t174)
  call void @scr_jsval_release_v(ptr %t177)
  %t187 = call ptr @scr_str_retain_v(ptr @sc_lit_23)
  %t188 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t189 = call zeroext i1 @scr_exc_pending()
  br i1 %t189, label %exc.u68, label %exc.k69
exc.u68:
  call void @scr_str_release(ptr %t187)
  call void @scr_jsval_release_v(ptr %t188)
  ret void
exc.k69:
  %t190 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t191 = call zeroext i1 @scr_exc_pending()
  br i1 %t191, label %exc.u70, label %exc.k71
exc.u70:
  call void @scr_str_release(ptr %t187)
  call void @scr_jsval_release_v(ptr %t188)
  call void @scr_jsval_release_v(ptr %t190)
  ret void
exc.k71:
  %t192 = call ptr @scr_jsval_get_prop(ptr %t190, ptr @sc_lit_16)
  %t193 = call zeroext i1 @scr_exc_pending()
  br i1 %t193, label %exc.u72, label %exc.k73
exc.u72:
  call void @scr_str_release(ptr %t187)
  call void @scr_jsval_release_v(ptr %t188)
  call void @scr_jsval_release_v(ptr %t190)
  call void @scr_jsval_release_v(ptr %t192)
  ret void
exc.k73:
  store double 0x0000000000000000, ptr %s194
  %t195 = call i32 @scr_jsval_exit_f64(ptr %t192, ptr %s194)
  %t196 = call zeroext i1 @scr_exc_pending()
  br i1 %t196, label %exc.u74, label %exc.k75
exc.u74:
  call void @scr_str_release(ptr %t187)
  call void @scr_jsval_release_v(ptr %t188)
  call void @scr_jsval_release_v(ptr %t190)
  call void @scr_jsval_release_v(ptr %t192)
  ret void
exc.k75:
  %t197 = load double, ptr %s194
  %t198 = fdiv double %t197, 0x4000000000000000
  %t199 = call ptr @scr_jsval_from_f64(double %t198)
  %t201 = getelementptr inbounds [1 x ptr], ptr %s200, i64 0, i64 0
  store ptr %t199, ptr %t201
  %t202 = call ptr @scr_jsval_call_method(ptr %t188, ptr @sc_lit_20, i32 1, ptr %s200)
  %t203 = call zeroext i1 @scr_exc_pending()
  br i1 %t203, label %exc.u76, label %exc.k77
exc.u76:
  call void @scr_str_release(ptr %t187)
  call void @scr_jsval_release_v(ptr %t188)
  call void @scr_jsval_release_v(ptr %t190)
  call void @scr_jsval_release_v(ptr %t192)
  call void @scr_jsval_release_v(ptr %t199)
  call void @scr_jsval_release_v(ptr %t202)
  ret void
exc.k77:
  store double 0x0000000000000000, ptr %s204
  %t205 = call i32 @scr_jsval_exit_f64(ptr %t202, ptr %s204)
  %t206 = call zeroext i1 @scr_exc_pending()
  br i1 %t206, label %exc.u78, label %exc.k79
exc.u78:
  call void @scr_str_release(ptr %t187)
  call void @scr_jsval_release_v(ptr %t188)
  call void @scr_jsval_release_v(ptr %t190)
  call void @scr_jsval_release_v(ptr %t192)
  call void @scr_jsval_release_v(ptr %t199)
  call void @scr_jsval_release_v(ptr %t202)
  ret void
exc.k79:
  %t207 = load double, ptr %s204
  %t208 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t208
  %t209 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t187, ptr %t209
  %t210 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t210
  %t211 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t207, ptr %t211
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t187)
  call void @scr_jsval_release_v(ptr %t188)
  call void @scr_jsval_release_v(ptr %t190)
  call void @scr_jsval_release_v(ptr %t192)
  call void @scr_jsval_release_v(ptr %t199)
  call void @scr_jsval_release_v(ptr %t202)
  %t212 = call ptr @scr_str_retain_v(ptr @sc_lit_24)
  %t213 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t214 = call zeroext i1 @scr_exc_pending()
  br i1 %t214, label %exc.u80, label %exc.k81
exc.u80:
  call void @scr_str_release(ptr %t212)
  call void @scr_jsval_release_v(ptr %t213)
  ret void
exc.k81:
  %t215 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t216 = call zeroext i1 @scr_exc_pending()
  br i1 %t216, label %exc.u82, label %exc.k83
exc.u82:
  call void @scr_str_release(ptr %t212)
  call void @scr_jsval_release_v(ptr %t213)
  call void @scr_jsval_release_v(ptr %t215)
  ret void
exc.k83:
  %t217 = call ptr @scr_jsval_get_prop(ptr %t215, ptr @sc_lit_16)
  %t218 = call zeroext i1 @scr_exc_pending()
  br i1 %t218, label %exc.u84, label %exc.k85
exc.u84:
  call void @scr_str_release(ptr %t212)
  call void @scr_jsval_release_v(ptr %t213)
  call void @scr_jsval_release_v(ptr %t215)
  call void @scr_jsval_release_v(ptr %t217)
  ret void
exc.k85:
  store double 0x0000000000000000, ptr %s219
  %t220 = call i32 @scr_jsval_exit_f64(ptr %t217, ptr %s219)
  %t221 = call zeroext i1 @scr_exc_pending()
  br i1 %t221, label %exc.u86, label %exc.k87
exc.u86:
  call void @scr_str_release(ptr %t212)
  call void @scr_jsval_release_v(ptr %t213)
  call void @scr_jsval_release_v(ptr %t215)
  call void @scr_jsval_release_v(ptr %t217)
  ret void
exc.k87:
  %t222 = load double, ptr %s219
  %t223 = call ptr @scr_jsval_from_f64(double %t222)
  %t225 = getelementptr inbounds [1 x ptr], ptr %s224, i64 0, i64 0
  store ptr %t223, ptr %t225
  %t226 = call ptr @scr_jsval_call_method(ptr %t213, ptr @sc_lit_22, i32 1, ptr %s224)
  %t227 = call zeroext i1 @scr_exc_pending()
  br i1 %t227, label %exc.u88, label %exc.k89
exc.u88:
  call void @scr_str_release(ptr %t212)
  call void @scr_jsval_release_v(ptr %t213)
  call void @scr_jsval_release_v(ptr %t215)
  call void @scr_jsval_release_v(ptr %t217)
  call void @scr_jsval_release_v(ptr %t223)
  call void @scr_jsval_release_v(ptr %t226)
  ret void
exc.k89:
  store double 0x0000000000000000, ptr %s228
  %t229 = call i32 @scr_jsval_exit_f64(ptr %t226, ptr %s228)
  %t230 = call zeroext i1 @scr_exc_pending()
  br i1 %t230, label %exc.u90, label %exc.k91
exc.u90:
  call void @scr_str_release(ptr %t212)
  call void @scr_jsval_release_v(ptr %t213)
  call void @scr_jsval_release_v(ptr %t215)
  call void @scr_jsval_release_v(ptr %t217)
  call void @scr_jsval_release_v(ptr %t223)
  call void @scr_jsval_release_v(ptr %t226)
  ret void
exc.k91:
  %t231 = load double, ptr %s228
  %t232 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t232
  %t233 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t212, ptr %t233
  %t234 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t234
  %t235 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t231, ptr %t235
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t212)
  call void @scr_jsval_release_v(ptr %t213)
  call void @scr_jsval_release_v(ptr %t215)
  call void @scr_jsval_release_v(ptr %t217)
  call void @scr_jsval_release_v(ptr %t223)
  call void @scr_jsval_release_v(ptr %t226)
  %t236 = call ptr @scr_str_retain_v(ptr @sc_lit_25)
  %t237 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t237
  %t238 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t236, ptr %t238
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t236)
  %t239 = call ptr @scr_str_retain_v(ptr @sc_lit_26)
  %t240 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t241 = call zeroext i1 @scr_exc_pending()
  br i1 %t241, label %exc.u92, label %exc.k93
exc.u92:
  call void @scr_str_release(ptr %t239)
  call void @scr_jsval_release_v(ptr %t240)
  ret void
exc.k93:
  %t242 = call ptr @scr_jsval_from_f64(double 0x4000000000000000)
  %t243 = call ptr @scr_jsval_from_f64(double 0x4024000000000000)
  %t245 = getelementptr inbounds [2 x ptr], ptr %s244, i64 0, i64 0
  store ptr %t242, ptr %t245
  %t246 = getelementptr inbounds [2 x ptr], ptr %s244, i64 0, i64 1
  store ptr %t243, ptr %t246
  %t247 = call ptr @scr_jsval_call_method(ptr %t240, ptr @sc_lit_27, i32 2, ptr %s244)
  %t248 = call zeroext i1 @scr_exc_pending()
  br i1 %t248, label %exc.u94, label %exc.k95
exc.u94:
  call void @scr_str_release(ptr %t239)
  call void @scr_jsval_release_v(ptr %t240)
  call void @scr_jsval_release_v(ptr %t242)
  call void @scr_jsval_release_v(ptr %t243)
  call void @scr_jsval_release_v(ptr %t247)
  ret void
exc.k95:
  store double 0x0000000000000000, ptr %s249
  %t250 = call i32 @scr_jsval_exit_f64(ptr %t247, ptr %s249)
  %t251 = call zeroext i1 @scr_exc_pending()
  br i1 %t251, label %exc.u96, label %exc.k97
exc.u96:
  call void @scr_str_release(ptr %t239)
  call void @scr_jsval_release_v(ptr %t240)
  call void @scr_jsval_release_v(ptr %t242)
  call void @scr_jsval_release_v(ptr %t243)
  call void @scr_jsval_release_v(ptr %t247)
  ret void
exc.k97:
  %t252 = load double, ptr %s249
  %t253 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t253
  %t254 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t239, ptr %t254
  %t255 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t255
  %t256 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t252, ptr %t256
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t239)
  call void @scr_jsval_release_v(ptr %t240)
  call void @scr_jsval_release_v(ptr %t242)
  call void @scr_jsval_release_v(ptr %t243)
  call void @scr_jsval_release_v(ptr %t247)
  %t257 = call ptr @scr_str_retain_v(ptr @sc_lit_28)
  %t258 = call double @pow(double 0x4000000000000000, double 0x4024000000000000)
  %t259 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t259
  %t260 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t257, ptr %t260
  %t261 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t261
  %t262 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t258, ptr %t262
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t257)
  %t263 = call ptr @scr_str_retain_v(ptr @sc_lit_29)
  %t264 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t265 = call zeroext i1 @scr_exc_pending()
  br i1 %t265, label %exc.u98, label %exc.k99
exc.u98:
  call void @scr_str_release(ptr %t263)
  call void @scr_jsval_release_v(ptr %t264)
  ret void
exc.k99:
  %t266 = call ptr @scr_jsval_from_f64(double 0x4090000000000000)
  %t268 = getelementptr inbounds [1 x ptr], ptr %s267, i64 0, i64 0
  store ptr %t266, ptr %t268
  %t269 = call ptr @scr_jsval_call_method(ptr %t264, ptr @sc_lit_30, i32 1, ptr %s267)
  %t270 = call zeroext i1 @scr_exc_pending()
  br i1 %t270, label %exc.u100, label %exc.k101
exc.u100:
  call void @scr_str_release(ptr %t263)
  call void @scr_jsval_release_v(ptr %t264)
  call void @scr_jsval_release_v(ptr %t266)
  call void @scr_jsval_release_v(ptr %t269)
  ret void
exc.k101:
  store double 0x0000000000000000, ptr %s271
  %t272 = call i32 @scr_jsval_exit_f64(ptr %t269, ptr %s271)
  %t273 = call zeroext i1 @scr_exc_pending()
  br i1 %t273, label %exc.u102, label %exc.k103
exc.u102:
  call void @scr_str_release(ptr %t263)
  call void @scr_jsval_release_v(ptr %t264)
  call void @scr_jsval_release_v(ptr %t266)
  call void @scr_jsval_release_v(ptr %t269)
  ret void
exc.k103:
  %t274 = load double, ptr %s271
  %t275 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t275
  %t276 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t263, ptr %t276
  %t277 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t277
  %t278 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t274, ptr %t278
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t263)
  call void @scr_jsval_release_v(ptr %t264)
  call void @scr_jsval_release_v(ptr %t266)
  call void @scr_jsval_release_v(ptr %t269)
  %t279 = call ptr @scr_str_retain_v(ptr @sc_lit_31)
  %t280 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t281 = call zeroext i1 @scr_exc_pending()
  br i1 %t281, label %exc.u104, label %exc.k105
exc.u104:
  call void @scr_str_release(ptr %t279)
  call void @scr_jsval_release_v(ptr %t280)
  ret void
exc.k105:
  %t282 = call ptr @scr_jsval_from_f64(double 0x408F400000000000)
  %t284 = getelementptr inbounds [1 x ptr], ptr %s283, i64 0, i64 0
  store ptr %t282, ptr %t284
  %t285 = call ptr @scr_jsval_call_method(ptr %t280, ptr @sc_lit_32, i32 1, ptr %s283)
  %t286 = call zeroext i1 @scr_exc_pending()
  br i1 %t286, label %exc.u106, label %exc.k107
exc.u106:
  call void @scr_str_release(ptr %t279)
  call void @scr_jsval_release_v(ptr %t280)
  call void @scr_jsval_release_v(ptr %t282)
  call void @scr_jsval_release_v(ptr %t285)
  ret void
exc.k107:
  store double 0x0000000000000000, ptr %s287
  %t288 = call i32 @scr_jsval_exit_f64(ptr %t285, ptr %s287)
  %t289 = call zeroext i1 @scr_exc_pending()
  br i1 %t289, label %exc.u108, label %exc.k109
exc.u108:
  call void @scr_str_release(ptr %t279)
  call void @scr_jsval_release_v(ptr %t280)
  call void @scr_jsval_release_v(ptr %t282)
  call void @scr_jsval_release_v(ptr %t285)
  ret void
exc.k109:
  %t290 = load double, ptr %s287
  %t291 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t291
  %t292 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t279, ptr %t292
  %t293 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t293
  %t294 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t290, ptr %t294
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t279)
  call void @scr_jsval_release_v(ptr %t280)
  call void @scr_jsval_release_v(ptr %t282)
  call void @scr_jsval_release_v(ptr %t285)
  %t295 = call ptr @scr_str_retain_v(ptr @sc_lit_33)
  %t296 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t296
  %t297 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t295, ptr %t297
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t295)
  %t298 = call ptr @scr_arr_new(i32 0, i64 3)
  %t299 = call double @scr_arr_push_f64(ptr %t298, double 0x4000000000000000)
  %t300 = call double @scr_arr_push_f64(ptr %t298, double 0x3FF0000000000000)
  %t301 = call double @scr_arr_push_f64(ptr %t298, double 0x3FB999999999999A)
  %t302 = load ptr, ptr @sc_g_e_logits
  call void @scr_arr_release(ptr %t302)
  store ptr %t298, ptr @sc_g_e_logits
  store double 0xFFF0000000000000, ptr @sc_g_e_maxVal
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c110
loop.c110:
  %t303 = load double, ptr %sc_l_i_0
  %t304 = load ptr, ptr @sc_g_e_logits
  %t305 = call ptr @scr_arr_retain_v(ptr %t304)
  %t306 = call double @scr_arr_len(ptr %t305)
  %t307 = fcmp olt double %t303, %t306
  call void @scr_arr_release(ptr %t305)
  br i1 %t307, label %loop.b111, label %loop.e112
loop.b111:
  %t308 = load ptr, ptr @sc_g_e_logits
  %t309 = call ptr @scr_arr_retain_v(ptr %t308)
  %t310 = load double, ptr %sc_l_i_0
  %t311 = call double @scr_arr_get_f64(ptr %t309, double %t310)
  %t312 = load double, ptr @sc_g_e_maxVal
  %t313 = fcmp ogt double %t311, %t312
  call void @scr_arr_release(ptr %t309)
  br i1 %t313, label %if.t114, label %if.j115
if.t114:
  %t314 = load ptr, ptr @sc_g_e_logits
  %t315 = call ptr @scr_arr_retain_v(ptr %t314)
  %t316 = load double, ptr %sc_l_i_0
  %t317 = call double @scr_arr_get_f64(ptr %t315, double %t316)
  store double %t317, ptr @sc_g_e_maxVal
  call void @scr_arr_release(ptr %t315)
  br label %if.j115
if.j115:
  br label %loop.u113
loop.u113:
  %t318 = load double, ptr %sc_l_i_0
  %t319 = fadd double %t318, 0x3FF0000000000000
  store double %t319, ptr %sc_l_i_0
  br label %loop.c110
loop.e112:
  %t320 = call ptr @scr_str_retain_v(ptr @sc_lit_34)
  %t321 = load double, ptr @sc_g_e_maxVal
  %t322 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t322
  %t323 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t320, ptr %t323
  %t324 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t324
  %t325 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t321, ptr %t325
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t320)
  %t326 = call ptr @scr_arr_new(i32 0, i64 0)
  %t327 = load ptr, ptr @sc_g_e_exps
  call void @scr_arr_release(ptr %t327)
  store ptr %t326, ptr @sc_g_e_exps
  store double 0x0000000000000000, ptr %sc_l_i_1
  br label %loop.c116
loop.c116:
  %t328 = load double, ptr %sc_l_i_1
  %t329 = load ptr, ptr @sc_g_e_logits
  %t330 = call ptr @scr_arr_retain_v(ptr %t329)
  %t331 = call double @scr_arr_len(ptr %t330)
  %t332 = fcmp olt double %t328, %t331
  call void @scr_arr_release(ptr %t330)
  br i1 %t332, label %loop.b117, label %loop.e118
loop.b117:
  %t333 = load ptr, ptr @sc_g_e_exps
  %t334 = call ptr @scr_arr_retain_v(ptr %t333)
  %t335 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t336 = call zeroext i1 @scr_exc_pending()
  br i1 %t336, label %exc.u120, label %exc.k121
exc.u120:
  call void @scr_arr_release(ptr %t334)
  call void @scr_jsval_release_v(ptr %t335)
  ret void
exc.k121:
  %t337 = load ptr, ptr @sc_g_e_logits
  %t338 = call ptr @scr_arr_retain_v(ptr %t337)
  %t339 = load double, ptr %sc_l_i_1
  %t340 = call double @scr_arr_get_f64(ptr %t338, double %t339)
  %t341 = load double, ptr @sc_g_e_maxVal
  %t342 = fsub double %t340, %t341
  %t343 = call ptr @scr_jsval_from_f64(double %t342)
  %t345 = getelementptr inbounds [1 x ptr], ptr %s344, i64 0, i64 0
  store ptr %t343, ptr %t345
  %t346 = call ptr @scr_jsval_call_method(ptr %t335, ptr @sc_lit_6, i32 1, ptr %s344)
  %t347 = call zeroext i1 @scr_exc_pending()
  br i1 %t347, label %exc.u122, label %exc.k123
exc.u122:
  call void @scr_arr_release(ptr %t334)
  call void @scr_jsval_release_v(ptr %t335)
  call void @scr_arr_release(ptr %t338)
  call void @scr_jsval_release_v(ptr %t343)
  call void @scr_jsval_release_v(ptr %t346)
  ret void
exc.k123:
  store double 0x0000000000000000, ptr %s348
  %t349 = call i32 @scr_jsval_exit_f64(ptr %t346, ptr %s348)
  %t350 = call zeroext i1 @scr_exc_pending()
  br i1 %t350, label %exc.u124, label %exc.k125
exc.u124:
  call void @scr_arr_release(ptr %t334)
  call void @scr_jsval_release_v(ptr %t335)
  call void @scr_arr_release(ptr %t338)
  call void @scr_jsval_release_v(ptr %t343)
  call void @scr_jsval_release_v(ptr %t346)
  ret void
exc.k125:
  %t351 = load double, ptr %s348
  %t352 = call double @scr_arr_push_f64(ptr %t334, double %t351)
  call void @scr_arr_release(ptr %t334)
  call void @scr_jsval_release_v(ptr %t335)
  call void @scr_arr_release(ptr %t338)
  call void @scr_jsval_release_v(ptr %t343)
  call void @scr_jsval_release_v(ptr %t346)
  br label %loop.u119
loop.u119:
  %t353 = load double, ptr %sc_l_i_1
  %t354 = fadd double %t353, 0x3FF0000000000000
  store double %t354, ptr %sc_l_i_1
  br label %loop.c116
loop.e118:
  %t355 = call ptr @scr_str_retain_v(ptr @sc_lit_35)
  %t356 = load ptr, ptr @sc_g_e_exps
  %t357 = call ptr @scr_arr_retain_v(ptr %t356)
  %t358 = call ptr @sc_f__x25_util_insp_0(ptr %t357, double 0x0000000000000000, double 0x4000000000000000)
  %t359 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t359
  %t360 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t355, ptr %t360
  %t361 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t361
  %t362 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t358, ptr %t362
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t355)
  call void @scr_str_release(ptr %t358)
  store double 0x0000000000000000, ptr @sc_g_e_expSum
  store double 0x0000000000000000, ptr %sc_l_i_2
  br label %loop.c126
loop.c126:
  %t363 = load double, ptr %sc_l_i_2
  %t364 = load ptr, ptr @sc_g_e_exps
  %t365 = call ptr @scr_arr_retain_v(ptr %t364)
  %t366 = call double @scr_arr_len(ptr %t365)
  %t367 = fcmp olt double %t363, %t366
  call void @scr_arr_release(ptr %t365)
  br i1 %t367, label %loop.b127, label %loop.e128
loop.b127:
  %t368 = load double, ptr @sc_g_e_expSum
  %t369 = load ptr, ptr @sc_g_e_exps
  %t370 = call ptr @scr_arr_retain_v(ptr %t369)
  %t371 = load double, ptr %sc_l_i_2
  %t372 = call double @scr_arr_get_f64(ptr %t370, double %t371)
  %t373 = fadd double %t368, %t372
  store double %t373, ptr @sc_g_e_expSum
  call void @scr_arr_release(ptr %t370)
  br label %loop.u129
loop.u129:
  %t374 = load double, ptr %sc_l_i_2
  %t375 = fadd double %t374, 0x3FF0000000000000
  store double %t375, ptr %sc_l_i_2
  br label %loop.c126
loop.e128:
  %t376 = call ptr @scr_str_retain_v(ptr @sc_lit_36)
  %t377 = load double, ptr @sc_g_e_expSum
  %t378 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t378
  %t379 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t376, ptr %t379
  %t380 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t380
  %t381 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t377, ptr %t381
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t376)
  %t382 = call ptr @scr_arr_new(i32 0, i64 0)
  %t383 = load ptr, ptr @sc_g_e_softmax
  call void @scr_arr_release(ptr %t383)
  store ptr %t382, ptr @sc_g_e_softmax
  store double 0x0000000000000000, ptr %sc_l_i_3
  br label %loop.c130
loop.c130:
  %t384 = load double, ptr %sc_l_i_3
  %t385 = load ptr, ptr @sc_g_e_exps
  %t386 = call ptr @scr_arr_retain_v(ptr %t385)
  %t387 = call double @scr_arr_len(ptr %t386)
  %t388 = fcmp olt double %t384, %t387
  call void @scr_arr_release(ptr %t386)
  br i1 %t388, label %loop.b131, label %loop.e132
loop.b131:
  %t389 = load ptr, ptr @sc_g_e_softmax
  %t390 = call ptr @scr_arr_retain_v(ptr %t389)
  %t391 = load ptr, ptr @sc_g_e_exps
  %t392 = call ptr @scr_arr_retain_v(ptr %t391)
  %t393 = load double, ptr %sc_l_i_3
  %t394 = call double @scr_arr_get_f64(ptr %t392, double %t393)
  %t395 = load double, ptr @sc_g_e_expSum
  %t396 = fdiv double %t394, %t395
  %t397 = call double @scr_arr_push_f64(ptr %t390, double %t396)
  call void @scr_arr_release(ptr %t390)
  call void @scr_arr_release(ptr %t392)
  br label %loop.u133
loop.u133:
  %t398 = load double, ptr %sc_l_i_3
  %t399 = fadd double %t398, 0x3FF0000000000000
  store double %t399, ptr %sc_l_i_3
  br label %loop.c130
loop.e132:
  %t400 = call ptr @scr_str_retain_v(ptr @sc_lit_37)
  %t401 = load ptr, ptr @sc_g_e_softmax
  %t402 = call ptr @scr_arr_retain_v(ptr %t401)
  %t403 = call ptr @sc_f__x25_util_insp_0(ptr %t402, double 0x0000000000000000, double 0x4000000000000000)
  %t404 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t404
  %t405 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t400, ptr %t405
  %t406 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t406
  %t407 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t403, ptr %t407
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t400)
  call void @scr_str_release(ptr %t403)
  store double 0x0000000000000000, ptr @sc_g_e_checkSum
  store double 0x0000000000000000, ptr %sc_l_i_4
  br label %loop.c134
loop.c134:
  %t408 = load double, ptr %sc_l_i_4
  %t409 = load ptr, ptr @sc_g_e_softmax
  %t410 = call ptr @scr_arr_retain_v(ptr %t409)
  %t411 = call double @scr_arr_len(ptr %t410)
  %t412 = fcmp olt double %t408, %t411
  call void @scr_arr_release(ptr %t410)
  br i1 %t412, label %loop.b135, label %loop.e136
loop.b135:
  %t413 = load double, ptr @sc_g_e_checkSum
  %t414 = load ptr, ptr @sc_g_e_softmax
  %t415 = call ptr @scr_arr_retain_v(ptr %t414)
  %t416 = load double, ptr %sc_l_i_4
  %t417 = call double @scr_arr_get_f64(ptr %t415, double %t416)
  %t418 = fadd double %t413, %t417
  store double %t418, ptr @sc_g_e_checkSum
  call void @scr_arr_release(ptr %t415)
  br label %loop.u137
loop.u137:
  %t419 = load double, ptr %sc_l_i_4
  %t420 = fadd double %t419, 0x3FF0000000000000
  store double %t420, ptr %sc_l_i_4
  br label %loop.c134
loop.e136:
  %t421 = call ptr @scr_str_retain_v(ptr @sc_lit_38)
  %t422 = load double, ptr @sc_g_e_checkSum
  %t423 = call ptr @scr_str_retain_v(ptr @sc_lit_39)
  %t424 = load double, ptr @sc_g_e_checkSum
  %t425 = fsub double %t424, 0x3FF0000000000000
  %t426 = call double @llvm.fabs.f64(double %t425)
  %t427 = fcmp olt double %t426, 0x3DDB7CDFD9D7BDBB
  %t428 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t428
  %t429 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t421, ptr %t429
  %t430 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t430
  %t431 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t422, ptr %t431
  %t432 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 0
  store i32 1, ptr %t432
  %t433 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 1
  store ptr %t423, ptr %t433
  %t434 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 3, i32 0
  store i32 2, ptr %t434
  %t435 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 3, i32 1
  %t436 = zext i1 %t427 to i8
  store i8 %t436, ptr %t435
  call void @scr_console_log(i64 4, ptr %logargs)
  call void @scr_str_release(ptr %t421)
  call void @scr_str_release(ptr %t423)
  %t437 = call ptr @scr_str_retain_v(ptr @sc_lit_40)
  %t438 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t438
  %t439 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t437, ptr %t439
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t437)
  %t440 = call ptr @scr_str_retain_v(ptr @sc_lit_41)
  %t441 = call double @sc_f_rsqrt(double 0x4010000000000000)
  %t442 = call zeroext i1 @scr_exc_pending()
  br i1 %t442, label %exc.u138, label %exc.k139
exc.u138:
  call void @scr_str_release(ptr %t440)
  ret void
exc.k139:
  %t443 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t443
  %t444 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t440, ptr %t444
  %t445 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t445
  %t446 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t441, ptr %t446
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t440)
  %t447 = call ptr @scr_str_retain_v(ptr @sc_lit_42)
  %t448 = call double @sc_f_rsqrt(double 0x4050000000000000)
  %t449 = call zeroext i1 @scr_exc_pending()
  br i1 %t449, label %exc.u140, label %exc.k141
exc.u140:
  call void @scr_str_release(ptr %t447)
  ret void
exc.k141:
  %t450 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t450
  %t451 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t447, ptr %t451
  %t452 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t452
  %t453 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t448, ptr %t453
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t447)
  %t454 = call ptr @scr_str_retain_v(ptr @sc_lit_43)
  %t455 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t455
  %t456 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t454, ptr %t456
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t454)
  %t457 = call ptr @scr_arr_new(i32 0, i64 4)
  %t458 = call double @scr_arr_push_f64(ptr %t457, double 0x3FF0000000000000)
  %t459 = call double @scr_arr_push_f64(ptr %t457, double 0x4000000000000000)
  %t460 = call double @scr_arr_push_f64(ptr %t457, double 0x4008000000000000)
  %t461 = call double @scr_arr_push_f64(ptr %t457, double 0x4010000000000000)
  %t462 = load ptr, ptr @sc_g_e_x
  call void @scr_arr_release(ptr %t462)
  store ptr %t457, ptr @sc_g_e_x
  store double 0x3EB0C6F7A0B5ED8D, ptr @sc_g_e_eps
  store double 0x0000000000000000, ptr @sc_g_e_sumSq
  store double 0x0000000000000000, ptr %sc_l_i_5
  br label %loop.c142
loop.c142:
  %t463 = load double, ptr %sc_l_i_5
  %t464 = load ptr, ptr @sc_g_e_x
  %t465 = call ptr @scr_arr_retain_v(ptr %t464)
  %t466 = call double @scr_arr_len(ptr %t465)
  %t467 = fcmp olt double %t463, %t466
  call void @scr_arr_release(ptr %t465)
  br i1 %t467, label %loop.b143, label %loop.e144
loop.b143:
  %t468 = load double, ptr @sc_g_e_sumSq
  %t469 = load ptr, ptr @sc_g_e_x
  %t470 = call ptr @scr_arr_retain_v(ptr %t469)
  %t471 = load double, ptr %sc_l_i_5
  %t472 = call double @scr_arr_get_f64(ptr %t470, double %t471)
  %t473 = load ptr, ptr @sc_g_e_x
  %t474 = call ptr @scr_arr_retain_v(ptr %t473)
  %t475 = load double, ptr %sc_l_i_5
  %t476 = call double @scr_arr_get_f64(ptr %t474, double %t475)
  %t477 = fmul double %t472, %t476
  %t478 = fadd double %t468, %t477
  store double %t478, ptr @sc_g_e_sumSq
  call void @scr_arr_release(ptr %t470)
  call void @scr_arr_release(ptr %t474)
  br label %loop.u145
loop.u145:
  %t479 = load double, ptr %sc_l_i_5
  %t480 = fadd double %t479, 0x3FF0000000000000
  store double %t480, ptr %sc_l_i_5
  br label %loop.c142
loop.e144:
  %t481 = load double, ptr @sc_g_e_sumSq
  %t482 = load ptr, ptr @sc_g_e_x
  %t483 = call ptr @scr_arr_retain_v(ptr %t482)
  %t484 = call double @scr_arr_len(ptr %t483)
  %t485 = fdiv double %t481, %t484
  store double %t485, ptr @sc_g_e_meanSq
  call void @scr_arr_release(ptr %t483)
  %t486 = call ptr @scr_str_retain_v(ptr @sc_lit_44)
  %t487 = load double, ptr @sc_g_e_meanSq
  %t488 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t488
  %t489 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t486, ptr %t489
  %t490 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t490
  %t491 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t487, ptr %t491
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t486)
  %t492 = call ptr @scr_jsval_global_get(ptr @sc_lit_0)
  %t493 = call zeroext i1 @scr_exc_pending()
  br i1 %t493, label %exc.u146, label %exc.k147
exc.u146:
  call void @scr_jsval_release_v(ptr %t492)
  ret void
exc.k147:
  %t494 = load double, ptr @sc_g_e_meanSq
  %t495 = load double, ptr @sc_g_e_eps
  %t496 = fadd double %t494, %t495
  %t497 = call ptr @scr_jsval_from_f64(double %t496)
  %t499 = getelementptr inbounds [1 x ptr], ptr %s498, i64 0, i64 0
  store ptr %t497, ptr %t499
  %t500 = call ptr @scr_jsval_call_method(ptr %t492, ptr @sc_lit_1, i32 1, ptr %s498)
  %t501 = call zeroext i1 @scr_exc_pending()
  br i1 %t501, label %exc.u148, label %exc.k149
exc.u148:
  call void @scr_jsval_release_v(ptr %t492)
  call void @scr_jsval_release_v(ptr %t497)
  call void @scr_jsval_release_v(ptr %t500)
  ret void
exc.k149:
  store double 0x0000000000000000, ptr %s502
  %t503 = call i32 @scr_jsval_exit_f64(ptr %t500, ptr %s502)
  %t504 = call zeroext i1 @scr_exc_pending()
  br i1 %t504, label %exc.u150, label %exc.k151
exc.u150:
  call void @scr_jsval_release_v(ptr %t492)
  call void @scr_jsval_release_v(ptr %t497)
  call void @scr_jsval_release_v(ptr %t500)
  ret void
exc.k151:
  %t505 = load double, ptr %s502
  store double %t505, ptr @sc_g_e_rms
  call void @scr_jsval_release_v(ptr %t492)
  call void @scr_jsval_release_v(ptr %t497)
  call void @scr_jsval_release_v(ptr %t500)
  %t506 = call ptr @scr_str_retain_v(ptr @sc_lit_45)
  %t507 = load double, ptr @sc_g_e_rms
  %t508 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t508
  %t509 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t506, ptr %t509
  %t510 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t510
  %t511 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t507, ptr %t511
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t506)
  %t512 = call ptr @scr_arr_new(i32 0, i64 0)
  %t513 = load ptr, ptr @sc_g_e_normalized
  call void @scr_arr_release(ptr %t513)
  store ptr %t512, ptr @sc_g_e_normalized
  store double 0x0000000000000000, ptr %sc_l_i_6
  br label %loop.c152
loop.c152:
  %t514 = load double, ptr %sc_l_i_6
  %t515 = load ptr, ptr @sc_g_e_x
  %t516 = call ptr @scr_arr_retain_v(ptr %t515)
  %t517 = call double @scr_arr_len(ptr %t516)
  %t518 = fcmp olt double %t514, %t517
  call void @scr_arr_release(ptr %t516)
  br i1 %t518, label %loop.b153, label %loop.e154
loop.b153:
  %t519 = load ptr, ptr @sc_g_e_normalized
  %t520 = call ptr @scr_arr_retain_v(ptr %t519)
  %t521 = load ptr, ptr @sc_g_e_x
  %t522 = call ptr @scr_arr_retain_v(ptr %t521)
  %t523 = load double, ptr %sc_l_i_6
  %t524 = call double @scr_arr_get_f64(ptr %t522, double %t523)
  %t525 = load double, ptr @sc_g_e_rms
  %t526 = fdiv double %t524, %t525
  %t527 = call double @scr_arr_push_f64(ptr %t520, double %t526)
  call void @scr_arr_release(ptr %t520)
  call void @scr_arr_release(ptr %t522)
  br label %loop.u155
loop.u155:
  %t528 = load double, ptr %sc_l_i_6
  %t529 = fadd double %t528, 0x3FF0000000000000
  store double %t529, ptr %sc_l_i_6
  br label %loop.c152
loop.e154:
  %t530 = call ptr @scr_str_retain_v(ptr @sc_lit_46)
  %t531 = load ptr, ptr @sc_g_e_normalized
  %t532 = call ptr @scr_arr_retain_v(ptr %t531)
  %t533 = call ptr @sc_f__x25_util_insp_0(ptr %t532, double 0x0000000000000000, double 0x4000000000000000)
  %t534 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t534
  %t535 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t530, ptr %t535
  %t536 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t536
  %t537 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t533, ptr %t537
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t530)
  call void @scr_str_release(ptr %t533)
  %t538 = call ptr @scr_str_retain_v(ptr @sc_lit_47)
  %t539 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t539
  %t540 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t538, ptr %t540
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t538)
  ret void
}

define internal void @sc_f__x25_main() #0 { ; %main
entry:
  call void @sc_f__x25_init_0()
  %t0 = call zeroext i1 @scr_exc_pending()
  br i1 %t0, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  ret void
}

define internal ptr @sc_f__x25_util_insp_0(ptr %p_sc_l_v_0, double %p_sc_l_r_0, double %p_sc_l_d_0) #0 { ; %util.insp.0
entry:
  %sc_l_v_0 = alloca ptr ; v
  %sc_l_r_0 = alloca double ; r
  %sc_l_d_0 = alloca double ; d
  %sc_l_n_0 = alloca double ; n
  %sc_l_s_0 = alloca double ; s
  %sc_l_i_0 = alloca double ; i
  %s14 = alloca double
  store ptr %p_sc_l_v_0, ptr %sc_l_v_0
  store double %p_sc_l_r_0, ptr %sc_l_r_0
  store double %p_sc_l_d_0, ptr %sc_l_d_0
  %t0 = load ptr, ptr %sc_l_v_0
  %t1 = call ptr @scr_arr_retain_v(ptr %t0)
  %t2 = call double @scr_arr_len(ptr %t1)
  store double %t2, ptr %sc_l_n_0
  call void @scr_arr_release(ptr %t1)
  %t3 = load double, ptr %sc_l_n_0
  %t4 = fcmp oeq double %t3, 0x0000000000000000
  br i1 %t4, label %if.t0, label %if.j1
if.t0:
  %t5 = call ptr @scr_str_retain_v(ptr @sc_lit_48)
  %t6 = load ptr, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t6)
  ret ptr %t5
if.j1:
  %t7 = load double, ptr %sc_l_r_0
  %t8 = load double, ptr %sc_l_d_0
  %t9 = fcmp ogt double %t7, %t8
  br i1 %t9, label %if.t2, label %if.j3
if.t2:
  %t10 = call ptr @scr_str_retain_v(ptr @sc_lit_49)
  %t11 = load ptr, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t11)
  ret ptr %t10
if.j3:
  %t12 = load double, ptr %sc_l_n_0
  %t13 = fcmp ogt double %t12, 0x4059000000000000
  br i1 %t13, label %tern.t4, label %tern.f5
tern.t4:
  store double 0x4059000000000000, ptr %s14
  br label %tern.j6
tern.f5:
  %t15 = load double, ptr %sc_l_n_0
  store double %t15, ptr %s14
  br label %tern.j6
tern.j6:
  %t16 = load double, ptr %s14
  store double %t16, ptr %sc_l_s_0
  %t17 = load double, ptr %sc_l_r_0
  %t18 = fadd double %t17, 0x3FF0000000000000
  call void @scr_insp_begin(double %t18)
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c7
loop.c7:
  %t19 = load double, ptr %sc_l_i_0
  %t20 = load double, ptr %sc_l_s_0
  %t21 = fcmp olt double %t19, %t20
  br i1 %t21, label %loop.b8, label %loop.e9
loop.b8:
  %t22 = load ptr, ptr %sc_l_v_0
  %t23 = call ptr @scr_arr_retain_v(ptr %t22)
  %t24 = load double, ptr %sc_l_i_0
  %t25 = call double @scr_arr_get_f64(ptr %t23, double %t24)
  %t26 = call ptr @scr_insp_f64(double %t25)
  call void @scr_insp_entry(ptr %t26, i1 true)
  call void @scr_arr_release(ptr %t23)
  call void @scr_str_release(ptr %t26)
  br label %loop.u10
loop.u10:
  %t27 = load double, ptr %sc_l_i_0
  %t28 = fadd double %t27, 0x3FF0000000000000
  store double %t28, ptr %sc_l_i_0
  br label %loop.c7
loop.e9:
  %t29 = load double, ptr %sc_l_n_0
  %t30 = fcmp ogt double %t29, 0x4059000000000000
  br i1 %t30, label %if.t11, label %if.j12
if.t11:
  %t31 = load double, ptr %sc_l_n_0
  %t32 = fsub double %t31, 0x4059000000000000
  %t33 = call ptr @scr_insp_more_items(double %t32)
  call void @scr_insp_entry(ptr %t33, i1 true)
  call void @scr_str_release(ptr %t33)
  br label %if.j12
if.j12:
  %t34 = call ptr @scr_str_retain_v(ptr @sc_lit_50)
  %t35 = call ptr @scr_str_retain_v(ptr @sc_lit_51)
  %t36 = call ptr @scr_str_retain_v(ptr @sc_lit_52)
  %t37 = load double, ptr %sc_l_r_0
  %t38 = fadd double %t37, 0x3FF0000000000000
  %t39 = load double, ptr %sc_l_n_0
  %t40 = fcmp ogt double %t39, 0x4059000000000000
  %t41 = call ptr @scr_insp_end(ptr %t34, ptr %t35, ptr %t36, double %t38, i1 true, i1 %t40)
  call void @scr_str_release(ptr %t34)
  call void @scr_str_release(ptr %t35)
  call void @scr_str_release(ptr %t36)
  %t42 = load ptr, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t42)
  ret ptr %t41
}

declare void @scr_exc_print_uncaught()

define i32 @main(i32 %argc, ptr %argv) #0 {
entry:
  call void @scr_init()
  store i64 0, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 1) ; Error
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 0)
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 1) ; TypeError
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 0)
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 1) ; RangeError
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 0)
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 1) ; SyntaxError
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 1) ; DOMException
  call void @scr_lib_init(i32 %argc, ptr %argv)
  call void @sc_f__x25_main()
  %exc = call zeroext i1 @scr_exc_pending()
  br i1 %exc, label %uncaught, label %ok
uncaught:
  call void @scr_exc_print_uncaught()
  %gu0 = load ptr, ptr @sc_g_e_logits
  call void @scr_arr_release(ptr %gu0) ; logits
  %gu2 = load ptr, ptr @sc_g_e_exps
  call void @scr_arr_release(ptr %gu2) ; exps
  %gu4 = load ptr, ptr @sc_g_e_softmax
  call void @scr_arr_release(ptr %gu4) ; softmax
  %gu6 = load ptr, ptr @sc_g_e_x
  call void @scr_arr_release(ptr %gu6) ; x
  %gu11 = load ptr, ptr @sc_g_e_normalized
  call void @scr_arr_release(ptr %gu11) ; normalized
  ret i32 1
ok:
  %g0 = load ptr, ptr @sc_g_e_logits
  call void @scr_arr_release(ptr %g0) ; logits
  %g2 = load ptr, ptr @sc_g_e_exps
  call void @scr_arr_release(ptr %g2) ; exps
  %g4 = load ptr, ptr @sc_g_e_softmax
  call void @scr_arr_release(ptr %g4) ; softmax
  %g6 = load ptr, ptr @sc_g_e_x
  call void @scr_arr_release(ptr %g6) ; x
  %g11 = load ptr, ptr @sc_g_e_normalized
  call void @scr_arr_release(ptr %g11) ; normalized
  ret i32 0
}

attributes #0 = { sanitize_address }
