; Generated by scriptc (LLVM backend) from /Users/sam/Dev/llama.scriptc/examples/phase0/perf.ts. Do not edit.

%ScrStr = type { i64, i64, i64 }
%ScrLogArg = type { i32, i64 }
%ScrVt = type { i64, i64, ptr }
%ScrUnion = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrClosure = type { i64, ptr, i64, ptr }
%ScrRegex = type { i64, ptr, ptr, ptr }
%ScrArr = type { i64, i64, i64, i32, ptr, ptr, ptr, ptr }
%ScrError = type { i64, ptr, ptr, ptr, ptr }
%ScrClassObj = type { i64, i64, i64, ptr, ptr }
%ScrEmitter = type { i64, ptr, ptr, ptr }
%ScrStream = type { i64, ptr, ptr, ptr, ptr }
%ScrCaught = type { i64, i32, double, i8, ptr, ptr, ptr, ptr }
%ScrBytes = type { i64, i64, i32, ptr, ptr }
%ScrBox = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrJsonBuf = type { ptr, i64, i64, ptr, i64, i64 }
%ScrDynPath = type { ptr, ptr, i64 }
%ScrIslandModule = type { ptr, ptr, i64, i64, i32, ptr, i64, i64 }
%ScrIslandEdge = type { ptr, ptr, ptr, i32 }

@scr_error_vts = external global [5 x %ScrVt]
declare void @scr_init()
declare void @scr_lib_init(i32, ptr)
declare ptr @scr_arr_new(i32, i64)
declare ptr @scr_arr_retain_v(ptr)
declare void @scr_arr_release_v(ptr)
declare double @scr_arr_push_f64(ptr, double)
declare void @scr_arr_release(ptr)
declare double @scr_arr_push_ref(ptr, ptr)
declare double @scr_date_now()
declare ptr @scr_arr_get_ref(ptr, double)
declare double @scr_arr_get_f64(ptr, double)
declare ptr @scr_str_retain_v(ptr)
declare void @scr_str_release_v(ptr)
declare void @scr_console_log(i64, ptr)
declare void @scr_str_release(ptr)
declare double @scr_arr_len(ptr)
declare ptr @scr_f64_to_scrstr(double)
declare ptr @scr_str_concat(ptr, ptr)
declare ptr @scr_num_to_fixed(double, double)
declare zeroext i1 @scr_exc_pending()
declare double @scr_math_max(double, double)
declare double @scr_math_round(double)

@sc_lit_0 = internal global { i64, i64, i64, [32 x i8] } { i64 -1, i64 31, i64 31, [32 x i8] c"--- Performance measurement ---\00" }
@sc_lit_1 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"matmul \00" }
@sc_lit_2 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"x\00" }
@sc_lit_3 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c": \00" }
@sc_lit_4 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"ms (\00" }
@sc_lit_5 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c" GFLOPS)\00" }
@sc_lit_6 = internal global { i64, i64, i64, [26 x i8] } { i64 -1, i64 25, i64 25, [26 x i8] c"\0A--- Loop performance ---\00" }
@sc_lit_7 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c" iterations: \00" }
@sc_lit_8 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"ms, result: \00" }
@sc_lit_9 = internal global { i64, i64, i64, [16 x i8] } { i64 -1, i64 15, i64 15, [16 x i8] c"iterations/ms: \00" }
@sc_lit_10 = internal global { i64, i64, i64, [32 x i8] } { i64 -1, i64 31, i64 31, [32 x i8] c"\0A--- Array fill performance ---\00" }
@sc_lit_11 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"Fill \00" }
@sc_lit_12 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c" elements: \00" }
@sc_lit_13 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"ms\00" }
@sc_lit_14 = internal global { i64, i64, i64, [20 x i8] } { i64 -1, i64 19, i64 19, [20 x i8] c"\0A\E2\9C\85 perf.ts passed\00" }

@sc_g_e_sizes = internal global ptr null ; sizes
@sc_g_e_loopSize = internal global double 0x0000000000000000 ; loopSize
@sc_g_e_startLoop = internal global double 0x0000000000000000 ; startLoop
@sc_g_e_acc = internal global double 0x0000000000000000 ; acc
@sc_g_e_loopTime = internal global double 0x0000000000000000 ; loopTime
@sc_g_e_fillSize = internal global double 0x0000000000000000 ; fillSize
@sc_g_e_startFill = internal global double 0x0000000000000000 ; startFill
@sc_g_e_fillArr = internal global ptr null ; fillArr
@sc_g_e_fillTime = internal global double 0x0000000000000000 ; fillTime
@sc_g_e__x25_loaded = internal global i1 false ; %loaded

define internal double @sc_f_benchMatmulNaive(double %p_sc_l_n_0) #0 { ; benchMatmulNaive
entry:
  %sc_l_n_0 = alloca double ; n
  %sc_l_a_0 = alloca ptr ; a
  %sc_l_b_0 = alloca ptr ; b
  %sc_l_i_0 = alloca double ; i
  %sc_l_rowA_0 = alloca ptr ; rowA
  %sc_l_rowB_0 = alloca ptr ; rowB
  %sc_l_j_0 = alloca double ; j
  %sc_l_start_0 = alloca double ; start
  %sc_l_c_0 = alloca ptr ; c
  %sc_l_i_1 = alloca double ; i
  %sc_l_row_0 = alloca ptr ; row
  %sc_l_j_1 = alloca double ; j
  %sc_l_sum_0 = alloca double ; sum
  %sc_l_k_0 = alloca double ; k
  %sc_l_elapsed_0 = alloca double ; elapsed
  store ptr null, ptr %sc_l_a_0
  store ptr null, ptr %sc_l_b_0
  store ptr null, ptr %sc_l_rowA_0
  store ptr null, ptr %sc_l_rowB_0
  store ptr null, ptr %sc_l_c_0
  store ptr null, ptr %sc_l_row_0
  store double %p_sc_l_n_0, ptr %sc_l_n_0
  %t0 = call ptr @scr_arr_new(i32 3, i64 0)
  store ptr %t0, ptr %sc_l_a_0
  %t1 = call ptr @scr_arr_new(i32 3, i64 0)
  store ptr %t1, ptr %sc_l_b_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c0
loop.c0:
  %t2 = load double, ptr %sc_l_i_0
  %t3 = load double, ptr %sc_l_n_0
  %t4 = fcmp olt double %t2, %t3
  br i1 %t4, label %loop.b1, label %loop.e2
loop.b1:
  %t5 = call ptr @scr_arr_new(i32 0, i64 0)
  store ptr %t5, ptr %sc_l_rowA_0
  %t6 = call ptr @scr_arr_new(i32 0, i64 0)
  store ptr %t6, ptr %sc_l_rowB_0
  store double 0x0000000000000000, ptr %sc_l_j_0
  br label %loop.c4
loop.c4:
  %t7 = load double, ptr %sc_l_j_0
  %t8 = load double, ptr %sc_l_n_0
  %t9 = fcmp olt double %t7, %t8
  br i1 %t9, label %loop.b5, label %loop.e6
loop.b5:
  %t10 = load ptr, ptr %sc_l_rowA_0
  %t11 = call ptr @scr_arr_retain_v(ptr %t10)
  %t12 = load double, ptr %sc_l_i_0
  %t13 = load double, ptr %sc_l_n_0
  %t14 = fmul double %t12, %t13
  %t15 = load double, ptr %sc_l_j_0
  %t16 = fadd double %t14, %t15
  %t17 = call double @scr_arr_push_f64(ptr %t11, double %t16)
  call void @scr_arr_release(ptr %t11)
  %t18 = load ptr, ptr %sc_l_rowB_0
  %t19 = call ptr @scr_arr_retain_v(ptr %t18)
  %t20 = load double, ptr %sc_l_j_0
  %t21 = load double, ptr %sc_l_n_0
  %t22 = fmul double %t20, %t21
  %t23 = load double, ptr %sc_l_i_0
  %t24 = fadd double %t22, %t23
  %t25 = call double @scr_arr_push_f64(ptr %t19, double %t24)
  call void @scr_arr_release(ptr %t19)
  br label %loop.u7
loop.u7:
  %t26 = load double, ptr %sc_l_j_0
  %t27 = fadd double %t26, 0x3FF0000000000000
  store double %t27, ptr %sc_l_j_0
  br label %loop.c4
loop.e6:
  %t28 = load ptr, ptr %sc_l_a_0
  %t29 = call ptr @scr_arr_retain_v(ptr %t28)
  %t30 = load ptr, ptr %sc_l_rowA_0
  %t31 = call ptr @scr_arr_retain_v(ptr %t30)
  %t32 = call double @scr_arr_push_ref(ptr %t29, ptr %t31)
  call void @scr_arr_release(ptr %t29)
  %t33 = load ptr, ptr %sc_l_b_0
  %t34 = call ptr @scr_arr_retain_v(ptr %t33)
  %t35 = load ptr, ptr %sc_l_rowB_0
  %t36 = call ptr @scr_arr_retain_v(ptr %t35)
  %t37 = call double @scr_arr_push_ref(ptr %t34, ptr %t36)
  call void @scr_arr_release(ptr %t34)
  %t38 = load ptr, ptr %sc_l_rowA_0
  call void @scr_arr_release(ptr %t38)
  %t39 = load ptr, ptr %sc_l_rowB_0
  call void @scr_arr_release(ptr %t39)
  br label %loop.u3
loop.u3:
  %t40 = load double, ptr %sc_l_i_0
  %t41 = fadd double %t40, 0x3FF0000000000000
  store double %t41, ptr %sc_l_i_0
  br label %loop.c0
loop.e2:
  %t42 = call double @scr_date_now()
  store double %t42, ptr %sc_l_start_0
  %t43 = call ptr @scr_arr_new(i32 3, i64 0)
  store ptr %t43, ptr %sc_l_c_0
  store double 0x0000000000000000, ptr %sc_l_i_1
  br label %loop.c8
loop.c8:
  %t44 = load double, ptr %sc_l_i_1
  %t45 = load double, ptr %sc_l_n_0
  %t46 = fcmp olt double %t44, %t45
  br i1 %t46, label %loop.b9, label %loop.e10
loop.b9:
  %t47 = call ptr @scr_arr_new(i32 0, i64 0)
  store ptr %t47, ptr %sc_l_row_0
  store double 0x0000000000000000, ptr %sc_l_j_1
  br label %loop.c12
loop.c12:
  %t48 = load double, ptr %sc_l_j_1
  %t49 = load double, ptr %sc_l_n_0
  %t50 = fcmp olt double %t48, %t49
  br i1 %t50, label %loop.b13, label %loop.e14
loop.b13:
  store double 0x0000000000000000, ptr %sc_l_sum_0
  store double 0x0000000000000000, ptr %sc_l_k_0
  br label %loop.c16
loop.c16:
  %t51 = load double, ptr %sc_l_k_0
  %t52 = load double, ptr %sc_l_n_0
  %t53 = fcmp olt double %t51, %t52
  br i1 %t53, label %loop.b17, label %loop.e18
loop.b17:
  %t54 = load double, ptr %sc_l_sum_0
  %t55 = load ptr, ptr %sc_l_a_0
  %t56 = call ptr @scr_arr_retain_v(ptr %t55)
  %t57 = load double, ptr %sc_l_i_1
  %t58 = call ptr @scr_arr_get_ref(ptr %t56, double %t57)
  %t59 = load double, ptr %sc_l_k_0
  %t60 = call double @scr_arr_get_f64(ptr %t58, double %t59)
  %t61 = load ptr, ptr %sc_l_b_0
  %t62 = call ptr @scr_arr_retain_v(ptr %t61)
  %t63 = load double, ptr %sc_l_k_0
  %t64 = call ptr @scr_arr_get_ref(ptr %t62, double %t63)
  %t65 = load double, ptr %sc_l_j_1
  %t66 = call double @scr_arr_get_f64(ptr %t64, double %t65)
  %t67 = fmul double %t60, %t66
  %t68 = fadd double %t54, %t67
  store double %t68, ptr %sc_l_sum_0
  call void @scr_arr_release(ptr %t56)
  call void @scr_arr_release(ptr %t58)
  call void @scr_arr_release(ptr %t62)
  call void @scr_arr_release(ptr %t64)
  br label %loop.u19
loop.u19:
  %t69 = load double, ptr %sc_l_k_0
  %t70 = fadd double %t69, 0x3FF0000000000000
  store double %t70, ptr %sc_l_k_0
  br label %loop.c16
loop.e18:
  %t71 = load ptr, ptr %sc_l_row_0
  %t72 = call ptr @scr_arr_retain_v(ptr %t71)
  %t73 = load double, ptr %sc_l_sum_0
  %t74 = call double @scr_arr_push_f64(ptr %t72, double %t73)
  call void @scr_arr_release(ptr %t72)
  br label %loop.u15
loop.u15:
  %t75 = load double, ptr %sc_l_j_1
  %t76 = fadd double %t75, 0x3FF0000000000000
  store double %t76, ptr %sc_l_j_1
  br label %loop.c12
loop.e14:
  %t77 = load ptr, ptr %sc_l_c_0
  %t78 = call ptr @scr_arr_retain_v(ptr %t77)
  %t79 = load ptr, ptr %sc_l_row_0
  %t80 = call ptr @scr_arr_retain_v(ptr %t79)
  %t81 = call double @scr_arr_push_ref(ptr %t78, ptr %t80)
  call void @scr_arr_release(ptr %t78)
  %t82 = load ptr, ptr %sc_l_row_0
  call void @scr_arr_release(ptr %t82)
  br label %loop.u11
loop.u11:
  %t83 = load double, ptr %sc_l_i_1
  %t84 = fadd double %t83, 0x3FF0000000000000
  store double %t84, ptr %sc_l_i_1
  br label %loop.c8
loop.e10:
  %t85 = call double @scr_date_now()
  %t86 = load double, ptr %sc_l_start_0
  %t87 = fsub double %t85, %t86
  store double %t87, ptr %sc_l_elapsed_0
  %t88 = load double, ptr %sc_l_elapsed_0
  %t89 = load ptr, ptr %sc_l_a_0
  call void @scr_arr_release(ptr %t89)
  %t90 = load ptr, ptr %sc_l_b_0
  call void @scr_arr_release(ptr %t90)
  %t91 = load ptr, ptr %sc_l_c_0
  call void @scr_arr_release(ptr %t91)
  ret double %t88
}

define internal void @sc_f__x25_init_0() #0 { ; %init.0
entry:
  %sc_l_si_0 = alloca double ; si
  %sc_l_n_0 = alloca double ; n
  %sc_l_ms_0 = alloca double ; ms
  %sc_l_flops_0 = alloca double ; flops
  %sc_l_gflops_0 = alloca double ; gflops
  %sc_l_i_0 = alloca double ; i
  %sc_l_i_1 = alloca double ; i
  %s30 = alloca double
  %logargs = alloca [1 x %ScrLogArg]
  %t0 = load i1, ptr @sc_g_e__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_e__x25_loaded
  %t1 = call ptr @scr_str_retain_v(ptr @sc_lit_0)
  %t2 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t2
  %t3 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t1, ptr %t3
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t1)
  %t4 = call double @sc_f_benchMatmulNaive(double 0x4040000000000000)
  %t5 = call ptr @scr_arr_new(i32 0, i64 4)
  %t6 = call double @scr_arr_push_f64(ptr %t5, double 0x4040000000000000)
  %t7 = call double @scr_arr_push_f64(ptr %t5, double 0x4050000000000000)
  %t8 = call double @scr_arr_push_f64(ptr %t5, double 0x4060000000000000)
  %t9 = call double @scr_arr_push_f64(ptr %t5, double 0x4070000000000000)
  %t10 = load ptr, ptr @sc_g_e_sizes
  call void @scr_arr_release(ptr %t10)
  store ptr %t5, ptr @sc_g_e_sizes
  store double 0x0000000000000000, ptr %sc_l_si_0
  br label %loop.c2
loop.c2:
  %t11 = load double, ptr %sc_l_si_0
  %t12 = load ptr, ptr @sc_g_e_sizes
  %t13 = call ptr @scr_arr_retain_v(ptr %t12)
  %t14 = call double @scr_arr_len(ptr %t13)
  %t15 = fcmp olt double %t11, %t14
  call void @scr_arr_release(ptr %t13)
  br i1 %t15, label %loop.b3, label %loop.e4
loop.b3:
  %t16 = load ptr, ptr @sc_g_e_sizes
  %t17 = call ptr @scr_arr_retain_v(ptr %t16)
  %t18 = load double, ptr %sc_l_si_0
  %t19 = call double @scr_arr_get_f64(ptr %t17, double %t18)
  store double %t19, ptr %sc_l_n_0
  call void @scr_arr_release(ptr %t17)
  %t20 = load double, ptr %sc_l_n_0
  %t21 = call double @sc_f_benchMatmulNaive(double %t20)
  store double %t21, ptr %sc_l_ms_0
  %t22 = load double, ptr %sc_l_n_0
  %t23 = fmul double 0x4000000000000000, %t22
  %t24 = load double, ptr %sc_l_n_0
  %t25 = fmul double %t23, %t24
  %t26 = load double, ptr %sc_l_n_0
  %t27 = fmul double %t25, %t26
  store double %t27, ptr %sc_l_flops_0
  %t28 = load double, ptr %sc_l_ms_0
  %t29 = fcmp ogt double %t28, 0x0000000000000000
  br i1 %t29, label %tern.t6, label %tern.f7
tern.t6:
  %t31 = load double, ptr %sc_l_flops_0
  %t32 = load double, ptr %sc_l_ms_0
  %t33 = fdiv double %t32, 0x408F400000000000
  %t34 = fdiv double %t31, %t33
  %t35 = fdiv double %t34, 0x41CDCD6500000000
  store double %t35, ptr %s30
  br label %tern.j8
tern.f7:
  store double 0x0000000000000000, ptr %s30
  br label %tern.j8
tern.j8:
  %t36 = load double, ptr %s30
  store double %t36, ptr %sc_l_gflops_0
  %t37 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t38 = load double, ptr %sc_l_n_0
  %t39 = call ptr @scr_f64_to_scrstr(double %t38)
  %t40 = call ptr @scr_str_concat(ptr %t37, ptr %t39)
  %t41 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  %t42 = call ptr @scr_str_concat(ptr %t40, ptr %t41)
  %t43 = load double, ptr %sc_l_n_0
  %t44 = call ptr @scr_f64_to_scrstr(double %t43)
  %t45 = call ptr @scr_str_concat(ptr %t42, ptr %t44)
  %t46 = call ptr @scr_str_retain_v(ptr @sc_lit_3)
  %t47 = call ptr @scr_str_concat(ptr %t45, ptr %t46)
  %t48 = load double, ptr %sc_l_ms_0
  %t49 = call ptr @scr_f64_to_scrstr(double %t48)
  %t50 = call ptr @scr_str_concat(ptr %t47, ptr %t49)
  %t51 = call ptr @scr_str_retain_v(ptr @sc_lit_4)
  %t52 = call ptr @scr_str_concat(ptr %t50, ptr %t51)
  %t53 = load double, ptr %sc_l_gflops_0
  %t54 = call ptr @scr_num_to_fixed(double %t53, double 0x4000000000000000)
  %t55 = call zeroext i1 @scr_exc_pending()
  br i1 %t55, label %exc.u9, label %exc.k10
exc.u9:
  call void @scr_str_release(ptr %t37)
  call void @scr_str_release(ptr %t39)
  call void @scr_str_release(ptr %t40)
  call void @scr_str_release(ptr %t41)
  call void @scr_str_release(ptr %t42)
  call void @scr_str_release(ptr %t44)
  call void @scr_str_release(ptr %t45)
  call void @scr_str_release(ptr %t46)
  call void @scr_str_release(ptr %t47)
  call void @scr_str_release(ptr %t49)
  call void @scr_str_release(ptr %t50)
  call void @scr_str_release(ptr %t51)
  call void @scr_str_release(ptr %t52)
  call void @scr_str_release(ptr %t54)
  ret void
exc.k10:
  %t56 = call ptr @scr_str_concat(ptr %t52, ptr %t54)
  %t57 = call ptr @scr_str_retain_v(ptr @sc_lit_5)
  %t58 = call ptr @scr_str_concat(ptr %t56, ptr %t57)
  %t59 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t59
  %t60 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t58, ptr %t60
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t37)
  call void @scr_str_release(ptr %t39)
  call void @scr_str_release(ptr %t40)
  call void @scr_str_release(ptr %t41)
  call void @scr_str_release(ptr %t42)
  call void @scr_str_release(ptr %t44)
  call void @scr_str_release(ptr %t45)
  call void @scr_str_release(ptr %t46)
  call void @scr_str_release(ptr %t47)
  call void @scr_str_release(ptr %t49)
  call void @scr_str_release(ptr %t50)
  call void @scr_str_release(ptr %t51)
  call void @scr_str_release(ptr %t52)
  call void @scr_str_release(ptr %t54)
  call void @scr_str_release(ptr %t56)
  call void @scr_str_release(ptr %t57)
  call void @scr_str_release(ptr %t58)
  br label %loop.u5
loop.u5:
  %t61 = load double, ptr %sc_l_si_0
  %t62 = fadd double %t61, 0x3FF0000000000000
  store double %t62, ptr %sc_l_si_0
  br label %loop.c2
loop.e4:
  %t63 = call ptr @scr_str_retain_v(ptr @sc_lit_6)
  %t64 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t64
  %t65 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t63, ptr %t65
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t63)
  store double 0x416312D000000000, ptr @sc_g_e_loopSize
  %t66 = call double @scr_date_now()
  store double %t66, ptr @sc_g_e_startLoop
  store double 0x0000000000000000, ptr @sc_g_e_acc
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c11
loop.c11:
  %t67 = load double, ptr %sc_l_i_0
  %t68 = load double, ptr @sc_g_e_loopSize
  %t69 = fcmp olt double %t67, %t68
  br i1 %t69, label %loop.b12, label %loop.e13
loop.b12:
  %t70 = load double, ptr @sc_g_e_acc
  %t71 = load double, ptr %sc_l_i_0
  %t72 = fadd double %t70, %t71
  store double %t72, ptr @sc_g_e_acc
  br label %loop.u14
loop.u14:
  %t73 = load double, ptr %sc_l_i_0
  %t74 = fadd double %t73, 0x3FF0000000000000
  store double %t74, ptr %sc_l_i_0
  br label %loop.c11
loop.e13:
  %t75 = call double @scr_date_now()
  %t76 = load double, ptr @sc_g_e_startLoop
  %t77 = fsub double %t75, %t76
  store double %t77, ptr @sc_g_e_loopTime
  %t78 = load double, ptr @sc_g_e_loopSize
  %t79 = call ptr @scr_f64_to_scrstr(double %t78)
  %t80 = call ptr @scr_str_retain_v(ptr @sc_lit_7)
  %t81 = call ptr @scr_str_concat(ptr %t79, ptr %t80)
  %t82 = load double, ptr @sc_g_e_loopTime
  %t83 = call ptr @scr_f64_to_scrstr(double %t82)
  %t84 = call ptr @scr_str_concat(ptr %t81, ptr %t83)
  %t85 = call ptr @scr_str_retain_v(ptr @sc_lit_8)
  %t86 = call ptr @scr_str_concat(ptr %t84, ptr %t85)
  %t87 = load double, ptr @sc_g_e_acc
  %t88 = call ptr @scr_f64_to_scrstr(double %t87)
  %t89 = call ptr @scr_str_concat(ptr %t86, ptr %t88)
  %t90 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t90
  %t91 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t89, ptr %t91
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t79)
  call void @scr_str_release(ptr %t80)
  call void @scr_str_release(ptr %t81)
  call void @scr_str_release(ptr %t83)
  call void @scr_str_release(ptr %t84)
  call void @scr_str_release(ptr %t85)
  call void @scr_str_release(ptr %t86)
  call void @scr_str_release(ptr %t88)
  call void @scr_str_release(ptr %t89)
  %t92 = call ptr @scr_str_retain_v(ptr @sc_lit_9)
  %t93 = load double, ptr @sc_g_e_loopSize
  %t94 = load double, ptr @sc_g_e_loopTime
  %t95 = call double @scr_math_max(double %t94, double 0x3FF0000000000000)
  %t96 = fdiv double %t93, %t95
  %t97 = call double @scr_math_round(double %t96)
  %t98 = call ptr @scr_f64_to_scrstr(double %t97)
  %t99 = call ptr @scr_str_concat(ptr %t92, ptr %t98)
  %t100 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t100
  %t101 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t99, ptr %t101
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t92)
  call void @scr_str_release(ptr %t98)
  call void @scr_str_release(ptr %t99)
  %t102 = call ptr @scr_str_retain_v(ptr @sc_lit_10)
  %t103 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t103
  %t104 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t102, ptr %t104
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t102)
  store double 0x412E848000000000, ptr @sc_g_e_fillSize
  %t105 = call double @scr_date_now()
  store double %t105, ptr @sc_g_e_startFill
  %t106 = call ptr @scr_arr_new(i32 0, i64 0)
  %t107 = load ptr, ptr @sc_g_e_fillArr
  call void @scr_arr_release(ptr %t107)
  store ptr %t106, ptr @sc_g_e_fillArr
  store double 0x0000000000000000, ptr %sc_l_i_1
  br label %loop.c15
loop.c15:
  %t108 = load double, ptr %sc_l_i_1
  %t109 = load double, ptr @sc_g_e_fillSize
  %t110 = fcmp olt double %t108, %t109
  br i1 %t110, label %loop.b16, label %loop.e17
loop.b16:
  %t111 = load ptr, ptr @sc_g_e_fillArr
  %t112 = call ptr @scr_arr_retain_v(ptr %t111)
  %t113 = call double @scr_arr_push_f64(ptr %t112, double 0x0000000000000000)
  call void @scr_arr_release(ptr %t112)
  br label %loop.u18
loop.u18:
  %t114 = load double, ptr %sc_l_i_1
  %t115 = fadd double %t114, 0x3FF0000000000000
  store double %t115, ptr %sc_l_i_1
  br label %loop.c15
loop.e17:
  %t116 = call double @scr_date_now()
  %t117 = load double, ptr @sc_g_e_startFill
  %t118 = fsub double %t116, %t117
  store double %t118, ptr @sc_g_e_fillTime
  %t119 = call ptr @scr_str_retain_v(ptr @sc_lit_11)
  %t120 = load double, ptr @sc_g_e_fillSize
  %t121 = call ptr @scr_f64_to_scrstr(double %t120)
  %t122 = call ptr @scr_str_concat(ptr %t119, ptr %t121)
  %t123 = call ptr @scr_str_retain_v(ptr @sc_lit_12)
  %t124 = call ptr @scr_str_concat(ptr %t122, ptr %t123)
  %t125 = load double, ptr @sc_g_e_fillTime
  %t126 = call ptr @scr_f64_to_scrstr(double %t125)
  %t127 = call ptr @scr_str_concat(ptr %t124, ptr %t126)
  %t128 = call ptr @scr_str_retain_v(ptr @sc_lit_13)
  %t129 = call ptr @scr_str_concat(ptr %t127, ptr %t128)
  %t130 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t130
  %t131 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t129, ptr %t131
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t119)
  call void @scr_str_release(ptr %t121)
  call void @scr_str_release(ptr %t122)
  call void @scr_str_release(ptr %t123)
  call void @scr_str_release(ptr %t124)
  call void @scr_str_release(ptr %t126)
  call void @scr_str_release(ptr %t127)
  call void @scr_str_release(ptr %t128)
  call void @scr_str_release(ptr %t129)
  %t132 = call ptr @scr_str_retain_v(ptr @sc_lit_14)
  %t133 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t133
  %t134 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t132, ptr %t134
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t132)
  ret void
}

define internal void @sc_f__x25_main() #0 { ; %main
entry:
  call void @sc_f__x25_init_0()
  %t0 = call zeroext i1 @scr_exc_pending()
  br i1 %t0, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  ret void
}

declare void @scr_exc_print_uncaught()

define i32 @main(i32 %argc, ptr %argv) #0 {
entry:
  call void @scr_init()
  store i64 0, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 1) ; Error
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 0)
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 1) ; TypeError
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 0)
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 1) ; RangeError
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 0)
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 1) ; SyntaxError
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 1) ; DOMException
  call void @scr_lib_init(i32 %argc, ptr %argv)
  call void @sc_f__x25_main()
  %exc = call zeroext i1 @scr_exc_pending()
  br i1 %exc, label %uncaught, label %ok
uncaught:
  call void @scr_exc_print_uncaught()
  %gu0 = load ptr, ptr @sc_g_e_sizes
  call void @scr_arr_release(ptr %gu0) ; sizes
  %gu7 = load ptr, ptr @sc_g_e_fillArr
  call void @scr_arr_release(ptr %gu7) ; fillArr
  ret i32 1
ok:
  %g0 = load ptr, ptr @sc_g_e_sizes
  call void @scr_arr_release(ptr %g0) ; sizes
  %g7 = load ptr, ptr @sc_g_e_fillArr
  call void @scr_arr_release(ptr %g7) ; fillArr
  ret i32 0
}

attributes #0 = { sanitize_address }
