; Generated by scriptc (LLVM backend) from /Users/sam/Dev/llama.scriptc/examples/phase0/types.ts. Do not edit.

%ScrStr = type { i64, i64, i64 }
%ScrLogArg = type { i32, i64 }
%ScrVt = type { i64, i64, ptr }
%ScrUnion = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrClosure = type { i64, ptr, i64, ptr }
%ScrRegex = type { i64, ptr, ptr, ptr }
%ScrArr = type { i64, i64, i64, i32, ptr, ptr, ptr, ptr }
%ScrError = type { i64, ptr, ptr, ptr, ptr }
%ScrClassObj = type { i64, i64, i64, ptr, ptr }
%ScrEmitter = type { i64, ptr, ptr, ptr }
%ScrStream = type { i64, ptr, ptr, ptr, ptr }
%ScrCaught = type { i64, i32, double, i8, ptr, ptr, ptr, ptr }
%ScrBytes = type { i64, i64, i32, ptr, ptr }
%ScrBox = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrJsonBuf = type { ptr, i64, i64, ptr, i64, i64 }
%ScrDynPath = type { ptr, ptr, i64 }
%ScrIslandModule = type { ptr, ptr, i64, i64, i32, ptr, i64, i64 }
%ScrIslandEdge = type { ptr, ptr, ptr, i32 }

@scr_error_vts = external global [5 x %ScrVt]
declare void @scr_init()
declare void @scr_lib_init(i32, ptr)
declare ptr @scr_str_retain_v(ptr)
declare void @scr_str_release_v(ptr)
declare void @scr_str_release(ptr)
declare void @scr_console_log(i64, ptr)
declare double @llvm.fabs.f64(double)
declare double @scr_parse_int(ptr, double)
declare double @scr_parse_float(ptr)
declare double @scr_string_to_number(ptr)
declare double @llvm.floor.f64(double)
declare double @llvm.ceil.f64(double)
declare double @scr_math_round(double)
declare double @llvm.trunc.f64(double)
declare double @scr_bit_or(double, double)
declare double @scr_bit_and(double, double)
declare double @scr_bit_xor(double, double)
declare double @scr_bit_not(double)
declare double @scr_bit_shl(double, double)
declare double @scr_bit_shr(double, double)
declare zeroext i1 @scr_num_is_finite(double)
declare ptr @scr_str_concat(ptr, ptr)
declare double @scr_str_utf16_len(ptr)
declare ptr @scr_str_char_at(ptr, double)
declare double @scr_str_index_of(ptr, ptr, double)
declare ptr @scr_str_split_limit(ptr, ptr, double)
declare ptr @scr_arr_retain_v(ptr)
declare void @scr_arr_release_v(ptr)
declare double @scr_arr_len(ptr)
declare void @scr_arr_release(ptr)
declare void @scr_insp_begin(double)
declare ptr @scr_arr_get_ref(ptr, double)
declare ptr @scr_insp_str(ptr)
declare void @scr_insp_entry(ptr, i1 zeroext)
declare ptr @scr_insp_more_items(double)
declare ptr @scr_insp_end(ptr, ptr, ptr, double, i1 zeroext, i1 zeroext)

@sc_lit_0 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"hello\00" }
@sc_lit_1 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"number:\00" }
@sc_lit_2 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"string:\00" }
@sc_lit_3 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"boolean:\00" }
@sc_lit_4 = internal global { i64, i64, i64, [26 x i8] } { i64 -1, i64 25, i64 25, [26 x i8] c"\0A--- Number precision ---\00" }
@sc_lit_5 = internal global { i64, i64, i64, [18 x i8] } { i64 -1, i64 17, i64 17, [18 x i8] c"MAX_SAFE_INTEGER:\00" }
@sc_lit_6 = internal global { i64, i64, i64, [18 x i8] } { i64 -1, i64 17, i64 17, [18 x i8] c"MIN_SAFE_INTEGER:\00" }
@sc_lit_7 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"EPSILON:\00" }
@sc_lit_8 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"MAX_VALUE:\00" }
@sc_lit_9 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"MIN_VALUE:\00" }
@sc_lit_10 = internal global { i64, i64, i64, [25 x i8] } { i64 -1, i64 24, i64 24, [25 x i8] c"\0A--- Float precision ---\00" }
@sc_lit_11 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c"0.1 + 0.2 =\00" }
@sc_lit_12 = internal global { i64, i64, i64, [19 x i8] } { i64 -1, i64 18, i64 18, [19 x i8] c"0.1 + 0.2 === 0.3?\00" }
@sc_lit_13 = internal global { i64, i64, i64, [35 x i8] } { i64 -1, i64 34, i64 34, [35 x i8] c"Math.abs(0.1 + 0.2 - 0.3) < 1e-15?\00" }
@sc_lit_14 = internal global { i64, i64, i64, [29 x i8] } { i64 -1, i64 28, i64 28, [29 x i8] c"\0A--- Numeric conversions ---\00" }
@sc_lit_15 = internal global { i64, i64, i64, [16 x i8] } { i64 -1, i64 15, i64 15, [16 x i8] c"parseInt('42'):\00" }
@sc_lit_16 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"42\00" }
@sc_lit_17 = internal global { i64, i64, i64, [20 x i8] } { i64 -1, i64 19, i64 19, [20 x i8] c"parseFloat('3.14'):\00" }
@sc_lit_18 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"3.14\00" }
@sc_lit_19 = internal global { i64, i64, i64, [15 x i8] } { i64 -1, i64 14, i64 14, [15 x i8] c"Number('123'):\00" }
@sc_lit_20 = internal global { i64, i64, i64, [4 x i8] } { i64 -1, i64 3, i64 3, [4 x i8] c"123\00" }
@sc_lit_21 = internal global { i64, i64, i64, [17 x i8] } { i64 -1, i64 16, i64 16, [17 x i8] c"Math.floor(3.7):\00" }
@sc_lit_22 = internal global { i64, i64, i64, [16 x i8] } { i64 -1, i64 15, i64 15, [16 x i8] c"Math.ceil(3.2):\00" }
@sc_lit_23 = internal global { i64, i64, i64, [17 x i8] } { i64 -1, i64 16, i64 16, [17 x i8] c"Math.round(3.5):\00" }
@sc_lit_24 = internal global { i64, i64, i64, [17 x i8] } { i64 -1, i64 16, i64 16, [17 x i8] c"Math.trunc(3.7):\00" }
@sc_lit_25 = internal global { i64, i64, i64, [18 x i8] } { i64 -1, i64 17, i64 17, [18 x i8] c"Math.trunc(-3.7):\00" }
@sc_lit_26 = internal global { i64, i64, i64, [28 x i8] } { i64 -1, i64 27, i64 27, [28 x i8] c"\0A--- Bitwise operations ---\00" }
@sc_lit_27 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"5 | 3 =\00" }
@sc_lit_28 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"5 & 3 =\00" }
@sc_lit_29 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"5 ^ 3 =\00" }
@sc_lit_30 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"~5 =\00" }
@sc_lit_31 = internal global { i64, i64, i64, [9 x i8] } { i64 -1, i64 8, i64 8, [9 x i8] c"5 << 1 =\00" }
@sc_lit_32 = internal global { i64, i64, i64, [10 x i8] } { i64 -1, i64 9, i64 9, [10 x i8] c"20 >> 2 =\00" }
@sc_lit_33 = internal global { i64, i64, i64, [24 x i8] } { i64 -1, i64 23, i64 23, [24 x i8] c"\0A--- Special values ---\00" }
@sc_lit_34 = internal global { i64, i64, i64, [10 x i8] } { i64 -1, i64 9, i64 9, [10 x i8] c"Infinity:\00" }
@sc_lit_35 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"-Infinity:\00" }
@sc_lit_36 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"NaN:\00" }
@sc_lit_37 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c"isNaN(NaN):\00" }
@sc_lit_38 = internal global { i64, i64, i64, [20 x i8] } { i64 -1, i64 19, i64 19, [20 x i8] c"isFinite(Infinity):\00" }
@sc_lit_39 = internal global { i64, i64, i64, [14 x i8] } { i64 -1, i64 13, i64 13, [14 x i8] c"isFinite(42):\00" }
@sc_lit_40 = internal global { i64, i64, i64, [27 x i8] } { i64 -1, i64 26, i64 26, [27 x i8] c"\0A--- String operations ---\00" }
@sc_lit_41 = internal global { i64, i64, i64, [4 x i8] } { i64 -1, i64 3, i64 3, [4 x i8] c"LLM\00" }
@sc_lit_42 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"Hello, \00" }
@sc_lit_43 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"!\00" }
@sc_lit_44 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"length:\00" }
@sc_lit_45 = internal global { i64, i64, i64, [11 x i8] } { i64 -1, i64 10, i64 10, [11 x i8] c"charAt(0):\00" }
@sc_lit_46 = internal global { i64, i64, i64, [20 x i8] } { i64 -1, i64 19, i64 19, [20 x i8] c"'abc'.indexOf('b'):\00" }
@sc_lit_47 = internal global { i64, i64, i64, [4 x i8] } { i64 -1, i64 3, i64 3, [4 x i8] c"abc\00" }
@sc_lit_48 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"b\00" }
@sc_lit_49 = internal global { i64, i64, i64, [26 x i8] } { i64 -1, i64 25, i64 25, [26 x i8] c"'hello world'.split(' '):\00" }
@sc_lit_50 = internal global { i64, i64, i64, [12 x i8] } { i64 -1, i64 11, i64 11, [12 x i8] c"hello world\00" }
@sc_lit_51 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c" \00" }
@sc_lit_52 = internal global { i64, i64, i64, [21 x i8] } { i64 -1, i64 20, i64 20, [21 x i8] c"\0A\E2\9C\85 types.ts passed\00" }
@sc_lit_53 = internal global { i64, i64, i64, [3 x i8] } { i64 -1, i64 2, i64 2, [3 x i8] c"[]\00" }
@sc_lit_54 = internal global { i64, i64, i64, [8 x i8] } { i64 -1, i64 7, i64 7, [8 x i8] c"[Array]\00" }
@sc_lit_55 = internal global { i64, i64, i64, [1 x i8] } { i64 -1, i64 0, i64 0, [1 x i8] c"\00" }
@sc_lit_56 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"[\00" }
@sc_lit_57 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"]\00" }

@sc_g_e_n = internal global double 0x0000000000000000 ; n
@sc_g_e_s = internal global ptr null ; s
@sc_g_e_b = internal global i1 false ; b
@sc_g_e_name = internal global ptr null ; name
@sc_g_e__x25_loaded = internal global i1 false ; %loaded

define internal void @sc_f__x25_init_0() #0 { ; %init.0
entry:
  %logargs = alloca [6 x %ScrLogArg]
  %t0 = load i1, ptr @sc_g_e__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_e__x25_loaded
  store double 0x4045000000000000, ptr @sc_g_e_n
  %t1 = call ptr @scr_str_retain_v(ptr @sc_lit_0)
  %t2 = load ptr, ptr @sc_g_e_s
  call void @scr_str_release(ptr %t2)
  store ptr %t1, ptr @sc_g_e_s
  store i1 true, ptr @sc_g_e_b
  %t3 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t4 = load double, ptr @sc_g_e_n
  %t5 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  %t6 = load ptr, ptr @sc_g_e_s
  %t7 = call ptr @scr_str_retain_v(ptr %t6)
  %t8 = call ptr @scr_str_retain_v(ptr @sc_lit_3)
  %t9 = load i1, ptr @sc_g_e_b
  %t10 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t10
  %t11 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t3, ptr %t11
  %t12 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t12
  %t13 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t4, ptr %t13
  %t14 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 0
  store i32 1, ptr %t14
  %t15 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 2, i32 1
  store ptr %t5, ptr %t15
  %t16 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 3, i32 0
  store i32 1, ptr %t16
  %t17 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 3, i32 1
  store ptr %t7, ptr %t17
  %t18 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 4, i32 0
  store i32 1, ptr %t18
  %t19 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 4, i32 1
  store ptr %t8, ptr %t19
  %t20 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 5, i32 0
  store i32 2, ptr %t20
  %t21 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 5, i32 1
  %t22 = zext i1 %t9 to i8
  store i8 %t22, ptr %t21
  call void @scr_console_log(i64 6, ptr %logargs)
  call void @scr_str_release(ptr %t3)
  call void @scr_str_release(ptr %t5)
  call void @scr_str_release(ptr %t7)
  call void @scr_str_release(ptr %t8)
  %t23 = call ptr @scr_str_retain_v(ptr @sc_lit_4)
  %t24 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t24
  %t25 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t23, ptr %t25
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t23)
  %t26 = call ptr @scr_str_retain_v(ptr @sc_lit_5)
  %t27 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t27
  %t28 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t26, ptr %t28
  %t29 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t29
  %t30 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double 0x433FFFFFFFFFFFFF, ptr %t30
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t26)
  %t31 = call ptr @scr_str_retain_v(ptr @sc_lit_6)
  %t32 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t32
  %t33 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t31, ptr %t33
  %t34 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t34
  %t35 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double 0xC33FFFFFFFFFFFFF, ptr %t35
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t31)
  %t36 = call ptr @scr_str_retain_v(ptr @sc_lit_7)
  %t37 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t37
  %t38 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t36, ptr %t38
  %t39 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t39
  %t40 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double 0x3CB0000000000000, ptr %t40
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t36)
  %t41 = call ptr @scr_str_retain_v(ptr @sc_lit_8)
  %t42 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t42
  %t43 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t41, ptr %t43
  %t44 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t44
  %t45 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double 0x7FEFFFFFFFFFFFFF, ptr %t45
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t41)
  %t46 = call ptr @scr_str_retain_v(ptr @sc_lit_9)
  %t47 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t47
  %t48 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t46, ptr %t48
  %t49 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t49
  %t50 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double 0x0000000000000001, ptr %t50
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t46)
  %t51 = call ptr @scr_str_retain_v(ptr @sc_lit_10)
  %t52 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t52
  %t53 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t51, ptr %t53
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t51)
  %t54 = call ptr @scr_str_retain_v(ptr @sc_lit_11)
  %t55 = fadd double 0x3FB999999999999A, 0x3FC999999999999A
  %t56 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t56
  %t57 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t54, ptr %t57
  %t58 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t58
  %t59 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t55, ptr %t59
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t54)
  %t60 = call ptr @scr_str_retain_v(ptr @sc_lit_12)
  %t61 = fadd double 0x3FB999999999999A, 0x3FC999999999999A
  %t62 = fcmp oeq double %t61, 0x3FD3333333333333
  %t63 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t63
  %t64 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t60, ptr %t64
  %t65 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 2, ptr %t65
  %t66 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  %t67 = zext i1 %t62 to i8
  store i8 %t67, ptr %t66
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t60)
  %t68 = call ptr @scr_str_retain_v(ptr @sc_lit_13)
  %t69 = fadd double 0x3FB999999999999A, 0x3FC999999999999A
  %t70 = fsub double %t69, 0x3FD3333333333333
  %t71 = call double @llvm.fabs.f64(double %t70)
  %t72 = fcmp olt double %t71, 0x3CD203AF9EE75616
  %t73 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t73
  %t74 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t68, ptr %t74
  %t75 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 2, ptr %t75
  %t76 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  %t77 = zext i1 %t72 to i8
  store i8 %t77, ptr %t76
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t68)
  %t78 = call ptr @scr_str_retain_v(ptr @sc_lit_14)
  %t79 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t79
  %t80 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t78, ptr %t80
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t78)
  %t81 = call ptr @scr_str_retain_v(ptr @sc_lit_15)
  %t82 = call ptr @scr_str_retain_v(ptr @sc_lit_16)
  %t83 = call double @scr_parse_int(ptr %t82, double 0x0000000000000000)
  %t84 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t84
  %t85 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t81, ptr %t85
  %t86 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t86
  %t87 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t83, ptr %t87
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t81)
  call void @scr_str_release(ptr %t82)
  %t88 = call ptr @scr_str_retain_v(ptr @sc_lit_17)
  %t89 = call ptr @scr_str_retain_v(ptr @sc_lit_18)
  %t90 = call double @scr_parse_float(ptr %t89)
  %t91 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t91
  %t92 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t88, ptr %t92
  %t93 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t93
  %t94 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t90, ptr %t94
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t88)
  call void @scr_str_release(ptr %t89)
  %t95 = call ptr @scr_str_retain_v(ptr @sc_lit_19)
  %t96 = call ptr @scr_str_retain_v(ptr @sc_lit_20)
  %t97 = call double @scr_string_to_number(ptr %t96)
  %t98 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t98
  %t99 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t95, ptr %t99
  %t100 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t100
  %t101 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t97, ptr %t101
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t95)
  call void @scr_str_release(ptr %t96)
  %t102 = call ptr @scr_str_retain_v(ptr @sc_lit_21)
  %t103 = call double @llvm.floor.f64(double 0x400D99999999999A)
  %t104 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t104
  %t105 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t102, ptr %t105
  %t106 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t106
  %t107 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t103, ptr %t107
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t102)
  %t108 = call ptr @scr_str_retain_v(ptr @sc_lit_22)
  %t109 = call double @llvm.ceil.f64(double 0x400999999999999A)
  %t110 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t110
  %t111 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t108, ptr %t111
  %t112 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t112
  %t113 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t109, ptr %t113
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t108)
  %t114 = call ptr @scr_str_retain_v(ptr @sc_lit_23)
  %t115 = call double @scr_math_round(double 0x400C000000000000)
  %t116 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t116
  %t117 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t114, ptr %t117
  %t118 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t118
  %t119 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t115, ptr %t119
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t114)
  %t120 = call ptr @scr_str_retain_v(ptr @sc_lit_24)
  %t121 = call double @llvm.trunc.f64(double 0x400D99999999999A)
  %t122 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t122
  %t123 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t120, ptr %t123
  %t124 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t124
  %t125 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t121, ptr %t125
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t120)
  %t126 = call ptr @scr_str_retain_v(ptr @sc_lit_25)
  %t127 = call double @llvm.trunc.f64(double 0xC00D99999999999A)
  %t128 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t128
  %t129 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t126, ptr %t129
  %t130 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t130
  %t131 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t127, ptr %t131
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t126)
  %t132 = call ptr @scr_str_retain_v(ptr @sc_lit_26)
  %t133 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t133
  %t134 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t132, ptr %t134
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t132)
  %t135 = call ptr @scr_str_retain_v(ptr @sc_lit_27)
  %t136 = call double @scr_bit_or(double 0x4014000000000000, double 0x4008000000000000)
  %t137 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t137
  %t138 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t135, ptr %t138
  %t139 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t139
  %t140 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t136, ptr %t140
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t135)
  %t141 = call ptr @scr_str_retain_v(ptr @sc_lit_28)
  %t142 = call double @scr_bit_and(double 0x4014000000000000, double 0x4008000000000000)
  %t143 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t143
  %t144 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t141, ptr %t144
  %t145 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t145
  %t146 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t142, ptr %t146
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t141)
  %t147 = call ptr @scr_str_retain_v(ptr @sc_lit_29)
  %t148 = call double @scr_bit_xor(double 0x4014000000000000, double 0x4008000000000000)
  %t149 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t149
  %t150 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t147, ptr %t150
  %t151 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t151
  %t152 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t148, ptr %t152
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t147)
  %t153 = call ptr @scr_str_retain_v(ptr @sc_lit_30)
  %t154 = call double @scr_bit_not(double 0x4014000000000000)
  %t155 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t155
  %t156 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t153, ptr %t156
  %t157 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t157
  %t158 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t154, ptr %t158
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t153)
  %t159 = call ptr @scr_str_retain_v(ptr @sc_lit_31)
  %t160 = call double @scr_bit_shl(double 0x4014000000000000, double 0x3FF0000000000000)
  %t161 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t161
  %t162 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t159, ptr %t162
  %t163 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t163
  %t164 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t160, ptr %t164
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t159)
  %t165 = call ptr @scr_str_retain_v(ptr @sc_lit_32)
  %t166 = call double @scr_bit_shr(double 0x4034000000000000, double 0x4000000000000000)
  %t167 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t167
  %t168 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t165, ptr %t168
  %t169 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t169
  %t170 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t166, ptr %t170
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t165)
  %t171 = call ptr @scr_str_retain_v(ptr @sc_lit_33)
  %t172 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t172
  %t173 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t171, ptr %t173
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t171)
  %t174 = call ptr @scr_str_retain_v(ptr @sc_lit_34)
  %t175 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t175
  %t176 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t174, ptr %t176
  %t177 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t177
  %t178 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double 0x7FF0000000000000, ptr %t178
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t174)
  %t179 = call ptr @scr_str_retain_v(ptr @sc_lit_35)
  %t180 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t180
  %t181 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t179, ptr %t181
  %t182 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t182
  %t183 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double 0xFFF0000000000000, ptr %t183
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t179)
  %t184 = call ptr @scr_str_retain_v(ptr @sc_lit_36)
  %t185 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t185
  %t186 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t184, ptr %t186
  %t187 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t187
  %t188 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double 0x7FF8000000000000, ptr %t188
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t184)
  %t189 = call ptr @scr_str_retain_v(ptr @sc_lit_37)
  %t190 = fcmp uno double 0x7FF8000000000000, 0x0000000000000000
  %t191 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t191
  %t192 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t189, ptr %t192
  %t193 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 2, ptr %t193
  %t194 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  %t195 = zext i1 %t190 to i8
  store i8 %t195, ptr %t194
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t189)
  %t196 = call ptr @scr_str_retain_v(ptr @sc_lit_38)
  %t197 = call i1 @scr_num_is_finite(double 0x7FF0000000000000)
  %t198 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t198
  %t199 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t196, ptr %t199
  %t200 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 2, ptr %t200
  %t201 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  %t202 = zext i1 %t197 to i8
  store i8 %t202, ptr %t201
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t196)
  %t203 = call ptr @scr_str_retain_v(ptr @sc_lit_39)
  %t204 = call i1 @scr_num_is_finite(double 0x4045000000000000)
  %t205 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t205
  %t206 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t203, ptr %t206
  %t207 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 2, ptr %t207
  %t208 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  %t209 = zext i1 %t204 to i8
  store i8 %t209, ptr %t208
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t203)
  %t210 = call ptr @scr_str_retain_v(ptr @sc_lit_40)
  %t211 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t211
  %t212 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t210, ptr %t212
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t210)
  %t213 = call ptr @scr_str_retain_v(ptr @sc_lit_41)
  %t214 = load ptr, ptr @sc_g_e_name
  call void @scr_str_release(ptr %t214)
  store ptr %t213, ptr @sc_g_e_name
  %t215 = call ptr @scr_str_retain_v(ptr @sc_lit_42)
  %t216 = load ptr, ptr @sc_g_e_name
  %t217 = call ptr @scr_str_retain_v(ptr %t216)
  %t218 = call ptr @scr_str_concat(ptr %t215, ptr %t217)
  %t219 = call ptr @scr_str_retain_v(ptr @sc_lit_43)
  %t220 = call ptr @scr_str_concat(ptr %t218, ptr %t219)
  %t221 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t221
  %t222 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t220, ptr %t222
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t215)
  call void @scr_str_release(ptr %t217)
  call void @scr_str_release(ptr %t218)
  call void @scr_str_release(ptr %t219)
  call void @scr_str_release(ptr %t220)
  %t223 = call ptr @scr_str_retain_v(ptr @sc_lit_44)
  %t224 = load ptr, ptr @sc_g_e_name
  %t225 = call ptr @scr_str_retain_v(ptr %t224)
  %t226 = call double @scr_str_utf16_len(ptr %t225)
  %t227 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t227
  %t228 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t223, ptr %t228
  %t229 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t229
  %t230 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t226, ptr %t230
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t223)
  call void @scr_str_release(ptr %t225)
  %t231 = call ptr @scr_str_retain_v(ptr @sc_lit_45)
  %t232 = load ptr, ptr @sc_g_e_name
  %t233 = call ptr @scr_str_retain_v(ptr %t232)
  %t234 = call ptr @scr_str_char_at(ptr %t233, double 0x0000000000000000)
  %t235 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t235
  %t236 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t231, ptr %t236
  %t237 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t237
  %t238 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t234, ptr %t238
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t231)
  call void @scr_str_release(ptr %t233)
  call void @scr_str_release(ptr %t234)
  %t239 = call ptr @scr_str_retain_v(ptr @sc_lit_46)
  %t240 = call ptr @scr_str_retain_v(ptr @sc_lit_47)
  %t241 = call ptr @scr_str_retain_v(ptr @sc_lit_48)
  %t242 = call double @scr_str_index_of(ptr %t240, ptr %t241, double 0x0000000000000000)
  %t243 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t243
  %t244 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t239, ptr %t244
  %t245 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 0, ptr %t245
  %t246 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store double %t242, ptr %t246
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t239)
  call void @scr_str_release(ptr %t240)
  call void @scr_str_release(ptr %t241)
  %t247 = call ptr @scr_str_retain_v(ptr @sc_lit_49)
  %t248 = call ptr @scr_str_retain_v(ptr @sc_lit_50)
  %t249 = call ptr @scr_str_retain_v(ptr @sc_lit_51)
  %t250 = call ptr @scr_str_split_limit(ptr %t248, ptr %t249, double 0x41EFFFFFFFE00000)
  %t251 = call ptr @sc_f__x25_util_insp_0(ptr %t250, double 0x0000000000000000, double 0x4000000000000000)
  %t252 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t252
  %t253 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t247, ptr %t253
  %t254 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 0
  store i32 1, ptr %t254
  %t255 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 1, i32 1
  store ptr %t251, ptr %t255
  call void @scr_console_log(i64 2, ptr %logargs)
  call void @scr_str_release(ptr %t247)
  call void @scr_str_release(ptr %t248)
  call void @scr_str_release(ptr %t249)
  call void @scr_str_release(ptr %t251)
  %t256 = call ptr @scr_str_retain_v(ptr @sc_lit_52)
  %t257 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t257
  %t258 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t256, ptr %t258
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t256)
  ret void
}

define internal void @sc_f__x25_main() #0 { ; %main
entry:
  call void @sc_f__x25_init_0()
  ret void
}

define internal ptr @sc_f__x25_util_insp_0(ptr %p_sc_l_v_0, double %p_sc_l_r_0, double %p_sc_l_d_0) #0 { ; %util.insp.0
entry:
  %sc_l_v_0 = alloca ptr ; v
  %sc_l_r_0 = alloca double ; r
  %sc_l_d_0 = alloca double ; d
  %sc_l_n_0 = alloca double ; n
  %sc_l_s_0 = alloca double ; s
  %sc_l_i_0 = alloca double ; i
  %s14 = alloca double
  store ptr %p_sc_l_v_0, ptr %sc_l_v_0
  store double %p_sc_l_r_0, ptr %sc_l_r_0
  store double %p_sc_l_d_0, ptr %sc_l_d_0
  %t0 = load ptr, ptr %sc_l_v_0
  %t1 = call ptr @scr_arr_retain_v(ptr %t0)
  %t2 = call double @scr_arr_len(ptr %t1)
  store double %t2, ptr %sc_l_n_0
  call void @scr_arr_release(ptr %t1)
  %t3 = load double, ptr %sc_l_n_0
  %t4 = fcmp oeq double %t3, 0x0000000000000000
  br i1 %t4, label %if.t0, label %if.j1
if.t0:
  %t5 = call ptr @scr_str_retain_v(ptr @sc_lit_53)
  %t6 = load ptr, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t6)
  ret ptr %t5
if.j1:
  %t7 = load double, ptr %sc_l_r_0
  %t8 = load double, ptr %sc_l_d_0
  %t9 = fcmp ogt double %t7, %t8
  br i1 %t9, label %if.t2, label %if.j3
if.t2:
  %t10 = call ptr @scr_str_retain_v(ptr @sc_lit_54)
  %t11 = load ptr, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t11)
  ret ptr %t10
if.j3:
  %t12 = load double, ptr %sc_l_n_0
  %t13 = fcmp ogt double %t12, 0x4059000000000000
  br i1 %t13, label %tern.t4, label %tern.f5
tern.t4:
  store double 0x4059000000000000, ptr %s14
  br label %tern.j6
tern.f5:
  %t15 = load double, ptr %sc_l_n_0
  store double %t15, ptr %s14
  br label %tern.j6
tern.j6:
  %t16 = load double, ptr %s14
  store double %t16, ptr %sc_l_s_0
  %t17 = load double, ptr %sc_l_r_0
  %t18 = fadd double %t17, 0x3FF0000000000000
  call void @scr_insp_begin(double %t18)
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c7
loop.c7:
  %t19 = load double, ptr %sc_l_i_0
  %t20 = load double, ptr %sc_l_s_0
  %t21 = fcmp olt double %t19, %t20
  br i1 %t21, label %loop.b8, label %loop.e9
loop.b8:
  %t22 = load ptr, ptr %sc_l_v_0
  %t23 = call ptr @scr_arr_retain_v(ptr %t22)
  %t24 = load double, ptr %sc_l_i_0
  %t25 = call ptr @scr_arr_get_ref(ptr %t23, double %t24)
  %t26 = call ptr @scr_insp_str(ptr %t25)
  call void @scr_insp_entry(ptr %t26, i1 false)
  call void @scr_arr_release(ptr %t23)
  call void @scr_str_release(ptr %t25)
  call void @scr_str_release(ptr %t26)
  br label %loop.u10
loop.u10:
  %t27 = load double, ptr %sc_l_i_0
  %t28 = fadd double %t27, 0x3FF0000000000000
  store double %t28, ptr %sc_l_i_0
  br label %loop.c7
loop.e9:
  %t29 = load double, ptr %sc_l_n_0
  %t30 = fcmp ogt double %t29, 0x4059000000000000
  br i1 %t30, label %if.t11, label %if.j12
if.t11:
  %t31 = load double, ptr %sc_l_n_0
  %t32 = fsub double %t31, 0x4059000000000000
  %t33 = call ptr @scr_insp_more_items(double %t32)
  call void @scr_insp_entry(ptr %t33, i1 false)
  call void @scr_str_release(ptr %t33)
  br label %if.j12
if.j12:
  %t34 = call ptr @scr_str_retain_v(ptr @sc_lit_55)
  %t35 = call ptr @scr_str_retain_v(ptr @sc_lit_56)
  %t36 = call ptr @scr_str_retain_v(ptr @sc_lit_57)
  %t37 = load double, ptr %sc_l_r_0
  %t38 = fadd double %t37, 0x3FF0000000000000
  %t39 = load double, ptr %sc_l_n_0
  %t40 = fcmp ogt double %t39, 0x4059000000000000
  %t41 = call ptr @scr_insp_end(ptr %t34, ptr %t35, ptr %t36, double %t38, i1 true, i1 %t40)
  call void @scr_str_release(ptr %t34)
  call void @scr_str_release(ptr %t35)
  call void @scr_str_release(ptr %t36)
  %t42 = load ptr, ptr %sc_l_v_0
  call void @scr_arr_release(ptr %t42)
  ret ptr %t41
}

define i32 @main(i32 %argc, ptr %argv) #0 {
entry:
  call void @scr_init()
  store i64 0, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 1) ; Error
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 0)
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 1) ; TypeError
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 0)
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 1) ; RangeError
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 0)
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 1) ; SyntaxError
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 1) ; DOMException
  call void @scr_lib_init(i32 %argc, ptr %argv)
  call void @sc_f__x25_main()
  %g1 = load ptr, ptr @sc_g_e_s
  call void @scr_str_release(ptr %g1) ; s
  %g3 = load ptr, ptr @sc_g_e_name
  call void @scr_str_release(ptr %g3) ; name
  ret i32 0
}

attributes #0 = { sanitize_address }
