; Generated by scriptc (LLVM backend) from /Users/sam/Dev/llama.scriptc/examples/debug_tok.ts. Do not edit.

%ScrStr = type { i64, i64, i64 }
%ScrLogArg = type { i32, i64 }
%ScrVt = type { i64, i64, ptr }
%ScrUnion = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrClosure = type { i64, ptr, i64, ptr }
%ScrRegex = type { i64, ptr, ptr, ptr }
%ScrArr = type { i64, i64, i64, i32, ptr, ptr, ptr, ptr }
%ScrError = type { i64, ptr, ptr, ptr, ptr }
%ScrClassObj = type { i64, i64, i64, ptr, ptr }
%ScrEmitter = type { i64, ptr, ptr, ptr }
%ScrStream = type { i64, ptr, ptr, ptr, ptr }
%ScrCaught = type { i64, i32, double, i8, ptr, ptr, ptr, ptr }
%ScrBytes = type { i64, i64, i32, ptr, ptr }
%ScrBox = type { i64, i32, ptr, ptr, ptr, i64 }
%ScrJsonBuf = type { ptr, i64, i64, ptr, i64, i64 }
%ScrDynPath = type { ptr, ptr, i64 }
%ScrIslandModule = type { ptr, ptr, i64, i64, i32, ptr, i64, i64 }
%ScrIslandEdge = type { ptr, ptr, ptr, i32 }
%sc_o__x25_m5_Tokenizer = type { i64, ptr, ptr, ptr, double, double, double, double } ; class %m5.Tokenizer (vt at 1) { tokenToIdMap; idToTokenMap; bosTokenId; eosTokenId; unkTokenId; padTokenId }
%sc_o__x25_m6_GGUFTokenizer = type { i64, ptr, ptr, ptr, double, double, double, double, ptr } ; class %m6.GGUFTokenizer (vt at 1) { tokenToIdMap; idToTokenMap; bosTokenId; eosTokenId; unkTokenId; padTokenId; tokens }
%sc_vtt__x25_m5_Tokenizer = type { %ScrVt } ; vtable: hierarchy rooted at %m5.Tokenizer

@scr_error_vts = external global [5 x %ScrVt]
declare void @scr_init()
declare void @scr_lib_init(i32, ptr)
declare ptr @scr_map_new(i32, i32, ptr, ptr, ptr)
declare void @scr_map_release(ptr)
declare ptr @scr_arr_new(i32, i64)
declare void @scr_arr_release(ptr)
declare ptr @scr_str_retain_v(ptr)
declare void @scr_str_release_v(ptr)
declare zeroext i1 @scr_exc_pending()
declare void @scr_union_release(ptr)
declare double @scr_arr_push_f64(ptr, double)
declare ptr @scr_str_from_char_code(ptr)
declare ptr @scr_union_retain_v(ptr)
declare void @scr_union_release_v(ptr)
declare ptr @scr_arr_retain_v(ptr)
declare void @scr_arr_release_v(ptr)
declare double @scr_arr_len(ptr)
declare ptr @scr_arr_get_ref(ptr, double)
declare ptr @scr_map_retain_v(ptr)
declare void @scr_map_release_v(ptr)
declare zeroext i1 @scr_map_has_str(ptr, ptr)
declare void @scr_str_release(ptr)
declare zeroext i1 @scr_map_get_str_f64(ptr, ptr, ptr)
declare ptr @scr_union_new_f64(i32, double)
declare void @scr_map_set_str_f64(ptr, ptr, double)
declare double @scr_arr_push_ref(ptr, ptr)
declare double @scr_fs_open(ptr, ptr)
declare ptr @scr_fs_stat(ptr)
declare void @scr_stats_release_v(ptr)
declare ptr @scr_stats_retain_v(ptr)
declare double @scr_stats_size(ptr)
declare double @scr_math_min(double, double)
declare ptr @scr_bytes_new(i32, double)
declare void @scr_bytes_release(ptr)
declare ptr @scr_bytes_retain_v(ptr)
declare void @scr_bytes_release_v(ptr)
declare double @scr_fs_read_sync(double, ptr, double, double, double)
declare double @scr_bytes_read_num(ptr, double, i32, i1 zeroext)
declare ptr @scr_error_new(i32, ptr)
declare ptr @scr_error_retain_v(ptr)
declare void @scr_error_release_v(ptr)
declare void @scr_throw_obj(ptr, ptr, ptr, ptr)
declare ptr @scr_bytes_to_str_range(ptr, ptr, double, double)
declare zeroext i1 @scr_str_eq(ptr, ptr)
declare void @scr_fs_close(double)
declare zeroext i1 @scr_union_get_bool(ptr)
declare double @scr_arr_get_f64(ptr, double)
declare double @scr_str_utf16_len(ptr)
declare double @scr_str_char_code_at(ptr, double)
declare zeroext i1 @scr_map_get_f64_f64(ptr, double, ptr)
declare double @scr_union_get_f64(ptr)
declare double @scr_bit_and(double, double)
declare ptr @scr_bytes_from_arr(i32, ptr)
declare ptr @scr_bytes_to_str(ptr, ptr)
declare ptr @scr_arr_slice(ptr, double, double)
declare zeroext i1 @scr_arr_includes_f64(ptr, double)
declare void @scr_map_set_f64_f64(ptr, double, double)
declare void @scr_jb_put_json_str(ptr, ptr)
declare void @scr_jb_init(ptr)
declare ptr @scr_jb_finish(ptr)
declare void @scr_console_log(i64, ptr)
declare void @scr_obj_alloc_note()
declare void @scr_obj_free_note()
declare void @free(ptr)
declare ptr @calloc(i64, i64)
declare void @scr_trap(ptr)

@sc_lit_0 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"<unk>\00" }
@sc_lit_1 = internal global { i64, i64, i64, [4 x i8] } { i64 -1, i64 3, i64 3, [4 x i8] c"<s>\00" }
@sc_lit_2 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"</s>\00" }
@sc_lit_3 = internal global { i64, i64, i64, [6 x i8] } { i64 -1, i64 5, i64 5, [6 x i8] c"<pad>\00" }
@sc_lit_4 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"\0A\00" }
@sc_lit_5 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"\09\00" }
@sc_lit_6 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"\0D\00" }
@sc_lit_7 = internal global { i64, i64, i64, [2 x i8] } { i64 -1, i64 1, i64 1, [2 x i8] c"r\00" }
@sc_lit_8 = internal global { i64, i64, i64, [13 x i8] } { i64 -1, i64 12, i64 12, [13 x i8] c"Invalid GGUF\00" }
@sc_lit_9 = internal global { i64, i64, i64, [5 x i8] } { i64 -1, i64 4, i64 4, [5 x i8] c"utf8\00" }
@sc_lit_10 = internal global { i64, i64, i64, [22 x i8] } { i64 -1, i64 21, i64 21, [22 x i8] c"tokenizer.ggml.tokens\00" }
@sc_lit_11 = internal global { i64, i64, i64, [28 x i8] } { i64 -1, i64 27, i64 27, [28 x i8] c"tokenizer.ggml.bos_token_id\00" }
@sc_lit_12 = internal global { i64, i64, i64, [28 x i8] } { i64 -1, i64 27, i64 27, [28 x i8] c"tokenizer.ggml.eos_token_id\00" }
@sc_lit_13 = internal global { i64, i64, i64, [39 x i8] } { i64 -1, i64 38, i64 38, [39 x i8] c"models/qwen2.5-0.5b-instruct-q8_0.gguf\00" }
@sc_lit_14 = internal global { i64, i64, i64, [104 x i8] } { i64 -1, i64 103, i64 103, [104 x i8] c"undefined is not representable in the target union (a value narrowed or asserted past it still held it)\00" }

@sc_unit_0 = internal global %ScrUnion { i64 -1, i32 1, ptr null, ptr null, ptr null, i64 0 } ; u1 unit arm
@sc_unit_1 = internal global %ScrUnion { i64 -1, i32 1, ptr null, ptr null, ptr null, i64 0 } ; u4 unit arm
@sc_unit_2 = internal global %ScrUnion { i64 -1, i32 1, ptr null, ptr null, ptr null, i64 0 } ; u3 unit arm

@sc_g_s__x25_m6_GGUFTokenizer_cpToByte = internal global ptr null ; GGUFTokenizer.cpToByte
@sc_g_m4_GGUF_MAGIC = internal global double 0x0000000000000000 ; GGUF_MAGIC
@sc_g_e_t = internal global ptr null ; t
@sc_g_m0__x25_loaded = internal global i1 false ; %loaded
@sc_g_m1__x25_loaded = internal global i1 false ; %loaded
@sc_g_m2__x25_loaded = internal global i1 false ; %loaded
@sc_g_m3__x25_loaded = internal global i1 false ; %loaded
@sc_g_m4__x25_loaded = internal global i1 false ; %loaded
@sc_g_m5__x25_loaded = internal global i1 false ; %loaded
@sc_g_m6__x25_loaded = internal global i1 false ; %loaded
@sc_g_e__x25_loaded = internal global i1 false ; %loaded

@sc_oom_msg = internal constant [24 x i8] c"scriptc: out of memory\0A\00"
define internal void @sc_oom() #0 {
entry:
  call void @scr_trap(ptr @sc_oom_msg)
  unreachable
}

@sc_bad_tag_msg = internal constant [44 x i8] c"scriptc: internal error: invalid union tag\0A\00"
define internal void @sc_bad_tag() #0 {
entry:
  call void @scr_trap(ptr @sc_bad_tag_msg)
  unreachable
}

@sc_vtable__x25_m5_Tokenizer = internal constant %sc_vtt__x25_m5_Tokenizer { %ScrVt { i64 5, i64 6, ptr @sc_reld__x25_m5_Tokenizer } } ; class %m5.Tokenizer

@sc_vtable__x25_m6_GGUFTokenizer = internal constant %sc_vtt__x25_m5_Tokenizer { %ScrVt { i64 6, i64 6, ptr @sc_reld__x25_m6_GGUFTokenizer } } ; class %m6.GGUFTokenizer

define internal ptr @sc_retain__x25_m5_Tokenizer(ptr %o) #0 { ; retain %m5.Tokenizer
entry:
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %done, label %check
check:
  %rc = load i64, ptr %o
  %imm = icmp eq i64 %rc, -1
  br i1 %imm, label %done, label %inc
inc:
  %n = add i64 %rc, 1
  store i64 %n, ptr %o
  br label %done
done:
  ret ptr %o
}

define internal void @sc_release__x25_m5_Tokenizer(ptr %o) #0 { ; release %m5.Tokenizer (dispatches)
entry:
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %done, label %check
check:
  %rc = load i64, ptr %o
  %imm = icmp eq i64 %rc, -1
  br i1 %imm, label %done, label %disp
disp:
  %vtp = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %o, i64 0, i32 1
  %vt = load ptr, ptr %vtp
  %relp = getelementptr inbounds %ScrVt, ptr %vt, i64 0, i32 2
  %rel = load ptr, ptr %relp
  call void %rel(ptr %o) ; the DYNAMIC class's teardown
  br label %done
done:
  ret void
}

define internal void @sc_reld__x25_m5_Tokenizer(ptr %o) #0 { ; direct release %m5.Tokenizer
entry:
  %rc = load i64, ptr %o
  %n = sub i64 %rc, 1
  store i64 %n, ptr %o
  %dead = icmp eq i64 %n, 0
  br i1 %dead, label %free, label %done
free:
  %f0 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %o, i64 0, i32 2
  %v0 = load ptr, ptr %f0
  call void @scr_map_release(ptr %v0) ; tokenToIdMap
  %f1 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %o, i64 0, i32 3
  %v1 = load ptr, ptr %f1
  call void @scr_arr_release(ptr %v1) ; idToTokenMap
  call void @scr_obj_free_note()
  call void @free(ptr %o)
  br label %done
done:
  ret void
}

define internal ptr @sc_new__x25_m5_Tokenizer() #0 { ; new %m5.Tokenizer
entry:
  %o = call ptr @calloc(i64 1, i64 ptrtoint (ptr getelementptr (%sc_o__x25_m5_Tokenizer, ptr null, i32 1) to i64))
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %oom, label %ok
oom:
  call void @sc_oom()
  unreachable
ok:
  store i64 1, ptr %o
  %vtp = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %o, i64 0, i32 1
  store ptr @sc_vtable__x25_m5_Tokenizer, ptr %vtp
  call void @scr_obj_alloc_note()
  ret ptr %o
}

define internal ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %o) #0 { ; retain %m6.GGUFTokenizer
entry:
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %done, label %check
check:
  %rc = load i64, ptr %o
  %imm = icmp eq i64 %rc, -1
  br i1 %imm, label %done, label %inc
inc:
  %n = add i64 %rc, 1
  store i64 %n, ptr %o
  br label %done
done:
  ret ptr %o
}

define internal void @sc_release__x25_m6_GGUFTokenizer(ptr %o) #0 { ; release %m6.GGUFTokenizer (dispatches)
entry:
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %done, label %check
check:
  %rc = load i64, ptr %o
  %imm = icmp eq i64 %rc, -1
  br i1 %imm, label %done, label %disp
disp:
  %vtp = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %o, i64 0, i32 1
  %vt = load ptr, ptr %vtp
  %relp = getelementptr inbounds %ScrVt, ptr %vt, i64 0, i32 2
  %rel = load ptr, ptr %relp
  call void %rel(ptr %o) ; the DYNAMIC class's teardown
  br label %done
done:
  ret void
}

define internal void @sc_reld__x25_m6_GGUFTokenizer(ptr %o) #0 { ; direct release %m6.GGUFTokenizer
entry:
  %rc = load i64, ptr %o
  %n = sub i64 %rc, 1
  store i64 %n, ptr %o
  %dead = icmp eq i64 %n, 0
  br i1 %dead, label %free, label %done
free:
  %f0 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %o, i64 0, i32 2
  %v0 = load ptr, ptr %f0
  call void @scr_map_release(ptr %v0) ; tokenToIdMap
  %f1 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %o, i64 0, i32 3
  %v1 = load ptr, ptr %f1
  call void @scr_arr_release(ptr %v1) ; idToTokenMap
  %f2 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %o, i64 0, i32 8
  %v2 = load ptr, ptr %f2
  call void @scr_arr_release(ptr %v2) ; tokens
  call void @scr_obj_free_note()
  call void @free(ptr %o)
  br label %done
done:
  ret void
}

define internal ptr @sc_new__x25_m6_GGUFTokenizer() #0 { ; new %m6.GGUFTokenizer
entry:
  %o = call ptr @calloc(i64 1, i64 ptrtoint (ptr getelementptr (%sc_o__x25_m6_GGUFTokenizer, ptr null, i32 1) to i64))
  %isnull = icmp eq ptr %o, null
  br i1 %isnull, label %oom, label %ok
oom:
  call void @sc_oom()
  unreachable
ok:
  store i64 1, ptr %o
  %vtp = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %o, i64 0, i32 1
  store ptr @sc_vtable__x25_m6_GGUFTokenizer, ptr %vtp
  call void @scr_obj_alloc_note()
  ret ptr %o
}

define internal void @sc_jw_0(ptr %b, ptr %v) #0 { ; stringify string
entry:
  call void @scr_jb_put_json_str(ptr %b, ptr %v)
  ret void
}

define internal void @sc_f__x25__x25_m5_Tokenizer_constructor(ptr %p_sc_l_this_0, ptr %p_sc_l_customVocab_0) #0 { ; %%m5.Tokenizer.constructor
entry:
  %sc_l_this_0 = alloca ptr ; this
  %sc_l_customVocab_0 = alloca ptr ; customVocab
  %sc_l_c_0 = alloca double ; c
  %sc_l_i_0 = alloca double ; i
  %sc_l_word_0 = alloca ptr ; word
  %s87 = alloca i1
  store ptr null, ptr %sc_l_word_0
  store ptr %p_sc_l_this_0, ptr %sc_l_this_0
  store ptr %p_sc_l_customVocab_0, ptr %sc_l_customVocab_0
  %t0 = load ptr, ptr %sc_l_this_0
  %t1 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t0)
  %t2 = call ptr @scr_map_new(i32 1, i32 0, ptr null, ptr null, ptr null)
  %t3 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t1, i64 0, i32 2
  %t4 = load ptr, ptr %t3
  store ptr %t2, ptr %t3
  call void @scr_map_release(ptr %t4)
  call void @sc_release__x25_m5_Tokenizer(ptr %t1)
  %t5 = load ptr, ptr %sc_l_this_0
  %t6 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t5)
  %t7 = call ptr @scr_arr_new(i32 2, i64 0)
  %t8 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t6, i64 0, i32 3
  %t9 = load ptr, ptr %t8
  store ptr %t7, ptr %t8
  call void @scr_arr_release(ptr %t9)
  call void @sc_release__x25_m5_Tokenizer(ptr %t6)
  %t10 = load ptr, ptr %sc_l_this_0
  %t11 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t10)
  %t12 = load ptr, ptr %sc_l_this_0
  %t13 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t12)
  %t14 = call ptr @scr_str_retain_v(ptr @sc_lit_0)
  %t15 = call double @sc_f__x25__x25_m5_Tokenizer_addToken(ptr %t13, ptr %t14)
  %t16 = call zeroext i1 @scr_exc_pending()
  br i1 %t16, label %exc.u0, label %exc.k1
exc.u0:
  call void @sc_release__x25_m5_Tokenizer(ptr %t11)
  %t17 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t17)
  %t18 = load ptr, ptr %sc_l_customVocab_0
  call void @scr_union_release(ptr %t18)
  ret void
exc.k1:
  %t19 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t11, i64 0, i32 6
  store double %t15, ptr %t19
  call void @sc_release__x25_m5_Tokenizer(ptr %t11)
  %t20 = load ptr, ptr %sc_l_this_0
  %t21 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t20)
  %t22 = load ptr, ptr %sc_l_this_0
  %t23 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t22)
  %t24 = call ptr @scr_str_retain_v(ptr @sc_lit_1)
  %t25 = call double @sc_f__x25__x25_m5_Tokenizer_addToken(ptr %t23, ptr %t24)
  %t26 = call zeroext i1 @scr_exc_pending()
  br i1 %t26, label %exc.u2, label %exc.k3
exc.u2:
  call void @sc_release__x25_m5_Tokenizer(ptr %t21)
  %t27 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t27)
  %t28 = load ptr, ptr %sc_l_customVocab_0
  call void @scr_union_release(ptr %t28)
  ret void
exc.k3:
  %t29 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t21, i64 0, i32 4
  store double %t25, ptr %t29
  call void @sc_release__x25_m5_Tokenizer(ptr %t21)
  %t30 = load ptr, ptr %sc_l_this_0
  %t31 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t30)
  %t32 = load ptr, ptr %sc_l_this_0
  %t33 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t32)
  %t34 = call ptr @scr_str_retain_v(ptr @sc_lit_2)
  %t35 = call double @sc_f__x25__x25_m5_Tokenizer_addToken(ptr %t33, ptr %t34)
  %t36 = call zeroext i1 @scr_exc_pending()
  br i1 %t36, label %exc.u4, label %exc.k5
exc.u4:
  call void @sc_release__x25_m5_Tokenizer(ptr %t31)
  %t37 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t37)
  %t38 = load ptr, ptr %sc_l_customVocab_0
  call void @scr_union_release(ptr %t38)
  ret void
exc.k5:
  %t39 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t31, i64 0, i32 5
  store double %t35, ptr %t39
  call void @sc_release__x25_m5_Tokenizer(ptr %t31)
  %t40 = load ptr, ptr %sc_l_this_0
  %t41 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t40)
  %t42 = load ptr, ptr %sc_l_this_0
  %t43 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t42)
  %t44 = call ptr @scr_str_retain_v(ptr @sc_lit_3)
  %t45 = call double @sc_f__x25__x25_m5_Tokenizer_addToken(ptr %t43, ptr %t44)
  %t46 = call zeroext i1 @scr_exc_pending()
  br i1 %t46, label %exc.u6, label %exc.k7
exc.u6:
  call void @sc_release__x25_m5_Tokenizer(ptr %t41)
  %t47 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t47)
  %t48 = load ptr, ptr %sc_l_customVocab_0
  call void @scr_union_release(ptr %t48)
  ret void
exc.k7:
  %t49 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t41, i64 0, i32 7
  store double %t45, ptr %t49
  call void @sc_release__x25_m5_Tokenizer(ptr %t41)
  store double 0x4040000000000000, ptr %sc_l_c_0
  br label %loop.c8
loop.c8:
  %t50 = load double, ptr %sc_l_c_0
  %t51 = fcmp olt double %t50, 0x405FC00000000000
  br i1 %t51, label %loop.b9, label %loop.e10
loop.b9:
  %t52 = load ptr, ptr %sc_l_this_0
  %t53 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t52)
  %t54 = call ptr @scr_arr_new(i32 0, i64 1)
  %t55 = load double, ptr %sc_l_c_0
  %t56 = call double @scr_arr_push_f64(ptr %t54, double %t55)
  %t57 = call ptr @scr_str_from_char_code(ptr %t54)
  %t58 = call double @sc_f__x25__x25_m5_Tokenizer_addToken(ptr %t53, ptr %t57)
  %t59 = call zeroext i1 @scr_exc_pending()
  br i1 %t59, label %exc.u12, label %exc.k13
exc.u12:
  call void @scr_arr_release(ptr %t54)
  %t60 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t60)
  %t61 = load ptr, ptr %sc_l_customVocab_0
  call void @scr_union_release(ptr %t61)
  ret void
exc.k13:
  call void @scr_arr_release(ptr %t54)
  br label %loop.u11
loop.u11:
  %t62 = load double, ptr %sc_l_c_0
  %t63 = fadd double %t62, 0x3FF0000000000000
  store double %t63, ptr %sc_l_c_0
  br label %loop.c8
loop.e10:
  %t64 = load ptr, ptr %sc_l_this_0
  %t65 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t64)
  %t66 = call ptr @scr_str_retain_v(ptr @sc_lit_4)
  %t67 = call double @sc_f__x25__x25_m5_Tokenizer_addToken(ptr %t65, ptr %t66)
  %t68 = call zeroext i1 @scr_exc_pending()
  br i1 %t68, label %exc.u14, label %exc.k15
exc.u14:
  %t69 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t69)
  %t70 = load ptr, ptr %sc_l_customVocab_0
  call void @scr_union_release(ptr %t70)
  ret void
exc.k15:
  %t71 = load ptr, ptr %sc_l_this_0
  %t72 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t71)
  %t73 = call ptr @scr_str_retain_v(ptr @sc_lit_5)
  %t74 = call double @sc_f__x25__x25_m5_Tokenizer_addToken(ptr %t72, ptr %t73)
  %t75 = call zeroext i1 @scr_exc_pending()
  br i1 %t75, label %exc.u16, label %exc.k17
exc.u16:
  %t76 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t76)
  %t77 = load ptr, ptr %sc_l_customVocab_0
  call void @scr_union_release(ptr %t77)
  ret void
exc.k17:
  %t78 = load ptr, ptr %sc_l_this_0
  %t79 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t78)
  %t80 = call ptr @scr_str_retain_v(ptr @sc_lit_6)
  %t81 = call double @sc_f__x25__x25_m5_Tokenizer_addToken(ptr %t79, ptr %t80)
  %t82 = call zeroext i1 @scr_exc_pending()
  br i1 %t82, label %exc.u18, label %exc.k19
exc.u18:
  %t83 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t83)
  %t84 = load ptr, ptr %sc_l_customVocab_0
  call void @scr_union_release(ptr %t84)
  ret void
exc.k19:
  %t85 = load ptr, ptr %sc_l_customVocab_0
  %t86 = call ptr @scr_union_retain_v(ptr %t85)
  %t88 = getelementptr inbounds %ScrUnion, ptr %t86, i64 0, i32 1
  %t89 = load i32, ptr %t88
  switch i32 %t89, label %u.bad21 [ i32 0, label %u.a22 i32 1, label %u.a23 ]
u.a22:
  store i1 true, ptr %s87 ; array: objects are truthy
  br label %ut.j20
u.a23:
  store i1 false, ptr %s87
  br label %ut.j20
u.bad21:
  call void @sc_bad_tag()
  unreachable
ut.j20:
  %t90 = load i1, ptr %s87
  call void @scr_union_release(ptr %t86)
  br i1 %t90, label %if.t24, label %if.j25
if.t24:
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c26
loop.c26:
  %t91 = load double, ptr %sc_l_i_0
  %t92 = load ptr, ptr %sc_l_customVocab_0
  %t93 = call ptr @scr_union_retain_v(ptr %t92)
  %t94 = getelementptr inbounds %ScrUnion, ptr %t93, i64 0, i32 5
  %t95 = load ptr, ptr %t94
  %t96 = call ptr @scr_arr_retain_v(ptr %t95)
  %t97 = call double @scr_arr_len(ptr %t96)
  %t98 = fcmp olt double %t91, %t97
  call void @scr_union_release(ptr %t93)
  call void @scr_arr_release(ptr %t96)
  br i1 %t98, label %loop.b27, label %loop.e28
loop.b27:
  %t99 = load ptr, ptr %sc_l_customVocab_0
  %t100 = call ptr @scr_union_retain_v(ptr %t99)
  %t101 = getelementptr inbounds %ScrUnion, ptr %t100, i64 0, i32 5
  %t102 = load ptr, ptr %t101
  %t103 = call ptr @scr_arr_retain_v(ptr %t102)
  %t104 = load double, ptr %sc_l_i_0
  %t105 = call ptr @scr_arr_get_ref(ptr %t103, double %t104)
  store ptr %t105, ptr %sc_l_word_0
  call void @scr_union_release(ptr %t100)
  call void @scr_arr_release(ptr %t103)
  %t106 = load ptr, ptr %sc_l_this_0
  %t107 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t106)
  %t108 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t107, i64 0, i32 2
  %t109 = load ptr, ptr %t108
  %t110 = call ptr @scr_map_retain_v(ptr %t109)
  %t111 = load ptr, ptr %sc_l_word_0
  %t112 = call ptr @scr_str_retain_v(ptr %t111)
  %t113 = call zeroext i1 @scr_map_has_str(ptr %t110, ptr %t112)
  %t114 = xor i1 %t113, true
  call void @sc_release__x25_m5_Tokenizer(ptr %t107)
  call void @scr_map_release(ptr %t110)
  call void @scr_str_release(ptr %t112)
  br i1 %t114, label %if.t30, label %if.j31
if.t30:
  %t115 = load ptr, ptr %sc_l_this_0
  %t116 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t115)
  %t117 = load ptr, ptr %sc_l_word_0
  %t118 = call ptr @scr_str_retain_v(ptr %t117)
  %t119 = call double @sc_f__x25__x25_m5_Tokenizer_addToken(ptr %t116, ptr %t118)
  %t120 = call zeroext i1 @scr_exc_pending()
  br i1 %t120, label %exc.u32, label %exc.k33
exc.u32:
  %t121 = load ptr, ptr %sc_l_word_0
  call void @scr_str_release(ptr %t121)
  %t122 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t122)
  %t123 = load ptr, ptr %sc_l_customVocab_0
  call void @scr_union_release(ptr %t123)
  ret void
exc.k33:
  br label %if.j31
if.j31:
  %t124 = load ptr, ptr %sc_l_word_0
  call void @scr_str_release(ptr %t124)
  br label %loop.u29
loop.u29:
  %t125 = load double, ptr %sc_l_i_0
  %t126 = fadd double %t125, 0x3FF0000000000000
  store double %t126, ptr %sc_l_i_0
  br label %loop.c26
loop.e28:
  br label %if.j25
if.j25:
  %t127 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t127)
  %t128 = load ptr, ptr %sc_l_customVocab_0
  call void @scr_union_release(ptr %t128)
  ret void
}

define internal double @sc_f__x25__x25_m5_Tokenizer_addToken(ptr %p_sc_l_this_0, ptr %p_sc_l_token_0) #0 { ; %%m5.Tokenizer.addToken
entry:
  %sc_l_this_0 = alloca ptr ; this
  %sc_l_token_0 = alloca ptr ; token
  %sc_l_id_0 = alloca double ; id
  %s15 = alloca double
  %s17 = alloca ptr
  store ptr %p_sc_l_this_0, ptr %sc_l_this_0
  store ptr %p_sc_l_token_0, ptr %sc_l_token_0
  %t0 = load ptr, ptr %sc_l_this_0
  %t1 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t0)
  %t2 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t1, i64 0, i32 2
  %t3 = load ptr, ptr %t2
  %t4 = call ptr @scr_map_retain_v(ptr %t3)
  %t5 = load ptr, ptr %sc_l_token_0
  %t6 = call ptr @scr_str_retain_v(ptr %t5)
  %t7 = call zeroext i1 @scr_map_has_str(ptr %t4, ptr %t6)
  call void @sc_release__x25_m5_Tokenizer(ptr %t1)
  call void @scr_map_release(ptr %t4)
  call void @scr_str_release(ptr %t6)
  br i1 %t7, label %if.t0, label %if.j1
if.t0:
  %t8 = load ptr, ptr %sc_l_this_0
  %t9 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t8)
  %t10 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t9, i64 0, i32 2
  %t11 = load ptr, ptr %t10
  %t12 = call ptr @scr_map_retain_v(ptr %t11)
  %t13 = load ptr, ptr %sc_l_token_0
  %t14 = call ptr @scr_str_retain_v(ptr %t13)
  store double 0x0000000000000000, ptr %s15
  %t16 = call zeroext i1 @scr_map_get_str_f64(ptr %t12, ptr %t14, ptr %s15)
  br i1 %t16, label %mg.p2, label %mg.a3
mg.p2:
  %t18 = load double, ptr %s15
  %t19 = call ptr @scr_union_new_f64(i32 0, double %t18)
  store ptr %t19, ptr %s17
  br label %mg.j4
mg.a3:
  store ptr @sc_unit_0, ptr %s17
  br label %mg.j4
mg.j4:
  %t20 = load ptr, ptr %s17
  %t21 = call double @sc_f__x25_union_narrow_0(ptr %t20)
  %t22 = call zeroext i1 @scr_exc_pending()
  br i1 %t22, label %exc.u5, label %exc.k6
exc.u5:
  call void @sc_release__x25_m5_Tokenizer(ptr %t9)
  call void @scr_map_release(ptr %t12)
  call void @scr_str_release(ptr %t14)
  %t23 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t23)
  %t24 = load ptr, ptr %sc_l_token_0
  call void @scr_str_release(ptr %t24)
  ret double 0x0000000000000000
exc.k6:
  call void @sc_release__x25_m5_Tokenizer(ptr %t9)
  call void @scr_map_release(ptr %t12)
  call void @scr_str_release(ptr %t14)
  %t25 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t25)
  %t26 = load ptr, ptr %sc_l_token_0
  call void @scr_str_release(ptr %t26)
  ret double %t21
if.j1:
  %t27 = load ptr, ptr %sc_l_this_0
  %t28 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t27)
  %t29 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t28, i64 0, i32 3
  %t30 = load ptr, ptr %t29
  %t31 = call ptr @scr_arr_retain_v(ptr %t30)
  %t32 = call double @scr_arr_len(ptr %t31)
  store double %t32, ptr %sc_l_id_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t28)
  call void @scr_arr_release(ptr %t31)
  %t33 = load ptr, ptr %sc_l_this_0
  %t34 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t33)
  %t35 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t34, i64 0, i32 2
  %t36 = load ptr, ptr %t35
  %t37 = call ptr @scr_map_retain_v(ptr %t36)
  %t38 = load ptr, ptr %sc_l_token_0
  %t39 = call ptr @scr_str_retain_v(ptr %t38)
  %t40 = load double, ptr %sc_l_id_0
  call void @scr_map_set_str_f64(ptr %t37, ptr %t39, double %t40)
  call void @sc_release__x25_m5_Tokenizer(ptr %t34)
  call void @scr_map_release(ptr %t37)
  call void @scr_str_release(ptr %t39)
  %t41 = load ptr, ptr %sc_l_this_0
  %t42 = call ptr @sc_retain__x25_m5_Tokenizer(ptr %t41)
  %t43 = getelementptr inbounds %sc_o__x25_m5_Tokenizer, ptr %t42, i64 0, i32 3
  %t44 = load ptr, ptr %t43
  %t45 = call ptr @scr_arr_retain_v(ptr %t44)
  %t46 = load ptr, ptr %sc_l_token_0
  %t47 = call ptr @scr_str_retain_v(ptr %t46)
  %t48 = call double @scr_arr_push_ref(ptr %t45, ptr %t47)
  call void @sc_release__x25_m5_Tokenizer(ptr %t42)
  call void @scr_arr_release(ptr %t45)
  %t49 = load double, ptr %sc_l_id_0
  %t50 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m5_Tokenizer(ptr %t50)
  %t51 = load ptr, ptr %sc_l_token_0
  call void @scr_str_release(ptr %t51)
  ret double %t49
}

define internal void @sc_f__x25__x25_m6_GGUFTokenizer_constructor(ptr %p_sc_l_this_0, ptr %p_sc_l_filePath_0) #0 { ; %%m6.GGUFTokenizer.constructor
entry:
  %sc_l_this_0 = alloca ptr ; this
  %sc_l_filePath_0 = alloca ptr ; filePath
  store ptr %p_sc_l_this_0, ptr %sc_l_this_0
  store ptr %p_sc_l_filePath_0, ptr %sc_l_filePath_0
  %t0 = load ptr, ptr %sc_l_this_0
  %t1 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t0)
  call void @sc_f__x25__x25_m5_Tokenizer_constructor(ptr %t1, ptr @sc_unit_1)
  %t2 = call zeroext i1 @scr_exc_pending()
  br i1 %t2, label %exc.u0, label %exc.k1
exc.u0:
  %t3 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t3)
  %t4 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t4)
  ret void
exc.k1:
  %t5 = load ptr, ptr %sc_l_this_0
  %t6 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t5)
  %t7 = call ptr @scr_arr_new(i32 2, i64 0)
  %t8 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %t6, i64 0, i32 8
  %t9 = load ptr, ptr %t8
  store ptr %t7, ptr %t8
  call void @scr_arr_release(ptr %t9)
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t6)
  %t10 = load ptr, ptr %sc_l_this_0
  %t11 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t10)
  %t12 = load ptr, ptr %sc_l_filePath_0
  %t13 = call ptr @scr_str_retain_v(ptr %t12)
  call void @sc_f__x25__x25_m6_GGUFTokenizer_loadFromGGUF(ptr %t11, ptr %t13)
  %t14 = call zeroext i1 @scr_exc_pending()
  br i1 %t14, label %exc.u2, label %exc.k3
exc.u2:
  %t15 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t15)
  %t16 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t16)
  ret void
exc.k3:
  %t17 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t17)
  %t18 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t18)
  ret void
}

define internal void @sc_f__x25__x25_m6_GGUFTokenizer_loadFromGGUF(ptr %p_sc_l_this_0, ptr %p_sc_l_filePath_0) #0 { ; %%m6.GGUFTokenizer.loadFromGGUF
entry:
  %sc_l_this_0 = alloca ptr ; this
  %sc_l_filePath_0 = alloca ptr ; filePath
  %sc_l_fd_0 = alloca double ; fd
  %sc_l_stat_0 = alloca ptr ; stat
  %sc_l_readSize_0 = alloca double ; readSize
  %sc_l_buf_0 = alloca ptr ; buf
  %sc_l_pos_0 = alloca double ; pos
  %sc_l_magic_0 = alloca double ; magic
  %sc_l_version_0 = alloca double ; version
  %sc_l_tensorCount_0 = alloca double ; tensorCount
  %sc_l_metadataCount_0 = alloca double ; metadataCount
  %sc_l_i_0 = alloca double ; i
  %sc_l_keyLen_0 = alloca double ; keyLen
  %sc_l_key_0 = alloca ptr ; key
  %sc_l_valType_0 = alloca double ; valType
  %sc_l_itemType_0 = alloca double ; itemType
  %sc_l_count_0 = alloca double ; count
  %sc_l_t_0 = alloca double ; t
  %sc_l_strLen_0 = alloca double ; strLen
  %sc_l_tokenStr_0 = alloca ptr ; tokenStr
  %sc_l_sLen_0 = alloca double ; sLen
  %sc_l_iType_0 = alloca double ; iType
  %sc_l_aCount_0 = alloca double ; aCount
  %sc_l_k_0 = alloca double ; k
  %sc_l_sLen_1 = alloca double ; sLen
  %s91 = alloca i1
  %s134 = alloca i1
  %s165 = alloca i1
  %s224 = alloca i1
  %s227 = alloca i1
  %s251 = alloca i1
  %s254 = alloca i1
  %s276 = alloca i1
  %s280 = alloca i1
  %s288 = alloca i1
  %s296 = alloca i1
  %s300 = alloca i1
  %s308 = alloca i1
  %s312 = alloca i1
  %s365 = alloca i1
  %s388 = alloca i1
  %s392 = alloca i1
  %s402 = alloca i1
  %s412 = alloca i1
  %s416 = alloca i1
  %s426 = alloca i1
  %s430 = alloca i1
  store ptr null, ptr %sc_l_stat_0
  store ptr null, ptr %sc_l_buf_0
  store ptr null, ptr %sc_l_key_0
  store ptr null, ptr %sc_l_tokenStr_0
  store ptr %p_sc_l_this_0, ptr %sc_l_this_0
  store ptr %p_sc_l_filePath_0, ptr %sc_l_filePath_0
  %t0 = load ptr, ptr %sc_l_filePath_0
  %t1 = call ptr @scr_str_retain_v(ptr %t0)
  %t2 = call ptr @scr_str_retain_v(ptr @sc_lit_7)
  %t3 = call double @scr_fs_open(ptr %t1, ptr %t2)
  %t4 = call zeroext i1 @scr_exc_pending()
  br i1 %t4, label %exc.u0, label %exc.k1
exc.u0:
  call void @scr_str_release(ptr %t1)
  call void @scr_str_release(ptr %t2)
  %t5 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t5)
  %t6 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t6)
  ret void
exc.k1:
  store double %t3, ptr %sc_l_fd_0
  call void @scr_str_release(ptr %t1)
  call void @scr_str_release(ptr %t2)
  %t7 = load ptr, ptr %sc_l_filePath_0
  %t8 = call ptr @scr_str_retain_v(ptr %t7)
  %t9 = call ptr @scr_fs_stat(ptr %t8)
  %t10 = call zeroext i1 @scr_exc_pending()
  br i1 %t10, label %exc.u2, label %exc.k3
exc.u2:
  call void @scr_str_release(ptr %t8)
  call void @scr_stats_release_v(ptr %t9)
  %t11 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t11)
  %t12 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t12)
  ret void
exc.k3:
  store ptr %t9, ptr %sc_l_stat_0
  call void @scr_str_release(ptr %t8)
  %t13 = fmul double 0x4040000000000000, 0x4090000000000000
  %t14 = fmul double %t13, 0x4090000000000000
  %t15 = load ptr, ptr %sc_l_stat_0
  %t16 = call ptr @scr_stats_retain_v(ptr %t15)
  %t17 = call double @scr_stats_size(ptr %t16)
  %t18 = call double @scr_math_min(double %t14, double %t17)
  store double %t18, ptr %sc_l_readSize_0
  call void @scr_stats_release_v(ptr %t16)
  %t19 = load double, ptr %sc_l_readSize_0
  %t20 = call ptr @scr_bytes_new(i32 0, double %t19)
  %t21 = call zeroext i1 @scr_exc_pending()
  br i1 %t21, label %exc.u4, label %exc.k5
exc.u4:
  call void @scr_bytes_release(ptr %t20)
  %t22 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t22)
  %t23 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t23)
  %t24 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t24)
  ret void
exc.k5:
  store ptr %t20, ptr %sc_l_buf_0
  %t25 = load double, ptr %sc_l_fd_0
  %t26 = load ptr, ptr %sc_l_buf_0
  %t27 = call ptr @scr_bytes_retain_v(ptr %t26)
  %t28 = load double, ptr %sc_l_readSize_0
  %t29 = call double @scr_fs_read_sync(double %t25, ptr %t27, double 0x0000000000000000, double %t28, double 0x0000000000000000)
  %t30 = call zeroext i1 @scr_exc_pending()
  br i1 %t30, label %exc.u6, label %exc.k7
exc.u6:
  call void @scr_bytes_release(ptr %t27)
  %t31 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t31)
  %t32 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t32)
  %t33 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t33)
  %t34 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t34)
  ret void
exc.k7:
  call void @scr_bytes_release(ptr %t27)
  store double 0x0000000000000000, ptr %sc_l_pos_0
  %t35 = load ptr, ptr %sc_l_buf_0
  %t36 = call ptr @scr_bytes_retain_v(ptr %t35)
  %t37 = load double, ptr %sc_l_pos_0
  %t38 = call double @scr_bytes_read_num(ptr %t36, double %t37, i32 4, i1 true)
  %t39 = call zeroext i1 @scr_exc_pending()
  br i1 %t39, label %exc.u8, label %exc.k9
exc.u8:
  call void @scr_bytes_release(ptr %t36)
  %t40 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t40)
  %t41 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t41)
  %t42 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t42)
  %t43 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t43)
  ret void
exc.k9:
  store double %t38, ptr %sc_l_magic_0
  call void @scr_bytes_release(ptr %t36)
  %t44 = load double, ptr %sc_l_pos_0
  %t45 = fadd double %t44, 0x4010000000000000
  store double %t45, ptr %sc_l_pos_0
  %t46 = load double, ptr %sc_l_magic_0
  %t47 = load double, ptr @sc_g_m4_GGUF_MAGIC
  %t48 = fcmp une double %t46, %t47
  br i1 %t48, label %if.t10, label %if.j11
if.t10:
  %t49 = call ptr @scr_str_retain_v(ptr @sc_lit_8)
  %t50 = call ptr @scr_error_new(i32 0, ptr %t49)
  call void @scr_throw_obj(ptr %t50, ptr @scr_error_retain_v, ptr @scr_error_release_v, ptr null)
  call void @scr_str_release(ptr %t49)
  %t51 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t51)
  %t52 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t52)
  %t53 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t53)
  %t54 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t54)
  ret void
if.j11:
  %t55 = load ptr, ptr %sc_l_buf_0
  %t56 = call ptr @scr_bytes_retain_v(ptr %t55)
  %t57 = load double, ptr %sc_l_pos_0
  %t58 = call double @scr_bytes_read_num(ptr %t56, double %t57, i32 4, i1 true)
  %t59 = call zeroext i1 @scr_exc_pending()
  br i1 %t59, label %exc.u12, label %exc.k13
exc.u12:
  call void @scr_bytes_release(ptr %t56)
  %t60 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t60)
  %t61 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t61)
  %t62 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t62)
  %t63 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t63)
  ret void
exc.k13:
  store double %t58, ptr %sc_l_version_0
  call void @scr_bytes_release(ptr %t56)
  %t64 = load double, ptr %sc_l_pos_0
  %t65 = fadd double %t64, 0x4010000000000000
  store double %t65, ptr %sc_l_pos_0
  %t66 = load ptr, ptr %sc_l_buf_0
  %t67 = call ptr @scr_bytes_retain_v(ptr %t66)
  %t68 = load double, ptr %sc_l_pos_0
  %t69 = call double @scr_bytes_read_num(ptr %t67, double %t68, i32 4, i1 true)
  %t70 = call zeroext i1 @scr_exc_pending()
  br i1 %t70, label %exc.u14, label %exc.k15
exc.u14:
  call void @scr_bytes_release(ptr %t67)
  %t71 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t71)
  %t72 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t72)
  %t73 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t73)
  %t74 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t74)
  ret void
exc.k15:
  store double %t69, ptr %sc_l_tensorCount_0
  call void @scr_bytes_release(ptr %t67)
  %t75 = load double, ptr %sc_l_pos_0
  %t76 = fadd double %t75, 0x4020000000000000
  store double %t76, ptr %sc_l_pos_0
  %t77 = load ptr, ptr %sc_l_buf_0
  %t78 = call ptr @scr_bytes_retain_v(ptr %t77)
  %t79 = load double, ptr %sc_l_pos_0
  %t80 = call double @scr_bytes_read_num(ptr %t78, double %t79, i32 4, i1 true)
  %t81 = call zeroext i1 @scr_exc_pending()
  br i1 %t81, label %exc.u16, label %exc.k17
exc.u16:
  call void @scr_bytes_release(ptr %t78)
  %t82 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t82)
  %t83 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t83)
  %t84 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t84)
  %t85 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t85)
  ret void
exc.k17:
  store double %t80, ptr %sc_l_metadataCount_0
  call void @scr_bytes_release(ptr %t78)
  %t86 = load double, ptr %sc_l_pos_0
  %t87 = fadd double %t86, 0x4020000000000000
  store double %t87, ptr %sc_l_pos_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c18
loop.c18:
  %t88 = load double, ptr %sc_l_i_0
  %t89 = load double, ptr %sc_l_metadataCount_0
  %t90 = fcmp olt double %t88, %t89
  store i1 %t90, ptr %s91
  br i1 %t90, label %log.r22, label %log.j23
log.r22:
  %t92 = load double, ptr %sc_l_pos_0
  %t93 = load double, ptr %sc_l_readSize_0
  %t94 = fcmp olt double %t92, %t93
  store i1 %t94, ptr %s91
  br label %log.j23
log.j23:
  %t95 = load i1, ptr %s91
  br i1 %t95, label %loop.b19, label %loop.e20
loop.b19:
  %t96 = load ptr, ptr %sc_l_buf_0
  %t97 = call ptr @scr_bytes_retain_v(ptr %t96)
  %t98 = load double, ptr %sc_l_pos_0
  %t99 = call double @scr_bytes_read_num(ptr %t97, double %t98, i32 4, i1 true)
  %t100 = call zeroext i1 @scr_exc_pending()
  br i1 %t100, label %exc.u24, label %exc.k25
exc.u24:
  call void @scr_bytes_release(ptr %t97)
  %t101 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t101)
  %t102 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t102)
  %t103 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t103)
  %t104 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t104)
  ret void
exc.k25:
  store double %t99, ptr %sc_l_keyLen_0
  call void @scr_bytes_release(ptr %t97)
  %t105 = load double, ptr %sc_l_pos_0
  %t106 = fadd double %t105, 0x4020000000000000
  store double %t106, ptr %sc_l_pos_0
  %t107 = load ptr, ptr %sc_l_buf_0
  %t108 = call ptr @scr_bytes_retain_v(ptr %t107)
  %t109 = call ptr @scr_str_retain_v(ptr @sc_lit_9)
  %t110 = load double, ptr %sc_l_pos_0
  %t111 = load double, ptr %sc_l_pos_0
  %t112 = load double, ptr %sc_l_keyLen_0
  %t113 = fadd double %t111, %t112
  %t114 = call ptr @scr_bytes_to_str_range(ptr %t108, ptr %t109, double %t110, double %t113)
  store ptr %t114, ptr %sc_l_key_0
  call void @scr_bytes_release(ptr %t108)
  call void @scr_str_release(ptr %t109)
  %t115 = load double, ptr %sc_l_pos_0
  %t116 = load double, ptr %sc_l_keyLen_0
  %t117 = fadd double %t115, %t116
  store double %t117, ptr %sc_l_pos_0
  %t118 = load ptr, ptr %sc_l_buf_0
  %t119 = call ptr @scr_bytes_retain_v(ptr %t118)
  %t120 = load double, ptr %sc_l_pos_0
  %t121 = call double @scr_bytes_read_num(ptr %t119, double %t120, i32 4, i1 true)
  %t122 = call zeroext i1 @scr_exc_pending()
  br i1 %t122, label %exc.u26, label %exc.k27
exc.u26:
  call void @scr_bytes_release(ptr %t119)
  %t123 = load ptr, ptr %sc_l_key_0
  call void @scr_str_release(ptr %t123)
  %t124 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t124)
  %t125 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t125)
  %t126 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t126)
  %t127 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t127)
  ret void
exc.k27:
  store double %t121, ptr %sc_l_valType_0
  call void @scr_bytes_release(ptr %t119)
  %t128 = load double, ptr %sc_l_pos_0
  %t129 = fadd double %t128, 0x4010000000000000
  store double %t129, ptr %sc_l_pos_0
  %t130 = load ptr, ptr %sc_l_key_0
  %t131 = call ptr @scr_str_retain_v(ptr %t130)
  %t132 = call ptr @scr_str_retain_v(ptr @sc_lit_10)
  %t133 = call zeroext i1 @scr_str_eq(ptr %t131, ptr %t132)
  store i1 %t133, ptr %s134
  br i1 %t133, label %log.r28, label %log.j29
log.r28:
  %t135 = load double, ptr %sc_l_valType_0
  %t136 = fcmp oeq double %t135, 0x4022000000000000
  store i1 %t136, ptr %s134
  br label %log.j29
log.j29:
  %t137 = load i1, ptr %s134
  call void @scr_str_release(ptr %t131)
  call void @scr_str_release(ptr %t132)
  br i1 %t137, label %if.t30, label %if.f32
if.t30:
  %t138 = load ptr, ptr %sc_l_buf_0
  %t139 = call ptr @scr_bytes_retain_v(ptr %t138)
  %t140 = load double, ptr %sc_l_pos_0
  %t141 = call double @scr_bytes_read_num(ptr %t139, double %t140, i32 4, i1 true)
  %t142 = call zeroext i1 @scr_exc_pending()
  br i1 %t142, label %exc.u33, label %exc.k34
exc.u33:
  call void @scr_bytes_release(ptr %t139)
  %t143 = load ptr, ptr %sc_l_key_0
  call void @scr_str_release(ptr %t143)
  %t144 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t144)
  %t145 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t145)
  %t146 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t146)
  %t147 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t147)
  ret void
exc.k34:
  store double %t141, ptr %sc_l_itemType_0
  call void @scr_bytes_release(ptr %t139)
  %t148 = load double, ptr %sc_l_pos_0
  %t149 = fadd double %t148, 0x4010000000000000
  store double %t149, ptr %sc_l_pos_0
  %t150 = load ptr, ptr %sc_l_buf_0
  %t151 = call ptr @scr_bytes_retain_v(ptr %t150)
  %t152 = load double, ptr %sc_l_pos_0
  %t153 = call double @scr_bytes_read_num(ptr %t151, double %t152, i32 4, i1 true)
  %t154 = call zeroext i1 @scr_exc_pending()
  br i1 %t154, label %exc.u35, label %exc.k36
exc.u35:
  call void @scr_bytes_release(ptr %t151)
  %t155 = load ptr, ptr %sc_l_key_0
  call void @scr_str_release(ptr %t155)
  %t156 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t156)
  %t157 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t157)
  %t158 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t158)
  %t159 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t159)
  ret void
exc.k36:
  store double %t153, ptr %sc_l_count_0
  call void @scr_bytes_release(ptr %t151)
  %t160 = load double, ptr %sc_l_pos_0
  %t161 = fadd double %t160, 0x4020000000000000
  store double %t161, ptr %sc_l_pos_0
  store double 0x0000000000000000, ptr %sc_l_t_0
  br label %loop.c37
loop.c37:
  %t162 = load double, ptr %sc_l_t_0
  %t163 = load double, ptr %sc_l_count_0
  %t164 = fcmp olt double %t162, %t163
  store i1 %t164, ptr %s165
  br i1 %t164, label %log.r41, label %log.j42
log.r41:
  %t166 = load double, ptr %sc_l_pos_0
  %t167 = load double, ptr %sc_l_readSize_0
  %t168 = fcmp olt double %t166, %t167
  store i1 %t168, ptr %s165
  br label %log.j42
log.j42:
  %t169 = load i1, ptr %s165
  br i1 %t169, label %loop.b38, label %loop.e39
loop.b38:
  %t170 = load ptr, ptr %sc_l_buf_0
  %t171 = call ptr @scr_bytes_retain_v(ptr %t170)
  %t172 = load double, ptr %sc_l_pos_0
  %t173 = call double @scr_bytes_read_num(ptr %t171, double %t172, i32 4, i1 true)
  %t174 = call zeroext i1 @scr_exc_pending()
  br i1 %t174, label %exc.u43, label %exc.k44
exc.u43:
  call void @scr_bytes_release(ptr %t171)
  %t175 = load ptr, ptr %sc_l_key_0
  call void @scr_str_release(ptr %t175)
  %t176 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t176)
  %t177 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t177)
  %t178 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t178)
  %t179 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t179)
  ret void
exc.k44:
  store double %t173, ptr %sc_l_strLen_0
  call void @scr_bytes_release(ptr %t171)
  %t180 = load double, ptr %sc_l_pos_0
  %t181 = fadd double %t180, 0x4020000000000000
  store double %t181, ptr %sc_l_pos_0
  %t182 = load ptr, ptr %sc_l_buf_0
  %t183 = call ptr @scr_bytes_retain_v(ptr %t182)
  %t184 = call ptr @scr_str_retain_v(ptr @sc_lit_9)
  %t185 = load double, ptr %sc_l_pos_0
  %t186 = load double, ptr %sc_l_pos_0
  %t187 = load double, ptr %sc_l_strLen_0
  %t188 = fadd double %t186, %t187
  %t189 = call ptr @scr_bytes_to_str_range(ptr %t183, ptr %t184, double %t185, double %t188)
  store ptr %t189, ptr %sc_l_tokenStr_0
  call void @scr_bytes_release(ptr %t183)
  call void @scr_str_release(ptr %t184)
  %t190 = load double, ptr %sc_l_pos_0
  %t191 = load double, ptr %sc_l_strLen_0
  %t192 = fadd double %t190, %t191
  store double %t192, ptr %sc_l_pos_0
  %t193 = load ptr, ptr %sc_l_this_0
  %t194 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t193)
  %t195 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %t194, i64 0, i32 8
  %t196 = load ptr, ptr %t195
  %t197 = call ptr @scr_arr_retain_v(ptr %t196)
  %t198 = load ptr, ptr %sc_l_tokenStr_0
  %t199 = call ptr @scr_str_retain_v(ptr %t198)
  %t200 = call double @scr_arr_push_ref(ptr %t197, ptr %t199)
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t194)
  call void @scr_arr_release(ptr %t197)
  %t201 = load ptr, ptr %sc_l_this_0
  %t202 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t201)
  %t203 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %t202, i64 0, i32 3
  %t204 = load ptr, ptr %t203
  %t205 = call ptr @scr_arr_retain_v(ptr %t204)
  %t206 = load ptr, ptr %sc_l_tokenStr_0
  %t207 = call ptr @scr_str_retain_v(ptr %t206)
  %t208 = call double @scr_arr_push_ref(ptr %t205, ptr %t207)
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t202)
  call void @scr_arr_release(ptr %t205)
  %t209 = load ptr, ptr %sc_l_this_0
  %t210 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t209)
  %t211 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %t210, i64 0, i32 2
  %t212 = load ptr, ptr %t211
  %t213 = call ptr @scr_map_retain_v(ptr %t212)
  %t214 = load ptr, ptr %sc_l_tokenStr_0
  %t215 = call ptr @scr_str_retain_v(ptr %t214)
  %t216 = load double, ptr %sc_l_t_0
  call void @scr_map_set_str_f64(ptr %t213, ptr %t215, double %t216)
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t210)
  call void @scr_map_release(ptr %t213)
  call void @scr_str_release(ptr %t215)
  %t217 = load ptr, ptr %sc_l_tokenStr_0
  call void @scr_str_release(ptr %t217)
  br label %loop.u40
loop.u40:
  %t218 = load double, ptr %sc_l_t_0
  %t219 = fadd double %t218, 0x3FF0000000000000
  store double %t219, ptr %sc_l_t_0
  br label %loop.c37
loop.e39:
  br label %if.j31
if.f32:
  %t220 = load ptr, ptr %sc_l_key_0
  %t221 = call ptr @scr_str_retain_v(ptr %t220)
  %t222 = call ptr @scr_str_retain_v(ptr @sc_lit_11)
  %t223 = call zeroext i1 @scr_str_eq(ptr %t221, ptr %t222)
  store i1 %t223, ptr %s224
  br i1 %t223, label %log.r45, label %log.j46
log.r45:
  %t225 = load double, ptr %sc_l_valType_0
  %t226 = fcmp oeq double %t225, 0x4010000000000000
  store i1 %t226, ptr %s227
  br i1 %t226, label %log.j48, label %log.r47
log.r47:
  %t228 = load double, ptr %sc_l_valType_0
  %t229 = fcmp oeq double %t228, 0x4014000000000000
  store i1 %t229, ptr %s227
  br label %log.j48
log.j48:
  %t230 = load i1, ptr %s227
  store i1 %t230, ptr %s224
  br label %log.j46
log.j46:
  %t231 = load i1, ptr %s224
  call void @scr_str_release(ptr %t221)
  call void @scr_str_release(ptr %t222)
  br i1 %t231, label %if.t49, label %if.f51
if.t49:
  %t232 = load ptr, ptr %sc_l_this_0
  %t233 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t232)
  %t234 = load ptr, ptr %sc_l_buf_0
  %t235 = call ptr @scr_bytes_retain_v(ptr %t234)
  %t236 = load double, ptr %sc_l_pos_0
  %t237 = call double @scr_bytes_read_num(ptr %t235, double %t236, i32 4, i1 true)
  %t238 = call zeroext i1 @scr_exc_pending()
  br i1 %t238, label %exc.u52, label %exc.k53
exc.u52:
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t233)
  call void @scr_bytes_release(ptr %t235)
  %t239 = load ptr, ptr %sc_l_key_0
  call void @scr_str_release(ptr %t239)
  %t240 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t240)
  %t241 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t241)
  %t242 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t242)
  %t243 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t243)
  ret void
exc.k53:
  %t244 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %t233, i64 0, i32 4
  store double %t237, ptr %t244
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t233)
  call void @scr_bytes_release(ptr %t235)
  %t245 = load double, ptr %sc_l_pos_0
  %t246 = fadd double %t245, 0x4010000000000000
  store double %t246, ptr %sc_l_pos_0
  br label %if.j50
if.f51:
  %t247 = load ptr, ptr %sc_l_key_0
  %t248 = call ptr @scr_str_retain_v(ptr %t247)
  %t249 = call ptr @scr_str_retain_v(ptr @sc_lit_12)
  %t250 = call zeroext i1 @scr_str_eq(ptr %t248, ptr %t249)
  store i1 %t250, ptr %s251
  br i1 %t250, label %log.r54, label %log.j55
log.r54:
  %t252 = load double, ptr %sc_l_valType_0
  %t253 = fcmp oeq double %t252, 0x4010000000000000
  store i1 %t253, ptr %s254
  br i1 %t253, label %log.j57, label %log.r56
log.r56:
  %t255 = load double, ptr %sc_l_valType_0
  %t256 = fcmp oeq double %t255, 0x4014000000000000
  store i1 %t256, ptr %s254
  br label %log.j57
log.j57:
  %t257 = load i1, ptr %s254
  store i1 %t257, ptr %s251
  br label %log.j55
log.j55:
  %t258 = load i1, ptr %s251
  call void @scr_str_release(ptr %t248)
  call void @scr_str_release(ptr %t249)
  br i1 %t258, label %if.t58, label %if.f60
if.t58:
  %t259 = load ptr, ptr %sc_l_this_0
  %t260 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t259)
  %t261 = load ptr, ptr %sc_l_buf_0
  %t262 = call ptr @scr_bytes_retain_v(ptr %t261)
  %t263 = load double, ptr %sc_l_pos_0
  %t264 = call double @scr_bytes_read_num(ptr %t262, double %t263, i32 4, i1 true)
  %t265 = call zeroext i1 @scr_exc_pending()
  br i1 %t265, label %exc.u61, label %exc.k62
exc.u61:
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t260)
  call void @scr_bytes_release(ptr %t262)
  %t266 = load ptr, ptr %sc_l_key_0
  call void @scr_str_release(ptr %t266)
  %t267 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t267)
  %t268 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t268)
  %t269 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t269)
  %t270 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t270)
  ret void
exc.k62:
  %t271 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %t260, i64 0, i32 5
  store double %t264, ptr %t271
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t260)
  call void @scr_bytes_release(ptr %t262)
  %t272 = load double, ptr %sc_l_pos_0
  %t273 = fadd double %t272, 0x4010000000000000
  store double %t273, ptr %sc_l_pos_0
  br label %if.j59
if.f60:
  %t274 = load double, ptr %sc_l_valType_0
  %t275 = fcmp oeq double %t274, 0x0000000000000000
  store i1 %t275, ptr %s276
  br i1 %t275, label %log.j64, label %log.r63
log.r63:
  %t277 = load double, ptr %sc_l_valType_0
  %t278 = fcmp oeq double %t277, 0x3FF0000000000000
  store i1 %t278, ptr %s276
  br label %log.j64
log.j64:
  %t279 = load i1, ptr %s276
  store i1 %t279, ptr %s280
  br i1 %t279, label %log.j66, label %log.r65
log.r65:
  %t281 = load double, ptr %sc_l_valType_0
  %t282 = fcmp oeq double %t281, 0x401C000000000000
  store i1 %t282, ptr %s280
  br label %log.j66
log.j66:
  %t283 = load i1, ptr %s280
  br i1 %t283, label %if.t67, label %if.f69
if.t67:
  %t284 = load double, ptr %sc_l_pos_0
  %t285 = fadd double %t284, 0x3FF0000000000000
  store double %t285, ptr %sc_l_pos_0
  br label %if.j68
if.f69:
  %t286 = load double, ptr %sc_l_valType_0
  %t287 = fcmp oeq double %t286, 0x4000000000000000
  store i1 %t287, ptr %s288
  br i1 %t287, label %log.j71, label %log.r70
log.r70:
  %t289 = load double, ptr %sc_l_valType_0
  %t290 = fcmp oeq double %t289, 0x4008000000000000
  store i1 %t290, ptr %s288
  br label %log.j71
log.j71:
  %t291 = load i1, ptr %s288
  br i1 %t291, label %if.t72, label %if.f74
if.t72:
  %t292 = load double, ptr %sc_l_pos_0
  %t293 = fadd double %t292, 0x4000000000000000
  store double %t293, ptr %sc_l_pos_0
  br label %if.j73
if.f74:
  %t294 = load double, ptr %sc_l_valType_0
  %t295 = fcmp oeq double %t294, 0x4010000000000000
  store i1 %t295, ptr %s296
  br i1 %t295, label %log.j76, label %log.r75
log.r75:
  %t297 = load double, ptr %sc_l_valType_0
  %t298 = fcmp oeq double %t297, 0x4014000000000000
  store i1 %t298, ptr %s296
  br label %log.j76
log.j76:
  %t299 = load i1, ptr %s296
  store i1 %t299, ptr %s300
  br i1 %t299, label %log.j78, label %log.r77
log.r77:
  %t301 = load double, ptr %sc_l_valType_0
  %t302 = fcmp oeq double %t301, 0x4018000000000000
  store i1 %t302, ptr %s300
  br label %log.j78
log.j78:
  %t303 = load i1, ptr %s300
  br i1 %t303, label %if.t79, label %if.f81
if.t79:
  %t304 = load double, ptr %sc_l_pos_0
  %t305 = fadd double %t304, 0x4010000000000000
  store double %t305, ptr %sc_l_pos_0
  br label %if.j80
if.f81:
  %t306 = load double, ptr %sc_l_valType_0
  %t307 = fcmp oeq double %t306, 0x4024000000000000
  store i1 %t307, ptr %s308
  br i1 %t307, label %log.j83, label %log.r82
log.r82:
  %t309 = load double, ptr %sc_l_valType_0
  %t310 = fcmp oeq double %t309, 0x4026000000000000
  store i1 %t310, ptr %s308
  br label %log.j83
log.j83:
  %t311 = load i1, ptr %s308
  store i1 %t311, ptr %s312
  br i1 %t311, label %log.j85, label %log.r84
log.r84:
  %t313 = load double, ptr %sc_l_valType_0
  %t314 = fcmp oeq double %t313, 0x4028000000000000
  store i1 %t314, ptr %s312
  br label %log.j85
log.j85:
  %t315 = load i1, ptr %s312
  br i1 %t315, label %if.t86, label %if.f88
if.t86:
  %t316 = load double, ptr %sc_l_pos_0
  %t317 = fadd double %t316, 0x4020000000000000
  store double %t317, ptr %sc_l_pos_0
  br label %if.j87
if.f88:
  %t318 = load double, ptr %sc_l_valType_0
  %t319 = fcmp oeq double %t318, 0x4020000000000000
  br i1 %t319, label %if.t89, label %if.f91
if.t89:
  %t320 = load ptr, ptr %sc_l_buf_0
  %t321 = call ptr @scr_bytes_retain_v(ptr %t320)
  %t322 = load double, ptr %sc_l_pos_0
  %t323 = call double @scr_bytes_read_num(ptr %t321, double %t322, i32 4, i1 true)
  %t324 = call zeroext i1 @scr_exc_pending()
  br i1 %t324, label %exc.u92, label %exc.k93
exc.u92:
  call void @scr_bytes_release(ptr %t321)
  %t325 = load ptr, ptr %sc_l_key_0
  call void @scr_str_release(ptr %t325)
  %t326 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t326)
  %t327 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t327)
  %t328 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t328)
  %t329 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t329)
  ret void
exc.k93:
  store double %t323, ptr %sc_l_sLen_0
  call void @scr_bytes_release(ptr %t321)
  %t330 = load double, ptr %sc_l_pos_0
  %t331 = load double, ptr %sc_l_sLen_0
  %t332 = fadd double 0x4020000000000000, %t331
  %t333 = fadd double %t330, %t332
  store double %t333, ptr %sc_l_pos_0
  br label %if.j90
if.f91:
  %t334 = load double, ptr %sc_l_valType_0
  %t335 = fcmp oeq double %t334, 0x4022000000000000
  br i1 %t335, label %if.t94, label %if.j95
if.t94:
  %t336 = load ptr, ptr %sc_l_buf_0
  %t337 = call ptr @scr_bytes_retain_v(ptr %t336)
  %t338 = load double, ptr %sc_l_pos_0
  %t339 = call double @scr_bytes_read_num(ptr %t337, double %t338, i32 4, i1 true)
  %t340 = call zeroext i1 @scr_exc_pending()
  br i1 %t340, label %exc.u96, label %exc.k97
exc.u96:
  call void @scr_bytes_release(ptr %t337)
  %t341 = load ptr, ptr %sc_l_key_0
  call void @scr_str_release(ptr %t341)
  %t342 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t342)
  %t343 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t343)
  %t344 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t344)
  %t345 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t345)
  ret void
exc.k97:
  store double %t339, ptr %sc_l_iType_0
  call void @scr_bytes_release(ptr %t337)
  %t346 = load double, ptr %sc_l_pos_0
  %t347 = fadd double %t346, 0x4010000000000000
  store double %t347, ptr %sc_l_pos_0
  %t348 = load ptr, ptr %sc_l_buf_0
  %t349 = call ptr @scr_bytes_retain_v(ptr %t348)
  %t350 = load double, ptr %sc_l_pos_0
  %t351 = call double @scr_bytes_read_num(ptr %t349, double %t350, i32 4, i1 true)
  %t352 = call zeroext i1 @scr_exc_pending()
  br i1 %t352, label %exc.u98, label %exc.k99
exc.u98:
  call void @scr_bytes_release(ptr %t349)
  %t353 = load ptr, ptr %sc_l_key_0
  call void @scr_str_release(ptr %t353)
  %t354 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t354)
  %t355 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t355)
  %t356 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t356)
  %t357 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t357)
  ret void
exc.k99:
  store double %t351, ptr %sc_l_aCount_0
  call void @scr_bytes_release(ptr %t349)
  %t358 = load double, ptr %sc_l_pos_0
  %t359 = fadd double %t358, 0x4020000000000000
  store double %t359, ptr %sc_l_pos_0
  %t360 = load double, ptr %sc_l_iType_0
  %t361 = fcmp oeq double %t360, 0x4020000000000000
  br i1 %t361, label %if.t100, label %if.f102
if.t100:
  store double 0x0000000000000000, ptr %sc_l_k_0
  br label %loop.c103
loop.c103:
  %t362 = load double, ptr %sc_l_k_0
  %t363 = load double, ptr %sc_l_aCount_0
  %t364 = fcmp olt double %t362, %t363
  store i1 %t364, ptr %s365
  br i1 %t364, label %log.r107, label %log.j108
log.r107:
  %t366 = load double, ptr %sc_l_pos_0
  %t367 = load double, ptr %sc_l_readSize_0
  %t368 = fcmp olt double %t366, %t367
  store i1 %t368, ptr %s365
  br label %log.j108
log.j108:
  %t369 = load i1, ptr %s365
  br i1 %t369, label %loop.b104, label %loop.e105
loop.b104:
  %t370 = load ptr, ptr %sc_l_buf_0
  %t371 = call ptr @scr_bytes_retain_v(ptr %t370)
  %t372 = load double, ptr %sc_l_pos_0
  %t373 = call double @scr_bytes_read_num(ptr %t371, double %t372, i32 4, i1 true)
  %t374 = call zeroext i1 @scr_exc_pending()
  br i1 %t374, label %exc.u109, label %exc.k110
exc.u109:
  call void @scr_bytes_release(ptr %t371)
  %t375 = load ptr, ptr %sc_l_key_0
  call void @scr_str_release(ptr %t375)
  %t376 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t376)
  %t377 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t377)
  %t378 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t378)
  %t379 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t379)
  ret void
exc.k110:
  store double %t373, ptr %sc_l_sLen_1
  call void @scr_bytes_release(ptr %t371)
  %t380 = load double, ptr %sc_l_pos_0
  %t381 = load double, ptr %sc_l_sLen_1
  %t382 = fadd double 0x4020000000000000, %t381
  %t383 = fadd double %t380, %t382
  store double %t383, ptr %sc_l_pos_0
  br label %loop.u106
loop.u106:
  %t384 = load double, ptr %sc_l_k_0
  %t385 = fadd double %t384, 0x3FF0000000000000
  store double %t385, ptr %sc_l_k_0
  br label %loop.c103
loop.e105:
  br label %if.j101
if.f102:
  %t386 = load double, ptr %sc_l_iType_0
  %t387 = fcmp oeq double %t386, 0x0000000000000000
  store i1 %t387, ptr %s388
  br i1 %t387, label %log.j112, label %log.r111
log.r111:
  %t389 = load double, ptr %sc_l_iType_0
  %t390 = fcmp oeq double %t389, 0x3FF0000000000000
  store i1 %t390, ptr %s388
  br label %log.j112
log.j112:
  %t391 = load i1, ptr %s388
  store i1 %t391, ptr %s392
  br i1 %t391, label %log.j114, label %log.r113
log.r113:
  %t393 = load double, ptr %sc_l_iType_0
  %t394 = fcmp oeq double %t393, 0x401C000000000000
  store i1 %t394, ptr %s392
  br label %log.j114
log.j114:
  %t395 = load i1, ptr %s392
  br i1 %t395, label %if.t115, label %if.f117
if.t115:
  %t396 = load double, ptr %sc_l_pos_0
  %t397 = load double, ptr %sc_l_aCount_0
  %t398 = fmul double %t397, 0x3FF0000000000000
  %t399 = fadd double %t396, %t398
  store double %t399, ptr %sc_l_pos_0
  br label %if.j116
if.f117:
  %t400 = load double, ptr %sc_l_iType_0
  %t401 = fcmp oeq double %t400, 0x4000000000000000
  store i1 %t401, ptr %s402
  br i1 %t401, label %log.j119, label %log.r118
log.r118:
  %t403 = load double, ptr %sc_l_iType_0
  %t404 = fcmp oeq double %t403, 0x4008000000000000
  store i1 %t404, ptr %s402
  br label %log.j119
log.j119:
  %t405 = load i1, ptr %s402
  br i1 %t405, label %if.t120, label %if.f122
if.t120:
  %t406 = load double, ptr %sc_l_pos_0
  %t407 = load double, ptr %sc_l_aCount_0
  %t408 = fmul double %t407, 0x4000000000000000
  %t409 = fadd double %t406, %t408
  store double %t409, ptr %sc_l_pos_0
  br label %if.j121
if.f122:
  %t410 = load double, ptr %sc_l_iType_0
  %t411 = fcmp oeq double %t410, 0x4010000000000000
  store i1 %t411, ptr %s412
  br i1 %t411, label %log.j124, label %log.r123
log.r123:
  %t413 = load double, ptr %sc_l_iType_0
  %t414 = fcmp oeq double %t413, 0x4014000000000000
  store i1 %t414, ptr %s412
  br label %log.j124
log.j124:
  %t415 = load i1, ptr %s412
  store i1 %t415, ptr %s416
  br i1 %t415, label %log.j126, label %log.r125
log.r125:
  %t417 = load double, ptr %sc_l_iType_0
  %t418 = fcmp oeq double %t417, 0x4018000000000000
  store i1 %t418, ptr %s416
  br label %log.j126
log.j126:
  %t419 = load i1, ptr %s416
  br i1 %t419, label %if.t127, label %if.f129
if.t127:
  %t420 = load double, ptr %sc_l_pos_0
  %t421 = load double, ptr %sc_l_aCount_0
  %t422 = fmul double %t421, 0x4010000000000000
  %t423 = fadd double %t420, %t422
  store double %t423, ptr %sc_l_pos_0
  br label %if.j128
if.f129:
  %t424 = load double, ptr %sc_l_iType_0
  %t425 = fcmp oeq double %t424, 0x4024000000000000
  store i1 %t425, ptr %s426
  br i1 %t425, label %log.j131, label %log.r130
log.r130:
  %t427 = load double, ptr %sc_l_iType_0
  %t428 = fcmp oeq double %t427, 0x4026000000000000
  store i1 %t428, ptr %s426
  br label %log.j131
log.j131:
  %t429 = load i1, ptr %s426
  store i1 %t429, ptr %s430
  br i1 %t429, label %log.j133, label %log.r132
log.r132:
  %t431 = load double, ptr %sc_l_iType_0
  %t432 = fcmp oeq double %t431, 0x4028000000000000
  store i1 %t432, ptr %s430
  br label %log.j133
log.j133:
  %t433 = load i1, ptr %s430
  br i1 %t433, label %if.t134, label %if.j135
if.t134:
  %t434 = load double, ptr %sc_l_pos_0
  %t435 = load double, ptr %sc_l_aCount_0
  %t436 = fmul double %t435, 0x4020000000000000
  %t437 = fadd double %t434, %t436
  store double %t437, ptr %sc_l_pos_0
  br label %if.j135
if.j135:
  br label %if.j128
if.j128:
  br label %if.j121
if.j121:
  br label %if.j116
if.j116:
  br label %if.j101
if.j101:
  br label %if.j95
if.j95:
  br label %if.j90
if.j90:
  br label %if.j87
if.j87:
  br label %if.j80
if.j80:
  br label %if.j73
if.j73:
  br label %if.j68
if.j68:
  br label %if.j59
if.j59:
  br label %if.j50
if.j50:
  br label %if.j31
if.j31:
  %t438 = load ptr, ptr %sc_l_key_0
  call void @scr_str_release(ptr %t438)
  br label %loop.u21
loop.u21:
  %t439 = load double, ptr %sc_l_i_0
  %t440 = fadd double %t439, 0x3FF0000000000000
  store double %t440, ptr %sc_l_i_0
  br label %loop.c18
loop.e20:
  %t441 = load double, ptr %sc_l_fd_0
  call void @scr_fs_close(double %t441)
  %t442 = call zeroext i1 @scr_exc_pending()
  br i1 %t442, label %exc.u136, label %exc.k137
exc.u136:
  %t443 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t443)
  %t444 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t444)
  %t445 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t445)
  %t446 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t446)
  ret void
exc.k137:
  %t447 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t447)
  %t448 = load ptr, ptr %sc_l_filePath_0
  call void @scr_str_release(ptr %t448)
  %t449 = load ptr, ptr %sc_l_stat_0
  call void @scr_stats_release_v(ptr %t449)
  %t450 = load ptr, ptr %sc_l_buf_0
  call void @scr_bytes_release(ptr %t450)
  ret void
}

define internal ptr @sc_f__x25__x25_m6_GGUFTokenizer_idToToken(ptr %p_sc_l_this_0, double %p_sc_l_id_0) #0 { ; %%m6.GGUFTokenizer.idToToken
entry:
  %sc_l_this_0 = alloca ptr ; this
  %sc_l_id_0 = alloca double ; id
  %s2 = alloca i1
  store ptr %p_sc_l_this_0, ptr %sc_l_this_0
  store double %p_sc_l_id_0, ptr %sc_l_id_0
  %t0 = load double, ptr %sc_l_id_0
  %t1 = fcmp olt double %t0, 0x0000000000000000
  store i1 %t1, ptr %s2
  br i1 %t1, label %log.j1, label %log.r0
log.r0:
  %t3 = load double, ptr %sc_l_id_0
  %t4 = load ptr, ptr %sc_l_this_0
  %t5 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t4)
  %t6 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %t5, i64 0, i32 8
  %t7 = load ptr, ptr %t6
  %t8 = call ptr @scr_arr_retain_v(ptr %t7)
  %t9 = call double @scr_arr_len(ptr %t8)
  %t10 = fcmp oge double %t3, %t9
  store i1 %t10, ptr %s2
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t5)
  call void @scr_arr_release(ptr %t8)
  br label %log.j1
log.j1:
  %t11 = load i1, ptr %s2
  br i1 %t11, label %if.t2, label %if.j3
if.t2:
  %t12 = call ptr @scr_str_retain_v(ptr @sc_lit_0)
  %t13 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t13)
  ret ptr %t12
if.j3:
  %t14 = load ptr, ptr %sc_l_this_0
  %t15 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t14)
  %t16 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %t15, i64 0, i32 8
  %t17 = load ptr, ptr %t16
  %t18 = call ptr @scr_arr_retain_v(ptr %t17)
  %t19 = load double, ptr %sc_l_id_0
  %t20 = call ptr @scr_arr_get_ref(ptr %t18, double %t19)
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t15)
  call void @scr_arr_release(ptr %t18)
  %t21 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t21)
  ret ptr %t20
}

define internal ptr @sc_f__x25__x25_m6_GGUFTokenizer_decode(ptr %p_sc_l_this_0, ptr %p_sc_l_tokenIds_0, ptr %p_sc_l_skipSpecialTokens_0) #0 { ; %%m6.GGUFTokenizer.decode
entry:
  %sc_l_this_0 = alloca ptr ; this
  %sc_l_tokenIds_0 = alloca ptr ; tokenIds
  %sc_l_skipSpecialTokens_0 = alloca ptr ; skipSpecialTokens
  %sc_l_skipSpecialTokens_1 = alloca i1 ; skipSpecialTokens
  %sc_l_rawBytes_0 = alloca ptr ; rawBytes
  %sc_l_i_0 = alloca double ; i
  %sc_l_id_0 = alloca double ; id
  %sc_l_tokStr_0 = alloca ptr ; tokStr
  %sc_l_c_0 = alloca double ; c
  %sc_l_code_0 = alloca double ; code
  %sc_l_b_0 = alloca ptr ; b
  %sc_l_outBuf_0 = alloca ptr ; outBuf
  %s5 = alloca i1
  %s27 = alloca i1
  %s35 = alloca i1
  %s39 = alloca i1
  %s59 = alloca double
  %s61 = alloca ptr
  %s72 = alloca double
  store ptr null, ptr %sc_l_rawBytes_0
  store ptr null, ptr %sc_l_tokStr_0
  store ptr null, ptr %sc_l_b_0
  store ptr null, ptr %sc_l_outBuf_0
  store ptr %p_sc_l_this_0, ptr %sc_l_this_0
  store ptr %p_sc_l_tokenIds_0, ptr %sc_l_tokenIds_0
  store ptr %p_sc_l_skipSpecialTokens_0, ptr %sc_l_skipSpecialTokens_0
  %t0 = load ptr, ptr %sc_l_skipSpecialTokens_0
  %t1 = call ptr @scr_union_retain_v(ptr %t0)
  %t2 = getelementptr inbounds %ScrUnion, ptr %t1, i64 0, i32 1
  %t3 = load i32, ptr %t2
  %t4 = icmp eq i32 %t3, 1
  br i1 %t4, label %tern.t0, label %tern.f1
tern.t0:
  store i1 true, ptr %s5
  br label %tern.j2
tern.f1:
  %t6 = load ptr, ptr %sc_l_skipSpecialTokens_0
  %t7 = call ptr @scr_union_retain_v(ptr %t6)
  %t8 = call zeroext i1 @scr_union_get_bool(ptr %t7)
  store i1 %t8, ptr %s5
  call void @scr_union_release(ptr %t7)
  br label %tern.j2
tern.j2:
  %t9 = load i1, ptr %s5
  store i1 %t9, ptr %sc_l_skipSpecialTokens_1
  call void @scr_union_release(ptr %t1)
  %t10 = call ptr @scr_arr_new(i32 0, i64 0)
  store ptr %t10, ptr %sc_l_rawBytes_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c3
loop.c3:
  %t11 = load double, ptr %sc_l_i_0
  %t12 = load ptr, ptr %sc_l_tokenIds_0
  %t13 = call ptr @scr_arr_retain_v(ptr %t12)
  %t14 = call double @scr_arr_len(ptr %t13)
  %t15 = fcmp olt double %t11, %t14
  call void @scr_arr_release(ptr %t13)
  br i1 %t15, label %loop.b4, label %loop.e5
loop.b4:
  %t16 = load ptr, ptr %sc_l_tokenIds_0
  %t17 = call ptr @scr_arr_retain_v(ptr %t16)
  %t18 = load double, ptr %sc_l_i_0
  %t19 = call double @scr_arr_get_f64(ptr %t17, double %t18)
  store double %t19, ptr %sc_l_id_0
  call void @scr_arr_release(ptr %t17)
  %t20 = load i1, ptr %sc_l_skipSpecialTokens_1
  br i1 %t20, label %if.t7, label %if.j8
if.t7:
  %t21 = load double, ptr %sc_l_id_0
  %t22 = load ptr, ptr %sc_l_this_0
  %t23 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t22)
  %t24 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %t23, i64 0, i32 4
  %t25 = load double, ptr %t24
  %t26 = fcmp oeq double %t21, %t25
  store i1 %t26, ptr %s27
  br i1 %t26, label %log.j10, label %log.r9
log.r9:
  %t28 = load double, ptr %sc_l_id_0
  %t29 = load ptr, ptr %sc_l_this_0
  %t30 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t29)
  %t31 = getelementptr inbounds %sc_o__x25_m6_GGUFTokenizer, ptr %t30, i64 0, i32 5
  %t32 = load double, ptr %t31
  %t33 = fcmp oeq double %t28, %t32
  store i1 %t33, ptr %s27
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t30)
  br label %log.j10
log.j10:
  %t34 = load i1, ptr %s27
  store i1 %t34, ptr %s35
  br i1 %t34, label %log.j12, label %log.r11
log.r11:
  %t36 = load double, ptr %sc_l_id_0
  %t37 = fcmp oeq double %t36, 0x410282E000000000
  store i1 %t37, ptr %s35
  br label %log.j12
log.j12:
  %t38 = load i1, ptr %s35
  store i1 %t38, ptr %s39
  br i1 %t38, label %log.j14, label %log.r13
log.r13:
  %t40 = load double, ptr %sc_l_id_0
  %t41 = fcmp oeq double %t40, 0x410282E800000000
  store i1 %t41, ptr %s39
  br label %log.j14
log.j14:
  %t42 = load i1, ptr %s39
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t23)
  br i1 %t42, label %if.t15, label %if.j16
if.t15:
  br label %loop.u6
if.j16:
  br label %if.j8
if.j8:
  %t43 = load ptr, ptr %sc_l_this_0
  %t44 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t43)
  %t45 = load double, ptr %sc_l_id_0
  %t46 = call ptr @sc_f__x25__x25_m6_GGUFTokenizer_idToToken(ptr %t44, double %t45)
  store ptr %t46, ptr %sc_l_tokStr_0
  store double 0x0000000000000000, ptr %sc_l_c_0
  br label %loop.c17
loop.c17:
  %t47 = load double, ptr %sc_l_c_0
  %t48 = load ptr, ptr %sc_l_tokStr_0
  %t49 = call ptr @scr_str_retain_v(ptr %t48)
  %t50 = call double @scr_str_utf16_len(ptr %t49)
  %t51 = fcmp olt double %t47, %t50
  call void @scr_str_release(ptr %t49)
  br i1 %t51, label %loop.b18, label %loop.e19
loop.b18:
  %t52 = load ptr, ptr %sc_l_tokStr_0
  %t53 = call ptr @scr_str_retain_v(ptr %t52)
  %t54 = load double, ptr %sc_l_c_0
  %t55 = call double @scr_str_char_code_at(ptr %t53, double %t54)
  store double %t55, ptr %sc_l_code_0
  call void @scr_str_release(ptr %t53)
  %t56 = load ptr, ptr @sc_g_s__x25_m6_GGUFTokenizer_cpToByte
  %t57 = call ptr @scr_map_retain_v(ptr %t56)
  %t58 = load double, ptr %sc_l_code_0
  store double 0x0000000000000000, ptr %s59
  %t60 = call zeroext i1 @scr_map_get_f64_f64(ptr %t57, double %t58, ptr %s59)
  br i1 %t60, label %mg.p21, label %mg.a22
mg.p21:
  %t62 = load double, ptr %s59
  %t63 = call ptr @scr_union_new_f64(i32 0, double %t62)
  store ptr %t63, ptr %s61
  br label %mg.j23
mg.a22:
  store ptr @sc_unit_0, ptr %s61
  br label %mg.j23
mg.j23:
  %t64 = load ptr, ptr %s61
  store ptr %t64, ptr %sc_l_b_0
  call void @scr_map_release(ptr %t57)
  %t65 = load ptr, ptr %sc_l_rawBytes_0
  %t66 = call ptr @scr_arr_retain_v(ptr %t65)
  %t67 = load ptr, ptr %sc_l_b_0
  %t68 = call ptr @scr_union_retain_v(ptr %t67)
  %t69 = getelementptr inbounds %ScrUnion, ptr %t68, i64 0, i32 1
  %t70 = load i32, ptr %t69
  %t71 = icmp ne i32 %t70, 1
  br i1 %t71, label %tern.t24, label %tern.f25
tern.t24:
  %t73 = load ptr, ptr %sc_l_b_0
  %t74 = call ptr @scr_union_retain_v(ptr %t73)
  %t75 = call double @scr_union_get_f64(ptr %t74)
  store double %t75, ptr %s72
  call void @scr_union_release(ptr %t74)
  br label %tern.j26
tern.f25:
  %t76 = load double, ptr %sc_l_code_0
  %t77 = call double @scr_bit_and(double %t76, double 0x406FE00000000000)
  store double %t77, ptr %s72
  br label %tern.j26
tern.j26:
  %t78 = load double, ptr %s72
  %t79 = call double @scr_arr_push_f64(ptr %t66, double %t78)
  call void @scr_arr_release(ptr %t66)
  call void @scr_union_release(ptr %t68)
  %t80 = load ptr, ptr %sc_l_b_0
  call void @scr_union_release(ptr %t80)
  br label %loop.u20
loop.u20:
  %t81 = load double, ptr %sc_l_c_0
  %t82 = fadd double %t81, 0x3FF0000000000000
  store double %t82, ptr %sc_l_c_0
  br label %loop.c17
loop.e19:
  %t83 = load ptr, ptr %sc_l_tokStr_0
  call void @scr_str_release(ptr %t83)
  br label %loop.u6
loop.u6:
  %t84 = load double, ptr %sc_l_i_0
  %t85 = fadd double %t84, 0x3FF0000000000000
  store double %t85, ptr %sc_l_i_0
  br label %loop.c3
loop.e5:
  %t86 = load ptr, ptr %sc_l_rawBytes_0
  %t87 = call ptr @scr_arr_retain_v(ptr %t86)
  %t88 = call ptr @scr_bytes_from_arr(i32 0, ptr %t87)
  store ptr %t88, ptr %sc_l_outBuf_0
  call void @scr_arr_release(ptr %t87)
  %t89 = load ptr, ptr %sc_l_outBuf_0
  %t90 = call ptr @scr_bytes_retain_v(ptr %t89)
  %t91 = call ptr @scr_str_retain_v(ptr @sc_lit_9)
  %t92 = call ptr @scr_bytes_to_str(ptr %t90, ptr %t91)
  call void @scr_bytes_release(ptr %t90)
  call void @scr_str_release(ptr %t91)
  %t93 = load ptr, ptr %sc_l_this_0
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t93)
  %t94 = load ptr, ptr %sc_l_tokenIds_0
  call void @scr_arr_release(ptr %t94)
  %t95 = load ptr, ptr %sc_l_skipSpecialTokens_0
  call void @scr_union_release(ptr %t95)
  %t96 = load ptr, ptr %sc_l_rawBytes_0
  call void @scr_arr_release(ptr %t96)
  %t97 = load ptr, ptr %sc_l_outBuf_0
  call void @scr_bytes_release(ptr %t97)
  ret ptr %t92
}

define internal ptr @sc_f__x25__x25_m6_GGUFTokenizer_static_x3a_buildCpToByteMap() #0 { ; %%m6.GGUFTokenizer.static:buildCpToByteMap
entry:
  %sc_l_bs_0 = alloca ptr ; bs
  %sc_l_b_0 = alloca double ; b
  %sc_l_b_1 = alloca double ; b
  %sc_l_b_2 = alloca double ; b
  %sc_l_cs_0 = alloca ptr ; cs
  %sc_l_n_0 = alloca double ; n
  %sc_l_b_3 = alloca double ; b
  %sc_l_m_0 = alloca ptr ; m
  %sc_l_i_0 = alloca double ; i
  store ptr null, ptr %sc_l_bs_0
  store ptr null, ptr %sc_l_cs_0
  store ptr null, ptr %sc_l_m_0
  %t0 = call ptr @scr_arr_new(i32 0, i64 0)
  store ptr %t0, ptr %sc_l_bs_0
  store double 0x4040800000000000, ptr %sc_l_b_0
  br label %loop.c0
loop.c0:
  %t1 = load double, ptr %sc_l_b_0
  %t2 = fcmp olt double %t1, 0x405FC00000000000
  br i1 %t2, label %loop.b1, label %loop.e2
loop.b1:
  %t3 = load ptr, ptr %sc_l_bs_0
  %t4 = call ptr @scr_arr_retain_v(ptr %t3)
  %t5 = load double, ptr %sc_l_b_0
  %t6 = call double @scr_arr_push_f64(ptr %t4, double %t5)
  call void @scr_arr_release(ptr %t4)
  br label %loop.u3
loop.u3:
  %t7 = load double, ptr %sc_l_b_0
  %t8 = fadd double %t7, 0x3FF0000000000000
  store double %t8, ptr %sc_l_b_0
  br label %loop.c0
loop.e2:
  store double 0x4064200000000000, ptr %sc_l_b_1
  br label %loop.c4
loop.c4:
  %t9 = load double, ptr %sc_l_b_1
  %t10 = fcmp olt double %t9, 0x4065A00000000000
  br i1 %t10, label %loop.b5, label %loop.e6
loop.b5:
  %t11 = load ptr, ptr %sc_l_bs_0
  %t12 = call ptr @scr_arr_retain_v(ptr %t11)
  %t13 = load double, ptr %sc_l_b_1
  %t14 = call double @scr_arr_push_f64(ptr %t12, double %t13)
  call void @scr_arr_release(ptr %t12)
  br label %loop.u7
loop.u7:
  %t15 = load double, ptr %sc_l_b_1
  %t16 = fadd double %t15, 0x3FF0000000000000
  store double %t16, ptr %sc_l_b_1
  br label %loop.c4
loop.e6:
  store double 0x4065C00000000000, ptr %sc_l_b_2
  br label %loop.c8
loop.c8:
  %t17 = load double, ptr %sc_l_b_2
  %t18 = fcmp olt double %t17, 0x4070000000000000
  br i1 %t18, label %loop.b9, label %loop.e10
loop.b9:
  %t19 = load ptr, ptr %sc_l_bs_0
  %t20 = call ptr @scr_arr_retain_v(ptr %t19)
  %t21 = load double, ptr %sc_l_b_2
  %t22 = call double @scr_arr_push_f64(ptr %t20, double %t21)
  call void @scr_arr_release(ptr %t20)
  br label %loop.u11
loop.u11:
  %t23 = load double, ptr %sc_l_b_2
  %t24 = fadd double %t23, 0x3FF0000000000000
  store double %t24, ptr %sc_l_b_2
  br label %loop.c8
loop.e10:
  %t25 = load ptr, ptr %sc_l_bs_0
  %t26 = call ptr @scr_arr_retain_v(ptr %t25)
  %t27 = call ptr @scr_arr_slice(ptr %t26, double 0x0000000000000000, double 0x7FF0000000000000)
  store ptr %t27, ptr %sc_l_cs_0
  call void @scr_arr_release(ptr %t26)
  store double 0x0000000000000000, ptr %sc_l_n_0
  store double 0x0000000000000000, ptr %sc_l_b_3
  br label %loop.c12
loop.c12:
  %t28 = load double, ptr %sc_l_b_3
  %t29 = fcmp olt double %t28, 0x4070000000000000
  br i1 %t29, label %loop.b13, label %loop.e14
loop.b13:
  %t30 = load ptr, ptr %sc_l_bs_0
  %t31 = call ptr @scr_arr_retain_v(ptr %t30)
  %t32 = load double, ptr %sc_l_b_3
  %t33 = call zeroext i1 @scr_arr_includes_f64(ptr %t31, double %t32)
  %t34 = xor i1 %t33, true
  call void @scr_arr_release(ptr %t31)
  br i1 %t34, label %if.t16, label %if.j17
if.t16:
  %t35 = load ptr, ptr %sc_l_bs_0
  %t36 = call ptr @scr_arr_retain_v(ptr %t35)
  %t37 = load double, ptr %sc_l_b_3
  %t38 = call double @scr_arr_push_f64(ptr %t36, double %t37)
  call void @scr_arr_release(ptr %t36)
  %t39 = load ptr, ptr %sc_l_cs_0
  %t40 = call ptr @scr_arr_retain_v(ptr %t39)
  %t41 = load double, ptr %sc_l_n_0
  %t42 = fadd double 0x4070000000000000, %t41
  %t43 = call double @scr_arr_push_f64(ptr %t40, double %t42)
  call void @scr_arr_release(ptr %t40)
  %t44 = load double, ptr %sc_l_n_0
  %t45 = fadd double %t44, 0x3FF0000000000000
  store double %t45, ptr %sc_l_n_0
  br label %if.j17
if.j17:
  br label %loop.u15
loop.u15:
  %t46 = load double, ptr %sc_l_b_3
  %t47 = fadd double %t46, 0x3FF0000000000000
  store double %t47, ptr %sc_l_b_3
  br label %loop.c12
loop.e14:
  %t48 = call ptr @scr_map_new(i32 0, i32 0, ptr null, ptr null, ptr null)
  store ptr %t48, ptr %sc_l_m_0
  store double 0x0000000000000000, ptr %sc_l_i_0
  br label %loop.c18
loop.c18:
  %t49 = load double, ptr %sc_l_i_0
  %t50 = load ptr, ptr %sc_l_bs_0
  %t51 = call ptr @scr_arr_retain_v(ptr %t50)
  %t52 = call double @scr_arr_len(ptr %t51)
  %t53 = fcmp olt double %t49, %t52
  call void @scr_arr_release(ptr %t51)
  br i1 %t53, label %loop.b19, label %loop.e20
loop.b19:
  %t54 = load ptr, ptr %sc_l_m_0
  %t55 = call ptr @scr_map_retain_v(ptr %t54)
  %t56 = load ptr, ptr %sc_l_cs_0
  %t57 = call ptr @scr_arr_retain_v(ptr %t56)
  %t58 = load double, ptr %sc_l_i_0
  %t59 = call double @scr_arr_get_f64(ptr %t57, double %t58)
  %t60 = load ptr, ptr %sc_l_bs_0
  %t61 = call ptr @scr_arr_retain_v(ptr %t60)
  %t62 = load double, ptr %sc_l_i_0
  %t63 = call double @scr_arr_get_f64(ptr %t61, double %t62)
  call void @scr_map_set_f64_f64(ptr %t55, double %t59, double %t63)
  call void @scr_map_release(ptr %t55)
  call void @scr_arr_release(ptr %t57)
  call void @scr_arr_release(ptr %t61)
  br label %loop.u21
loop.u21:
  %t64 = load double, ptr %sc_l_i_0
  %t65 = fadd double %t64, 0x3FF0000000000000
  store double %t65, ptr %sc_l_i_0
  br label %loop.c18
loop.e20:
  %t66 = load ptr, ptr %sc_l_m_0
  %t67 = call ptr @scr_map_retain_v(ptr %t66)
  %t68 = load ptr, ptr %sc_l_bs_0
  call void @scr_arr_release(ptr %t68)
  %t69 = load ptr, ptr %sc_l_cs_0
  call void @scr_arr_release(ptr %t69)
  %t70 = load ptr, ptr %sc_l_m_0
  call void @scr_map_release(ptr %t70)
  ret ptr %t67
}

define internal void @sc_f__x25_init_0() #0 { ; %init.0
entry:
  %t0 = load i1, ptr @sc_g_m0__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_m0__x25_loaded
  ret void
}

define internal void @sc_f__x25_init_1() #0 { ; %init.1
entry:
  %t0 = load i1, ptr @sc_g_m1__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_m1__x25_loaded
  ret void
}

define internal void @sc_f__x25_init_2() #0 { ; %init.2
entry:
  %t0 = load i1, ptr @sc_g_m2__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_m2__x25_loaded
  call void @sc_f__x25_init_0()
  call void @sc_f__x25_init_1()
  ret void
}

define internal void @sc_f__x25_init_3() #0 { ; %init.3
entry:
  %t0 = load i1, ptr @sc_g_m3__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_m3__x25_loaded
  ret void
}

define internal void @sc_f__x25_init_4() #0 { ; %init.4
entry:
  %t0 = load i1, ptr @sc_g_m4__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_m4__x25_loaded
  call void @sc_f__x25_init_2()
  call void @sc_f__x25_init_3()
  store double 0x41D19551D1C00000, ptr @sc_g_m4_GGUF_MAGIC
  ret void
}

define internal void @sc_f__x25_init_5() #0 { ; %init.5
entry:
  %t0 = load i1, ptr @sc_g_m5__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_m5__x25_loaded
  ret void
}

define internal void @sc_f__x25_init_6() #0 { ; %init.6
entry:
  %t0 = load i1, ptr @sc_g_m6__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_m6__x25_loaded
  call void @sc_f__x25_init_4()
  call void @sc_f__x25_init_5()
  %t1 = call ptr @sc_f__x25__x25_m6_GGUFTokenizer_static_x3a_buildCpToByteMap()
  %t2 = load ptr, ptr @sc_g_s__x25_m6_GGUFTokenizer_cpToByte
  call void @scr_map_release(ptr %t2)
  store ptr %t1, ptr @sc_g_s__x25_m6_GGUFTokenizer_cpToByte
  ret void
}

define internal void @sc_f__x25_init_7() #0 { ; %init.7
entry:
  %s11 = alloca %ScrJsonBuf
  %logargs = alloca [1 x %ScrLogArg]
  %t0 = load i1, ptr @sc_g_e__x25_loaded
  br i1 %t0, label %if.t0, label %if.j1
if.t0:
  ret void
if.j1:
  store i1 true, ptr @sc_g_e__x25_loaded
  call void @sc_f__x25_init_6()
  %t1 = call ptr @sc_new__x25_m6_GGUFTokenizer()
  %t2 = call ptr @scr_str_retain_v(ptr @sc_lit_13)
  %t3 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t1)
  call void @sc_f__x25__x25_m6_GGUFTokenizer_constructor(ptr %t3, ptr %t2)
  %t4 = call zeroext i1 @scr_exc_pending()
  br i1 %t4, label %exc.u2, label %exc.k3
exc.u2:
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t1)
  ret void
exc.k3:
  %t5 = load ptr, ptr @sc_g_e_t
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %t5)
  store ptr %t1, ptr @sc_g_e_t
  %t6 = load ptr, ptr @sc_g_e_t
  %t7 = call ptr @sc_retain__x25_m6_GGUFTokenizer(ptr %t6)
  %t8 = call ptr @scr_arr_new(i32 0, i64 1)
  %t9 = call double @scr_arr_push_f64(ptr %t8, double 0x40FA762000000000)
  %t10 = call ptr @sc_f__x25__x25_m6_GGUFTokenizer_decode(ptr %t7, ptr %t8, ptr @sc_unit_2)
  call void @scr_jb_init(ptr %s11)
  call void @sc_jw_0(ptr %s11, ptr %t10)
  %t12 = call ptr @scr_jb_finish(ptr %s11)
  %t13 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 0
  store i32 1, ptr %t13
  %t14 = getelementptr inbounds %ScrLogArg, ptr %logargs, i64 0, i32 1
  store ptr %t12, ptr %t14
  call void @scr_console_log(i64 1, ptr %logargs)
  call void @scr_str_release(ptr %t10)
  call void @scr_str_release(ptr %t12)
  ret void
}

define internal void @sc_f__x25_main() #0 { ; %main
entry:
  call void @sc_f__x25_init_7()
  %t0 = call zeroext i1 @scr_exc_pending()
  br i1 %t0, label %exc.u0, label %exc.k1
exc.u0:
  ret void
exc.k1:
  ret void
}

define internal double @sc_f__x25_union_narrow_0(ptr %p_sc_l_u_0) #0 { ; %union.narrow.0
entry:
  %sc_l_u_0 = alloca ptr ; u
  store ptr %p_sc_l_u_0, ptr %sc_l_u_0
  %t0 = load ptr, ptr %sc_l_u_0
  %t1 = call ptr @scr_union_retain_v(ptr %t0)
  %t2 = getelementptr inbounds %ScrUnion, ptr %t1, i64 0, i32 1
  %t3 = load i32, ptr %t2
  %t4 = icmp eq i32 %t3, 1
  call void @scr_union_release(ptr %t1)
  br i1 %t4, label %if.t0, label %if.j1
if.t0:
  %t5 = call ptr @scr_str_retain_v(ptr @sc_lit_14)
  %t6 = call ptr @scr_error_new(i32 1, ptr %t5)
  call void @scr_throw_obj(ptr %t6, ptr @scr_error_retain_v, ptr @scr_error_release_v, ptr null)
  call void @scr_str_release(ptr %t5)
  %t7 = load ptr, ptr %sc_l_u_0
  call void @scr_union_release(ptr %t7)
  ret double 0x0000000000000000
if.j1:
  %t8 = load ptr, ptr %sc_l_u_0
  %t9 = call ptr @scr_union_retain_v(ptr %t8)
  %t10 = call double @scr_union_get_f64(ptr %t9)
  call void @scr_union_release(ptr %t9)
  %t11 = load ptr, ptr %sc_l_u_0
  call void @scr_union_release(ptr %t11)
  ret double %t10
}

declare void @scr_exc_print_uncaught()

define i32 @main(i32 %argc, ptr %argv) #0 {
entry:
  call void @scr_init()
  store i64 0, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 0, i32 1) ; Error
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 0)
  store i64 1, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 1, i32 1) ; TypeError
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 0)
  store i64 2, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 2, i32 1) ; RangeError
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 0)
  store i64 3, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 3, i32 1) ; SyntaxError
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 0)
  store i64 4, ptr getelementptr inbounds ([5 x %ScrVt], ptr @scr_error_vts, i64 0, i64 4, i32 1) ; DOMException
  call void @scr_lib_init(i32 %argc, ptr %argv)
  call void @sc_f__x25_main()
  %exc = call zeroext i1 @scr_exc_pending()
  br i1 %exc, label %uncaught, label %ok
uncaught:
  call void @scr_exc_print_uncaught()
  %gu0 = load ptr, ptr @sc_g_s__x25_m6_GGUFTokenizer_cpToByte
  call void @scr_map_release(ptr %gu0) ; GGUFTokenizer.cpToByte
  %gu2 = load ptr, ptr @sc_g_e_t
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %gu2) ; t
  ret i32 1
ok:
  %g0 = load ptr, ptr @sc_g_s__x25_m6_GGUFTokenizer_cpToByte
  call void @scr_map_release(ptr %g0) ; GGUFTokenizer.cpToByte
  %g2 = load ptr, ptr @sc_g_e_t
  call void @sc_release__x25_m6_GGUFTokenizer(ptr %g2) ; t
  ret i32 0
}

attributes #0 = { sanitize_address }
